### ISSUE TITLE
Polygon for Midco (420552455) is full of crazy

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1004]
The polygon for Midco, which is parented by the locality of Santa Maria stretches all the way over to, and covers, Santa Barbara. This causes unexpected reverse geo results and general weirdness as outlined here:

https://github.com/whosonfirst-data/whosonfirst-data/issues/997

https://whosonfirst.mapzen.com/spelunker/id/420552455/

**Comment by thisisaaronland** [comment]
Sure, but let's make a separate ticket for that? Midco is an immediate problem affecting a known use of the data.

**Comment by stepps00** [comment]
I'll use this issue to track the similar cases to Midco.. I've opened up https://github.com/whosonfirst-data/whosonfirst-data/issues/1005 to track neighbourhood updates in Santa Barbara.

**Comment by thisisaaronland** [comment]
Fixed as part of issue #1005
