### ISSUE TITLE
Upgrade neighbourhood shapes in Santa Barbara, CA

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1005]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First

### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Files are in the `misc/Issue 1005` folder in S3.

Over to @thisisaaronland for import.

**Comment by thisisaaronland** [comment]
This has outstanding properties that need to be accounted for: 

```
  File "/usr/local/lib/python2.7/dist-packages/mapzen/whosonfirst/properties/__init__.py", line 89, in resolve
    raise Exception, "Unknown key %s" % k
Exception: Unknown key santabar:NHOOD
```

**Comment by nvkelso** [comment]
Did this get pulled into your config?
https://github.com/whosonfirst/whosonfirst-sources/pull/91

On Wed, Oct 18, 2017 at 4:30 PM, Aaron Straup Cope <notifications@github.com

**Comment by thisisaaronland** [comment]
That's not where the data needs to be updated. Stuff needs to be added here: 

https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/source_data_aliases.json

**Comment by nvkelso** [comment]
@stepps00 Can you take another look, please?

**Comment by stepps00** [comment]
Added the aliases for Santa Barbara here: https://github.com/whosonfirst/whosonfirst-properties/commit/a45900010f28156e9831e514121459bad87e50e9
