### ISSUE TITLE
Problems with "Nowy Miasto" neighbourhood label

### ISSUE THREAD

**Issue by zerebubuth** [whosonfirst-data/whosonfirst-data#1008]
@matkoniecz [reported to us on the `vector-datasource` repository](https://github.com/tilezen/vector-datasource/issues/1410) that the ["Nowy Miasto" neighbourhood](https://whosonfirst.mapzen.com/spelunker/id/1108945649/) is problematic:

> There are two problems with it - "Nowe Miasto" (described at https://pl.wikipedia.org/wiki/Nowe_Miasto_w_Krakowie ) is name for (partially/mostly/almost completely failed) urban project, I am not aware of anybody using this name as an orientation point/area of city.
>
> And certainly "Nowy Miasto" is ungrammatical, if anything it should be "Nowe Miasto".

The name should be updated. And from the Wikipedia page, it seems like it perhaps needs a cessation date some time in 1998?

**Comment by matkoniecz** [comment]
> And from the Wikipedia page, it seems like it perhaps needs a cessation date some time in 1998?

no, what happened in 1998 is that company decided to not build anything due to land ownership issues.

According to this article construction started in 2004.

>  u'wof:placetype': u'neighbourhood',

what is the definition of placetype? I looked around this repo but failed to find anything.

**Comment by matkoniecz** [comment]
https://whosonfirst.mapzen.com/docs/placetypes/

has 

> Things no one will agree on. Ever.

So apparently that is place to put anything that has at least vaguely defined location - so maybe existence of this entry is not wrong.

**Comment by zerebubuth** [comment]
I wonder if that definition is intended as a humorous nod to the widespread lack of agreed-upon sharp boundaries for neighbourhoods (c.f. [This Isn't F**king Dalston](http://thisisntfuckingdalston.co.uk/), etc...)

It sounds to me like that label (even if changed to be grammatically correct) isn't very useful on the map. There are always names that a small number of people use, but which don't achieve popularity ([for example](https://www.reddit.com/r/sanfrancisco/comments/65k1m1/dont_you_love_it_when_real_estate_agents_try_to/)). Might this be a case like that? In which case, is there some way we can mark it up as "not useful for display"?

**Comment by stepps00** [comment]
Thanks for the issue, @zerebubuth and @matkoniecz - a few notes below:

> The name should be updated. And from the Wikipedia page, it seems like it perhaps needs a cessation date some time in 1998?

I will go ahead and update the `wof:name` for this record to "Nowe Miasto" and store the existing `wof:name` as a variant name. As mentioned in https://github.com/whosonfirst-data/whosonfirst-data/issues/1008#issuecomment-338637931, I won't add a cessation date, because this record still represents a "current" neighbourhood in Krakow. 

>what is the definition of placetype? I looked around this repo but failed to find anything.

See: https://github.com/whosonfirst/whosonfirst-placetypes for more placetype details. (I will also take a look at https://github.com/whosonfirst-data/whosonfirst-data/issues/1009).

> It sounds to me like that label (even if changed to be grammatically correct) isn't very useful on the map. There are always names that a small number of people use, but which don't achieve popularity (for example). Might this be a case like that? In which case, is there some way we can mark it up as "not useful for display"?

It is possible to suppress the label for this record, yes. I will update this record's `wof:name` and, in the same commit, adjust the `mz:hierarchy_label` property.

**Comment by stepps00** [comment]
A recent commit updated the `wof:name` for this record, as well as:

- Added a `name:eng_x_preferred` property
- Added a `name:eng_x_variant` property
- Updated the `mz:is_funky` property
- Updated the `mz:hierarchy_label` property

I will close this issue once that commit is merged to master.

Information about our placetypes categorization(s) can be found here: https://github.com/whosonfirst/whosonfirst-placetypes 

I've also opened https://github.com/whosonfirst/whosonfirst-placetypes/issues/10 to track better placetype descriptions. 

Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1009
