### ISSUE TITLE
Check hierarchy of this Edinburgh locality

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#1011]
This came in through support (see Desk 1166) from a Pelias user.

It appears that these Edinburgh locality records may be duplicates.

https://whosonfirst.mapzen.com/spelunker/id/101913925/ --> in a different region
https://whosonfirst.mapzen.com/spelunker/id/101750629/

**Comment by stepps00** [comment]
This looks like a multi-part polygon being imported as separate records, similar to issues we've had in the past. Normally I would merge the records into one and carry on, but the https://whosonfirst.mapzen.com/spelunker/id/101913925/ record looks suspiciously like the outline of the town Musselburgh (we don't have a `locality` record for that place). 

I'll do a little digging and propose either a merge of records or a new record for Musselburgh.

**Comment by stepps00** [comment]
Records:
- Edinburgh: https://whosonfirst.mapzen.com/spelunker/id/101750629/
- Edinburgh, which is actually Musselburgh: https://whosonfirst.mapzen.com/spelunker/id/101913925/
- Musselburgh: https://whosonfirst.mapzen.com/spelunker/id/1125942117

The "Edinburgh" record above is the actual record for Edinburgh in WOF. It's geometry and properties are correct and do not need any updates.

The second Edinburgh record is actually Musselburgh, but was somehow imported with incorrect names, concordances, and properties.

The "Musselburgh" record above is a new Musselburgh record, sourced from Quattroshapes, that has correct properties from Quattroshapes. 

I will propose a PR that supersedes 101913925 into 1125942117, updates the geometry of 1125942117 with the geometry of 101913925, and ensures the Musselburgh properties are correct. This should clear up the initial issue and give WOF the correct admin records in this area.
