### ISSUE TITLE
Update name fields for regions in Belgium

### ISSUE THREAD

**Issue by randymeech** [whosonfirst-data/whosonfirst-data#102]
From a user report:

The name of at least 2 Belgian provinces is incorrect. It should be Oost-Vlaanderen & West-Vlaanderen. Not Oost-Vlanderen & West-Vlanderen

**Comment by nvkelso** [comment]
In Who's On First has these features:

* [Oost-Vlanderen](http://whosonfirst.mapzen.com/spelunker/id/85681733/)
* [West-Vlanderen](http://whosonfirst.mapzen.com/spelunker/id/85681709/)

We can add the alternative spellings easily. But to move the new spelling into the default name needs more research to confirm the request. (The names are sourced from EuroGeoGraphics sourced from national mapping agencies today.)

**Comment by hugovk** [comment]
Dutch Wikipedia has "Oost-Vlaanderen" and links to the tourism and official sites which both also use "Oost-Vlaanderen". None of the three sites use "Oost-Vlanderen".
https://nl.wikipedia.org/wiki/Oost-Vlaanderen#Externe_links
http://www.tov.be/nl
http://www.oost-vlaanderen.be/public/index.cfm

Similarly for "West-Vlaanderen".
 https://nl.wikipedia.org/wiki/West-Vlaanderen#Externe_links
http://www.west-vlaanderen.be/Paginas/default.aspx

**Comment by Platzii** [comment]
Oost-Vlaanderen is already fixed by #284 
West-Vlaanderen still missing the 'a'.

**Comment by nvkelso** [comment]
Drrr, you're right. Sorry about the partial fix!
