### ISSUE TITLE
Add concordance with Natural Earth admin-0 countries

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#103]
Natural Earth has unique, stable country codes (alpha-3), we should add concordance to those, and import the Natural Earth properties. That'll also get us more GeoNames.org and WOE GeoPlanet ID concordances.

**Comment by stepps00** [comment]
concordance with `ne:adm0_a3`

Note the HASC and GeoName properties.

We could add alt geoms:

- 85668127-alt-ne-display-zoom6.geojson (default – we think this is already imported for all?
- 85668127-alt-ne-display-terrestrial-zoom6.geojson ("lakes" file)

**Comment by stepps00** [comment]
For the empires we could look at NE adm0 soverignty files:

concordance with `ne:sov_a3`.

There's opportunity for alt geom work, too.

**Comment by stepps00** [comment]
Verified that all adm0 features in Who's On First have all properties (and correct values) from the Natural Earth `ne_10m_admin_0_countries` file. The one exception is:

`"ne:fips_10"` (Natural Earth file)
`"ne:fips_10_"` (Who's On First record)

The values in Who's On First are correct.

**Comment by nvkelso** [comment]
Let's remove the trailing _ from WOF ne property.
