### ISSUE TITLE
deprecated places exported in bundles

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1030]
heya,

I've been working with the bundles today and found that the deprecated place `420559115` was in the `neighbourhood` bundle.

Is this the expected behavior for bundles?

I know they don't contain alt geometries, could you please point me in the direction of some code or docs which explains what is included/excluded from bundles when they are generated?

- https://whosonfirst.mapzen.com/spelunker/id/420559115/

Thanks!

**Comment by thisisaaronland** [comment]
Nothing is excluded from bundles. Those decisions are left to consumers of the data.

**Comment by missinglink** [comment]
Agh cool, thanks!

**Comment by thisisaaronland** [comment]
I am not opposed to generating trimmed/pruned bundles but they do not exist today and will require typing specific to the task, in these places:

* https://github.com/whosonfirst/go-whosonfirst-bundles/blob/master/bundles.go#L16-L27
* https://github.com/whosonfirst/go-whosonfirst-bundles/blob/master/bundles.go#L155-L183
* https://github.com/whosonfirst/go-whosonfirst-clone/blob/master/clone.go#L357-L384

**Comment by thisisaaronland** [comment]
Related: https://github.com/whosonfirst/go-whosonfirst-index/issues/4
