### ISSUE TITLE
Standardize harvested Statoids properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1031]
Some records were imported with `statoids:as_of_date`, while others were imported with `statoids:as-of-date`. Standardize the `statoids:` properties.

PR https://github.com/whosonfirst-data/whosonfirst-data/pull/943 was completed to fix this issue, but we do not have an open issue for this.

**Comment by nvkelso** [comment]
Since #943 has been merged, closing.
