### ISSUE TITLE
Investigate qs_pg neighbourhood points that fall outside locality boundaries

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1032]
The `qs_pg` import included neighbourhood records that fall "in the water" and outside of locality boundaries. Example:

Lincoln Park, NJ: https://whosonfirst.mapzen.com/spelunker/id/1126075727/

This is a valid area of Jersey City, NJ, but the geometry is offset. The true location of this place falls under/near [West Bergen](https://whosonfirst.mapzen.com/spelunker/id/85855225/). Investigate the ~1000 neighbourhood records in the list below.

[watery-neighbourhoods-id.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1479944/watery-neighbourhoods-id.txt)

**Comment by nvkelso** [comment]
This is a dup of https://github.com/whosonfirst-data/whosonfirst-data/issues/137. Closing this one in favor of the original.
