### ISSUE TITLE
mz:is_current property not set on all records

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1033]
heya,

I was trying to use the `mz:is_current` field today to filter out non-current records from bundles.

I noticed that some records don't have this field set, eg. `0/0.geojson`.

If this the expected behavior? I'm guessing the correct behaviour here is to assume `mz:is_current=1`

Thanks

**Comment by missinglink** [comment]
Working with this field is quite difficult at the moment, due to the mixed-bag of values.

Summary of values of `mz:is_current` field, for all bundles:

|value|type|count|
|---|---|---|
|-1|integer|473411|
||null|147156|
|0|integer|42323|
|1|integer|31300|
|1|text|3258|
|0|text|609|

The field is additionally difficult to deal with when the NULL values need to be converted to `1` instead of `0`.

Would it be possible to do a batch fix up to:
- ensure that the field is always present
- standardize the types to either `string` or `integer` 

Thanks!

**Comment by stepps00** [comment]
Thanks for the issue @missinglink - our export tools, specifically [this section](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L129-L140), ensure an `mz:is_current` property exists on each updated record. Check out the [mz property description](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/README.md#is_current) for value descriptions.

Anything tagged with a `0` value is "not current", anything with a `1` is presumed "current", and anything with a `-1` (and `NULL` value) is "undetermined" and needs review.

I am not opposed to doing a batch update in the future to tag all null values with `-1`, but the more immediate issue to fix is converting the string values to integers. I'll keep this issue open to track those changes.

**Comment by thisisaaronland** [comment]
@dphiffer - would you double-check and make sure that BI isn't encoding these as strings; no reason to think that it is but since we're all here talking about it...

**Comment by stepps00** [comment]
This was fixed in recent work on each per-country repo. Each WOF record should now have this property set (with an int value).
