### ISSUE TITLE
possibly duplicate 'Saint Peter Port'

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1043]
these two records appear to be duplicates of the same `locality`

- https://whosonfirst.mapzen.com/spelunker/id/1125780105/
- https://whosonfirst.mapzen.com/spelunker/id/1125821075/

**Comment by stepps00** [comment]
Yeah, these are two duplicate records. Since there are both point geometries, this should be a relatively quick fix in BI. Stay tuned.

**Comment by stepps00** [comment]
Closed, but relevant: https://github.com/whosonfirst-data/whosonfirst-data/issues/738

**Comment by nvkelso** [comment]
(Going thru BI, still.)

**Comment by stepps00** [comment]
https://whosonfirst.mapzen.com/spelunker/id/1125821075/ and https://whosonfirst.mapzen.com/spelunker/id/1125780105/ have been updated through BI, closing issue.
