### ISSUE TITLE
Set default mz:min_zoom on all features

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1047]
@nvkelso to add details.

**Comment by stepps00** [comment]
@nvkelso do we have a min/max zoom lookup chart per placetype?

Sub-locality zoom levels are here: https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/issue_workflows/sf_neighbourhood_updates_pt_2.md#setting-min_zoom-and-max_zoom

**Comment by nvkelso** [comment]
See also:

- Tilezen OSM > min_zoom calculation
    https://github.com/tilezen/vector-datasource/blob/ff43086cb7a4f11bba5f1774fd451a4401e42286/vectordatasource/transform.py#L1218-L1245

**Comment by nvkelso** [comment]
_NOTE: there are floats in there not just ints._

placetype | mz:min_zoom | mz:max_zoom | lbl:min_zoom | lbl:max_zoom | note
--- | --- | --- | --- | --- | ---
address | 17 | | | | from Tilezen
arcade | 17.5 | | 17.5 | 19 |
borough | 10 | | | 13 | min_zoom to 9 for important places
building | 16 | | | | min_zoom to 13 for important places
campus | 13 | | | | min_zoom to 11 for important places
concourse | 17 | | 17 | 18.5 |
constituency | | | | | skip this one
continent | 1 | | | 5 |
country | 0 | | 4 | 8 | lbl:min_zoom and lbl:max_zoom vary followup with issue later per links
county | 6 | | 8 | 10 |
dependency | 0 | | 4 | 8 | lbl:min_zoom and lbl:max_zoom vary followup with issue later per links
disputed | 0 | | 6 | 10 | lbl:min_zoom and lbl:max_zoom vary followup with issue later per links
empire | | | | | skip this one
enclosure | 18 | | 18 | 20 |
installation | 19 | | | |
intersection | | | | | skip this one
localadmin | 9 | | 11 | 13 |
locality | 9 | | 11 | 15 | varies widely by population
macrocounty | 5 | | 9 | |
macrohood | 13 | | | 15 | min_zoom to 1 for important places
macroregion | 3 | | 5 | 7 |
marinearea | 4 | | | |  
metroarea | | | | | skip this one
microhood | 16 | | | 18 | rarely modify min_zoom or max_zoom
neighbourhood | 15 | | | 18 | min_zoom to 13 for important places
ocean | 0 | | | 10 | 
planet | | | | | skip this one
postalcode | | | | | skip this one
region | 4 | | 8 | | lbl:min_zoom and lbl:max_zoom vary followup with issue later per links
timezone | | | | | skip this one
venue | 16 | | | | min_zoom to 13 for important places, zoom 17+ for less important places
wing | 16 | | 16.5 | 18 |

**Comment by stepps00** [comment]
> NOTE: there are floats in there not just ints.

The [min](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/min_zoom.json) and [max](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/max_zoom.json) zoom props are floats, so all ints in the table above will be imported as floats.

**Comment by nvkelso** [comment]
For `locality` and `localadmin` we can do something like:

population_rank | mz:min_zoom | mz:max_zoom | lbl:min_zoom | lbl:max_zoom | note
-- | --- | --- | --- | --- | ---
18 | 1 | | 2.5 | 12 | Over 1b
17 | 1.5 | | 2.5 | 12 | 100m to 1b
16 | 2 | | 2.5 | 12 |  50m to 100m
15 | 2.1 | | 2.5 | 12 |  20m to 50m
14 | 2.5 | | 2.5 | 12 |  10m to 20m
13 | 3 | | | 12 |  5m to 10m
12 | 4 | | | 13 |  1m to 5m
11 | 5 | | | 13 |  500k to 1m
10 | 6 | | | 13 |  200k to 500k
9  | 7 | | | 14 | 100k to 200k
8  | 8 | | | 14 | 50k to 100k
7  | 9 | | | 14 | 20k to 50k
6  | 10 | | | 15 | 10k to 20k
5  | 11 | | | 15 | 5k to 10k
4  | 11 | | 11.5 | 15 | 2k to 5k
3  | 11 | | 12 | 16 | 1k to 2k
2  | 11 | | 12.5 | 17 | 200 to 1k
1  | 11 | | 13 | 18 | Less than 200
0  | 11 | | 13.5| 18 | Locale (no population) / places that only are visible at 50k scale or larger (but not neighbourhoods)

See also:

- https://github.com/whosonfirst/whosonfirst-properties/blob/238803ee5465ae6d372ef98b3da760e75882d529/properties/wof/README.md

**Comment by stepps00** [comment]
New zoom properties and values were added in recent crawls of each per-country repo. Closing.
