### ISSUE TITLE
Invalid names for 85894597 "Le Village de la Gare" (merge issue ?)

### ISSUE THREAD

**Issue by amatissart** [whosonfirst-data/whosonfirst-data#1049]
Neighbourhood [85894597](https://whosonfirst.mapzen.com/spelunker/id/85894597/) in Canada has several names that reference ["Gare de Marne-la-Vallée - Chessy"](https://www.wikidata.org/wiki/Q801167), which is a completely unrelated train station in France.

It seems to be caused by a2091c1f9. But this commit is too large for me to check if other side-effects exist or if that is an isolated issue.

**Comment by stepps00** [comment]
Thanks for the issue @amatissart - I will take a look and verify correct names for this record. Stay tuned.

**Comment by stepps00** [comment]
Hey @amatissart - I've gone ahead and reworked the `name:*` properties for [Le Village de la Gare](https://whosonfirst.mapzen.com/spelunker/id/85894597/), they should no longer contain references to the train station with a similar name. 

This is fixed, so closing issue. Thanks again!
