### ISSUE TITLE
Add concordance with Quattroshapes gazetteer IDs to QS geoms

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#105]
Quattroshapes has a separate gazetteer point file with unique, stable IDs (ints), we should add concordance to those, and import the more, better properties. That'll also get us more GeoNames.org and WOE GeoPlanet ID concordances.

**Comment by stepps00** [comment]
@nvkelso - is this the "quatroshapes localities (with geonames concordance) - 420 mb" file? ([link](http://static.quattroshapes.com/gn-qs_localities.zip))

**Comment by nvkelso** [comment]
Good enough with #824.
