### ISSUE TITLE
[Duplicate] city Conflans-Sainte-Honorine

### ISSUE THREAD

**Issue by antoine-de** [whosonfirst-data/whosonfirst-data#1050]
Hi,

It seems to be 2 locality named "Conflans-Sainte-Honorine" (both belonging to the same [county](https://whosonfirst.mapzen.com/spelunker/id/102065383/)):

 * https://whosonfirst.mapzen.com/spelunker/id/101749953/
 * https://whosonfirst.mapzen.com/spelunker/id/1125878541/

the first one has a nice shape and is from `quattroshapes` whereas the second is only a point and is derived from `qs_pg` (but what is the difference between `qs_pg` and `quattroshapes` ?)

I would vote for the removal of the second locality (and I can try to do it if you agree on it), but maybe there is a better way to handle this.

**Comment by stepps00** [comment]
Hi @antoine-de , thanks for the issue.. these are duplicate features. I've gone ahead and updated the two records, deprecating the point record and keeping the record with a full geometry - changes to these records should be seen shortly.

To answer your question, "Quattroshapes" is a source name used to represent any geometry or property from Quattroshapes, while "qs_pg" represents any geometry or property from Quattroshape's point gazetteer.

Our [sources repo](https://github.com/whosonfirst/whosonfirst-sources/tree/master/sources) has a bit more information about the difference between the two source names.

I'll close this issue and link the change commits to this issue once the changes are processed. Stay tuned.

**Comment by stepps00** [comment]
1/2: https://github.com/whosonfirst-data/whosonfirst-data/commit/1bc4bfbe08ee900934fc2c5223191552db824d0e

**Comment by stepps00** [comment]
This issue was taken care of via Boundary Issues (commit links above). Closing.
