### ISSUE TITLE
Refine admin polygons in Germany, including Köln (Cologne)

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#1051]
This came in through support (see Desk 291). 

The user was looking for a geojson of the full hierarchy of a german federal state down to cities, for example of "Nordrhein-Westfalen".

Mapzen places provides UMZ Urban Polygons for the cities and not the geometries of the real administrative places. Köln (Cologne) does not look very complete. 

https://whosonfirst.mapzen.com/spelunker/id/404227541/

Dropping in an issue here for this.

**Comment by stepps00** [comment]
I'm closing this issue, as it will be taken case of as part of https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1. Let's use https://github.com/whosonfirst-data/whosonfirst-data/issues/1606 for all related admin updates in Germany.
