### ISSUE TITLE
Lack of lots of Japanese translation

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [whosonfirst-data/whosonfirst-data#1060]
Hi,

Many features in Japan lack Japanese translations.

For example, in the following statistics, Japan has 1738 counties, but only 439 (25%) counties have Japanese translations. 

https://whosonfirst.mapzen.com/spelunker/id/85632429/descendants/?exclude=nullisland&placetype=county

Why? 

I read this[ blog post on adding translations done in this summer](https://mapzen.com/blog/summer-2017-wof/), and found he did a good job.

We wish we could use WoF because the places API seems nice, but we can't.

**Comment by stepps00** [comment]
Hey @HIRANO-Satoshi - thank you for the issue. 

Much of translation and name addition work was done using [GeoNames](http://www.geonames.org/) concordances. This relies on a concordance value in each Who's On First record; many of the county records in Japan were recently imported through our [Mesoshapes work](https://mapzen.com/blog/mesoshapes/), which did not include any concordance values. 

Once concordances are added to our county records in Japan, we can easily re-run our GeoNames work. Alternatively, we can use another source, like the [Japanese governments free gazetteer](https://github.com/whosonfirst-data/whosonfirst-data/issues/90) to import new names.

Either way, I'll use this issue to track name updates for Japan admin name updates at all placetypes.

**Comment by HIRANO-Satoshi** [comment]
@stepps00  Thanks for your reply. I understand. For example [this](https://whosonfirst.mapzen.com/spelunker/id/890519957/) has concordance (geonames 7452809)
and Japanese names while [another one](https://whosonfirst.mapzen.com/spelunker/id/1108740275/) does not have both.

GeoNames has many Japanese names, but I found many lack preferred flag and it shows one of alternative names.

I looked at the "Japanese governments free gazetteer" but it is dated in 2007. The owner @nyampire seems a map person working for OSM as a member of OSM Foundation Japan . Maybe he knows more recent sources.

@nyampire Could you kindly tell us what your [KSJ2-adm-boundary-2015](https://github.com/nyampire/KSJ2-adm-boundary-2015) repo include? Have you finished importing it to OSM?

01_Hokkaido-fix.osm includes the following content.

```
  <node id='-1393624' visible='true' lat='43.304985' lon='142.05012' />
  <node id='-1393622' visible='true' lat='43.304915' lon='142.049723' />
  <node id='-1393620' visible='true' lat='43.304896' lon='142.049431' />
  <node id='-1393618' visible='true' lat='43.305123' lon='142.049336' />
  <node id='-1393616' visible='true' lat='43.305436' lon='142.049179' />
  <node id='-1393614' visible='true' lat='43.305674' lon='142.048995' />
  <node id='-1393612' visible='true' lat='43.305904' lon='142.048509' />
  <node id='-1393610' visible='true' lat='43.306012' lon='142.04825' />
  <node id='-1393608' visible='true' lat='43.306213' lon='142.047991' />
  <node id='-1393606' visible='true' lat='43.306654' lon='142.047621' />
...skipping...
    <tag k='name' v='月形町' />
    <tag k='name:en' v='Tsukigata' />
    <tag k='name:ja' v='月形町' />
    <tag k='name:ja_kana' v='つきがたちょう' />
    <tag k='name:ja_rm' v='Tsukigata-Cho' />
    <tag k='source' v='KSJ2/N03' />
    <tag k='type' v='boundary' />
  </relation>
  <relation id='-1818827' action='modify' visible='true'>
    <member type='way' ref='-1828078' role='outer' />
    <member type='way' ref='-1828712' role='outer' />
    <tag k='type' v='boundary' />
  </relation>
  <relation id='-1818827' action='modify' visible='true'>
    <member type='way' ref='-1828078' role='outer' />
    <member type='way' ref='-1828712' role='outer' />
    <member type='way' ref='-1828489' role='outer' />
    <member type='way' ref='-1828383' role='outer' />
    <tag k='admin_level' v='7' />
    <tag k='boundary' v='administrative' />
    <tag k='name' v='京極町' />
    <tag k='name:en' v='Kyogoku' />
    <tag k='name:ja' v='京極町' />
    <tag k='name:ja_kana' v='きょうごくちょう' />
    <tag k='name:ja_rm' v='Kyogoku-Cho' />
    <tag k='source' v='KSJ2/N03' />
    <tag k='type' v='boundary' />
  </relation>
```

**Comment by nyampire** [comment]
Hello @HIRANO-Satoshi.
Administrative boundary import 2015 was already finished. But I feel it is not well maintained those days. (e.g. I'm realizing the change of municipality boundary about 黒川郡富谷町, 2016 Oct 10.th)
As you mentioned above, it contains Japanese name (漢字), English name, Hiragana and Romanized description.
It is about municipality name. Not neighbourhood (丁目/字) data.

If you want to improve JP name with those data, I recommend to add 地方公共団体コード ([discussion](https://lists.openstreetmap.org/pipermail/talk-ja/2017-September/009858.html)) first as primary key to join.

**Comment by HIRANO-Satoshi** [comment]
@nyampire  Thanks for your prompt reply. I understand. 

I think it must be nice data for WoF, since locality and county seems in confusion in WoF, actually.
I would appreciate if you could help WoF people to import your data. I'm not familiar with maps and addresses.
Do you have any plan to update your repo?

You mentioned about Japanese municipality ID system. It would be nice if WoF people could import it in concordance. Actually, the data is written in Japanese and I don't think they understand it. I have just written an email to the governmental agency for improvement.

http://www.soumu.go.jp/denshijiti/code.html

**Comment by nyampire** [comment]
@HIRANO-Satoshi Unfortunately I have no plan to improve [my repo](https://github.com/nyampire/KSJ2-adm-boundary-2015). Because it is for the page for OSM data import clarification.
I'm not familiar with WoF dataset & format, and I'm not a code person :). 
If you could work on that import to WoF, I would like to help.

> English name of JP municipality
Some of government sector has plan to make those dataset as official (GSI, Geospatial Information Authority is making the dataset and government CIO has published the draft guideline for English name.)
So if you need more "official" dataset, it may be better to wait until 2018 April.

**Comment by HIRANO-Satoshi** [comment]
Okay, thanks.

GSI will publish a new dataset of the official IDs.

You think the original source of your repo will include the new official IDs (maybe after long delay),  or you need to import the IDs into your repo if you want to do so?

**Comment by HIRANO-Satoshi** [comment]
Since I have switched to OpenStreetMap data, I no longer need to resolve this issue. 

Thanks much, @stepps00, @nyampire.
