### ISSUE TITLE
Hole in Kazakhstan country

### ISSUE THREAD

**Issue by nlehuby** [whosonfirst-data/whosonfirst-data#1068]
https://whosonfirst.mapzen.com/spelunker/id/85632307/

The country of Kazakhstan has a strange circular hole around the Байконур city

![screenshot-2018-1-3 kazakhstan 85632307](https://user-images.githubusercontent.com/919962/34522018-071750bc-f091-11e7-9430-4313a371c475.png)

**Comment by nvkelso** [comment]
That’s the cosmodrome, a lease area with Russia. 

The “right” / consistent thing to do here would be adding a sovereignty for Kaz that also includes the “circle”.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/blob/69f1945017f03b608b3276dc389a6e715c512f9d/data/115/933/953/5/1159339535.geojson

**Comment by stepps00** [comment]
This issue will be fixed as a subtask of https://github.com/whosonfirst-data/whosonfirst-data/issues/1930.

**Comment by stepps00** [comment]
This issue was fixed recently. The geometry of Kazakhstan no longer has a hole over the cosmodrome.

https://spelunker.whosonfirst.org/id/85632307/
https://github.com/whosonfirst-data/whosonfirst-data-admin-kz/blob/master/data/856/323/07/85632307.geojson
