### ISSUE TITLE
5 places have a wof:country that is not a two letter ISO code (it's -99 instead)

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1070]
Using the excellent `whosonfirst-data-latest.db` SQLite file:

    sqlite3 whosonfirst-data-latest.db
    sqlite> select id from geojson where length(json_extract(body, '$.properties."wof:country"')) > 2;
    421173973
    1141906215
    1141906217
    1141908383
    1141908385

Further inspection:

	sqlite> select id, json_extract(body, '$.properties."wof:name"'), json_extract(body, '$.properties."wof:country"') from geojson where id in (421173973, 1141906215, 1141906217, 1141908383, 1141908385);
	421173973|Ceerigaabo|-99
	1141906215|Laascaanood|-99
	1141906217|Ceerigaabo|-99
	1141908383|Boorama|-99
	1141908385|Maydh|-99

**Comment by simonw** [comment]
All five of those are within Somaliland https://whosonfirst.mapzen.com/spelunker/id/85632733/ - which https://en.wikipedia.org/wiki/Somaliland says is "a self-declared state internationally recognised as an autonomous region of Somalia"

Somaliland in Who's On First https://whosonfirst.mapzen.com/spelunker/id/85632733/ has a `wof:country` of `XS` - https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#XS says "The codes XE, XS and XW are used by WhatsApp to represent the flags of England, Scotland and Wales as Emoji"

**Comment by thisisaaronland** [comment]
@nvkelso @stepps00 is `XY` or `XX` the correct country code to assign in this instance?

https://github.com/whosonfirst/whosonfirst-placetypes#iso-country-codes

**Comment by nvkelso** [comment]
If we’re using XS for Somaliland the country than let’s be consistent and reuse that.

All X* codes are user defined versus standards so it’s all fair game in that range.

**Comment by straup** [comment]
`XS` it is. I will update the `placetypes` docs accordingly. We should probably make a machine-readable lookup table for the `X*` countries but one thing at a time...

@simonw are you comfortable trapping this in code on your end for the time being? Where "time being" means long enough for me to finish up the GH -> updated -> S3 hooks using these records to test with.

**Comment by simonw** [comment]
Very happy - I've baked this special case into my import script
