### ISSUE TITLE
Point geometry in Sudan

### ISSUE THREAD

**Issue by peterneubauer** [whosonfirst-data/whosonfirst-data#1074]
It seems https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/421/188/081/421188081.geojson is containing just a point as the shape and thus shouldd be adapted to a polygon or removed?

**Comment by stepps00** [comment]
Hey @peterneubauer - thanks for the issue. 

Who's On First maintains both point geometries and polygon geometries - both are valid geometry types for our records. Additional records with point geometries in Sudan can be found [here](https://whosonfirst.mapzen.com/spelunker/id/85632751/descendants/?exclude=nullisland&geometry=point).

Ideally, we would update these geometries with polygons, but until we are able to verify a data source with an [open license](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/definition/data_licenses.md), we'll have to keep this record (and others) as is.

**Comment by peterneubauer** [comment]
Ok,
I was under the impression that on country level, all shapes were polygons. Will just check to exclude Point geometries from our system.

Thanks @stepps00 for the fast answer!
