### ISSUE TITLE
Greenfield Town is the wrong name for Greenfield, MA

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1077]
One of our users was confused by "Greenfield Town, MA" in our search results.

https://places.whosonfirst.org/id/85950383

This does seem like an odd name for https://en.m.wikipedia.org/wiki/Greenfield,_Massachusetts

**Comment by simonw** [comment]
It looks like there is a local controversy related to this: http://www.recorder.com/Greenfield-residents-will-have-chance-to-weigh-in-before-city-town-vote-14410321

Nevertheless, for Who's On First I feel "Greenfield" is a more correct name than "Greenfield Town". In fact that article suggests that the correct name would be "The City known as the Town of Greenfield".

**Comment by simonw** [comment]
Hah, I just found this deprecated record for "City of Greenfield Town" https://places.whosonfirst.org/id/1125365187/

**Comment by simonw** [comment]
Recent news story from December 21st 2017: http://nepr.net/post/identity-crisis-no-more-greenfield-mass-finally-calls-itself-city

**Comment by stepps00** [comment]
Fixed via: https://github.com/whosonfirst-data/whosonfirst-data/pull/1078
