### ISSUE TITLE
Invalid wof:hierarchy for 85632605, 85632663 and 85784759

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1079]
The `wof:hierarchy` field on these three events has `e_id` or `o_id` or similar proporties, which are invalid - all other hierarchy property keys in Who's On First are of the form `country_id` etc:

https://places.whosonfirst.org/id/85632605

	[
	    {
	        "continent_id": 102191569,
	        "country_id": 85632605,
	        "e_id": 85632605,
	        "g_id": 85632605,
	        "i_id": 85632605,
	        "n_id": 85632605,
	        "o_id": 85632605,
	        "r_id": 85632605
	    }
	]

I initially thought this should be `"region_id": 85632605` but that's the same place ID as the country itself (this place is a country) so actually I think these keys should just be removed.

https://places.whosonfirst.org/id/85632663

	[
	    {
	        "continent_id": "102191583",
	        "country_id": 85632663,
	        "e_id": 85632663,
	        "g_id": 85632663,
	        "i_id": 85632663,
	        "n_id": 85632663,
	        "o_id": 85632663,
	        "r_id": 85632663
	    }
	]

I initially thought this should be `"region_id": 85632663` but that's the same place ID as the country itself (this place is a country) so actually I think these keys should just be removed.

https://places.whosonfirst.org/id/85784759

	[
	    {
	        "b_id": 85784759,
	        "continent_id": 102191575,
	        "country_id": 85633041,
	        "g_id": 85784759,
	        "h_id": 85784759,
	        "locality_id": 101738793,
	        "neighbourhood_id": 85784759,
	        "o_id": 85784759,
	        "r_id": 85784759,
	        "region_id": 136251273,
	        "u_id": 85784759
	    }
	]

I initially thought this should be `"borough_id": 85784759` but that's the same place ID as the neighbourhood itself (this place is a neighbourhood) so actually I think these keys should just be removed.

**Comment by simonw** [comment]
Pull request: https://github.com/whosonfirst-data/whosonfirst-data/pull/1080

**Comment by stepps00** [comment]
Fixed via: https://github.com/whosonfirst-data/whosonfirst-data/pull/1116
