### ISSUE TITLE
Add GeoNames populated places not already in WOF

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#108]
Related #109.

~Blocked by:~
~- #107 Add QS gazetteer points for places not already in WOF~
~- #106 Add rough city polygon data for areas not covered by Quattroshapes~
~- #105 Add concordance with Quattroshapes gazetteer IDs to QS geoms~
~- #104 Add concordance with Natural Earth admin-1~
~- #103 Add concordance with Natural Earth admin-0 countries~

**Comment by nvkelso** [comment]
This would be any place in GeoNames that doesn't already have a concordance, in the following general place types:

- `country` (deprecate)
- `disputed` (deprecate)
- `dependency` (deprecate)
- `continent` (deprecate)
- `ocean` (deprecate)
- `marinearea` (deprecate)
- `macroregion` (deprecate)
- `region` (deprecate)
- `macrocounty` (deprecate)
- `county` (deprecate)
- `localadmin` (by country if Quattroshapes had good polygons deprecate e.g. in UK, France, else import)
- `locality`
- `neighbourhood` (with special handling for Zach's polygons and Nat's points)

**Comment by stepps00** [comment]
@thisisaaronland I'm going to start working on this issue this week, but having difficulties pooling 4M+ ids from BrooklynIntegers. Would there be an issue with minting even-numbered unique ids locally to use for new records' wof:ids?

**Comment by thisisaaronland** [comment]
You mean https://www.missionintegers.com/ ? Those will be even slower because "the cloud".

Let me see what the what is with Brooklyn Integers...

**Comment by stepps00** [comment]
FWIW, I'm able to mint new Brooklyn Integers via `requests` in Python slowly, but seeing:

```ERROR failed to create new integer, because Failed to generate any integers```

when using the `go-whosonfirst-api` tools. Ideally I could grab 4.5M ids at once and append them to the GeoNames import file(s).

**Comment by thisisaaronland** [comment]
Yeah, so it's important to remember that what you are trying to do _is an edge case_.

It is not possible to "grab 4.5 _million_ IDs at once" because... well, it's an edge case. It may be that you need to spin up (n) processes to grab (y) integers each, accounting for failures along the way and then stitch them back in to a single file that your code can reference.

**Comment by thisisaaronland** [comment]
Also, when you are seeing `Failed to generate any integers` errors it is most likely that the API (really the database) is being throttled. I tried (maybe not hard enough...) to have Smithsonian Library take over the running of BI as a public service but until then we go to war with the rate-limits we have...

**Comment by stepps00** [comment]
>>>  It may be that you need to spin up (n) processes to grab (y) integers each, accounting for failures along the way and then stitch them back in to a single file that your code can reference.

:+1: This is what I've started doing in the meantime.

**Comment by nvkelso** [comment]
I'm fine calling the **locality** PRs good enough. 

We've done enough original research on the coarse geocoding placetypes (like `county` and `region`) that we effectively own it and think what we have in WOF is good as-is. The neighbourhoods are also a mixed bag, I'm hesitant to add more chaos to the mix.

So yes, I'd close this issue once #1394 is merged :)
