### ISSUE TITLE
Two records for the locality of Nashville

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1082]
This Nashville locality looks good: https://places.whosonfirst.org/id/101723183

This one (a point-only geometry) appears to be an unnecessary duplicate: https://places.whosonfirst.org/id/1141909337

**Comment by stepps00** [comment]
Thanks @simonw - I'll take care of this duplicate Nashville set..

**Comment by stepps00** [comment]
This duplicate pair is being tracked in: https://github.com/whosonfirst-data/whosonfirst-data/pull/1272

**Comment by stepps00** [comment]
This duplicate pair has been taken care of in a recent [pull request]().

Point record (now "not current"): https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/114/190/933/7/1141909337.geojson

Polygon record (current, superseding the point record): https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/101/723/183/101723183.geojson
