### ISSUE TITLE
Potential duplicate records for Birmingham/Wolverhampton/Walsall/Dudley

### ISSUE THREAD

**Issue by commadelimited** [whosonfirst-data/whosonfirst-data#1086]
When trolling through the WOF data set I came across these seemingly duplicate entries.

```
wof_id, name
101914055, Birmingham/Wolverhampton/Walsall/Dudley
101914057, Birmingham/Wolverhampton/Walsall/Dudley
101914039, Birmingham/Wolverhampton/Walsall/Dudley
101914033, Birmingham/Wolverhampton/Walsall/Dudley
101914027, Birmingham/Wolverhampton/Walsall/Dudley
101914049, Birmingham/Wolverhampton/Walsall/Dudley
101914045, Birmingham/Wolverhampton/Walsall/Dudley
101914043, Birmingham/Wolverhampton/Walsall/Dudley
101914031, Birmingham/Wolverhampton/Walsall/Dudley
101914035, Birmingham/Wolverhampton/Walsall/Dudley
101914037, Birmingham/Wolverhampton/Walsall/Dudley
101914041, Birmingham/Wolverhampton/Walsall/Dudley 
```

**Comment by stepps00** [comment]
This is great - thanks @commadelimited.

It looks like this is a case of a MultiPolygon feature being imported as several records, rather than a single record. I'll investigate and propose a change soon.

**Comment by commadelimited** [comment]
Glad to help.

**Comment by stepps00** [comment]
Will be included in: https://github.com/whosonfirst-data/whosonfirst-data/pull/1436

**Comment by stepps00** [comment]
Each of these cases had been taken care of and replaced with new locality/localadmin coverage. 

Closing this issue, I'll circle back and link to new records once the Spelunker is up-to-date.
