### ISSUE TITLE
Trim name fields

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1087]
Heya,

I noticed that this record has a trailing space in the name, would it be possible to programmatically trim spaces from names when they are added/processed?

```
{
"id": 102063261,
...
"name:eng_x_preferred": [
"München "
],
```

Tx!

**Comment by stepps00** [comment]
@missinglink - definitely possible to catch other instances of these trailing spaces. I'll update this issue with any similar cases.

**Comment by aaparmeggiani** [comment]
If my count is wright, in the same situation you have .. 
```
sqlite> select count(*) from names where name like '% ';
70117
```
with the top culprits .. 

```
sqlite> select id, count(*) as count from names where name like '% ' group by id order by count desc;
     id     | count
------------+-------
 1125892065 |   174
  101748691 |    67
  101819833 |    65
  101819723 |    64
 1125905623 |    64
 1125945577 |    64
 1125897693 |    64
 1126049711 |    64
 1126011967 |    64
 1125786193 |    63
```

**Comment by aaparmeggiani** [comment]
Not only whitespaces, but I also found a couple of \n (s) which are being carried to the sqlite files and breaking csv exports .. 

```
gis=# select id, name, regexp_matches(name, '[\n]+' ) from spr;
     id     |             name             | regexp_matches
------------+------------------------------+----------------
   85801073 | Vivier d'Oie                +| {"            +
            |                              | "}
 1108943237 | Tosko Celo                  +| {"            +
            |                              | "}
 1108943249 | Zgornja Hrusica             +| {"            +
            |                              | "}
 1108943285 | Spodnja Zadobrova           +| {"            +
            |                              | "}
 1108943287 | Zgornja Zadobrova           +| {"            +
            |                              | "}
 1108943373 | Dobrava pri Crnucah         +| {"            +
            |                              | "}
 1108946249 |                             +| {"            +
            | Les Pentes croix-roussiennes | "}
 1108946301 |                             +| {"            +
            | Montchat                     | "}
 1108950881 |                             +| {"            +
            | Arnavutkoy Merkez            | "}
(9 rows)
```

Ex: Rel [#1108946301](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/110/894/630/1/1108946301.geojson)
```
    "wof:id":1108946301,
    "wof:lastmodified":1496506772,
    "wof:name":"\nMontchat",
    "wof:parent_id":101749431,
    "wof:placetype":"neighbourhood",
    "wof:repo":"whosonfirst-data",
    "wof:superseded_by":[],
    "wof:supersedes":[],
    "wof:tags":[]
```

Also in the names table:

```
gis=# select id, name, regexp_matches(name, '[\n]+' ) from names;
    id     |               name               | regexp_matches
-----------+----------------------------------+----------------
  85632497 | [                               +| {"            +
           |             "\u5723\u8bde\u5c9b"+| "}
           |         ]                        |
 101737491 | Old Town                        +| {"            +
           | National Capital                 | "}
(2 rows)
```

What's the best way to help/fix?   
 - PR correcting the `.geojson` s ? 
 - PR adding trim/sanitize to the sqlite generators?
 - PR adding tests ??

**Comment by stepps00** [comment]
Hey @aaparmeggiani - thanks for the info. If you are able to provide a list of `wof:id`s with these issues, I can file a PR with fixes to the `name:*` properties to remove erroneous spacing and return values. 

If you have a test you'd like to add, feel free to poke around the [tests repo](https://github.com/whosonfirst/whosonfirst-tests) and submit a PR.

**Comment by aaparmeggiani** [comment]
Hi @stepps00, all id's listed above are `wof:id`s from the original `whosonfirst-data-latest.db` (as you can double-check from the Mountchat ([1108946301](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/110/894/630/1/1108946301.geojson)).  Please find the the whitespace ones [here](https://github.com/whosonfirst-data/whosonfirst-data/files/1816613/names.ids-with-whitespaces.zip), generated from:
```
select distinct(id) from names where name like '% ';
```

Thanks for your help and link to the tests repo!

**Comment by stepps00** [comment]
Thanks @aaparmeggiani - this slipped through the cracks, but I will take a look.

**Comment by stepps00** [comment]
Closed via: https://github.com/whosonfirst-data/whosonfirst-data/pull/1088

**Comment by missinglink** [comment]
related, https://spelunker.whosonfirst.org/id/102063543/

```
"name:eng_x_preferred": [ "Darmstadt " ],
```

there is also a trailing space in the statoids property:

```
"statoids:name": "Darmstadt ",
```

**Comment by vicchi** [comment]
@thisisaaronland _Definitely_ a "yes" to trapping this with the JSON schema ... `patterns.value` is the field you need. Sticking a regex sort-of-but-not-quite like `^[a-zA-Z].*[a-zA-z]$` (and yes, I know, that we'd need to refine this to handle i18n and the like) into `patterns.value` would allow the JSON schema validation to holler loudly at the presence of leading and trailing whitespace. I sort of designed the extensions to the properties definitions to be used in this sort of way.

Once identified, we could add code to actually _fix_ and thus trim the offending whitespace into the `wof-fix-props` script that lurks here: https://github.com/whosonfirst/py-mapzen-whosonfirst-geojson/blob/master/scripts/wof-fix-props.

With the caveat that I seem to have a day job now and that whilst this should be straightforward-ish to implement, check/validate and fix, I'll assign this to myself and take a look as soon as I have some spare time.

**Comment by stepps00** [comment]
#1564 was just merged to fix any existing issue of a trailing space in a `name:` property. Feel free to re-open if there are other records affected or more work around catching these cases programatically.
