### ISSUE TITLE
471/260/517/471260517.geojson has invalid coordinates

### ISSUE THREAD

**Issue by n3ziniuka5** [whosonfirst-data/whosonfirst-data#1095]
link - https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/blob/master/data/471/260/517/471260517.geojson

There are some other postcodes like this as well. Would it be possible to somehow filter out such postcodes? Or fix the data?

**Comment by stepps00** [comment]
Hey @n3ziniuka5 - thanks for the issue. 

Who's On First does have quite a few `postalcode` records with null geometries (with coordinates falling at `0,0`). We do know that these places exist, in this case the postal code "NW3 2EZ", but we have not found accurate openly licensed data to use to update our records. Until then, we'll use this record to maintain properties about "NW3 2EZ".

If we do find open data for postal codes that have geometries, we can definitely update our records, but until then we'll have to store null geometries.

**Comment by stepps00** [comment]
Closing and picking up when we find better data.
