### ISSUE TITLE
102062935 needs name and hierarchy updates

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1104]
https://spelunker.whosonfirst.org/id/102062935/

This record is a `county` in Switzerland, representing water bodies between Switzerland and Italy. However, it's centroid is causing the hierarchy to include Italy (instead of Switzerland). Also, this record does not have a `wof:name`. 

Either update the record with new `wof:name`, `reversegeo:latitude`, and `reversegeo:longitude` properties, or deprecate this record.

**Comment by stepps00** [comment]
When updating `county`-level admin records in the past, we've generally removed records like this, as they serve no administrative purpose at the `county` level.

**Comment by nvkelso** [comment]
Another option is to set to exclude from hierarchy label and mz:is_funky = 1, possibly also statistical gore since the authoritative sources seem to include it.
