### ISSUE TITLE
Add Finland admin2 records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1105]
WOF is missing 70 `admin2`-level [sub-regions](https://en.wikipedia.org/wiki/Administrative_divisions_of_Finland) of Finland -- find a new source and update accordingly.

**See:**
- https://en.wikipedia.org/wiki/Administrative_divisions_of_Finland
- http://www.statoids.com/ufi.html
- http://www.statoids.com/yfi.html

**Comment by stepps00** [comment]
Related #1099

**Comment by stepps00** [comment]
Tagging @vesameskanen and @hannesj, as you both have helped update Finland WOF records in the past - I'd like to create new records for Finland subregions ("seutukunta"), but am unable to find open data for this administrative division.

The National Land Survey of Finland does not seem to have this data.. do either of you know of a source for this division?

**Comment by vesameskanen** [comment]
Hi, 
I could only find these:

https://www.opendata.fi/data/en/dataset/tilastokeskuksen-palvelurajapinta-wfs
http://geo.stat.fi/geoserver/wfs?service=WFS&request=GetCapabilities&version=1.0.0

The wfs service seems to include seutukunta division.  I hope it helps.
