### ISSUE TITLE
Updates to Singapore and descendants

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1109]
In WOF, [Singapore](https://spelunker.whosonfirst.org/id/85632605/) currently has following descendant records:

- 72 `locality` records
- five `region` records
- two `county` records
- one `neighbourhood` record

However, Singapore is a city-state with the following actual administrative divisions:

- Five [regions](https://en.wikipedia.org/wiki/Regions_of_Singapore)
- 29 [constituencies](https://en.wikipedia.org/wiki/Constituencies_of_Singapore)
- 55 [planning areas](https://en.wikipedia.org/wiki/Regions_of_Singapore)

Update records as appropriate.

**Comment by nvkelso** [comment]
Are the constituencies local admin or county or? 

Are the planning areas neighbourhood... or at least seeds for neighbourhood a or macro hoods?

**Comment by stepps00** [comment]
I would expect the breakdown in Singapore to look something like:

- One country (`"wof:placetype":"country"`)
- Five regions (`"wof:placetype":"region"`)
- 29 constituency (`"wof:placetype":"localadmin"`)
- 55 planning areas  (`"wof:placetype":"neighbourhood"`)

Not all planning areas have administrative function, though. So the planning areas may need a bit of work to determine if we need to add a statistical_gore (or similar) flag to each of those records.

Detailed map of placetypes for reference: https://www.singstat.gov.sg/docs/default-source/default-document-library/publications/publications_and_papers/population_and_population_structure/population2015-map1.pdf

**Comment by stepps00** [comment]
And, in addition to this, the current geometries in WOF at the [country](https://spelunker.whosonfirst.org/id/85632605/) and region levels should be updated.

**Comment by missinglink** [comment]
Added a comment on https://github.com/whosonfirst-data/whosonfirst-data/issues/1092#issuecomment-776312261 regarding subdivisions of the planning areas.

**Comment by missinglink** [comment]
note: the link above to `singstat.gov.sg` is now returning 404, this one works:
https://www.singstat.gov.sg/-/media/files/publications/population/population2019-map1.pdf

**Comment by missinglink** [comment]
The `data.gov.sg` website lists data downloads for `region`, `planning area` and `subzone` KML files published under the [Singapore Open Data Licence](https://data.gov.sg/open-data-licence).

https://data.gov.sg/search?q=boundary+2019

**Comment by nvkelso** [comment]
That license is workable for WOF.

**Comment by missinglink** [comment]
What is the desired placetype mapping for Singapore, does this look right?

[Country](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=country`
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=macroregion`
[Regions](https://en.wikipedia.org/wiki/Regions_of_Singapore) -> `wof:placetype=region`
[Planing Areas](https://en.wikipedia.org/wiki/Planning_Areas_of_Singapore) -> `wof:placetype=locality`
[Subzones](https://en.wikipedia.org/wiki/Subzones_of_Singapore) -> `wof:placetype=neighbourhood`
[Constituencies](https://en.wikipedia.org/wiki/Constituencies_of_Singapore)-> `wof:placetype=constituency`

**Comment by stepps00** [comment]
Because of the relatively low amount of records in Singapore and workable source license, this may be an issue I can fix with a PR over the next couple of weeks.

@missinglink I haven't dug into the placetype mapping in Singapore yet, but at first glance, I'd imagine the placetype structure could be something like this:

[Country](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=country`
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=region` (coterminous)
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=county` (coterminous)
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=locality` (coterminous)
[Planning Areas](https://en.wikipedia.org/wiki/Planning_Areas_of_Singapore) -> `wof:placetype=borough`
[Subzones](https://en.wikipedia.org/wiki/Subzones_of_Singapore) -> `wof:placetype=neighbourhood`
[Constituencies](https://en.wikipedia.org/wiki/Constituencies_of_Singapore)-> `wof:placetype=constituency`

**Comment by missinglink** [comment]
That was the other scheme I was considering.

You didn't mention the Regions in your structure above.

The tricky thing with Singapore is that the Country and City are coterminous and the Regions are a subdivision of that coterminous area.

So either the City of Singapore is in a place type *above* region (such as `macroregion`) or the City is a `county`, but then the Regions parent the City which seems wrong to me 🤔

**Comment by stepps00** [comment]
Ah - I just updated my comment above.. I placed the "regions" at the borough level and "planning areas" at the macrohood placetype.

IMO, "Singapore" should be a locality, so it's just a matter of placing the remaining subdivisions at a placetype below locality. I'm also open to suggestion if there are strong opinions on placetypes in Singapore.

**Comment by nvkelso** [comment]
@stepps00 your proposal makes sense to me, please proceed. 

In practice, there might be some subzones (neighbourhoods) that are more like microhoods (a few norths and souths), and a few that should also be dual listed as placetype `campus` (airports, hospitals, university). Housing estates are unique and might also sometimes quality for campus treatment. But basic approach would be to import everything straight and ignore these subtleties till they come up in user feedback.

**Comment by stepps00** [comment]
I'm going to start pushing commits to a new branch with updated records in Singapore, but:

> The tricky thing with Singapore is that the Country and City are coterminous and the Regions are a subdivision of that coterminous area.

I think this can be represented in WOF using `wof:placetype_alt` properties in this placetype setup:

[Country](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=country` (coterminous)
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=region` (coterminous)
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=county` (coterminous)
[City](https://en.wikipedia.org/wiki/Singapore) -> `wof:placetype=locality` (coterminous)
[Regions](https://en.m.wikipedia.org/wiki/Regions_of_Singapore) -> `wof:placetype=borough` (placetype_alt of `macroregion`)
[Planning Areas](https://en.wikipedia.org/wiki/Planning_Areas_of_Singapore) -> `wof:placetype=macrohood`
[Subzones](https://en.wikipedia.org/wiki/Subzones_of_Singapore) -> `wof:placetype=neighbourhood`

This might not be perfect, but the "common" placetypes should represent a single "Singapore".. my hope is by reworking the `wof:placetype_alt` property, the "region" subdivision issue would solve that issue.

**Comment by stepps00** [comment]
@missinglink this work should be complete, curious what improvements Pelias sees from these updates.

PR with fixes: https://github.com/whosonfirst-data/whosonfirst-data-admin-sg/pull/9
New source: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/sg-sggov.json
