### ISSUE TITLE
Consolidate regions in Ireland per 2014 local gov't reform act

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#115]
http://www.geonames.org/2961190/north-tipperary.html
http://api.geonames.org/getJSON?geonameId=2961190&username=demo

https://en.wikipedia.org/wiki/North_Tipperary
"...It was abolished on 3 June 2014"

does geonames contain historic data?

```
{
  "type": "Feature",
  "properties": {
    "id": "2963597",
    "gid": "gn:venue:2963597",
    "layer": "venue",
    "source": "gn",
    "name": "Ireland",
    "country_a": "IRL",
    "country": "Ireland",
    "region": "North Tipperary",
    "confidence": 0.947,
    "label": "Ireland, North Tipperary"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -8,
      53
    ]
  }
}
```

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-data/commit/3600a7ed04200ee04767ba12d9714ea3c48e9c39

Do we know what if anything it was superseded by?

**Comment by nvkelso** [comment]
The Who's On First records: 

**Tipperary**
* [South Tipperary](http://whosonfirst.mapzen.com/spelunker/id/85685019/)
* [South Tipperary](http://whosonfirst.mapzen.com/spelunker/id/85684971/)

Looks like these two should me merged into a new `Tipperary` region. Same for...

**Limerick:**
* [Limerick](http://whosonfirst.mapzen.com/spelunker/id/85684987/)
* [Limerick City](http://whosonfirst.mapzen.com/spelunker/id/85684985/)

**Waterford**:
* [Waterford](http://whosonfirst.mapzen.com/spelunker/id/85684953/)
* [Waterford City](http://whosonfirst.mapzen.com/spelunker/id/85684949/)

```
LOCAL GOVERNMENT REFORM ACT 2014
An Act to make further and better provision in relation to local government and, in particular, to amalgamate Limerick County Council with Limerick City Council, Waterford County Council with Waterford City Council and North Tipperary County Council with South Tipperary County Council
```

The Wikipedia links are:

1.  Tipperary County Council Tipperary County Council, 2014-05-29. Quote: "Tipperary County Council will become an official unified authority on Tuesday, 3rd June 2014. The new authority combines the existing administration of North Tipperary County Council and South Tipperary County Council."
2. http://www.irishstatutebook.ie/pdf/2014/en.act.2014.0001.pdf

**Comment by nvkelso** [comment]
It should also be said that of course GeoNames.org contains historic data, just like Who's On First contains historic data ;) History is `now` unless someone marks it history.

**Comment by stepps00** [comment]
This was fixed per https://github.com/whosonfirst-data/whosonfirst-data/pull/1237. Any follow-up work being taken care of in #1238.
