### ISSUE TITLE
Romania: region updates

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1177]
WOF has 43 region records in Romania, but should have 42 region records. Investigate the difference in placetype count.

https://spelunker.whosonfirst.org/id/85633745/descendants/?exclude=nullisland&placetype=region

See:
- https://en.wikipedia.org/wiki/Administrative_divisions_of_Romania

**Comment by ImreSamu** [comment]
As I see  [Tulcea county](https://en.wikipedia.org/wiki/Tulcea_County)   duplicated 

85687651 Tulcea — this is a region in Romania :  https://spelunker.whosonfirst.org/id/85687651/
85687679 Tulcea — this is a region in Romania :  https://spelunker.whosonfirst.org/id/85687679/

**Comment by stepps00** [comment]
Thanks @ImreSamu - will propose a PR with a fix.
