### ISSUE TITLE
Implode Wellington

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#118]
See also: 

https://whosonfirst.mapzen.com/spelunker/search/?q=wellington&iso=nz&placetype=locality

**Comment by stepps00** [comment]
For all of New Zealand, in preparation for new data import.

**Comment by stepps00** [comment]
`Locality` records in New Zealand were updated as follows:

* All `locality` records were loaded in QGIS and dissolved based on the `wof:name` field. 
* This shrunk the amount NZ localities from 2,053 records to 628 records (the remaining 1,425 records will be superseded to the 628 records).
* A [.geojson file](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20118/Issue118_NewLocalityGeometries.geojson) with new geometries for the 628 `locality` records was added into S3. This file included `wof:name` and `wof:id` fields.
* A [.csv file](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20118/Issue118_SupersededRecords.csv) with the 1,425 records to be superseded was added to S3. These records should be superseded to the 628 records in the .geojson file based on the `wof:name` field. This file included `wof:name` and `wof:id` fields.

**Comment by nvkelso** [comment]
@stepps00 The **.geojson** file looks good. But looks like **.csv** file only includes records that should be superseded, but it doesn't say with what. Can you add a 3rd column saying what the `superseded_by` id is? This could be accomplished with a data join on the names in the .geojson file, I think.

@thisisaaronland looks like `lbl` and `mps` latitude and longitude values will need to be recalculated for this much bigger polygons in the .geojson file (in addition to adding all the `supersedes` values from the CSV).

**Comment by stepps00** [comment]
The [.csv file](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20118/Issue118_SupersededRecords.csv) now contains three rows, including what each recorded will be superseded by:

* `wof:name`
* `wof:id`
* `wof:superseded_by`

**Comment by nvkelso** [comment]
Mesoshapes locality work for NZ makes this complicated.

**Comment by stepps00** [comment]
This issue is being tracked in [this branch](https://github.com/whosonfirst-data/whosonfirst-data/tree/stepps00/implode-wellington) (will update once turned into a PR).
