### ISSUE TITLE
Revert Paris neighbourhoods

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1204]
The work done under https://github.com/whosonfirst-data/whosonfirst-data/issues/410 includes data from [Open Data Paris](https://github.com/whosonfirst/whosonfirst-sources/tree/d24c4c9d8b89ac5764eec7258966d145ed43a1a5/sources#open-data-paris) which while "open" is under ODbL so needs to be removed and rebuilt.

**Comment by nvkelso** [comment]
- Deprecate the Open Data Paris source.
- For neighbourhoods that existed prior to #410 we'll move all open data paris properties and geometries from that record, and revert the geometry to the earlier geom (probably quattroshapes). Don't store the open data paris geom as an alt – it gets deleted.
- For neighbourhoods that were new in #410, remove all non-generated props except the name and the label centroid geometry as default geom (but remove the mapshaper bits), since we at Mapzen verified the place exists and was generally located there.

**Comment by stepps00** [comment]
Planning to tackle this soon. Lists of ids:

Ids of records that were imported during #410: [list](https://github.com/whosonfirst-data/whosonfirst-data/files/2384980/new_ids.txt)
Ids of records that existed prior to #410: [list](https://github.com/whosonfirst-data/whosonfirst-data/files/2384981/old_ids.txt)
