### ISSUE TITLE
Investigate new country shape for Iraq

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1207]
The country shape of Iraq does not include the northern regions, causing discrepencies in the hierarchies and country assignments of various descendant records. 

These region records are in Iraq, but not part of the country geometry of Iraq:

https://spelunker.whosonfirst.org/id/85672417/
https://spelunker.whosonfirst.org/id/85672475/
https://spelunker.whosonfirst.org/id/85672425/

<img width="1099" alt="screen shot 2018-06-01 at 9 59 37 am" src="https://user-images.githubusercontent.com/18567700/40853461-faa8c4fc-6582-11e8-8f47-b5dd2cf4aac5.png">

We store several alt-geometries that include these areas. Suggest swapping the default geometry with an alt. See: https://github.com/whosonfirst-data/whosonfirst-data/tree/master/data/856/321/91/

**Comment by nvkelso** [comment]
I'm fine promoting the `meso` as default geom – and also storing that as the specific rev geo polygon.

**Comment by nvkelso** [comment]
Background: looks like the disputed area of Kurdistan forms the missing polygon area – but I don't see that in WOF – @stepps00 can you find it?

**Comment by stepps00** [comment]
@nvkelso - there is no disputed area of Kurdistan covering that area.. I imagine that was the intention when we first imported these shapes, but for now, that area has a gap in country/disputed geom coverage.

Will file a PR to swap geoms, can include a new disputed Kurdistan record if necessary.
