### ISSUE TITLE
[hierarchy] European union - new NUTS 2016 classification - valid from 1 January 2018 

### ISSUE THREAD

**Issue by ImreSamu** [whosonfirst-data/whosonfirst-data#1209]
The EU  territorial code system was modified on 1 January 2018.
 
The  _" current `NUTS 2016` classification is valid from **1 January 2018** and lists 104 regions at NUTS 1, 281 regions at NUTS 2 and 1348 regions at NUTS 3 level."_  see more :  http://ec.europa.eu/eurostat/web/nuts/background

details: 
http://ec.europa.eu/eurostat/documents/345175/629341/NUTS2013-NUTS2016.xls  

## NUTS 1 changes ( major socio-economic regions)

|Code 2013 | Code 2016 | Label | Change | Explanation (new = old)
|----------|-----------|-------|--------|-----------------------------
| | FRB | CENTRE — VAL DE LOIRE | new NUTS 1 region, identical to ex-NUTS 2 region FR24 | FRB=FR24
| | FRC | BOURGOGNE-FRANCHE-COMTÉ | new NUTS 1 region, merge of ex-NUTS 2 regions FR26 and FR43 | FRC=FR26+FR43
| | FRD | NORMANDIE | new NUTS 1 region, merge of ex-NUTS 2 regions FR23 and FR25 | FRD=FR23+FR25
| | FRE | NORD-PAS DE CALAIS-PICARDIE | new NUTS 1 region, merge of ex-NUTS 2 regions FR22 and FR30 | FRE=FR22+FR30
| | FRF | ALSACE-CHAMPAGNE-ARDENNE-LORRAINE | new NUTS 1 region, merge of ex-NUTS 2 regions FR 21, FR 41 and FR42 | FRF=FR21+FR41+FR42
| | FRG | PAYS DE LA LOIRE | new NUTS 1 region, identical to ex-NUTS 2 region FR51 | FRG=FR51
| | FRH | BRETAGNE | new NUTS 1 region, identical to ex-NUTS 2 region FR52 | FRH=FR52
| | FRI | AQUITAINE-LIMOUSIN-POITOU-CHARENTES | new NUTS 1 region, merge of ex-NUTS 2 regions FR53, FR61 and FR63 | FRI=FR53+FR61+FR63
| | FRJ | LANGUEDOC-ROUSSILLON-MIDI-PYRÉNÉES | new NUTS 1 region, merge of ex-NUTS 2 regions FR62 and FR81 | FRJ=FR62+FR81
|FR7 | FRK | AUVERGNE-RHÔNE-ALPES | relabelled and recoded | FRK=FR7
| | FRL | PROVENCE-ALPES-CÔTE D’AZUR | new NUTS 1 region, identical to ex-NUTS 2 region FR82 | FRL=FR82
| | FRM | CORSE | new NUTS 1 region, identical to ex-NUTS 2 region FR83 | FRM=FR83
|FRA | FRY | RUP FR — RÉGIONS ULTRAPÉRIPHÉRIQUES FRANÇAISES | relabelled and recoded | FRY=FRA
|FR2 |  | Bassin Parisien | discontinued | 
|FR3 |  | Nord-Pas-de-Calais | discontinued | 
|FR4 |  | Est | discontinued | 
|FR5 |  | Ouest | discontinued | 
|FR6 |  | Sud-Ouest | discontinued | 
|FR7 |  | Centre-Est | discontinued | 
|FR8 |  | Méditerranée | discontinued | 
|PL1 |  | REGION CENTRALNY | discontinued | 
|PL2 | PL2 | MAKROREGION POŁUDNIOWY | relabelled | PL2=PL2
|PL3 |  | REGION WSCHODNI | discontinued | 
|PL4 | PL4 | MAKROREGION PÓŁNOCNO-ZACHODNI | relabelled | PL4=PL4
|PL5 | PL5 | MAKROREGION POŁUDNIOWO-ZACHODNI | relabelled | PL5=PL5
|PL6 | PL6 | MAKROREGION PÓŁNOCNY | relabelled | PL6=PL6
| | PL7 | MAKROREGION CENTRALNY | new region, made from ex-PL11 and PL33 | PL7=PL11+PL33
| | PL8 | MAKROREGION WSCHODNI | new region, equals ex-PL3 minus PL33 | PL8=PL3-PL33
| | PL9 | MAKROREGION WOJEWÓDZTWO MAZOWIECKIE | new region, equals ex-PL12 | PL9=PL12

## NUTS 2 changes (basic regions for the application of regional policies )
 
| Code 2013 | Code 2016 | Label | Change | Explanation (new = old)
| -------------- | --------------- | -------- | ---------- | ---------------------------------
| IE01 |  | Border, Midland and Western | discontinued | 
|  | IE04 | Northern and Western | new region | 
| IE02 |  | Southern and Eastern | discontinued | 
|  | IE05 | Southern | new region, made from ex-IE023, IE024 and IE025 | IE05=IE023+IE024+IE025
|  | IE06 | Eastern and Midland | new region | 
| FR24 | FRB0 | Centre — Val de Loire | recoded and relabelled | FRB0=FR24
| FR26 | FRC1 | Bourgogne | recoded | FRC1=FR26
| FR43 | FRC2 | Franche-Comté | recoded | FRC2=FR43
| FR25 | FRD1 | Basse-Normandie  | recoded | FRD1=FRFR25
| FR23 | FRD2 | Haute-Normandie  | recoded | FRD2=FR23
| FR30 | FRE1 | Nord-Pas de Calais | recoded | FRE1=FR30
| FR22 | FRE2 | Picardie | recoded | FRE2=FR22
| FR42 | FRF1 | Alsace | recoded | FRF1=FR42
| FR21 | FRF2 | Champagne-Ardenne | recoded | FRF2=FR21
| FR41 | FRF3 | Lorraine | recoded | FRF3=FR41
| FR51 | FRG0 | Pays de la Loire | recoded | FRG0=FR51
| FR52 | FRH0 | Bretagne | recoded | FRH0=FR52
| FR61 | FRI1 | Aquitaine | recoded | FRI1=FR61
| FR63 | FRI2 | Limousin | recoded | FRI2=FR63
| FR53 | FRI3 | Poitou-Charentes | recoded | FRI3=FR53
| FR81 | FRJ1 | Languedoc-Roussillon | recoded | FRJ1=FR81
| FR62 | FRJ2 | Midi-Pyrénées | recoded | FRJ2=FR62
| FR72 | FRK1 | Auvergne | recoded | FRK1=FR72
| FR71 | FRK2 | Rhône-Alpes | recoded | FRK2=FR71
| FR82 | FRL0 | Provence-Alpes-Côte d’Azur | recoded | FRL0=FR82
| FR83 | FRM0 | Corse | recoded | FRM0=FR83
| FRA1 | FRY1 | Guadeloupe | recoded | FRY1=FRA1
| FRA2 | FRY2 | Martinique  | recoded | FRY2=FRA2
| FRA3 | FRY3 | Guyane | recoded | FRY3=FRA3
| FRA4 | FRY4 | La Réunion  | recoded | FRY4=FRA4
| FRA5 | FRY5 | Mayotte | recoded | FRY5=FRA5
| LT00 |  | Lietuva | split into new LT01 and LT02 | 
|  | LT01 | Sostinės regionas | new region, equals ex-NUTS 3 region LT00A | LT01=LT00A
|  | LT02 | Vidurio ir vakarų Lietuvos regionas  | new region, ex-LT00 minus ex-LT00A | LT02=LT00-LT00A
| HU10 |  | Közép-Magyarország | discontinued; split into new HU11 and HU12 | 
|  | HU11 | Budapest | new region, equals ex-NUTS 3 region HU101 | HU11=HU101
|  | HU12 | Pest | new region, equals ex-NUTS 3 region HU102 | HU12=HU102
| PL11 | PL71 | Łódzkie | recoded | PL71=PL11
| PL33 | PL72 | Świętokrzyskie | recoded | PL72=PL33
| PL31 | PL81 | Lubelskie | recoded | PL81=PL31
| PL32 | PL82 | Podkarpackie | recoded | PL82=PL32
| PL34 | PL84 | Podlaskie | recoded | PL84=PL34
| PL12 |  | Mazowieckie | discontinued; split into new PL91 and PL92 | 
|  | PL91 | Warszawski stołeczny | new region, equals ex-PL127, PL129 and PL12A minus new PL926 |  PL91=PL127+PL129+PL12A-newPL926
|  | PL92 | Mazowiecki regionalny | new region, made from ex-PL128, PL12B, PL12C, PL12D, PL12E plus new PL926 | PL92=PL128+PL12B+PL12C+PL12D+PL12E+new PL926
| UKM2 | UKM7 | Eastern Scotland  |  boundary shift; lost ex-UKM24  |  UKM7=UKM2-UKM24
| UKM3 |  | South Western Scotland  |  discontinued; split into new UKM8 and UKM9  |  
|  |  UKM8  |  West Central Scotland | new region, made from ex-UKM31, UKM34, UKM35 and UKM36  |  UKM8=UKM31+UKM34+UKM35+UKM36
|  | UKM9  |  Southern Scotland  |  new region, made from ex-UKM24, UKM32, UKM33, UKM37 and UKM38  |  UKM9=UKM24+UKM32+UKM33+UKM37+UKM38
 
## NUTS 3 changes  ( small regions for specific diagnoses  )
 ... see XLS  http://ec.europa.eu/eurostat/documents/345175/629341/NUTS2013-NUTS2016.xls  
 
 
### special  comment for Hungary 
 the official info about the changes :  https://www.ksh.hu/regional_atlas_counties?lang=en
 but the wikipedia pages not yet updated  ( be careful! )  https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_Hungary

**Comment by ImreSamu** [comment]
the proposed mappings ( EU -  WOF placetypes )

EU  hierarchical system  | whosonfirst placetype     | comment 
-----| ----------   | --------------------
NUTS0 | country  |  28 country
NUTS1 | macroregion |  104 regions at NUTS 1
NUTS2 | region |   281 regions at NUTS 2
NUTS3 | ~county |  1348 regions at NUTS 3 level.
LAU ( Local Administrative Units)  | locality |    99 759

**Comment by nvkelso** [comment]
@ImreSamu Hey! Good to have you back working on Who's On First :)

Your proposal in https://github.com/whosonfirst-data/whosonfirst-data/issues/1209#issuecomment-394097604 generally looks workable except for LAU generally mapping to WOF's `localadmin` placetype (good) instead of `locality` (bad). 

NOTE: I expect that not all LAU will be included in WOF at present, but almost all NUTS0, NUTS1, NUTS2, and NUTS3 should be. Does NUTS now include geometry for these at least as a centroid that we could import under CC0 or CC-BY to have the full set of features?

How would we add this data to WOF? At first I thought as a new set of concordances (with a `nuts2016` namespace), but NUTS regions often span administrative units so it's not a 1:1 mapping. So maybe as a new `nuts2016` **property** _prefix_ and then property _keys_ of nuts0, nuts1 & etc? For example: `nuts2016:nuts0` = `HU`, `nuts2018:nuts1` = `HU01` (made up values).

This will require **sources** repo work and **properties** repo work. The sources repo description should specify that even though the prefix is `nuts2016` it's only valid from 2018+?

Is there a reason to add the earlier NUTS codes, too?

/cc @stepps00.

**Comment by ImreSamu** [comment]
Geodata licensing : 

I have received some information[1], but as I see - it is not OK for the project 
- licensing : "Our license agreement only covers non-commercial use. "
- not up-to-date. ( "Communes 2013" ; "Communal centroids 2010"; "Communal centroids 2006" )

[1] LAU data : http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/communes#commcentroids10

from the FAQ:
```
Q.    Which are the rules and constraints for the usage of data for commercial purposes?
A.    Eurostat, being a license holder of the geospatial data coming from EuroGeographics, is not allowed to assign the rights for the usage of data. Our license agreement only covers non-commercial use. Please contact www.eurogeographics.org to obtain a license for commercial use.
```
http://ec.europa.eu/eurostat/web/gisco/faq


---

still researching ...

**Comment by nvkelso** [comment]
@ImreSamu We can still use the data you pointed at to add concordances to and validate our own data for the same. In terms of matching it up (for the concordances), could you see which countries have what % matches and propose a concordances PR? 

Then for countries:

- low score look for new country source
- mediam score probably requires manual cleanup &/or new country source
- high score just requires a little manual cleanup

@stepps00 is also working on a GeoNames import that would bring in more localadmin records, too.

**Comment by ImreSamu** [comment]
There are a brand new ( 2018 ) version of the EU LAU list
https://ec.europa.eu/eurostat/documents/345175/501971/EU-28-LAU-2018-NUTS-2016.xlsx

And I have created a simple wof-lau count(*) comparison by wof_country: 
https://gist.github.com/ImreSamu/237f86f7728bee94f24e4ff2a3559bff
( WOF last git log: `Mon Sep 17 18:03:10 2018 -0700` )


( Thinking about this problem ) 
imho : We can use the data in 2 ways
* 1. as you wrote : " to add concordances to and validate our own data "
* 2. importing Lat/Long (center position) data from wikidata ( EU-28-LAU-2018-NUTS-2016.xlsx + Wikidata )

At least (the importing) only working for this countries ( ~ active local Wikidata community )

country |  LAU code mapping | label
--------| ---------------------------------------------  | ----- |
AT | [P964](https://www.wikidata.org/wiki/Property:P964) |  Austrian municipality key |
DE | [P439](https://www.wikidata.org/wiki/Property:P439) |  German municipality key |  
ES | [P772](https://www.wikidata.org/wiki/Property:P772) |  INE municipality code |
FR | [P374](https://www.wikidata.org/wiki/Property:P374) |  INSEE municipality code |
HU | [P939](https://www.wikidata.org/wiki/Property:P939) |  KSH code  |
IT | [P635](https://www.wikidata.org/wiki/Property:P635) |  ISTAT ID |
SE | [P525](https://www.wikidata.org/wiki/Property:P525) |  Swedish municipality code | 
SK | [P782](https://www.wikidata.org/wiki/Property:P782) |  LAU |

I have wrote some draft SQL - and  ~99.6% match 

As I see -at least the Hungarian WOF data can be fixed with this method.
- importing missing localities ( Hungary - lau:3155 vs. wof:1787 ) with center position from wikidata.

**Comment by nvkelso** [comment]
Rad! Sounds like a good plan :)

**Comment by stepps00** [comment]
Here is a breakdown of placetypes per country I compiled through recent placetype cleanup: https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/definition/placetypes_by_country.md

Open to changing this if we recognize an issue.

**Comment by ImreSamu** [comment]
>But looking at your Gist I wonder if we should first agree what WOF placetype matched up to what
> EU_LAU as I don't think they're always locality, sometimes county, sometimes localadmin?

yes,  it is different country-by-country

imho: we need **country-by-country metadata rules** - for comparing with other databases 
* https://ec.europa.eu/eurostat/web/nuts/national-structures-eu  `(last update 10/04/2018, based on NUTS 2016 and LAU 2017) ` -  frequent changes
* wikidata
* .... 

 

@stepps00 : thank you ;  
* I am thinking of extending with other metadata ( eu/wikidata/osm )  ( 'wof_valid' - is from your table )
* purpose:  using by programs/code generators   for : QA dashboard   or  wikidata/eustat matching
 
#### draft - Hungary ( metadata ):

example:
* id: [85633237](https://spelunker.whosonfirst.org/id/85633237) 
* country: Hungary
* wikidata: [Q28-Hungary](https://www.wikidata.org/wiki/Q28) 
* macroregion: 
  * wof_valid = true
  * eu=  NUTS1
  * eu:count:y2018 = 3 
  * osm=  `admin_level=4 and boundary=administrative in Hungary`
* region:
  * wof_valid =  true
  * eu  = NUTS2
  * eu:count:y2018  = 8
  * osm = `admin_level=5 and boundary=administrative in Hungary` 
  * wikidata:
      * 'instance of' = [Q254450- planning and statistical region of Hungary](https://www.wikidata.org/wiki/Q254450)  
* macrocounty: 
  * wof_valid= false 
* county: 
  * wof_valid= true 
  * eu=   NUTS3
  * eu:count:y2018= 20
  * osm= `admin_level=6 and boundary=administrative in Hungary`
  * wikidata:
    * 'located in the administrative territorial entity (P131)' = 'Hungary'
    * AND has [P300 ISO 3166-2 code](https://www.wikidata.org/wiki/Property:P300) 
    * ( AND P300 like 'HU% )
* localadmin:  
  * wof_valid= false
  * eu=  LAU
  * eu:count:y2018= 3155
  * osm= `admin_level=8 and boundary=administrative in Hungary`
  * wikidata:
    * 'located in the administrative territorial entity (P131)' = 'Hungary' 
    * AND has [P939 KSH code](https://www.wikidata.org/wiki/Property:P939)
* locality: 
  * wof_valid= true




### Wikidata admin codes
 
There are lot of  'Wikidata property for authority control for administrative subdivisions' 
and I need a country specific wof-wikidata metadata for fine matching.

wikidata query - for actual - admin properties:  http://tinyurl.com/y7r23dpu

example:
```
...
 -CBS municipality code (P382)
 -dantai code (P429)
 -German municipality key (P439)
 -German district key (P440)
 -China administrative division code (P442)
 -Swedish county code (P507)
 -Swedish municipality code (P525)
 -NUTS code (P605)
 -ISTAT ID (P635)
 -OKATO ID (P721)
 -OKTMO ID (P764)
 -Swiss municipality code (P771)
 -INE municipality code (P772)
 -ISO 3166-3 (P773)
 -FIPS 55-3 (locations in the US) (P774)
 -LAU (P782)
 -Italian cadastre code (P806)
 -FIPS 10-4 (countries and regions) (P901)
 -KSH code (P939)
 -Austrian municipality key (P964)
 -Thailand central administrative unit code (P1067)
 -KOATUU identifier (P1077)
 -ATVK ID (P1115)
 -ELSTAT geographical code (P1116)
 -EHAK id (P1140)
...
```

**Comment by nvkelso** [comment]
NUTS 2021 is out now... and there are a few other issues that track this now for:

- updating per country administrative features with new national mapping agency data
- proposing to add a new `statistical` WOF placetype as NUTS is now _closer_ to administrative geography, but still not 100% and should be treated as a special thing.
