### ISSUE TITLE
Update disputed areas from Natural Earth v4.1

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1215]
They have 80 ~~100~~, we only have 40. What gives.

Also:

- set controlled on hierarchy
- set parent_id to -4 (?) or similar to indicate multiple parents
- See other issue about disputed territory names
- A few other random existing issues.
- Exporify these / cleanup bunk belongs_to property dups
- clean/scrub/update ne properties on existing features
- will need to re-run population scripts
- clean/scrub names and labels on disputed features for wof:name and common name:*, eg:
    **name:eng_x_preferred**: `Falkland Islands (Islas Malvinas)`
    **name:esp_x_preferred**: `Islas Malvinas (Falkland Islands)`
    Take particular care to also update the `country` &/or `dependency` record's name's as those are what usually drive the label generation, not the disputed's record's name.
- might as well scrub a few `marinearea` labels the same way for `Persian Gulf (Arabian Sea)` and  `Sea of Japan (East Sea)`
- add and document new `mz:hierarchy_label:{placetype}` flags to all as follows to indicate if a PIP is within the disputed area skip the following in the label construction – then we could have overrides per disputed later (say Taiwan) and it's data driven – and can be overriden later by different `pov` point of view flags per country, would need to be paired with some revGeo work, rainy day):
    `mz:hierarchy_label:country` = 0
    `mz:hierarchy_label:macroregion` = 0
    `mz:hierarchy_label:region` = 0
    `mz:hierarchy_label:macrocounty` = 0
    `mz:hierarchy_label:county` = 0
    `mz:hierarchy_label:localadmin` = 0
    `mz:hierarchy_label:locality` = 1
    For **Palestine** and **Taiwan** it'd be skip the `country` but include the rest?

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/6

**Comment by thisisaaronland** [comment]
We should not be using multiple `:` separators. I would suggest following the naming conventions for names and use `_x_FOO` if you need custom stuff.

**Comment by nvkelso** [comment]
FWIW we use multiple `:` separators today for things like `src:population:date` Should we file an issue to change the 2nd `:` to `_`? Doesn't affect many properties. Is there an implication for this, like Spelunker display?

**Comment by nvkelso** [comment]
Others joint parenthetical names besides Falkland ([src](https://www.cia.gov/library/publications/the-world-factbook/fields/2070.html)):

- Andean Southern Ice Field (Campo de Hielo Sur), which it looks like we have as a region but need also as a `disputed`
