### ISSUE TITLE
Rework any properties with multiple : separators

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1216]
Crawl the repo for any records that contain properties with multiple `:` separators.
Remap those properties to new property names and update records/docs accordingly.

Example:

`statoids:population:date` -> `statoids:population_date`

Per conversation in #1215.

**Comment by nvkelso** [comment]
I think we'd "deprecate" the old property and mark it as superseded by the new property ID?

**Comment by stepps00** [comment]
Main properties to rework with `_`:

```
meso:wof:id
src:lbl:centroid
statoids:population:date
src:population:date
```

In addition, there are ~1700 `zs:*` properties that have multiple `:` separators. Example:

```
zs:8083:housing10
zs:8083:blockids
zs:8077:pop10
```

**Comment by stepps00** [comment]
This was fixed in each per-country repo.

The whosonfirst-properties repo needs to be updated to reflect these changes, but this change is not reflected in the data.
