### ISSUE TITLE
Neighbourhoods in Solihull (UK) should be descendants of the locality of Solihull

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1221]
Here's a neighbourhood within the city of Solihull, UK - https://en.wikipedia.org/wiki/Solihull

https://spelunker.whosonfirst.org/id/85787275/

It has this hierarchy:

![2018-06-14 at 11 30 am](https://user-images.githubusercontent.com/9599/41430962-5a39851c-6fc6-11e8-9f8b-38e8d50cffdb.png)

It's within the region of Solihull ( https://spelunker.whosonfirst.org/id/85684267/ ) but I think the hierarchy should also put it inside the locality of Solihull ( https://spelunker.whosonfirst.org/id/1125891303/ )

**Comment by stepps00** [comment]
Hey @simonw - thanks for the issue.. this goes back to the same issue we've seen previously where the locality has a `Point` geometry, so when we do point-in-polygon work, the neighbourhood does not pick up the locality in its hierarchy.

I have an open issue ([here](https://github.com/whosonfirst-data/whosonfirst-data/issues/430)) to update geometries for `locality` and `localadmin` records parent/child combinations in the UK.. once that lands, I suspect this issue will be fixed. Thanks again!

**Comment by stepps00** [comment]
Fixed in https://github.com/whosonfirst-data/whosonfirst-data/pull/1253, closing.
