### ISSUE TITLE
Duplicate: two Solihull localities (both marked mz:is_current = -1)

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1222]
https://spelunker.whosonfirst.org/id/1126055031/ and https://spelunker.whosonfirst.org/id/1125891303/

Both are Solihull (a city in the UK) - both have `mz:is_current = -1`

![2018-06-14 at 11 43 am](https://user-images.githubusercontent.com/9599/41431541-20e3c7d0-6fc8-11e8-93b9-d6e301272a99.png)

Related: #1221

**Comment by nvkelso** [comment]
`-1` here indicates we don't know if it's current or not current.

Agree these are duplicates of each other from the same source (but one ur sources was GeoNames, the other ur source was GeoPlanet).
