### ISSUE TITLE
367 neighbourhoods are missing their hierarchies

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1225]
There are 367 neighbourhoods for which hierarchies is currently `[]`.

I've listed them and plotted them all on a map here: https://whosonfirst-data-bad-hierarchies-bug.now.sh/bad-places/bad-places?_facet=is_current&_facet=country

![2018-06-20 at 10 43 pm](https://user-images.githubusercontent.com/9599/41699992-5677494a-74db-11e8-9835-d0dacb38ead1.png)

You can export that data as a CSV here: https://whosonfirst-data-bad-hierarchies-bug.now.sh/bad-places/bad-places.csv

By-country breakdown is:

    JP 156
    SA 81
    EG 42
    PE 25
    LB 13
    OM 13
    KR 11
    XX 5
    SD 3
    AE 2
    KO 2
    US 1

Mainly for my own benefit (since this is against my own custom Whos_On_First MySQL table) here's the SQL query I used to find them:
```
select Whos_On_First.id, Whos_On_First.country, Whos_On_First.name, PlaceTypes.name, Whos_On_First.id,is_current,
X(Whos_On_First.point) as longitude, Y(Whos_On_First.point) as latitude,
Whos_On_First.parent_id, Whos_On_First.hierarchies,
concat("http://spelunker.whosonfirst.org/id/", Whos_On_First.id) as spelunker_url
from Whos_On_First join PlaceTypes on Whos_On_First.placetype = PlaceTypes.id
where Whos_On_First.hierarchies = JSON_ARRAY();
```

**Comment by stepps00** [comment]
Hey @simonw - thanks for the issue.

I recently pushed [this commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/65dfe8930a1c8f2c8624adf02e9b618d0f09a533), which updated hierarchies for any record with `"wof:hierarchy:[],".

I spot checked the records in master and things look correct - the Spelunker is out of sync, so the hierarchies may not appear to be updated, but the records themselves should be correct.

I'll go ahead and close this issue shortly, unless you're still seeing some issues on the master branch.

**Comment by stepps00** [comment]
I've verified that each of the 367 neighbourhood records have full hierarchies, from https://github.com/whosonfirst-data/whosonfirst-data/commit/65dfe8930a1c8f2c8624adf02e9b618d0f09a533.

Closing this issue and referring to #1226 for any discrepancies between GitHub and the distribution files.
