### ISSUE TITLE
SQLite whosonfirst-data-latest.db has not been updated since 2018-01-25

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1226]
https://dist.whosonfirst.org/sqlite/ says the following:

>  whosonfirst-data-latest.db 8b4ea8180d121ee7772030f571893ea955c336c99a41bab7e954568cc5d2c171
This database contains 729,270 Who's On First records and is 5.5 GB compressed and 15 GB uncompressed.
It was created 2018-01-25T17:18:46Z and (the data itself) was last updated on 2017-12-31T08:21:52Z.

Will this be updated again soon or should I switch to pulling data directly from the git repository?

**Comment by stepps00** [comment]
As of today, the sqlite distributions do not contain some of the newer changes, so I'd suggest pulling directly from the Git repo. The goal is to re-index the dist page and Spelunker soon..

**Comment by nvkelso** [comment]
@stepps00 Can you share documentation on how @simonw could generate his own SQLite dist files from master?

**Comment by stepps00** [comment]
Yep - the [go-whosonfirst-dist](https://github.com/whosonfirst/go-whosonfirst-dist) repository has tools written in Go that can rebundle the whosonfirst-data repository into a sqlite file.

The `README` has more detail, but after setup, running:

```
> mkdir tmp
> ./bin/wof-dist-build -timings -verbose -workdir ./tmp -build-sqlite -build-meta whosonfirst-data
```

should trigger a git clone of wof-data and output the sqlite bundle + metafiles.

**Comment by thisisaaronland** [comment]
@simonw – it's coming but it's competing for a) a general refactoring of the `go-whosonfirst-dist` package and b) the part where there are competing interests for my daylight hours.

But in the short term, the code snippet that @stepps00 mentioned above should work.

**Comment by stepps00** [comment]
Closing this issue since the distribution files have been updated.

https://dist.whosonfirst.org/sqlite/
