### ISSUE TITLE
Ceremonial counties of England

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1228]
Heya,

I was hoping to find an entry for the 'Greater Manchester' region for the UK

eg:
- https://www.openstreetmap.org/relation/88084
- http://www.geonames.org/2648108/greater-manchester.html
- https://en.wikipedia.org/wiki/Greater_Manchester

We have had reports that users are not able to find locations by referring to 'Manchester' as the Greater Manchester Region, which is a very common search pattern in the UK, and useful for label generation.

An example, is a town such as [Wigan](https://spelunker.whosonfirst.org/id/85683733/) which should really be associated with the 'Greater Manchester' region.

From wikipedia:

> Wigan is a town in Greater Manchester, England, on the River Douglas, 7.9 miles south-west of Bolton, 10 miles north of Warrington and 16 miles west-northwest of Manchester.

In this case WOF describes Wigan as a region which is directly parented by England. Is this correct, it seems like the placetype of `region` in this case is too high a level for a 'town'?

We currently have two Manchester records in WOF, one is a [locality](https://spelunker.whosonfirst.org/id/101750525/) and one is a [region](https://spelunker.whosonfirst.org/id/85683651/), but in this case the region only contains a small extension at the southern end of the shape.

The WOF region seems to be the same as [this relation from OSM](https://www.openstreetmap.org/relation/146656) which OSM says is level 8 (~borough), I'm not sure what the WOF locality represents, maybe someone else knows?

OSM also has the entry linked above [88084](https://www.openstreetmap.org/relation/88084) which is level 6 (~county).

So.. I'm trying to figure out if we can fix this?

It would be great if we could add a new record for the 'Greater Manchester Region' and slot it in to the heirarchy above the existing 'region' records, I'm guessing it would be classed as a 'macroregion'?

[edit] [England](https://spelunker.whosonfirst.org/id/404227469/) is a macroregion so that probably won't work?

The only other place I see it fitting in is if we either reclassify wigan as something like a county or a localadmin/locality and put it under the region `146656`, or we introduce a new level of the hierarchy which is almost certainly a bad idea?

I didn't check the rest of the UK but I imagine it's a problem for the whole country.

@nvkelso is this a known issue?
@stepps00 this might be relevant to the work you are planning regarding UK localities?

thanks and apologies if this is a known issue, I did a quick search and didn't find anything.

**Comment by missinglink** [comment]
https://en.wikipedia.org/wiki/Ceremonial_counties_of_England

**Comment by stepps00** [comment]
Thanks for the issue @missinglink 

This issue is similar to some of the work we did to update neighbourhoods in London and #225. The original import of UK data did not include a record for Greater Manchester, but did include the divisions of Greater Manchester:

- https://spelunker.whosonfirst.org/id/85683651/
- https://spelunker.whosonfirst.org/id/85683615/
- https://spelunker.whosonfirst.org/id/85684495/
- https://spelunker.whosonfirst.org/id/85684195/
- https://spelunker.whosonfirst.org/id/85683677/
- https://spelunker.whosonfirst.org/id/85683689/

I need to investigate this issue a little further before I have a suggestion/PR, but I suspect we will have to A. create a new region record for Greater Manchester B. demote existing regions to a lower placetype C. use some `wof:coterminous` or wof:placetype_alt` magic to categorize the lower placetypes under existing regions.

Either way, we are missing the Greater Manchester record - this issue should stay open and track the addition of that new record.

**Comment by nvkelso** [comment]
I can see adding and adjusting the hierarchies for the six "metropolitan counties" like we did for London. Those are part of the administrative structure.

Metropolitan county | Metropolitan districts | Number | County population
-- | -- | -- | --
Greater Manchester | Manchester, Bolton, Bury, Oldham, Rochdale, Salford, Stockport, Tameside, Trafford, Wigan | 10 | 2,573,200
Merseyside | Liverpool, Knowsley, St Helens, Sefton, Wirral | 5 | 1,365,000
South Yorkshire | Sheffield, Barnsley, Doncaster, Rotherham | 4 | 1,290,000
Tyne and Wear | Newcastle upon Tyne, Gateshead, South Tyneside, North Tyneside, Sunderland | 5 | 1,089,400
West Midlands | Birmingham, Coventry, Dudley, Sandwell, Solihull, Walsall, Wolverhampton | 7 | 2,591,300
West Yorkshire | Leeds, Bradford, Calderdale, Kirklees, Wakefield | 5 | 2,161,200

Let's do that before thinking about adding a new UK-only "ceremonial county" placetype. We've contemplated adding `postal_locality` which is mostly USA specific so it's not totally out of rhelm of possibilities, but let's try solving the problem with existing placetypes first.

See also:

- https://en.wikipedia.org/wiki/Metropolitan_county
- https://en.wikipedia.org/wiki/Metropolitan_borough
- https://en.wikipedia.org/wiki/Combined_authority
- https://en.wikipedia.org/wiki/Ceremonial_counties_of_England
- London: https://spelunker.whosonfirst.org/id/101750367/

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/1368/commits/3c9d647925ec8729062a4b76a56813f279c14639

**Comment by stepps00** [comment]
:tada: Greater Manchester: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/136/069/855/5/1360698555.geojson

This placetypes (and any placetype "above" locality) has been updated in the UK, including all ceremonial counties from the Ordnance Survey file.

Closing this issue, but please re-open/file a follow-up if needed.

**Comment by missinglink** [comment]
Amazing, great work, thanks!
