### ISSUE TITLE
Update iso code for Poland descendants

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1236]
https://spelunker.whosonfirst.org/id/85633723/descendants/?exclude=nullisland&iso=po

The ISO code for Poland is PL, not PO.

https://en.wikipedia.org/wiki/ISO_3166-2:PL

**Comment by nvkelso** [comment]
Another mistake sourced from Quattroshapes?

**Comment by stepps00** [comment]
Looking at the diff/blame, they were just originally imported with that PO code. Good news is that there aren't too many of 'em.

**Comment by stepps00** [comment]
Fixed in https://github.com/whosonfirst-data/whosonfirst-data/pull/1253, closing.
