### ISSUE TITLE
erroneous Sydney record

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1251]
heya,

we have few records for Sydney `[ 101932003, 102049151, 404226357 ]` but I just found this one:
- https://spelunker.whosonfirst.org/id/85771099/

... which is all sorts of wrong :)
- placetype 'neighborhood'
- unusual geometry
- orphaned hierarchy

Could we just delete this one?

It has all the same name properties as the real Syndey so it's causing headaches for geocoding

**Comment by stepps00** [comment]
Thanks @missinglink - notes below:

Sydney record:

This looks like a bunk neighbourhood record that needs to be tagged as `"mz:is_current":1`.
This Syndey record is also incorrectly tagged as a "megacity", so its a touch of https://github.com/whosonfirst-data/whosonfirst-data/issues/701.

London record:

This looks like a separate issue, though the `zetashapes` geometry is quite large. I suspect the record represents [an actual London area in Wisconsin](https://en.wikipedia.org/wiki/London,_Wisconsin), but I'll need to investigate a bit more. This record will likely stay, but I'll push a PR and link to this issue.

**Comment by orangejulius** [comment]
It also looks like the label centroid for [101932003](https://spelunker.whosonfirst.org/id/101932003/)(the main Sydney locality record) is incorrect. It's quite a bit south of the bounding box.

Originally reported in https://github.com/pelias/pelias/issues/664

**Comment by stepps00** [comment]
@orangejulius - the Sydney record was recently updated ([here](https://github.com/whosonfirst-data/whosonfirst-data/commit/8e7e70e57f6903120a986fd3c525766e00870993)) to include a `lbl` latitude/longitude value within the geometry. This is fixed [in master](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/101/932/003/101932003.geojson), but the dist files and Spelunker are out of sync at the moment.

I'll chat with @missinglink this week about new additions to WOF and the best ways for Pelias to integrate.

Keeping this open, as the original issue is still occurring.

**Comment by orangejulius** [comment]
@stepps00 oh great.

Let us know how we can help with anything related to the machinery of WOF. If there are, for example, server requirements we may be able to lend a hand.

**Comment by stepps00** [comment]
Aside from the erroneous neighbourhood of Sydney mentioned in the original issue comment, all of these various issues should be taken care of. The Sydney neighbourhood point is being updated via https://github.com/whosonfirst-data/whosonfirst-data-admin-au/pull/3.

Feel free to file follow-ups if you see anything else that needs fixing in AU.
