### ISSUE TITLE
no records named Ohiya

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1252]
heya,

WOF doesn't seem to contain any records named 'Ohiya' despite there being some records in geonames:

http://www.geonames.org/search.html?q=ohiya&country=

Is it possible to bring any of these into WOF, maybe this one? 
http://www.geonames.org/1232714/ohiya.html

related: https://github.com/pelias/pelias/issues/728

**Comment by stepps00** [comment]
This is a known issue and part of https://github.com/whosonfirst-data/whosonfirst-data/issues/108, which I hope to tackle soon.. I'd prefer to import all "leftover" populated places from GeoNames at once, but I'll update this issue once Ohiya is added..

**Comment by missinglink** [comment]
Great thanks @stepps00, I'll add any other relevant places I find to this ticket.

http://www.geonames.org/3095157/korzkiew.html

**Comment by stepps00** [comment]
:tada: Record for Ohiya has been added: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/129/315/424/9/1293154249.geojson

**Comment by stepps00** [comment]
(And Korzkiew)

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/129/391/575/9/1293915759.geojson

**Comment by pathmapper** [comment]
Thanks a lot @stepps00 .
