### ISSUE TITLE
Some Austrian cities listed in Australia

### ISSUE THREAD

**Issue by nigelhorne** [whosonfirst-data/whosonfirst-data#1255]
For example, in the file whosonfirst-data-latest.db, the entry for Litschau has "iso:country":"AU", even though it correctly lists  "qs:adm0":"\u00d6sterreich"

Try this command to view the record:

sqlite3 whosonfirst-data-latest.db
> select * from geojson where body like '%LITSCHAU%' LIMIT 1;

the iso:country field should be AT not AU.

Alternatively look at https://spelunker.whosonfirst.org/search/?q=LITSCHAU, you'll see in 'filter by Country (ISO code)', 110 entries for at, and 1 for au.  The 1 for au is incorrect.

**Comment by stepps00** [comment]
Thanks, @nigelhorne - I will take a look at this and propose a PR.

Full list of offenders:

https://spelunker.whosonfirst.org/id/102191581/descendants/?exclude=nullisland&iso=au
