### ISSUE TITLE
classification of UK 'metropolitan boroughs'

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1265]
good day chaps!

I wanted to create an issue separate from https://github.com/whosonfirst-data/whosonfirst-data/issues/1228 to discuss the current classification of [Metropolitan borough](https://en.wikipedia.org/wiki/Metropolitan_borough) records in the UK.

We are currently classifying them as `region`, but it seems like `localadmin` might be a more appropriate placetype considering they are a form of local government?

Classifying them as `region` also causes some problems for the issue linked above #1228, being so high up the hierarchy doesn't leave any room to add Ceremonial Counties without adding a new placetype.

Does anyone remember the back-history of why they were classified `region` or could maybe explain why they might not be suitable for classification as `localadmin`?

here's an example of one such metropolitan borough:
- https://en.wikipedia.org/wiki/Metropolitan_Borough_of_Wigan
- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/837/33/85683733.geojson

```javascript
"wof:placetype": "region",
"wof:placetype_local": "metropolitan borough"
```

cheerio!

**Comment by missinglink** [comment]
In fact, we already have the polygon classified as a `localadmin` here: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/404/450/053/404450053.geojson

I found this by looking at [Hindley](https://spelunker.whosonfirst.org/id/101872175/) which is a direct descendant of the metro borough of Wigan, the record links to a `localadmin` with no name.

ref: https://en.wikipedia.org/wiki/Hindley,_Greater_Manchester

**Comment by stepps00** [comment]
These divisions were also added as new records as part of #1367. 

Metropolitan boroughs of Greater Manchester, for example, can be found here:
https://spelunker.whosonfirst.org/id/1360698555/descendants/?exclude=nullisland&placetype=county
