### ISSUE TITLE
Pongola - Invalid Geometry

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1270]
The geometry for `Pongola 101/927/443/101927443.geojson` is invalid, it's type is set as `Polygon` but it's just a single line.

https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/101/927/443/101927443.geojson

**Comment by stepps00** [comment]
I've verified that this feature is invalid in a set of ids I processed for #1071.

Closing in preference of that issue/PR.
