### ISSUE TITLE
San Diego - Possible Invalid Geometry

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1271]
The geometry for `San Diego` appears to be invalid.
I wasn't able to determine the source of the error, but I've also reported it to RTTOPO to see if I can find out.

https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/859/222/27/85922227.geojson
https://git.osgeo.org/gitea/rttopo/librttopo/issues/34

**Comment by nvkelso** [comment]
@missinglink Can we get more background on why you think it's invalid? Like it's valid GeoJSON but the ElasticSearch parser think's it's invalid for some reason (like ring winding order)?

**Comment by missinglink** [comment]
hmm... I'm not sure what's going on here. one month ago I opened this issue https://git.osgeo.org/gitea/rttopo/librttopo/issues/34 because RTTOPO was erroring on this geom but when I write a test case it seems to pass...

```bash
#!/bin/bash

docker pull missinglink/spatialite:latest;

function test(){
  echo "--- $1 ---";
  GEOJSON=$(sed "s/'/"/g $1);

  docker run --rm -i \
    -v "$(pwd)/85977539.geojson:/tmp/test.geojson" \
     missinglink/spatialite:latest <<SQL
  SELECT IsValid( GeomFromGeoJSON( '${GEOJSON}' ) );
  SELECT IsValidReason( GeomFromGeoJSON( '${GEOJSON}' ) );
  SELECT IsValidDetail( GeomFromGeoJSON( '${GEOJSON}' ) );
  SELECT MakeValid( GeomFromGeoJSON( '${GEOJSON}' ) );
SQL
}

# download files
[ -f '85977539.geojson'  ] || curl -sO 'https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/859/775/39/85977539.geojson';
[ -f '85922227.geojson'  ] || curl -sO 'https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/859/222/27/85922227.geojson';

# run tests
test '85977539.geojson';
test '85922227.geojson';
```

It's possibly a version mismatch of my tooling, if so, apologies. But since the same tooling caught some other errors (such as https://github.com/whosonfirst-data/whosonfirst-data/issues/1270) I'm wondering if it's the data or the code...

**Comment by stepps00** [comment]
Interesting! No worries about opening this issue, but I'm going to close it for now as we've both verified the geometry to be valid.

If anything else pops up with this geom, feel free to reopen the issue.
