### ISSUE TITLE
France locality vis-a-vis localadmin

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1277]
Following up from https://github.com/whosonfirst-data/whosonfirst-data/issues/1094 where we added new and correct `localadmin` shapes let's now figure out which are **coterminous** with existing `locality` records and clean those up (the `locality` shapes are generally poor compared to the new `localadmin` shapes).

Suggested approach is to find the **coterminous** features and then instead of carrying around 2 records let's recast the `localadmin` as a `locality` with a **placetype_alt** of `localadmin`, and for the `locality` that aren't coterminous keep them as-is for now. (Which means deprecating some new `localadmin` into the existing `locality` records but adding props and &etc).

Possible problems: non-coterminous localities might still be at the boundary of a new localadmin but not be clipped by that localadmin. That's sad, but probably beyond the scope of this issue. Our hypothesis is most of the coterminous ones will clean up 70%+ of these boundary inconsistencies leaving a few rural areas funky but overall much much better.

**Comment by stepps00** [comment]
Reviewing https://github.com/whosonfirst-data/whosonfirst-data/issues/1094, the original `locality`/`localadmin` file division is based on name joins, not on any specific administrative division/classification.

Right now, WOF has ~35k records at the `localadmin` placetypes that represent "communes" of France. I suspect workflow above will result in the correct `locality`/`localadmin` records.

**Comment by stepps00** [comment]
A few screenshots of existing coverage in France:

**Purple: localadmin records with wof:name labels**
**Green: locality records with wof:name labels**

<img width="1037" alt="screen shot 2018-10-16 at 9 51 16 am" src="https://user-images.githubusercontent.com/18567700/47033241-276b2e00-d129-11e8-982a-eb3da01e7568.png">

<img width="927" alt="screen shot 2018-10-16 at 9 51 37 am" src="https://user-images.githubusercontent.com/18567700/47033242-276b2e00-d129-11e8-8e0d-810eeef131d4.png">

**Comment by nvkelso** [comment]
The case of Auray and Brech in the bottom image is interesting, tell me
more about fix options there?

**Comment by stepps00** [comment]
WOF has localadmin and locality records for both Brech and Auray, so that case is actually more straight-forward than other cases. The boundaries of the Auray locality record overlap the localadmin boundaries of Auray and Brech, but joining by locations using the locality centroids and matching lowercase names  should result in a correct match here.

Another interesting case is matching "Crac'H" and "Crach". I am in the process of stripping out certain characters and replacing uppercase characters in all name fields so I can use a string of sanitized/lowercase names + lat + long to match these layers. This will result in "Crac'H" -> "crach" and "Crach" -> "crach". This will give me a high percentage of matches, then I'll do a second pass at matching by location.

**Comment by nvkelso** [comment]
But for Brech there is a locality for Brech inside the same-named localadmin, and Auray's locality polygon breaches into the localadmin of Brech. So for the breach'd portion, what is that? Similar story places out a few more places.

One option is to cleanup the boundaries by dissolving all French locality polgyons together and then doing a union on the localadmin polygons and then doing a point in polgyon join to name the results back with their original locality. But that would leave orphans in the examples above. What do we call the orphans?

**Comment by stepps00** [comment]
So the breached area is a portion of Auray's geometry that should have been Brech; the original `quattroshapes` source geometry was incorrect to begin with, but these new purple commune geometries are correct. This is the same issue we've run into in other European countries.. I think slicing up these `quattroshapes` geometries and dissolving features is extra work that could be skipped if we simply use the commune boundaries as locality/localadmin.

The `quattroshapes` sourced geometries represent the "core" area of the commune, but often overlap commune boundaries or represent communes that have since been dissolved into their neighbors. 

If we do the following, I think WOF would have correct coverage:

  - Create a join string on each layer, something like:
`lower( to_string("join_name")) +  left( to_string("lbl_latitu"),3 )+ left(to_string("lbl_longit"), 3)`
  - Join `localadmin` layer to the `locality` layer using join string
  - If match, supersede `localadmin` into `locality` and bring over extra properties, flag with placetype_alt of `localadmin`
  - For leftovers, join by location
  - If match, supersede `localadmin` into `locality` and bring over extra properties, flag with placetype_alt of `localadmin`
  - Deprecate any non-matching localities
  - Optionally, move non-joined `localadmin` to `locality`, bring over extra properties, flag with placetype_alt of `localadmin` 

This would leave WOF with contiguous commune coverage at the `locality` and `localadmin` level. The existing `quattroshapes` geometries would be stored as alt geometries and there would be no need to slice up geometries.

Thoughts?

**Comment by stepps00** [comment]
I'm finishing up the matching between the `locality` and `localadmin` placetypes in France. About 32,000 of the 35,285 existing localadmin records have been matched to a locality record. These 32k records will be updated as pointed out in https://github.com/whosonfirst-data/whosonfirst-data/issues/1277#issuecomment-430456165.

Matching was done several ways:
- Match locality records with point geometries to localadmin records, using:
`lower( to_string("join_name")) + left( to_string("lbl_latitu"),3 )+ left(to_string("lbl_longit"), 3)`
- Convert locality records with polygon geometries to point geometries, using their centroids, and match to localadmin records, using:
- Match locality records with point geometries to localadmin records, using:
`lower( to_string("join_name")) + left( to_string("lbl_latitu"),3 )+ left(to_string("lbl_longit"), 3)`
- Create a match value on leftovers using a levensthein distance, anything under .3 being considered a "match":
`( levenshtein(  "join_nam_1" , "join_name" ))/length("join_name")`
- Match by reviewing leftovers, with special care around "St." vs "Saint"

The workflow above still seems correct, will update as this work progresses.
