### ISSUE TITLE
Inconsistent french iso code ISO 3166 (fra_x_preferred vs fre_x_preferred)

### ISSUE THREAD

**Issue by Joxit** [whosonfirst-data/whosonfirst-data#1282]
The [Normandy](https://spelunker.whosonfirst.org/id/1108826393/) region in France have a `fre_x_preferred` instead of `fra_x_preferred`.
It's an [ISO 639-2/B](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) code for french but it seems that usually it is fra which is used as for [France](https://spelunker.whosonfirst.org/id/85633147/).

Is this normal or an error?

**Comment by stepps00** [comment]
Hey @joxit, thanks for the issue.

It sounds like a bit of https://github.com/whosonfirst-data/whosonfirst-data/issues/291 still lingers in Normandy. This is an error; the `name:` property should use the `fra` language code instead of the `fre` language code.

**Comment by Joxit** [comment]
Thanks for the reply
Ok, I found many entries with `fre`  code, and some of them have both `fre` and `fra`

**Comment by stepps00** [comment]
If you have a list of `wof:id`s with records that contain `fre`, that would be very useful -- otherwise, I can propose a PR with updated iso language codes.

**Comment by Joxit** [comment]
Ok, I will try to get a list of `wof:id` next week :)

**Comment by Joxit** [comment]
Hi,

It is not only French who is affected by this issue but othe riso too. I have a mapping from iso639-2B to iso639-2T [here]( https://github.com/pelias/placeholder/blob/ca0439c612f93ad5f04de3973d29ff7d60bbbb5f/config/language/alternatives.js).

And here is the full list with number of line : 

| lines    | link      |
| -------: | -------: |
| 14756 | [alb](https://media.jawg.io/wof-lang/alb) |
| 38436 | [arm](https://media.jawg.io/wof-lang/arm) |
| 99910 | [baq](https://media.jawg.io/wof-lang/baq) |
| 616 | [bur](https://media.jawg.io/wof-lang/bur) |
| 108905 | [chi](https://media.jawg.io/wof-lang/chi) |
| 65858 | [cze](https://media.jawg.io/wof-lang/cze) |
| 194024 | [dut](https://media.jawg.io/wof-lang/dut) |
| 196856 | [fre](https://media.jawg.io/wof-lang/fre) |
| 17608 | [geo](https://media.jawg.io/wof-lang/geo) |
| 148502 | [ger](https://media.jawg.io/wof-lang/ger) |
| 20036 | [gre](https://media.jawg.io/wof-lang/gre) |
| 42437 | [ice](https://media.jawg.io/wof-lang/ice) |
| 11898 | [mac](https://media.jawg.io/wof-lang/mac) |
| 683 | [mao](https://media.jawg.io/wof-lang/mao) |
| 95309 | [may](https://media.jawg.io/wof-lang/may) |
| 73150 | [per](https://media.jawg.io/wof-lang/per) |
| 94794 | [rum](https://media.jawg.io/wof-lang/rum) |
| 57914 | [slo](https://media.jawg.io/wof-lang/slo) |
| 565 | [tib](https://media.jawg.io/wof-lang/tib) |
| 52195 | [wel](https://media.jawg.io/wof-lang/wel) |

Each line is like `data/{id-path}/{id}.geojson`.

**Comment by stepps00** [comment]
Thanks, @joxit - this is fantastic. Looks like we have quite a few records that need `name:*` property updates.. I would like to prioritize this, as its a simple conversion of language codes -- once I have a PR ready, I'll flag this issue.

**Comment by stepps00** [comment]
This work was completed in each of the per-country repos over the weekend. There are ~260 per-country repos and an equal number of pull requests that will be linked to this issue. Once linked, we can merge and close this issue.

Thanks again, @joxit

**Comment by stepps00** [comment]
This work is complete for all repos, with the exceptions of:

- [https://github.com/whosonfirst-data/whosonfirst-data-admin-xn](Null Island repo)
- [https://github.com/whosonfirst-data/whosonfirst-data-admin-un](United Nations repo)
- [https://github.com/whosonfirst-data/whosonfirst-data-admin-um](US Minor Outlying Islands repo)

There are no affected records in these three repos.

**Comment by Joxit** [comment]
Huge! Nice job guys!

**Comment by Joxit** [comment]
I will remove links from https://github.com/whosonfirst-data/whosonfirst-data/issues/1282#issuecomment-415094113 then :)

@stepps00 If you have time to take a look to my PR here : https://github.com/whosonfirst-data/whosonfirst-data-postalcode-fr/pull/2
