### ISSUE TITLE
Wrong `fra_x_variant` for Mauritius

### ISSUE THREAD

**Issue by Joxit** [whosonfirst-data/whosonfirst-data#1286]
`Île de France` is a wrong french variant for Mauritius [`id: 85632357`](https://spelunker.whosonfirst.org/id/85632357/). 

It's only an historical variant and it also conflicts with the real [`Île de France`](https://spelunker.whosonfirst.org/id/404227465/).

**Comment by stepps00** [comment]
Thanks @joxit - looks like the record for [Mauritius](https://spelunker.whosonfirst.org/id/85632357/) already has a `name:fra_x_historical` property that includes the "Île de France" name. 

Sounds like both records have (or have had) the "Île de France" name, is that true? If so, we're fine with storing the name in both records.

**Comment by Joxit** [comment]
Yes, both records have "Île de France". But the point is that Mauritius should not have "Île de France" as fra_x_variant because this name was used only between 1715 and 1814.
In the French language we don't call Mauritius like this anymore.
