### ISSUE TITLE
Frankfurt am Main vs. Frankfurt (Oder)

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1294]
via https://github.com/pelias/pelias/issues/743
via https://github.com/GIScience/openrouteservice-app/issues/244

Germany has two places called 'Frankfurt' which are commonly confused.

There is the major metro city of [Frankfurt am Main](https://en.wikipedia.org/wiki/Frankfurt) which is fairly centrally located within Germany, and there is the town of [Frankfurt (Oder)](https://en.wikipedia.org/wiki/Frankfurt_(Oder)) which is located in the far East near the border with Poland.

Looking at the WOF records it appears that there were errors when generating the documents, in both cases there are names which are assigned to the incorrect geometry:

- https://spelunker.whosonfirst.org/id/102063589/
- https://spelunker.whosonfirst.org/id/102063919/

Eg. record `102063589` contains the property `qsa2 | Frankfurt am Main` (correct) and also `name.eng_x_preferred | Frankfurt (Oder)` (incorrect).

Conversely, the record `102063919` has the property `qsa2 | Frankfurt (Oder)` (correct) and also `name.eng_x_preferred | Frankfurt am Main` (incorrect).

The issue also effects `statoids`, where the larger city has the population of the smaller region, so I'm not sure how extensive the errors go, they were possibly compounding through multiple imports.

There is also a minor issue of a trailing space in the name `Frankfurt (Oder) ` which could possibly be fixed within the scope of this issue.

**Comment by stepps00** [comment]
It looks like a bad statoids join, which pulled out incorrect names for each record. This can be fixed by simply swapping around the statoids and name properties (I'll double check if there are more bunk properties).

The trailing spaces can also be taken care of in the same commit.
