### ISSUE TITLE
PIP work needed to 404429199

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1296]
https://spelunker.whosonfirst.org/id/404429199/

PIP this record to update descendant records. This record was updated through https://github.com/whosonfirst-data/whosonfirst-data/pull/1139 - follow up with PIP work in this issue.

**Comment by nvkelso** [comment]
Maybe give it a name, too?

**Comment by stepps00** [comment]
This was fixed during all the recent UK work. Closing.
