### ISSUE TITLE
Promote overseas collectivities of France to dependency (from region of France)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#13]
Currently we show this as a region of France, but it is a country of the France empire:

wof_id  iso name
85632737    MF  Saint Martin

data/856/327/37/85632737.geojson

parent now:
85633147
parent proposed:
102191575 (continent), though caveat about France empire

It's also known as: St-Martin

**Comment by stepps00** [comment]
In addition to this, we have a duplicate Saint Martin record, https://whosonfirst.mapzen.com/spelunker/id/85673879/#12/18.0778/-63.0788, which is a `region` parented by another `region.

Plan to clean-up:

1. Deprecate `85673879`, supersede it into `85632737`.
2. Create a new country record for Saint Martin, with mostly the same geometry and properties of `85632737`. Manually update its hierarchy to include France and North America, sets the `wof:controlled` prop to include the `wof:hierarchy`.
3. Keep `85632737`, add the new country record to its `wof:hierarchy` and `wof:parent_id` properties.

**Comment by nvkelso** [comment]
In reviewing the placetype it looks like most other overseas collectivities of France we list as `dependency`, so let's use that here instead of `country`.

See also:

- https://en.wikipedia.org/wiki/Overseas_collectivity

And the other oddball is this one, let's change it's placetype to dependency as well so they all match:

- https://whosonfirst.mapzen.com/spelunker/id/85632371/
