### ISSUE TITLE
Update Thailand region records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1306]
Update region records in Thailand using the Geo-Informatics and Space Technology Development Agency's open admin data. 78 total records (76 + 2 special admin areas).

Source: https://github.com/whosonfirst/whosonfirst-sources/issues/108

**Comment by stepps00** [comment]
In addition to any geometry updates, ensure the name translations and `wof:name` values are current and correct.

**Comment by missinglink** [comment]
:+1: I also noticed today that the shape of the coastline doesn't match the base map, it's causing reverse geocoding issues around the coast, which is unfortunately where a lot of the cool beach bars and accommodation are :)

<img width="706" alt="screenshot 2019-02-27 at 15 11 28" src="https://user-images.githubusercontent.com/738069/53496443-54016000-3aa2-11e9-8af8-5f29361c7273.png">

**Comment by missinglink** [comment]
oops, possibly highjacked this issue? I was referring to the `country` record, not the `region` records, should I open a separate issue?

**Comment by nvkelso** [comment]
It’s okay, we usually rebuild country shape at same time

**Comment by nvkelso** [comment]
We do reccoment snapping to near country, though.

**Comment by stepps00** [comment]
This is the case in many countries, but I agree that the country geometry could be updated to better include the smaller islands and more coastline.

We can add a new country geometry like we've done in other countries, by dissolving descendant region (or county) geometries.
