### ISSUE TITLE
Boquillas Crossing, TX is in the Mexican hierachy

### ISSUE THREAD

**Issue by nigelhorne** [whosonfirst-data/whosonfirst-data#1313]
I thought I'd asked this question, but I can't find the issue, so I'm asking again.  Please close as a dup if you can find it.

The record 1125877787 correctly marks

`"wof:country":"US",`

however the wof:hierarchy->locality_id is set to 1125877787 which is in Mexico.  See https://spelunker.whosonfirst.org/id/1125877787/

**Comment by nvkelso** [comment]
That was for a different place in https://github.com/whosonfirst-data/whosonfirst-data/issues/1249.

Any place **exactly** along a border like this will always be a little tricky for us as it'll be a combination of the feature's lat/lng not always being in the right spot (this one looks too far into Mexico), and the polygons of US and Mexico perhaps needing to be adjusted.

BTW: find issue's you've create in this repo with https://github.com/whosonfirst-data/whosonfirst-data/issues/created_by/nigelhorne%20.

**Comment by nvkelso** [comment]
This also seems like a special type of "breaches" where the parent hierarchy as reported in "wof:country" is inconsistent with the PIP country_id. @thisisaaronland should we calculate that during PIP and add to the breaches list?

**Comment by thisisaaronland** [comment]
It wouldn't hurt. I think I always had a similar project (compare `iso/wof:country` against `wof:hierarchy.[].country_id`) but it kept getting bumped by other things...

**Comment by stepps00** [comment]
Looks like there are two US neighbourhood records on the border that also have Mexico in their hierarchies: [85885059](https://spelunker.whosonfirst.org/id/85885059) & [85882453](https://spelunker.whosonfirst.org/id/85882453).
