### ISSUE TITLE
dependency missing alpha3

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1314]
Heya,

The dependency record for [Akrotiri](https://spelunker.whosonfirst.org/id/85632743/) is missing alpha3 country code information.

This is the only dependency/country record I have found which is missing this property.

The code we have will accept either `wof:country_alpha3` or, if that's not available `ne:iso_a3` for this value, in this case neither is present.

Thanks!

**Comment by stepps00** [comment]
Thanks for the issue @missinglink - it looks like neither of the overseas UK dependencies
 of [Dhekelia Sovereign Base Area](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/856/323/87/85632387.geojson) and [Akrotiri](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/856/327/43/85632743.geojson) have `wof:country_alpha3` or `ne:iso_a3` properties. Neither have [ISO 3166-1](https://www.iso.org/obp/ui/#search/code/) codes.

We could add the ISO code of the UK to Dhekelia and Akrotiri, but that muddles the property a bit. Leaving this open to discuss..

**Comment by nvkelso** [comment]
Let's assign them our own `X?` codes... though if someone else is using an `X?` code for these let's follow their convention.

**Comment by stepps00** [comment]
Sure.. I'll propose the following:

Dhekelia Sovereign Base Area:
  - `wof:country_alpha3` = `ESB` (Eastern Sovereign Base Area)

Akrotiri:
  - `wof:country_alpha3` = `WSB` (Western Sovereign Base Area)

@missinglink, let me know if you find additional records, I will file a PR.

**Comment by nvkelso** [comment]
These must be values in the A??, QM?, X??, or ZZ? namespaces.

So `XEB` and `XWB` could work as long as they are unique in our usage, or propose something else.

> User-assigned code elements are codes at the disposal of users who need to add further names of countries, territories, or other geographical entities to their in-house application of ISO 3166-1, and the ISO 3166/MA will never use these codes in the updating process of the standard. The following alpha-3 codes can be user-assigned: AAA to AAZ, QMA to QZZ, XAA to XZZ, and ZZA to ZZZ.



See also: 

- https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by missinglink** [comment]
This is great thanks.

I don't have any strong opinions on what codes to assign them, just having something unique is super useful :)

I haven't seen any others but if I do I'll let you know.

**Comment by missinglink** [comment]
Is there somewhere in the docs we could add this information for our future selves to understand why we can't find them on iso.org?

**Comment by thisisaaronland** [comment]
Not the most intuitive place for this documentation but: 

https://github.com/whosonfirst/whosonfirst-placetypes#iso-country-codes
