### ISSUE TITLE
Outremont is not a neighbourhood

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#132]
See also: https://github.com/whosonfirst/go-whosonfirst-pip/issues/5

It is an actual locality:

https://whosonfirst.mapzen.com/spelunker/id/85784831/

**Comment by thisisaaronland** [comment]
Well, technically it's a borough...

http://ville.montreal.qc.ca/portal/page?_pageid=5977,86679930&_dad=portal&_schema=PORTAL

**Comment by stepps00** [comment]
Updates to Outremont were completed through the Montreal neighbourhood updates in #418.

Closing this issue, can re-open if we more work is needed on this record.
