### ISSUE TITLE
Baja California - US, should be MX 

### ISSUE THREAD

**Issue by nigelhorne** [whosonfirst-data/whosonfirst-data#1327]
All of the names (e.g. qs:gn_adm0_cc) make it look like it should be in MX, however wof:country is set to US.  See https://spelunker.whosonfirst.org/id/101993551/

```
      'qs:name_adm1' => 'Baja California',
      'wof:lastmodified' => 1531874239,
      'mz:is_official' => 0,
      'src:geom_alt' => [
                          'quattroshapes'
                        ],
      'qs:gn_namadm1' => '02',
      'edtf:inception' => 'uuuu',
      'wof:parent_id' => 101993551,
      'qs:name' => 'Playas de Tijuana Secc Tecnomex',
      'name:unk_x_variant' => [
                                'Playas de Tijuana Secc Tecnomex'
                              ],
      'qs:name_adm2' => 'Tijuana',
      'mz:is_landuse_aoi' => 0,
      'wof:hierarchy' => [
                           {
                             'neighbourhood_id' => 85883149,
                             'region_id' => 85686541,
                             'locality_id' => 101993551,
                             'country_id' => 85633293,
                             'county_id' => 102074501,
                             'continent_id' => 102191575
                           }
                         ],
      'geom:bbox' => '-117.10485,32.533955,-117.10485,32.533955',
      'qs:woe_adm1' => 2346265,
      'qs:name_adm0' => "M\x{e9}xico",
      'qs:local_max' => 2893,
      'wof:breaches' => [],
      'geom:area_square_m' => '5137474.801738',
      'qs:placetype' => 'Suburb',
      'qs:local_sum' => 14029,
      'qs:quad_count' => 8,
      'mps:latitude' => '32.536022',
      'mz:is_hard_boundary' => 0,
      'name:spa_x_preferred' => [
                                  'Playas de Tijuana Secc Tecnomex'
                                ],
      'wof:geomhash' => '9787dc3f5ccfe4e7050a7d69a4f73d18',
      'lbl:latitude' => '32.533955',
      'qs:name_local' => 'Tijuana',
      'mz:max_zoom' => '18',
      'gn:id' => '',
      'edtf:cessation' => 'uuuu',
      'qs:woe_adm0' => 23424900,
      'qs:localhoods' => 36,
      'qs:gn_nam_loc' => 'Tijuana, Tijuana, Baja California, MX',
      'qs:woe_lau' => 0,
      'qs:woe_adm2' => 12599694,
      'wof:lang' => [
                      'spa'
                    ],
      'mz:is_funky' => 0,
      'wof:belongsto' => [
                           102191575,
                           85633293,
                           101993551,
                           102074501,
                           85686541
                         ],
      'lbl:longitude' => '-117.10485',
      'wof:supersedes' => [],
      'qs:gn_adm0_cc' => 'MX',
      'wof:concordances' => {
                              'qs:id' => 1155286,
                              'gp:id' => 55891150
                            },
      'mps:longitude' => '-117.104789',
      'wof:id' => 85883149,
      'mz:hierarchy_label' => 0,
      'src:lbl:centroid' => 'yerbashapes',
      'wof:name' => 'Playas de Tijuana Secc Tecnomex',
      'wof:repo' => 'whosonfirst-data',
      'geom:area' => '0',
      'geom:latitude' => '32.533955',
      'src:geom' => 'mz',
      'wof:superseded_by' => [],
      'geom:longitude' => '-117.10485',
      'mz:note' => 'not in SD',
      'qs:woe_local' => 149361,
      'qs:photo_sum' => 45,
      'edtf:deprecated' => '2017-01-19',
      'name:eng_x_preferred' => [
                                  'Playas de Tijuana Secc Tecnomex'
                                ],
      'iso:country' => 'US',
      'qs:photo_max' => 18,
      'qs:woe_ver' => '7.10.0',
      'mz:tier_locality' => 2,
      'qs:gn_id' => 0,
      'wof:country' => 'US',
      'mz:is_current' => 0,
      'wof:placetype' => 'neighbourhood',
      'wof:tags' => [],
      'mz:min_zoom' => '15',
      'qs:gn_local' => 3981609
```

**Comment by stepps00** [comment]
Thanks @nigelhorne - the properties above come from the [Playas de Tijuana Secc Tecnomex](https://spelunker.whosonfirst.org/id/85883149/), which has been deprecated and tagged as no longer current (as part of San Diego neighbourhood updates).

We could sanity check the [descendant records of Tijuana ](https://spelunker.whosonfirst.org/id/101993551/descendants/?exclude=nullisland) to make sure we correctly catalogue records on the US/MX border, though, similar to the work done in #1313.

**Comment by nigelhorne** [comment]
I note that wof:superseded_by is empty, if edtf:deprecated a "standard" field?

**Comment by stepps00** [comment]
The `edtf:deprecated` property is not a common property - it is only present when we've deprecated a record.. the property to check currency would be `mz:is_current`. Any record flagged with `mz:is_current` equal to `0` should be considered "not current".

**Comment by nigelhorne** [comment]
I've committed https://github.com/nigelhorne/Geo-Coder-Free/commit/c64155af5b847fbb88e5667f4ca45fae08cfbf26 which I hope will handle this.

Thanks for the pointer.

**Comment by nigelhorne** [comment]
What about records where mz_is_current is set to -1, such as https://spelunker.whosonfirst.org/id/1126128871/

**Comment by nvkelso** [comment]
`mz:is_current` = **-1** means that it might be current (or might not be) but a human hasn't verified it in either situation.

**Comment by nvkelso** [comment]
(Closing this issue again to keep organized... if there is a new problem please open a new issue.)

**Comment by thisisaaronland** [comment]
@nigelhorne - In case you aren't already aware: We make an effort to ensure that all properties are defined and documented in the https://github.com/whosonfirst/whosonfirst-properties repo, in both human and machine-readable formats. For example:

* https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/is_current.json
* https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/mz#is_current

There is also @vicchi 's work to generate JSON Schema schema-thingies derived from the properties repo:

* https://github.com/whosonfirst/whosonfirst-json-schema
* https://whosonfirst.org/blog/2018/05/25/three-steps-backwards/

**Comment by nigelhorne** [comment]
That's useful, thank you @thisisaaronland.

I see it defines field names, but what about contents?  For example https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/is_current.json doesn't mention the value -1.

**Comment by thisisaaronland** [comment]
@nigelhorne - It (the `whosonfirst-properties` definitions) does not define things like enumerated sets. For a couple reasons:

1. I still have scars from the (well-meaning) madness that was XML Schema so we have generally opted for human/developer documentation over documentation targeted at machines first (for example, POD rather than JavaDoc :-) 
2. We are feeling our way as we go. Strictly speaking the human readable documentation _should_ be generated from a `PROPERTY.json` file and a corresponding `PROPERTY-remarks.md` file, if necessary. We are not doing that here so there is a disconnect between the human and machine docs. That should be fixed.

Paging @vicchi and @stepps00 for comments, #feelings, etc.
