### ISSUE TITLE
Australian Capital Territory abbreviation is not `CT`

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1349]
Pelias users have reported that `CT` is not a valid or expected abbreviation for the Australian Capital Territory.

Currently, the WOF [ACT record](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/814/93/85681493.geojson) has `CT` for `label:eng_x_abbreviation` and `wof:shortcode`.

Let me know if this is intended, or if you have information suggesting `CT` is ok to use in this case.

If it is correct in some cases, we'll look into using `abrv:eng_x_preferred` which is set to `ACT` for that record.

**Comment by nvkelso** [comment]
> Currently, the WOF ACT record has CT for label:eng_x_abbreviation and wof:shortcode.

Here's what I see for [ACT record](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/814/93/85681493.geojson)

```
"abrv:eng_x_preferred":[ "ACT"],
"label:eng_x_abbreviation":"CT",
"wof:shortcode":"CT",
```

Seems like the label property is funky to me, and the (newer) `abrv` property is correct. It's possible the shortcode should also be ACT, 3-char shortcodes are allowed. Each country seems to have different practices around this so we can try to be as consistent as possible in WOF but you may also need per country logic in your application.

But let's see what @stepps00 says when he's back from his trip!

**Comment by stepps00** [comment]
Thanks @orangejulius 

Agreed that the `CT` value is odd for this record.. The shortcode and abbreviation values are usually sourced from an existing property value (like HASC code), so I'd be fine converting the record to include:

```
"abrv:eng_x_preferred":[ "ACT"],
"label:eng_x_abbreviation":"ACT",
"wof:shortcode":"ACT"
```

Also agree that the `label:` property is funky and may be stripped; I'll file a PR with property edits shortly. If any other codes/abbreviations are reported as funky, feel free to report.
