### ISSUE TITLE
Wrong `fra_x_preferred` for Saint-Alban (101750685)

### ISSUE THREAD

**Issue by Joxit** [whosonfirst-data/whosonfirst-data#1351]
In [101750685](https://spelunker.whosonfirst.org/id/101750685/) properties, `Alban de Verulamium` is the preferred french name.

This is not correct, the preferred name is `Saint-Alban`.

That means that all these properties are also wrong: `bre_x_preferred` `cat_x_preferred` `deu_x_preferred` `ita_x_preferred` `nld_x_preferred` `por_x_preferred` `rus_x_preferred` `spa_x_preferred` `srp_x_preferred` (these are translations of `Alban de Verulamium`)

**Comment by stepps00** [comment]
Hey @joxit - thanks for the issue.. we are actually updating all `locality` records in France, via https://github.com/whosonfirst-data/whosonfirst-data/pull/1343 as a follow up to the `localadmin` updates we completed in https://github.com/whosonfirst-data/whosonfirst-data/issues/1094.

This is a simple property edit for one of the already updated localities, so I'll add these name changes into the pull request and close once merged.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/1343/commits/792102845ca0758737190fb94df7955d9c09e82f

**Comment by Joxit** [comment]
Hi @stepps00, yes I saw your work with #1343, it's awesome and incredibly huge! 

Thx for your fix 😊
