### ISSUE TITLE
erroneous London records

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1360]
Heya,

I saw that a bunch of erroneous London records were cleaned up recently, there are still two records which I think are suspicious and likely not correct:

- https://spelunker.whosonfirst.org/id/101914079/
- https://spelunker.whosonfirst.org/id/101914071/

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1367#issuecomment-435144511

**Comment by nvkelso** [comment]
@stepps00 please file a spot fix just for these 2 records before doing the whole UK cleanup.
