### ISSUE TITLE
typo in 101748453

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1363]
In `101748453` the `name:deu_x_preferred` property is `"Bundesstadt"` (en: 'Federal City') when it should be the name of the capital city `"Bern"`

Note that `deu` is the main language in the German part of Switzerland so this name is particularly importand to get correct as it'll likely show up on basemaps and as the default name in search.

**Comment by missinglink** [comment]
ref: https://en.wikipedia.org/wiki/Talk%3ACanton_of_Bern#Berne

**Comment by stepps00** [comment]
Thanks, @missinglink -- I'll take a look and update in a PR shortly.
