### ISSUE TITLE
Update AUS abbreviations

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1393]
Hi!

Similar to https://github.com/whosonfirst-data/whosonfirst-data/issues/1349, the abbreviation for the Australian state of [Victoria](https://spelunker.whosonfirst.org/id/85681497/) has been set to `VI` in both `wof:shortcode` and `label:eng_x_abbreviation`. Based on [Wikipedia](https://en.wikipedia.org/wiki/States_and_territories_of_Australia#States,_territories,_and_external_territories) and other sources it appears this is not correct, and it's always `VIC`.

I checked all the other Australian states, and they are correct.

**Comment by NickStallman** [comment]
Just a follow up for this issue, there are still state abbrevation errors present.
I detected these errors being used in Pelias.

Queensland - 85681463
abrv:eng_x_preferred is correctly set to QLD but label:eng_x_abbreviation is set to QL

Victoria - 85681497
abrv:eng_x_preferred is correctly set to VIC but label:eng_x_abbreviation is set to VI

Tasmania - 85681583
abrv:eng_x_preferred is correctly set to TAS but label:eng_x_abbreviation is set to TS

Australian states use a mixture of two letter and three letter abbreviations, but there is never any cross over.
The two letter abbreviations are very jarring for a three letter state, it's never shortened like that.
The Wikipedia source is accurate.

**Comment by stepps00** [comment]
Thanks @NickStallman.. this can be tackled through #218. Reopening until those examples are closed.
