### ISSUE TITLE
Some new GeoNames locality records should be campuses

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1431]
Some of the `PPL` GeoNames placetype records introduced recently as locality records should actually be campus records, specifically any "Mobile Home" or "Mobile Home Park" records.

Poke around and find other inconsistencies and note them here.

**Comment by stepps00** [comment]
Full list of ids: [ids.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/2846338/mobile_home_ids.txt).

**Comment by thisisaaronland** [comment]
Mobile homes were classified as neighbourhoods in Where On Earth/GeoPlanet, yielding Endless Hilarity when it came to people geotagging their Flickr photos...

**Comment by nvkelso** [comment]
Turns out people _still_ have strong opinions about seeing these in geotag results ;)
