### ISSUE TITLE
Lat/Lon 0 for some records

### ISSUE THREAD

**Issue by arvindkartik** [whosonfirst-data/whosonfirst-data#1442]
I came across some WOF records having lat/lon as 0.

Here are a few of them. 
https://spelunker.whosonfirst.org/id/504785687/            
https://spelunker.whosonfirst.org/id/421314847/        
https://spelunker.whosonfirst.org/id/554813699/        
https://spelunker.whosonfirst.org/id/421252021/        
https://spelunker.whosonfirst.org/id/504786551/

**Comment by stepps00** [comment]
Hey @arvindkartik thanks for the issue.

We have a similar issue (see [this comment](https://github.com/whosonfirst-data/whosonfirst-data/issues/1346#issuecomment-431891674), specifically) tracking postalcode records without geometries. I'm going to close this issue as a duplicate.

The short answer is that this is not ideal, but expected in some cases. If you know of any sources with openly licensed postalcode data that can be added to WOF, feel free to add links below.
