### ISSUE TITLE
Ceremonial counties for Ireland?

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1443]
Similar to https://github.com/whosonfirst-data/whosonfirst-data/issues/1228 which added ceremonial "counties" in England... let's ensure the old "counties" of Ireland are represented well in Who's On First.

Perhaps this is just some name work, like adding `County Cork` as an English name variant to: https://spelunker.whosonfirst.org/id/85684963/.

But perhaps it's also filling in an empty placetype slot with these (and marking some coterminous with modern equivalents when they are the same)?

**Comment by stepps00** [comment]
Closing this in preference of https://github.com/whosonfirst-data/whosonfirst-data/issues/1849.
