### ISSUE TITLE
Update South Africa admin1 name translations and wof:name values

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1458]
Investigate and fix.

https://spelunker.whosonfirst.org/id/85633813/descendants/?exclude=nullisland&placetype=region

**Comment by nvkelso** [comment]
For example: Change `Northern Province` region name to `Limpopo`, check other names.

**Comment by stepps00** [comment]
All admin1 names and geometries look great in South Africa, aside from the Limpopo / Northern Province example.
