### ISSUE TITLE
Lowercase "and" in default WOF and English names

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1466]
[404429267](https://spelunker.whosonfirst.org/id/404429267/) `Grovesend And Waungron Community` should be **Grovesend and Waungron Community** with lowercase `and`.

![image](https://user-images.githubusercontent.com/853051/51418231-263a0a80-1b37-11e9-9d0e-97ce05484b6e.png)

**Comment by stepps00** [comment]
This `And` -> `and` change was recently made in the `uk-localities` branch (see [here](https://github.com/whosonfirst-data/whosonfirst-data/blob/stepps00/uk-localities/data/404/429/267/404429267.geojson)).

Once that branch merges, I'll crawl to find any other cases. There are a few similar casing issues that may need to be revisited.
