### ISSUE TITLE
clip Nunavut’s geometry to the ocean

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst-data/whosonfirst-data#1475]
https://spelunker.whosonfirst.org/id/85682105/

Maybe from the Canada geometry?

**Comment by stepps00** [comment]
Can merge: 
https://spelunker.whosonfirst.org/id/1158869063/
https://spelunker.whosonfirst.org/id/1158869045/
https://spelunker.whosonfirst.org/id/1158869069/

**Comment by burritojustice** [comment]
While we're in the area, those "county" names are outdated, before Nunavut became it's own territory.

Keewatin Region -> Kivalliq Region / ᑭᕙᓪᓕᖅ   https://en.wikipedia.org/wiki/Kivalliq_Region
Baffin Region -> Qikiqtaaluk Region / ᕿᑭᖅᑖᓗᒃ    https://en.wikipedia.org/wiki/Qikiqtaaluk_Region 
(Kitikmeot Region / ᕿᑎᕐᒥᐅᑦ is the same)

more here https://en.wikipedia.org/wiki/List_of_regions_of_Nunavut

Maybe some alt names? Statscan still uses the old names btw.

**Comment by nvkelso** [comment]
Let's please save existing geom as alt with purpose for revGeo.

**Comment by thisisaaronland** [comment]
mmmm.... multiple geometries.
