### ISSUE TITLE
Comb thru descarteslabs fork and cherry pick

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#148]
https://github.com/descarteslabs/whosonfirst-data/commits/master

There are some incompatible differences in how they are using strings instead of ints for IDs, and their fork is pre-pretty line break GeoJSON so it'll be a bit of a slog.

**Comment by zeke** [comment]
:cherries:

**Comment by stepps00** [comment]
Descartes Labs no longer has public repositories...

**Comment by zeke** [comment]
🦀

**Comment by nvkelso** [comment]
Boo.
