### ISSUE TITLE
Add mz:approximate=1 to locality records with new whosonfirst-sourced geometries

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1480]
Recently, we've updated many locality records' geometries with "approximate" polygons (replacing point geometries).

These geometries have a `src:geom` of `whosonfirst`, and should also have a `mz:approximate=1`property to indicate they're approximate representations of the locality's boundary.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1479

**Comment by nvkelso** [comment]
Let's just track that in #1479 – all the work the last few months is high fidelity.
