### ISSUE TITLE
Quebec needs more St. Lawrence river

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1487]
The entire river is missing which will confuse anyone from Quebec (Canada even). Current record should be made an alt/reverse-geo geometry.

https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/136/251/273/136251273.geojson

**Comment by nvkelso** [comment]
You mean in the big bay part? Can you attach map image that matches your expectation?

**Comment by thisisaaronland** [comment]
No, the big river part :-)

<img width="731" alt="screen shot 2019-02-20 at 09 37 23" src="https://user-images.githubusercontent.com/12658759/53112014-2ee57e00-34f3-11e9-906f-8f0b85ea7ae4.png">

The screenshot depicts a quick and dirty version that is the difference of:

* https://spelunker.whosonfirst.org/id/136251273/
* https://spelunker.whosonfirst.org/id/404529181/

And then the union of:

* https://spelunker.whosonfirst.org/id/101738059/

Because I got bored trying to figure out clipping and joining polygons in QGIS so I just deleted the more detailed polygon for L'Île-d'Anticosti (from the record for `136251273`) and then added it after the fact.

Compressed GeoJSON file attached with a bogus `.txt` extension to "trick" GitHub into letting me attach it...

[qc3.geojson.bz2.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/2885815/qc3.geojson.bz2.txt)

**Comment by nvkelso** [comment]
Got it, we'll store current record as reverse geo geom and adjust default like you propose, along with the Nunavut change.

**Comment by stepps00** [comment]
This was completed through #1514, closing.
