### ISSUE TITLE
Rural US neighbourhoods are grossly oversized

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#149]
Looks like some Zetashapes neighbourhood geoms (USA only) are radically larger than the Quattroshape geoms in less than ideal ways. This is resulting in the label positions (mapshaper using the Zetashape sourced consensus geom) being kilometers away from the actual features, and far outside the bounds of the Quattroshape geoms.

We should use the Quattroshapes geoms for these instead, and regenerate the label positions.

For example: [Korblex](https://whosonfirst.mapzen.com/spelunker/id/85828813/) in Arcata, California has a label centroid that is 50 km away of it's actual location (shown in yellow box). 

<img width="1199" alt="screen shot 2015-11-07 at 21 31 25" src="https://cloud.githubusercontent.com/assets/853051/11018984/115117c2-8598-11e5-833f-b7114e62fed8.png">

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst/whosonfirst-data/issues/137

**Comment by nvkelso** [comment]
Related: #179 (Some urban neighbourhoods are missing / shriveled)

**Comment by stepps00** [comment]
Per comment in https://github.com/whosonfirst-data/whosonfirst-data/issues/341#issuecomment-228793367, locality_tier 1,2,3 should all be reset back to Quattroshapes as default geometry (moving data shapes to `alt:geom`).

**Comment by nvkelso** [comment]
Also look at the **null** `tier_locality` as they seem extra big.

**Comment by stepps00** [comment]
To do:

- [] 
- [] 
- [] 
- []

**Comment by nvkelso** [comment]
Noting that this workflow didn't capture junk `zetashapes` neighbourhoods which effectively have `mz:tier_locality` of NULL.
