### ISSUE TITLE
Haan locality in Germany is too small

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1490]
![image](https://user-images.githubusercontent.com/853051/53045243-f33eab80-3441-11e9-9820-f81aa674efd6.png)

As @thisisaaronland mentioned, OSM data can not be imported in to WOF because of license incompatibilities (ODbL for OSM and CDLA 1.0 for WOF). 

_Originally posted by @thisisaaronland in https://github.com/whosonfirst-data/whosonfirst-data/pull/1486#issuecomment-464833122_

**Comment by nvkelso** [comment]
@schorba Is there another openly license data source for this information?

**Comment by stepps00** [comment]
I'm closing this issue, as it will be taken case of as part of https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1. Let's use https://github.com/whosonfirst-data/whosonfirst-data/issues/1606 for all related admin updates in Germany.
