### ISSUE TITLE
Update Frankfurt records' names

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1494]
As a follow up to https://github.com/whosonfirst-data/whosonfirst-data/issues/1294, let's update the name properties in the records for Frankfurt, Germany ([Frankfurt am Main](https://spelunker.whosonfirst.org/id/101913837/) and [Frankfurt (Oder)](https://spelunker.whosonfirst.org/id/101748801/)).

**Comment by stepps00** [comment]
Related: https://github.com/pelias/pelias/issues/763

**Comment by nvkelso** [comment]
Our convention is to use `{lang}_x_preferred_disambiguation` for this. Please don't change the default preferred name.

- https://github.com/whosonfirst/whosonfirst-properties/blob/71804e87f2ff33fabf9689c7b2a6238ac0317484/properties/label/README.md#lang_x_preferred_disambiguation

**Comment by stepps00** [comment]
This was actually fixed through #1298, and geometries were recently updated through the Germany admin work we recently merged. Both Frankfurt records should be correct.
