### ISSUE TITLE
Promote Serranilla Bank to disputed (from region of -1)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#15]
wof_id	iso	name
85681363	XX	Serranilla Bank

data/102/191/575102191575.geojson

parent now: 
-1
proposed parent:
102191575

**Comment by stepps00** [comment]
`wof:parent_id` field value is now `102191575` 

OK to close this issue?

**Comment by nvkelso** [comment]
That's correct, but somehow it has North America as it's country now?

> country	North America 102191575

Needs to be removed from the hierarchy.

**Comment by stepps00** [comment]
@nvkelso should the `country` ID be removed altogether or should we replace the ID of North America with the ID of the counties that administer and/or claim Serranilla Bank?

Administered by
* Colombia

Claimed by
* Honduras
* Nicaragua
* United States


https://en.wikipedia.org/wiki/Serranilla_Bank

**Comment by nvkelso** [comment]
Yes, let's do that.
