### ISSUE TITLE
GitHub: "Excessive resource usage" 

### ISSUE THREAD

**Issue by hugovk** [whosonfirst-data/whosonfirst-data#1507]
I got a support message from GitHub for my fork of this repo:

---

Hello Hugo,

I work on the Support team at GitHub, and we have some concerns about your repository:

https://github.com/hugovk/whosonfirst-data

We've noticed that your repository is essentially being used as a database, and has grown to a size many magnitudes larger than our 1GB soft limit:

https://help.github.com/en/articles/what-is-my-disk-quota#file-and-repository-size-limitations

Git and GitHub are not optimised for use as a database. As a result, the repository is consuming a non-trivial amount of resources, and has the potential to negatively affect the GitHub service for other users.

We are therefore writing to ask that you migrate this data elsewhere, and delete the repository from GitHub within 30 days. If you could please acknowledge receipt of this email, and confirm your plans to remove this repository as soon as possible, we would be most grateful.

Please let us know if you have any questions or concerns.

Regards,

GitHub Support

---

My fork is 3 years out of date and just over 5 GB. I don't need my fork right now so will delete it, but thought I should mention this.

**Comment by NickStallman** [comment]
Yeah I got this as well. Apparently they've also contacted Who's On First about the parent repository.

**Comment by nvkelso** [comment]
Yes, we also got the notice. Will update once we have further information &/or resolution path.

**Comment by chapmanjacobd** [comment]
It's kind of weird that they do this but also do this: https://github.com/blog/2041-improving-map-data-on-github

**Comment by snadorp** [comment]
Our fork just got disabled by Github:

```
Access to the dcmn-com/whosonfirst-data repository has been disabled due to excessive use of resources.

Please contact GitHub Support by replying to this email to restore access.

The repository was disabled due to excessive disk use.
```

**Comment by nvkelso** [comment]
We continue to work with Github on a solution. So far we've split the big mono repo for the admin placetypes into per country repos. They're evaluating that, and we're also updating tooling for the per country repos. Expect more movement on it this month.

**Comment by hugovk** [comment]
We can close this now. 👍 

https://whosonfirst.org/blog/2019/05/09/changes/
