### ISSUE TITLE
Update geometry of the Korean Demilitarized Zone

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1510]
https://spelunker.whosonfirst.org/id/1159339505/

<img width="1212" alt="screen shot 2019-03-04 at 11 43 02 am" src="https://user-images.githubusercontent.com/18567700/53758561-ede65580-3e72-11e9-9438-7cc050a5f399.png">

The current geometry is generalized; create a new geometry and move the existing geometry to an alt file.

**See**: https://en.wikipedia.org/wiki/Korean_Demilitarized_Zone

> The DMZ is 250 kilometres (160 miles) long, and about 4 kilometres (2.5 miles) wide.

**Comment by nvkelso** [comment]
Please also do this for the South Korea portion: 

- https://spelunker.whosonfirst.org/id/1159339503/
