### ISSUE TITLE
Update English preferred names in Turkey admin2 records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1527]
https://spelunker.whosonfirst.org/id/85632393/descendants/?exclude=nullisland&placetype=county

County records in Turkey often have parenthetical names appended to the end of the English preferred name. In these cases, we should swap the English preferred and variant names.

Examples:
- https://spelunker.whosonfirst.org/id/890462793/
  - "Adalar (Istanbul)" vs. "Adalar"
- https://spelunker.whosonfirst.org/id/890462627/
  - "Kadiköy (Istanbul)" vs. "Kadiköy"

**Comment by nvkelso** [comment]
The `Adalar (Istanbul)` could also be stored into the disambiguation label.
