### ISSUE TITLE
Update English preferred name Województwo wielkopolskie - > Greater Poland Voivodeship.

### ISSUE THREAD

**Issue by mleginus** [whosonfirst-data/whosonfirst-data#1532]
While some regions in Poland do have English name correctly translated like (Województwo małopolskie -> Lesser Poland Voivodeship / https://spelunker.whosonfirst.org/id/85687291/). This is not the case for Województwo wielkopolskie - > Greater Poland Voivodeship - https://spelunker.whosonfirst.org/id/85687323/.

https://github.com/whosonfirst-data/whosonfirst-data/pull/1531

**Comment by stepps00** [comment]
Fixed via #1533
