### ISSUE TITLE
Adjust and add label:* properties to admin1 and admin2

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1534]
Ensure that all admin1 and admin2 have appropriate `label:eng_*` properties. With any feature that has existing label properties, make sure they are correct, ie: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/856/768/13/85676813.geojson

See also: https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/label

**Comment by nvkelso** [comment]
Please reserve `label:eng_x_preferred` for cases where their is ambiguity in the name between placetypes in the same location. Instead fill out `label:eng_x_preferred_longname`.

**Comment by stepps00** [comment]
This was completed through the linked issues above (#1551 / #1558)
