### ISSUE TITLE
Move all wof:label values into label:* properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1540]
WOF has two properties that contain the same information, the [`wof:label`](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/label.json) property and the [`label:eng_x_preferred_longname`](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/label#lang_x_preferred_longname) property. Both are being used, but we should standardize on a single property. 

Move any `wof:label` values into the `label:eng_x_preferred_longname` and remove the `wof:label` property.

**Comment by thisisaaronland** [comment]
I don't know that this is necessary. `wof:label` is akin to `wof:name` in that it's a default label, common to _all_ records the same way name is.

The question is not whether or `wof:name` or `wof:label` are English or Chinese or whatever, only that there is a common default across the set of records.

**Comment by stepps00** [comment]
That's fair. At minimum, it would be useful to backfill the appropriate `label:*` property with the `wof:label` value, when available.

**Comment by nvkelso** [comment]
Turns out Pelias does use `wof:label` in preference to `wof:name`, per @missinglink:

- https://github.com/pelias/whosonfirst/blob/02cabb2f13fc2db0dc25cc023e138bea592e167e/src/components/extractFields.js#L60

**Comment by nvkelso** [comment]
I view this as reducing a data editing tax which causes logic overhead and causes time delay. Ultimately there is always `wof:name` to fall back to already for downstream consumers. 

While I agree it's more consistent to always provide a `wof:label` if any `label:*` is defined, in practice it's always going to duplicate `label:eng_x_preferred` or `label:eng_x_preferred_longname` as the data stands today and is anticipated to be edited in the future. 

What @stepps00 is proposing here is a fallback cascade for downstream consumers of WOF like:

- **Proposed:** Start with `label:*`, to `name:*` then finally `wof:name`
- **Existing:*** What we have today is `label:*`, to `wof:label` to `name:*` then finally `wof:name`

For localization, it's more consistent for the end customer to stay in the requested language tree than have an uneven localization experience.

NOTE: Existing `wof:label` is based on sparse data, like 3k records.

**Comment by missinglink** [comment]
Regarding Pelias, we currently don't support `label:*` but it sounds like we should start supporting that ASAP!
I interpreted the existing `wof:label` property as "The label in the local language", and that's how we use it.

We can fairly easily migrate to using `label:{LANG}_x_preferred_longname` instead.
The issue we'll face is that we don't know the local default `{LANG}` to use, and defaulting to `eng` will make the default labels very english-centric.

It seems like we will need a new property which provides the default label language for the geography?
If we had that per-record, then we could proceed without breaking backwards compatibility.

Regarding the deprecation, we can begin changing our code once the decision has been made, it will take some time for our users to upgrade.
We have a growing number of custom installations and forks which will be affected by this change, so it would be nice if the depreaction window was 4-8 weeks between when you're sure it's going away and the day the field is no more.

**Comment by nvkelso** [comment]
We'll keep the existing `wof:label` in there for now, but won't maintain it. Consider this official deprecation notice. 

> The issue we'll face is that we don't know the local default {LANG} to use, and defaulting to eng will make the default labels very english-centric.

That's another discussion ;)

**Comment by thisisaaronland** [comment]
The default language is _already_ English and has been from the beginning. The point is not that English _should_ be the default language but that there is a common, default language across the entire data set for `wof:name` and `wof:label`. It's English today but it could easily be Chinese or Spanish in a few years.

The purpose of the `name:*` fields is to accommodate all the other languages and do so in a way that leaves the decision up to the consumer.

**Comment by missinglink** [comment]
Hi @nvkelso, I'm just looking at implementing this in Pelias now, does this sound like the correct workflow to use?

I'm using https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/1ae3397312336b101b276df07add7550e10f3343/data/102/080/271/102080271.geojson as a reference

Relevant fields shown below:

```javascript
"wof:label": "Municipio de Manatí",
"label:eng_x_preferred_longname": [ "Manatí Municipality" ],
"label:spa_x_preferred_longname": [ "Municipio de Manatí" ],
"wof:lang_x_official": [ "spa", "eng" ]
```

What I'm doing is:
1. cycling through the `wof:lang_x_official` array checking to see if an `label:{lang}_x_preferred_longname` property exists.
2. if that is not found then looking for `label:eng_x_preferred_longname`
3. else check if `wof:label` exists

Does that sounds correct to you?
My goal is to achieve a refactor that doesn't trigger any failures in our test suite, so I'd like the value to be the same as it was for `wof:label`

**Comment by nvkelso** [comment]
@missinglink Generally yes sounds good!

Please note `longname` (with the placetype included in the name) is just one kind of `label`, and it's really up to the application to fallback to English label before the general `wof:label` (should be a config since different instances / requestors of Pelias would have different language preference). 

Similar to the `disambiguation` label, `longname` is intended as a standalone name... caution should be used when stringing it together to form a concatenated string of all the hierarchy names into a Pelias label. Look at what we've been doing with the US region names (which are `eng_us` and `eng`) to see how we guard against odd longnames for different audiences.

1. cycling through the `wof:lang_x_official` array checking to see if an `label:{lang}_x_preferred_longname` property exists.
2. else cycling through the `wof:lang_x_official` array checking to see if an `label:{lang}_x_preferred` property exists.
3. else if that is not found then looking for `label:{fallback_lang}_x_preferred_longname` (from Pelias setting or request headers which should include device locale)
4. else check if `wof:label` exists
5. else cycle the `name` localization properties
6. else ultimate fallback to `wof:name`

**Comment by thisisaaronland** [comment]
Blog post!

But, really... It would useful/good as a way to make people aware of https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/label (and friends) and to spur reference implementations (code) in places like:

https://github.com/whosonfirst/go-whosonfirst-names
https://github.com/whosonfirst/go-whosonfirst-geojson-v2/blob/master/properties/whosonfirst/whosonfirst.go

Also, we haven't had a blog post in a while...

**Comment by missinglink** [comment]
Thanks for your review:
For future reference here's an example workflow in javascript:

```javascript
// get an array of language codes spoken at this location
function getLanguages(properties) {
  if (!Array.isArray(properties['wof:lang_x_official'])) { return []; }
  return properties['wof:lang_x_official']
    .filter(l => (typeof l === 'string' && l.length === 3))
    .map(l => l.toLowerCase());
}

// convenience function to safely concat array fields
function concatArrayFields(properties, fields){
  let arr = [];
  fields.forEach(field => {
    if (Array.isArray(properties[field]) && properties[field].length) {
      arr = arr.concat(properties[field]);
    }
  });
  // dedupe array
  return arr.filter((item, pos, self) => self.indexOf(item) === pos);
}

// note: 'wof:label' has been officially deprecated
// see: https://github.com/whosonfirst-data/whosonfirst-data/issues/1540
// see: https://github.com/whosonfirst-data/whosonfirst-data/pull/1548
function getLabels(properties) {

  // consider all official languages
  let langs = getLanguages(properties);

  // OPTIONAL: fallback to English
  if (!langs.includes('eng')) { langs.push('eng'); }

  // find labels in official languages
  let labelFields = langs.map(l => `label:${l}_x_preferred_longname`);
  labelFields = labelFields.concat(langs.map(l => `label:${l}_x_preferred`));
  let labels = concatArrayFields(properties, labelFields);

  return labels;
}
```
