### ISSUE TITLE
Flag all records that fall on null island

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1542]
Tag any admin record with a `0,0` geometry, preferrably with a property flag like `mz:is_nullisland`. 

Another option could be `mz:is_funky`, but according to the property definition, it is reserved for places suspected to be (eventually) deprecated.

https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/is_funky.json

**Comment by nvkelso** [comment]
Let's just update the doc and use `mz:is_funky`. Either they are legit places and will be fixed, or they will be deprecated.

**Comment by stepps00** [comment]
This was fixed in each per country repo.

If a record falls on null island, it is marked with `"mz:is_funky":1`.
