### ISSUE TITLE
Give polygon geometries to any "megacity" NE populated place

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1547]
Natural Earth has a populated places file (see: [this page](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/)) that contains ~600 populated places with a "megacity" flag. In some cases, WOF has a polygon geometry representing this place. In others, WOF has a point geometry. 

In cases where WOF has a point geometry, add a new polygon geometry to the record. This can be done similar to how https://github.com/whosonfirst-data/whosonfirst-data/pull/1528 was accomplished, where parent geometries were used when coterminous with the locality (or hand-curating when no data is available).

Lastly, ensure that all the populated places are actually in WOF. If not, add them.

**Comment by nvkelso** [comment]
Instead of reusing the NE polygon, let's prefer making new polygons from scratch (like we did in India).

**Comment by stepps00** [comment]
There are 590 "populated place" records in Natural Earth with a "megacity" flag and 391 "locality" records in Who's On First with a "megacity" flag.

Assuming each of the 590 Natural Earth records are represented in Who's On First, I'm going to suggest:
- [ ] Curating polygon geometries for all 590 records, if not already present
- [ ] Adding a `wof:megacity` flag to the 199 records (diff of NE<>WOF) in Who's On First that don't currently have the property flag
- [ ] Bringing over a Natural Earth concordance to each of the "megacity" records
- [ ] Adding any missing "populated place" from Natural Earth that are not in Who's On First

After the GeoNames import, I suspect that no new locality records need to be added to Who's On First as a part of this record. I'd also like to track adding Natural Earth concordances for _all_ the places in a new issue, since that will require more substantial matching.

**Comment by stepps00** [comment]
This issue will be fixed once the above PRs are merged to each per-country repo.

**Comment by thisisaaronland** [comment]
Blog post, please.

**Comment by stepps00** [comment]
This is complete, closing.
