### ISSUE TITLE
Please expose 3-character country codes

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#155]
Pelias uses these codes.  I think this is a duplicate of #103, but I wanted to make it official that search/pelias uses them.

**Comment by thisisaaronland** [comment]
@nvkelso can you think of any reason not to get use 3-letter codes for wof:country?

**Comment by nvkelso** [comment]
As default or as add on? Both should be included somewhere in the data.

**Comment by stephenkhess** [comment]
Both 2- and 3-character ISO codes would be best for Pelias purposes.

**Comment by thisisaaronland** [comment]
Can you walk me through this a bit more? 2 - 3 letter code mappings are readily available and it's not clear what the point of including them both in WOF would be.

**Comment by stephenkhess** [comment]
That's true, there are plenty of sources for the 2->3 letter code mappings for countries, but the idea is that if Pelias is going to start using WOF for administrative data, then it should be *the* source for administrative data.  Pulling in a 3rd party lookup library muddies the water, so to speak.  But we can certainly do that if you think it would be best.

**Comment by stepps00** [comment]
Once the mesoshape imports are complete, I can crawl the whosonfirst-data repo (and venue/postcode repos, if desired) to add in an iso alpha-3 code field to each record. 

This would involve joining metafiles for each of our placetypes to the appropriate iso code in [this csv file](https://github.com/whosonfirst-data/whosonfirst-data/files/520572/iso_codes.csv.zip) and inserting the new iso property field into each record with a script similar to [this one](https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/add-field.py). Unless, of course, there is a faster method to add a property field to each record.

**Comment by stepps00** [comment]
Per conversation, the first run of this property addition will be done on all country records. The 3 letter `iso` property should match the existing `iso:country` property.

**Comment by nvkelso** [comment]
(Regarding comment https://github.com/whosonfirst-data/whosonfirst-data/issues/155#issue-116128410, this is not a dup of #103.)
