### ISSUE TITLE
Add label bbox for locality and localadmin points

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1575]
Let's add a default `lbl:bbox` for features of the following placetypes when their default  geometry is a point and they don't already have a `lbl:bbox`, that roughly matches the assumed geographic extent for these types of features. Right now the geom:bbox is too tight on just the centroid (as the geom:bbox should be). 

- `locality` points add ~+-.01~ (+-.02) decimal degrees from the geom lat/lng (see comment below)
- `localadmin` points add +-.1 decimal degrees from the geom lat/lng
- `neighbourhood` points add +-.005 decimal degrees from the geom lat/lng

Test case:

- Ettersburg, California: https://spelunker.whosonfirst.org/id/1242987043/

Desired zoom: 

![image](https://user-images.githubusercontent.com/853051/55504220-40976680-5605-11e9-85b2-d33c46bbfb49.png)

Current Spelunker default:

![image](https://user-images.githubusercontent.com/853051/55504195-2f4e5a00-5605-11e9-8017-530a08d4bb26.png)

While most other apps would just zoom to geom bbox:

![image](https://user-images.githubusercontent.com/853051/55504272-586eea80-5605-11e9-95c0-dddf5d802056.png)

**Comment by stepps00** [comment]
Noting that we're changing the value for the locality placetype to:

locality points add **+-.02** decimal degrees from the geom lat/lng

**Comment by stepps00** [comment]
This was fixed in recent crawl work on each per-country repo.

Example in India: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-in/master/data/132/711/616/9/1327116169.geojson
