### ISSUE TITLE
Add label bbox for Vegas

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1577]
That includes the casino Strip and the airport:

- https://spelunker.whosonfirst.org/id/85974801/

![image](https://user-images.githubusercontent.com/853051/55515430-75b0b280-561f-11e9-9b52-27605d000f4c.png)

**Comment by stepps00** [comment]
This was fixed in https://github.com/whosonfirst-data/whosonfirst-data/commit/deea599c523f00bf10c280dea9f36485519182bf, as part of #1581.
