### ISSUE TITLE
Neimersk neighbourhood in Luxemburg is funky

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#159]
As [reported](https://twitter.com/grischard/status/664464951055163392) on Twitter, the neighbourhood of Neimersk [85802101](https://whosonfirst.mapzen.com/spelunker/id/85802101/) is probably funky. 

We can mark this `mz:is_funky=1` to suppress it from map display easily. But deprecating the feature will need more research to fill in the area so there's not a hole in neighbourhood coverage.

![screen shot 2015-11-11 at 10 20 43](https://cloud.githubusercontent.com/assets/853051/11099049/ea4beb0c-885d-11e5-9631-1505306f719b.png)

**Comment by nvkelso** [comment]
Not listed as legit neighbourhood in Wikipedia: https://en.wikipedia.org/wiki/Quarters_of_Luxembourg_City

**Comment by nvkelso** [comment]
Work in progress: https://github.com/whosonfirst/whosonfirst-data/commit/d19ed4ad0d645f43fbe389392da344069067721b. This will hide it from display on Mapzen vector tiles, but still be listed in the meta files and still have a geom.

**Comment by todrobbins** [comment]
:heart: `mz:is_funky":1`

**Comment by stepps00** [comment]
https://spelunker.whosonfirst.org/id/85802101/ 

This feature is now flagged with `mz:is_funky:1`, as https://github.com/whosonfirst-data/whosonfirst-data/commit/d19ed4ad0d645f43fbe389392da344069067721b was merged.

We have more work to do in Luxembourg (see: https://github.com/whosonfirst-data/whosonfirst-data/issues/1149), so we can revisit neighbourhoods independent of this issue if needed.

Closing.
