### ISSUE TITLE
Missing German locality

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1596]
Heya,

We had a bug report today that the town of `Halle` is present in OSM but missing in WOF.

ref: https://www.openstreetmap.org/relation/138701

**Comment by chrispahm** [comment]
Thanks @missinglink for opening the issue!
I tried with a couple more locations, such as [Schellerten](https://www.openstreetmap.org/relation/1182651) and [Spenge](https://www.openstreetmap.org/relation/147440) and had the same problem.

**Comment by stepps00** [comment]
Thanks @missinglink and @chrispahm - we will take a look and propose a fix shortly. Are either of you aware of a source/list of all expected towns in Germany?

**Comment by ImreSamu** [comment]
>Are either of you aware of a source/list of all expected towns in Germany?

one of the source is the EU LAU scheet ( https://ec.europa.eu/eurostat/web/nuts/local-administrative-units )
select: ["Correspondence table LAU – NUTS 2016, EU-28 and EFTA / available Candidate Countries"](https://ec.europa.eu/eurostat/documents/345175/501971/EU-28-LAU-2018-NUTS-2016.xlsx)    ( Version7 - `2019.01.23`)

- on the "DE" sheet ( sorted by International name )  at least 4 "Halle"
![image](https://user-images.githubusercontent.com/2217320/57244860-aa0df900-7039-11e9-91b9-d4ab9454b6cd.png)

but I am not sure what is the best source for importing with Geodata (Lat/Lon)

**Comment by stepps00** [comment]
After a bit of sleuthing, it looks like WOF does have records for the examples listed above (Halle, Schellerton, and Spenge). The names and geometries may need work, but the records do seem to be present:

Halle locality: https://spelunker.whosonfirst.org/id/101809093/
Halle localadmin: https://spelunker.whosonfirst.org/id/1125364737/
Schellerton locality: https://spelunker.whosonfirst.org/id/101807587/
Schellerton localadmin: https://spelunker.whosonfirst.org/id/1125324083/
Spenge locality: https://spelunker.whosonfirst.org/id/101838041/
Spenge localadmin: https://spelunker.whosonfirst.org/id/1125273335/

Between the Quattroshapes imports and more recent GeoNames import, I'd be surprised if records were completely missing in WOF. Geometries of localadmin records could use some love, but importing new records or new point geometries is probably not the best solution. Ideally, we can find better polygons for these features.

**Comment by chrispahm** [comment]
Thanks for having a look at this @stepps00, @ImreSamu ,
I found an official list of all localities referenced with lat/lng coordinates here

https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/05-staedte.xlsx?__blob=publicationFile&v=3

which I remapped a little to be better (machine) readable in the `.csv` file I attached.
[localities_germany.csv.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/3149465/localities_germany.csv.zip)

**Comment by stepps00** [comment]
If WOF is missing any of these records, then yes, they should be imported.. but my hunch is that WOF already has records for these features that have point geometries already.

If we're able to find a source of better polygon data (or import any missing points), then that would be very helpful.

**Comment by chrispahm** [comment]
Alright, I just did a quick search, and regarding the polygons it looks like the following (official) resource has them available

http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=1&gdz_unt_zeile=13&gdz_user_id=0
(in German)

the site offers a download in SHAPE file format, and a WMS & WFS service. I just checked the WMS to see if it has the correct data, and there it looks like the layer `vg250_gem` contains the polygons for the localities. In the WFS, the FeatureTypes are called `vg250:vg250_gem`. Hope that helps!

**Comment by stepps00** [comment]
Closing this issue, as https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1 landed. This PR included new geometries at all placetypes, and I've verified that the examples listed above (Halle, Schellerton, and Spenge) have more detailed geometries for both the locality and localadmin placetypes.

Halle locality: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/101/809/093/101809093.geojson
Schellerton locality: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/101/807/587/101807587.geojson
Spenge locality: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/101/838/041/101838041.geojson

Thanks for the help on this @chrispahm @ImreSamu
