### ISSUE TITLE
Decompression Error for most recent whosonfirst-data-latest.db.bz2 file

### ISSUE THREAD

**Issue by TariqAHassan** [whosonfirst-data/whosonfirst-data#1604]
Attempts to unpack the latest `whosonfirst-data-latest.db.bz2` file fail.

On Ubuntu, this can be replicated by running:

```
wget https://dist.whosonfirst.org/sqlite/whosonfirst-data-latest.db.bz2 \
 && bzip2 -dk whosonfirst-data-latest.db.bz2
```

The full error is the following:

```
bzip2: Data integrity error when decompressing.
        Input file = /path/goes/here, output file = /path/goes/here

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

bzip2: Deleting output file /path/goes/here, if it exists.
```

**Comment by stepps00** [comment]
Hey @TariqAHassan - thanks for the issue. Are you still seeing this error?

This repo is generally used to track issues related to records themselves, so I'm going to close this in preference of an issue in the https://github.com/whosonfirst/go-whosonfirst-dist repository.

We are also in the process of revamping the way we create WOF distributions.. feel free to track updates in the new issue and thanks for your patience!
