### ISSUE TITLE
Wrong Locality boundary in Rostock Germany

### ISSUE THREAD

**Issue by greyeagle** [whosonfirst-data/whosonfirst-data#1606]
Issue
Even OSM data is correct, WOF is giving an incorrect location and county for the following address: 
Schachtelhalmweg 36, 18055 Rostock

WOF is assigning this location to Kessin instead of Rostock. Seems the boundaries are wrong. 

How to Reproduce
You can reproduce this by
https://pelias.github.io/compare/#/v1/search%3Ftext=Schachtelhalmweg%2036%2018055

Possible Solution/Data Source
I propose to use public open data from:
http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=1&gdz_unt_zeile=13&gdz_user_id=0
to fix the locality (and all other administrative) boundaries in Germany. If I can help fetching the shape files in a specific coordinate system if you need a German speaker for that (no English download page), please let me know. 

License of Proposed Data Source
German Open Data license permits any type of usage, provided the correct attribution is given:
https://www.govdata.de/dl-de/by-2-0

Related Issues
I suppose this issue is related to #1596 and #962 as well. The possible solution is the same.

**Comment by stepps00** [comment]
Thanks @greyeagle, the links to existing issues, and a potential license!

I'll take a look at this more closely when we start on the data updates - which should be sooner rather than later - and likely merge this issue with the other related issues.

**Comment by nvkelso** [comment]
Sounds like a good first ticket to exercise the country fanout repos :)

**Comment by stepps00** [comment]
Thanks again, @greyeagle - we are tracking updated to admin records in Germany via https://github.com/whosonfirst-data/whosonfirst-data-admin-de/compare/stepps00/placetype-cleanup, stay tuned for more info.

**Comment by greyeagle** [comment]
@stepps00 You're very much welcome. Thank you for taking this up. I'm looking forward to the further steps.
