### ISSUE TITLE
Upgrade neighbourhood shapes for Berlin

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#161]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`
# 

**Original report:**

The Boroughs and localities of Berlin are missing, also significant neighbourhoods etc. such as:

https://en.wikipedia.org/wiki/Mitte
https://en.wikipedia.org/wiki/Kreuzberg
https://en.wikipedia.org/wiki/Neuk%C3%B6lln
https://en.wikipedia.org/wiki/Charlottenburg-Wilmersdorf

https://en.wikipedia.org/wiki/Boroughs_and_localities_of_Berlin

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/issues/419

**Comment by stepps00** [comment]
[Download link](https://www.statistik-berlin-brandenburg.de/produkte/opendata/geometrienOD.asp?Kat=6301) for CC-BY borough data. 
[New source](https://github.com/whosonfirst/whosonfirst-sources/pull/15) in a PR for Berlin Open Data.

At first glance, this data looks great for boroughs, but the "localities" (which look more like what Who's on First calls neighbourhoods) do not have a name attribute in the source data. More to come...

**Comment by nvkelso** [comment]
From the comment in https://github.com/whosonfirst-data/whosonfirst-data/issues/419#issuecomment-236716163:

**Other possible sources:**

**Berlin**

- Bezirke (districts) and Ortsteile (localities): http://daten.berlin.de/datensaetze?field_category_tid%5B%5D=231 

**Potsdam**

- http://www.potsdam.de/cms/beitrag/10088596/513412/ 
- https://de.wikipedia.org/wiki/Potsdam

**Comment by stepps00** [comment]
**Source**: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/ssuberlin.json

**Properties**: https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/source_data_aliases.json#L101-L103

**Comment by stepps00** [comment]
Closing issue. This work was completed in commit 1db1e84.
