### ISSUE TITLE
Update admin data in Catalonia

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1613]
https://github.com/whosonfirst/whosonfirst-sources/issues/149

Use data provided by @geostarters to update administrative data in Catalonia.

**Comment by missinglink** [comment]
The geocode.earth team went to meet ICGC in Barcelona this month.

They are super friendly and a very knowledgeable + capable team who are keen to help improve coverage in WOF for Catalonia.

**Comment by stepps00** [comment]
@missinglink - that's great, the ICGC data is now in the `whosonfirst-data-admin-es` repo, giving the localadmin and region records in Catalonia more detailed geometries and extra properties/concordances.

**Comment by geostarters** [comment]
We detect some cases in catalonian data where the name is not the same that the esp-cicgc, name. The official names of Catalonian localadmins come from ICGC. 

In https://spelunker.whosonfirst.org/id/404334615/, the correct name (Brunyola i Sant Martí Sapresa) appears in esp-icgc/la, but the others names are incorrect (Brunyola).

Can you explain this cases?

**Comment by stepps00** [comment]
Hey @geostarters - thanks for the report.

It looks like the names in the record you linked retained their original name (pre `esp-icgc` import). I've reopened this issue to crawl each of the localadmin records in this region to compare their existing `wof:name` value with the `esp-icgc:la` value.

**Comment by geostarters** [comment]
Another question:
We have official localities also. And in who's on first the localities are based in quattroshapes info.  
What data would you need to import our "official" localities?

Examples of incorrect locality poligons:
https://spelunker.whosonfirst.org/id/101774309/ 
https://spelunker.whosonfirst.org/id/101774315/

**Comment by stepps00** [comment]
@geostarters that's great to hear.. are you able to provide a download link to a shapefile or GeoJSON with the locality shapes, as well as the license terms?

If so, we can start to de-duplicate the existing WOF records, update WOF records with new shapes, and clean up any "leftover" locality records that don't match to your source.

**Comment by stepps00** [comment]
The PR linked above will update names and name translations for ~690 localadmin features.. once merged, this issue can be closed out.

@geostarters feel free to open a new issue in this repo if you have locality data to share, Who's On First would be happy to update the existing Quattroshapes locality geometries.

**Comment by stepps00** [comment]
The fix for this is in - if additional locality data is provided, let's work to add ASCII, English `wof:name` values on these places, if possible.
