### ISSUE TITLE
Harvest more concordance values from QS properties in Spain

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1615]
As a follow-up to https://github.com/whosonfirst-data/whosonfirst-data-admin-es/pull/1, crawl admin records in Spain and add more concordances (like FIPS) to current records.

**Comment by nvkelso** [comment]
The was completed in September 2023 as part of https://github.com/whosonfirst-data/whosonfirst-data/issues/2164.
