### ISSUE TITLE
Netherlands country not child of empire

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1632]
The [country of Netherlands](https://spelunker.whosonfirst.org/id/85633337/) is not parented by the [empire of Netherlands](https://spelunker.whosonfirst.org/id/136253051/).

If possible, it would be nice to have this association present, we use relationships like this for selective deduplication in Pelias :)

**Comment by stepps00** [comment]
Thanks @missinglink, nice catch. This should be as simple as changing the hierarchy in the country record and using the PIP tools to update descendant records.

Are you aware of any other country/empire records missing this relationship (or even region/empire relationships)?

**Comment by missinglink** [comment]
I only found that one by chance.

It stood out to me which means its probably fairly uncommon.
