### ISSUE TITLE
Charlotte, NC, USA missing population rank

### ISSUE THREAD

**Issue by henrylyne** [whosonfirst-data/whosonfirst-data#1633]
Charlotte, North Carolina doesn't have a population rank:
https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/859/813/33/85981333.geojson

I believe it should be population_rank: 11

I didn't find instructions on how to submit data improvements, I would like to learn more about it.

Thanks!

Henry

**Comment by stepps00** [comment]
Thanks for the issue @henrylyne - we'll take a look.

**Comment by henrylyne** [comment]
I would love to file a pull request but using the exportify tool is a blocker. I just spent the last couple of hours trying to get it to work.

**Comment by thisisaaronland** [comment]
@henrylyne The `wof-exportify` tool (really all of the `py-mapzen-whosonfirst-` toolchain...) is a "known known" of not-awesome-ness. There is a slow-moving project to [port the tool to Go ](https://github.com/whosonfirst/go-whosonfirst-export) but it has to fight for attention with all the other things (like my day job :-)

What specifically are you having trouble with?

**Comment by henrylyne** [comment]
Hi @thisisaaronland , I believe my first mistake was trying to run it with the latest versions of pip and python, so maybe having some env setup instructions in https://github.com/whosonfirst/py-mapzen-whosonfirst-export would get me started on the right foot.

If getting these tools working in the latest versions of python would be useful, I would be willing to help with that, but would probably need some help in return. Many of the porting problems seem fairly easy to resolve, but am not extremely proficient in Python.

@stepps00 definitely appreciate what you do and didn't mean to complain. I would really like to make data updates easier to WoF easier for you. Thanks!

**Comment by thisisaaronland** [comment]
@henrylyne Also on the list is migrating all the `py-mapzen-whosonfirst-` stuff to Python 3 (because it's finally time...) so if you want to take a stab at that you would be a hero (and I would gladly help out and answer questions along the way).

**Comment by stepps00** [comment]
@henrylyne - this issue alone is great, so thanks for filing.. let us know if anything else catches your eye.

**Comment by henrylyne** [comment]
@thisisaaronland what is the best way to get in touch with you? I sent you an email to your resume@ email, and also shot you a flickrmail with my email address.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/115

We've added a `wof:population_rank` property to the locality record for Charlotte, so we should be good here. I'll close this issue, but @henrylyne feel free to let us know if you find additional cases.
