### ISSUE TITLE
Paihia, New Zealand misspelled

### ISSUE THREAD

**Issue by henrylyne** [whosonfirst-data/whosonfirst-data#1643]
The WoF entry spells it Pahia, but the actual spelling is Paihia.
https://spelunker.whosonfirst.org/id/101915123/

Properties that need updating:
eng_x_preferred
loc
locality
name

Sources:
https://en.wikipedia.org/wiki/Paihia
https://www.google.com/maps/place/Paihia,+New+Zealand/@-35.282095,174.0271954,12.62z/data=!4m5!3m4!1s0x6d0ba2b63a911e4f:0x500ef6143a2f380!8m2!3d-35.2806679!4d174.0910345
http://www.paihia.co.nz/

Thanks!

**Comment by stepps00** [comment]
Thanks @henrylyne - we're tracking an update through the above pull request.

Note that we do edit the `name:*` and `wof:*` properties, but we do not edit the `qs:*` properties. We leave any source property (in this case, `qs` represents the Quattroshapes source) in tact.
