### ISSUE TITLE
Licensing information - link targets not available

### ISSUE THREAD

**Issue by pathmapper** [whosonfirst-data/whosonfirst-data#1651]
Some link targets are not available anymore:

https://whosonfirst.org/docs/licenses/

![Auswahl_592](https://user-images.githubusercontent.com/20856381/60765426-82b7c480-a09a-11e9-986f-096496c8fba8.png)

https://github.com/whosonfirst-data/whosonfirst-data#license

![Auswahl_593](https://user-images.githubusercontent.com/20856381/60765551-919f7680-a09c-11e9-8b10-b69faede40b0.png)

**Comment by stepps00** [comment]
Thanks @pathmapper - we'll take a look!

**Comment by nvkelso** [comment]
The extremely verbose (comprehensive) version of the license lives on:

- https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md

But we'll need to rework the website and possibly add a "short" license readme to the sources repo.

Thanks for the tip!

**Comment by stepps00** [comment]
Closing this issue, as we've done a bit of work to fix licensing issues recently through:

- https://github.com/whosonfirst-data/whosonfirst-data/pull/1797
- https://github.com/whosonfirst/whosonfirst-www/pull/71
- https://github.com/whosonfirst/whosonfirst-sources/pull/162

https://whosonfirst.org/docs/licenses/ is now up to date with a list of source license information and we've added a [`LICENSE.md`](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/LICENSE.md) file back to this repo.
