### ISSUE TITLE
No up-to-date bundles available

### ISSUE THREAD

**Issue by pathmapper** [whosonfirst-data/whosonfirst-data#1661]
There are no bundle updates in 2019: https://dist.whosonfirst.org/bundles/

**Comment by stepps00** [comment]
Hey @pathmapper - thanks for the issue.

You're right, unfortunately the bundles have not been updated recently. We hope to tackle this in the near-ish term.

Related issue: https://github.com/whosonfirst-data/whosonfirst-data/issues/1463

**Comment by stepps00** [comment]
The Geocode Earth team
