### ISSUE TITLE
Nunavut geometry fails to parse when right-hand rule for multi-polygons is enforced

### ISSUE THREAD

**Issue by reidab** [whosonfirst-data/whosonfirst-data#1671]
This seems to be a somewhat recent change, as my importer was parsing it successfully last week.

Using, for example, ruby with https://github.com/rgeo/rgeo-geojson

1. `curl -o 85682105.geojson https://data.whosonfirst.org/856/821/05/85682105.geojson`
2. `gem install rgeo-geojson`
3. `ruby -rrgeo-geojson -e "RGeo::GeoJSON.decode(File.read('85682105.geojson'))"` will throw an exception
4. Disabling strict multi-polygon assertions allows the parse to be successful: `ruby -rrgeo-geojson -e "RGeo::GeoJSON.decode(File.read('85682105.geojson'), geo_factory: RGeo::Cartesian.preferred_factory(uses_lenient_multi_polygon_assertions: true))"`

**Comment by stepps00** [comment]
Thanks for the issue @reidab - I ran the geometry against a [validation script]() and do see the following issues:

```
Warning 1: Hole lies outside shell at or near point -89.024288438131947 68.278819346757146
```

Work was done to fix invalid geometries in https://github.com/whosonfirst-data/whosonfirst-data/pull/1293, but it looks like this issue still touches Nunavut.

I'll file an issue shortly with a fix -- let us know if you find additional cases!
