### ISSUE TITLE
Update Noida, India geometry

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1680]
https://spelunker.whosonfirst.org/id/102031133/

Most of the records for highly populated localities in India were recently updated with new geometries through #1592. It looks like the northern portion of the locality for Noida spans north a bit too far to incorrectly include Vaishali.

QA the locality geometry and store the existing shape as an alt.

**Comment by nvkelso** [comment]
Since the shape is WOF we'd just update it?

**Comment by stepps00** [comment]
This record was taken care of in a commit in this PR: https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/17.

Once merged, we can close this issue.

https://github.com/whosonfirst-data/whosonfirst-data-admin-in/blob/stepps00/delhi-updates/data/102/031/133/102031133.geojson
