### ISSUE TITLE
Keeping UK postcodes up to date

### ISSUE THREAD

**Issue by tomtaylor** [whosonfirst-data/whosonfirst-data#1685]
I'd love to build some tooling to keep the UK postcode data up to date. I'm opening this issue to discuss how to approach this (as a WOF newbie), and to track the progress.

UK postcodes are quite granular, typically identifying 5-30 properties, and so change quite frequently.

The most suitable source is probably [OS Open Names](https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-names.html), which has a fairly liberal license that I believe is compatible with WOF, is already mentioned [as a source](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/os.json), and is updated fairly frequently.

Can anyone (@thisisaaronland?), give me a potted history of how the current UK postcode data set got in? Is there any existing equivalent tooling for other countries to look at?

**Comment by tomtaylor** [comment]
OK, I've started work on this. Gonna write some updates here for future adventurers.

I'm actually using the [ONS Postcode Directory](http://data.nicva.org/dataset/ons-postcode-products/resource/4babcbf7-7b17-4a59-9a5c-5530066b2344), because it contains both current and terminated postcodes, with dates for inception and cessation.

I've started [writing a script](https://github.com/tomtaylor/whosonfirst-postalcode-gb-os-sync), which deprecates invalid postcodes and ceases postcodes that no longer exist.

I'm making changes to the data over here: https://github.com/tomtaylor/whosonfirst-data-postalcode-gb and will make a PR when I'm confident I've not messed anything up.

So far I've made two changes, both up for discussion:

1) There's a number of postcodes in the current data that are actually prefixes, like W1A which is a kind of postal region. These are incomplete, and not really postcodes, so I've deprecated these, and suggest we continue the discussion in https://github.com/whosonfirst-data/whosonfirst-data/issues/540 about what we do with these kind of meta postcodes.

2) I've found ~1000 postcodes the ONS data doesn't recognise as current or terminated. I've ceased these. None of them have any geography, and seem to have come from Geoplanet at some point.

**Comment by tomtaylor** [comment]
Also, it's worth mentioning that the Northern Ireland postcodes (starting with BT) are under a more restrictive license, so I don't believe we can use the geography from these in WOF as it stands. 🙄

**Comment by thisisaaronland** [comment]
Sorry for the slow reply.

The history of the UK postal codes is that they were first imported using the GeoPlanet (7.10.0) dump and then updated with the publicly available Ordnance Survey data, circa 2015/16.

Any tooling to track changes, and in particular ceased or deprecated postal codes, is most welcome!

**Comment by tomtaylor** [comment]
Thanks @thisisaaronland! Do you know remember how they were mapped into the UK hierarchy? Was it a simple point-in-nearest-locality?

**Comment by tomtaylor** [comment]
Here's a PR: https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/2

**Comment by tomtaylor** [comment]
A separate PR as a single commit (working with large git repos is _hard_), this time with ~500,000 new postcodes.

https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/3

@stepps00 - you might have thoughts on this?

**Comment by stepps00** [comment]
@tomtaylor - unfortunately, large GIt commits and "infinite" files changed in a commit are the reality we have to work with right now.

If it is possible to separate the changes into several commits, I'd suggest committing changes to each of the twelve folders inside of the `data` folder as individual commits. Smaller commits (both in files changes and total size of the changes) seem to make Git happier, so I'd suggest trying that so you're able to at least see the diff of your changes.

**Comment by tomtaylor** [comment]
@stepps00 thanks - I've checked the diffs locally and I'm pretty confident the script is doing what I expect. Happy to split if that makes it easier to review though, but I don't know if reviewing 200k files is much easier than 2M! Or even if that's small enough for Github to handle?

I've tried to include links to specific examples for each class of change - could generate you the diff  for each and upload as a Gist if that'd be useful?

**Comment by stepps00** [comment]
Yeah, that's all true.. comparing 200k files isn't much different than comparing 2M :) If you do have examples that you're able to throw into a Gist, that would definitely be helpful!

With one of the examples you provided ([this one](https://raw.githubusercontent.com/tomtaylor/whosonfirst-data-postalcode-gb/sync-against-ons-postcode-directory/data/454/124/323/454124323.geojson)), it looks the GeoJSON is valid, but formatted differently than WOF records. Here is the record in its current state: [link](https://raw.githubusercontent.com/tomtaylor/whosonfirst-data-postalcode-gb/sync-against-ons-postcode-directory/data/454/124/323/454124323.geojson).

When updating WOF records, we use a tool to validate the changes and update machine-generate properties (like `wof:lastmodified`, which we use when creating distributions and bundles). Take a look at the tool and let me know if this is something you can wire in to your existing changeset ([Python](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/scripts/wof-exportify) version, [Go](https://github.com/whosonfirst/go-whosonfirst-export) version).

Other than that, the changes look great -- I'll poke around again, but let me know your thoughts on "exportifying" the changes.

**Comment by tomtaylor** [comment]
So, I’ve used the Go exporter library (see here: https://github.com/tomtaylor/wof-sync-os-postcodes/blob/master/wofdata/wofdata.go#L249), but if it’s producing non-compliant JSON, we should probably fix that!

@thisisaaronland, any thoughts?

**Comment by tomtaylor** [comment]
OK, I've had a go at seeing if I can reproduce the Python JSON formatting in Go. I'm sure there's good historical reasons for the formatting... but it's a bit weird!

The first level of nesting uses a 2 space indent, but the properties object has a 4 space.

There's one problem remaining, which is that the properties object has no whitespace between the key and value, while the rest of the objects do. I think fixing this would involve patching `pretty`, because it's not an exposed option.

Have look over here: https://github.com/tomtaylor/go-whosonfirst-format

**Comment by tomtaylor** [comment]
I think there's also an argument to be made that we should align some of the more idiosyncratic aspects of the Python formatter with normal behaviour in Go, which has the added benefit of it easier to adopt other languages in the future.

**Comment by tomtaylor** [comment]
@stepps00 here's the diffs: https://gist.github.com/tomtaylor/dd4303af42008ac1be9f3d02660af441

**Comment by thisisaaronland** [comment]
@tomtaylor - Not to muddy the waters but the Python exporter code can not be retired soon enough in favour of the Go package. It's on the list but time and typing, and all that...

**Comment by tomtaylor** [comment]
@thisisaaronland understood, maybe we should just fix the key sort order (it looks like it flips the sort order of id and properties), and leave everything apart from geometry as 2 space indent with ‘normal’ spacing around keys?

**Comment by tomtaylor** [comment]
In the Go package, I mean.

**Comment by tomtaylor** [comment]
I've just opened a new PR, https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/4, which fixes the issues above and syncs against the Feb 2020 release of the ONS postcode directory. I'd really like to get this merged, so please let me know what I can do to help.

**Comment by stepps00** [comment]
This was fixed through https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/4 - thanks @tomtaylor!
