### ISSUE TITLE
Bunk name in Vosges Department, France

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1687]
https://spelunker.whosonfirst.org/id/85683223/

The `name:fra_x_preferred` property value is "Massif des Vosges" - this is a mountain range with the same name, not the department in France. Update French translations in this record.

**Comment by ImreSamu** [comment]
The hungarian name has a same problem ;  the current  WOF value is  ~  mountain range
 
Now:
* hun_x_preferred =Vogézek    ( same as a "hun" name from here  https://www.wikidata.org/wiki/Q187843 )

Prefered: 
* hun_x_preferred =Vosges      (  "hun" name from here  https://www.wikidata.org/wiki/Q3105 )

**Comment by stepps00** [comment]
Good catch, thanks @ImreSamu!
