### ISSUE TITLE
Update Jammu and Kashmir region, per new union territory boundaries

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1690]
Label properties in the [Jammu/Kashmir region](https://github.com/whosonfirst-data/whosonfirst-data-admin-in/blob/master/data/856/721/37/85672137.geojson) record should be updated to reference the it's new status of "Union Territory", rather than it's old  status of "State".

https://en.wikipedia.org/wiki/Jammu_and_Kashmir

**Comment by stepps00** [comment]
Actually, the former state was split into two new union territories, Jammu and Kashmir, and Ladakh.

- https://en.wikipedia.org/wiki/Jammu_and_Kashmir_(union_territory)
- https://en.wikipedia.org/wiki/Ladakh

Maps of the new boundaries can be found here: https://mha.gov.in/sites/default/files/PressRelease_NoteonUTofJK%26Ladakh_04112019.pdf

**Comment by nvkelso** [comment]
- [PressRelease_NoteonUTofJK&Ladakh_04112019.pdf](https://github.com/whosonfirst-data/whosonfirst-data/files/3843180/PressRelease_NoteonUTofJK.Ladakh_04112019.pdf)

**Comment by stepps00** [comment]
I haven't been able to locate downloadable admin1 boundaries for these new territories, so I may digitize them for this issue. There are various admin1 boundary datasets available, but they all seem to be released before these territories were created. A few online portals show these boundaries, they all seem to be sourced from: https://bharatmaps.gov.in/NewVersion/map.aspx

I'll update this issue when I've made some progress on the boundaries (they'll be aligned with all nearby country and disputed places).
