### ISSUE TITLE
102063947 and 102063901 are mixed up and having wrong Statoids data

### ISSUE THREAD

**Issue by pathmapper** [whosonfirst-data/whosonfirst-data#1697]
https://spelunker.whosonfirst.org/id/102063901/

![image](https://user-images.githubusercontent.com/20856381/63327498-98253d00-c32e-11e9-8920-3682230caac2.png)

There is also some information regarding Oldenburg which doesn't belong there, e.g.
`eng_x_preferred`

Ref https://github.com/GIScience/openrouteservice-app/issues/291

**Comment by pathmapper** [comment]
The geometry is also not correct (see https://www.wikidata.org/wiki/Q5940#/media/File:Lower_Saxony_OS_(Lkr).svg for how it looks).

I'll submit a PR to https://github.com/whosonfirst-data/whosonfirst-data-admin-de.

**Comment by pathmapper** [comment]
[Quattroshapes download links are down](https://github.com/foursquare/quattroshapes/issues/10), at least since January 2018, so remove the alt geometry and related properties?

**Comment by pathmapper** [comment]
Turns out that
https://spelunker.whosonfirst.org/id/102063947/
https://spelunker.whosonfirst.org/id/102063901/
are mixed up and both are having some unrelated "Oldenburg" data from Statoids.

**Comment by stepps00** [comment]
Thanks for this, @pathmapper 

I agree that the `statoids:*` properties in the two records above need to be swapped - we are incorrectly matching the "district-free city" to the "rural" record's properties, and vice versa. The geometries for each record are correct, the record matching the above wikidata link corresponds to this one in WOF: https://spelunker.whosonfirst.org/id/102063947/

**Comment by pathmapper** [comment]
Thanks @stepps00, sorted things out in https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/17.

**Comment by stepps00** [comment]
Thanks for the work, @pathmapper.. I've added a more detailed comment here: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/17/files#r341267640
