### ISSUE TITLE
85681273 is not a valid region of Kazakhstan

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#17]
This polygon should surely belong to one of the other regions of the country. 

In FIPS format, +99 means other small island WTF knows what to do with, and that's where this funky data came from.

**Comment by stepps00** [comment]
Previous PR attached to this issue was closed in favor of an upcoming meso PR.
The feature referenced in this issue (and all `region` features in Kazakhstan) have been updated in [this commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/43ceb592557d58508000e8e58047241255838bb9).

**Comment by stepps00** [comment]
https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/856/812/73/85681273.geojson

Record `85681273.geojson` was deprecated when the commit referenced above was merged to `master`, closing issue.
