### ISSUE TITLE
Arunachal Pradesh needs love (general India, China salient)

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#170]
Arunachal Pradesh 856/722/59/85672259.geojson
- India
- China

@nvkelso - is this already the case in QS or just an import error (aka "my bad")

See also: The Sino-Indian dispute

**Comment by stepps00** [comment]
Disputed record of `India` that is actually the `Arunachal Pradesh` province:
https://whosonfirst.mapzen.com/spelunker/id/85632701

Region record of the `Arunachal Pradesh` province:
https://whosonfirst.mapzen.com/spelunker/id/85672259

Propose that we keep both the disputed record and the region record, update/correct both as the Arunachal Pradesh province, and split the hierarchy of the disputed record (similar to what we've done in other disputed records like [Northern Cyprus](https://whosonfirst.mapzen.com/spelunker/id/85632375) and [Golan Heights](https://whosonfirst.mapzen.com/spelunker/id/85632221)).

**Comment by nvkelso** [comment]
Related to India, Pakistan work in #169.

**Comment by stepps00** [comment]
https://spelunker.whosonfirst.org/id/85672259/
https://spelunker.whosonfirst.org/id/85632701/

These records need name updates (remove "India" name variants, ensure both records have all correct translations, storing "Southern TIbet" in correct name property) and need geometries aligned. Once complete, this record can be closed.

**Comment by stepps00** [comment]
This specific issue with Arunachal Pradesh is complete, but there is additional work around this disputed place taking place through https://github.com/whosonfirst-data/whosonfirst-data/issues/1930.

Closing this issue, tracking additional updates to this record through the PR for #1930.
