### ISSUE TITLE
Close duplicate Flatiron, NY neighbourhood record that's in New Jersey

### ISSUE THREAD

**Issue by henrylyne** [whosonfirst-data/whosonfirst-data#1704]
https://spelunker.whosonfirst.org/id/85865709/

The Hierarchy is incorrect for Flatiron, it should go to Manhattan -> New York City etc. https://spelunker.whosonfirst.org/id/421205771/

Wikipedia agrees:
https://en.wikipedia.org/wiki/Flatiron_District
As does Google Maps:
https://www.google.com/maps/place/Flatiron+District,+New+York,+NY/@40.7415872,-73.993156,16z/data=!3m1!4b1!4m5!3m4!1s0x89c259a2554a6a5b:0xe6b006f94fb1dcd4!8m2!3d40.740083!4d-73.9903489

**Comment by nvkelso** [comment]
The correct Flatiron district is this NYC record:

- https://spelunker.whosonfirst.org/id/85869245/

The one you reported should be "closed" and superseded into the 85869245 record.

**Comment by henrylyne** [comment]
Ah yes, that new record looks good, what nvkelso said.

**Comment by stepps00** [comment]
:+1: Thanks @henrylyne - I'll go ahead and close this issue.
