### ISSUE TITLE
Westelijk Havengebied, NL, hierarchy is broken

### ISSUE THREAD

**Issue by zetahernandez** [whosonfirst-data/whosonfirst-data#1705]
Just found this entry on the **Whos_On_First** table where the **wof:id** is the same to the **wof:parent_id** for Westelijk Havengebied neighbourhood on the Netherlands that's breaking the hierarchical tree. Should the parent_id point to the immediate known parent **borough_id=1108802287** on this place?.

| id         | parent_id  | name                  | placetype | country | hierarchies                                                                                                                                                      |
|------------|------------|-----------------------|-----------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1108802955 | 1108802955 | Westelijk Havengebied | 8         | NL      | [{"region_id": 85687053, "borough_id": 1108802287, "country_id": 85633337, "locality_id": 101751893, "continent_id": 102191581, "neighbourhood_id": 1108802955}] |
|            |            |                       |           |         |                                                                                                                                                                  |

[whosonfirst-data-admin-nl](https://github.com/whosonfirst-data/whosonfirst-data-admin-nl/blob/e49289290756488385cbf138c8a0bfc85552cef6/data/110/880/295/5/1108802955.geojson?short_path=835a69d#L66)

**Comment by zetahernandez** [comment]
Pull request https://github.com/whosonfirst-data/whosonfirst-data-admin-nl/pull/7

**Comment by stepps00** [comment]
Thanks for the issue and PR, @zetahernandez 

We haven't updated data in the Netherlands in some time, so I'm surprised to see this issue appear. That being said, it does look like the `wof:id` and `wof:parent_id` are the same value.

I'll poke around a bit more to see if this affects any other records and update shortly.

**Comment by stepps00** [comment]
After updating, I noticed that this was likely passed on because the record has been deprecated and is considered "not current" (`mz:is_current = 1`).

The record that supersedes this record is: 1108945595.
