### ISSUE TITLE
Add new alt_label property to each alt file

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1714]
To properly index alt files in the distributions, it looks like we need to include a property to each WOF record that contains the full filename of each alt file for that record.

Right now, WOF maintains a `src:geom_alt` property (list) that contains each alt file _source_. But, WOF should add a _new_ property (also list) that includes the full filename of each. This new property would be similar to the [`reversegeo:geometry`](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/reversegeo#geometry) property.

As an example, let's look at [Canada](https://github.com/whosonfirst-data/whosonfirst-data-admin-ca/blob/master/data/856/330/41/85633041.geojson):

https://github.com/whosonfirst-data/whosonfirst-data-admin-ca/tree/master/data/856/330/41

Existing `src:geom_alt` property:

```
src:geom_alt:[
  "quattroshapes",
  "naturalearth",
  "whosonfirst"
]
```

New proposed property would be something like:

```
wof:alt_files:[
  "85633041-alt-naturalearth-display-terrestrial-zoom6.geojson",
  "85633041-alt-naturalearth.geojson",
  "85633041-alt-quattroshapes.geojson",
  "85633041-alt-whosonfirst-reversegeo.geojson"
]
```

**Comment by nvkelso** [comment]
@thisisaaronland is the `.geojson` part important here or do we want to leave the extension flexible? For instance, on disk in the Git repo these are .geojson... but by the time they are loaded into a DB the file extension is less relevant?

**Comment by thisisaaronland** [comment]
Close, but not what @stepps00 has proposed above. I will need to spend 15-20 minutes looking at the state of things and I will report back here.

**Comment by thisisaaronland** [comment]
Okay, so the issue is not the principal (WOF) record but rather the alt file itself. We need to encode enough information in the alt file record to allow it to be written to disk from a non disk-based source. For example, writing the bundles from the SQLite distributions.

The approach we've taken at SFO Museum is to add a `wof:alt_label` property to the alt file. For example:

```
    "wof:alt_label": "swim-route"
```

https://raw.githubusercontent.com/sfomuseum-data/sfomuseum-data-flights-2019-09/master/data/147/776/004/7/1477760047-alt-swim-route.geojson

These values match the `src:geom_alt` property in the principal record:

```
    "src:geom_alt": ["swim-route", "swim-path", "swim-takeoff"]
```

https://raw.githubusercontent.com/sfomuseum-data/sfomuseum-data-flights-2019-09/master/data/147/776/004/7/1477760047.geojson

Maybe it should be `src:alt_label` instead of `wof:alt_label` ? I am open to #feelings about it...

**Comment by stepps00** [comment]
I'm also open to the property/prefix that we use in the alt file to store this information.

Because many of the admin records in WOF have an "extras" usage in the alt filename, the `src:geom` values of a record don't always match the record's alt filenames. In the Canada example used in the original issue comment, we have two alt files from Natural Earth.

```
"85633041-alt-naturalearth-display-terrestrial-zoom6.geojson"
"85633041-alt-naturalearth.geojson",
```

In the "85633041-alt-naturalearth-display-terrestrial-zoom6.geojson", assuming we go with "wof:alt_label", would we maintain the following property/property value?

```
"wof:alt_label": "naturalearth-display-terrestrial-zoom6"
```

For most alt files, this seems like a simple property addition, but in some cases where we're adding "extras" to the alt filename (or storing duplicate geometries from the same source), I want to make sure we're encoding the correct information in the alt file.

**Comment by nvkelso** [comment]
> Maybe it should be `src:alt_label` instead of `wof:alt_label` ? I am open to #feelings about it...

I vote for `src:alt_label`, it's closer to the original's `src:geom_alt`.

(This should be paired with a change to the dist logic to test for either of those being present.)

The test for parent_id should be entirely removed from the isAlt test, that's causing issues for many WOF data records.

**Comment by stepps00** [comment]
Completed through all the linked PRs above. Closing.
