### ISSUE TITLE
Review wof:lang_* properties 

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1718]
We've updated various macroregion, region, and macrocounty records since adding `wof:lang_x_official` and `wof:lang_x_spoken` properties to admin records in https://github.com/whosonfirst-data/whosonfirst-data/issues/290.

In some of these cases, we've superseded records or adjusted records and lost `wof:lang_x_` properties in the process. Localadmin records in Slovenia, for example, should have language codes added to them, since admin records in Slovenia were updated via https://github.com/whosonfirst-data/whosonfirst-data/pull/764.

**Comment by missinglink** [comment]
:+1: Pelias uses the `wof:lang_x_official` property to reduce the number of languages we index to `all official languages + english`

**Comment by stepps00** [comment]
Slovenia localadmin records were given new language properties through https://github.com/whosonfirst-data/whosonfirst-data-admin-si/pull/6, but there are still macroregion, region, and macrocounty records that have "lost" this property through superseding.

I'm going to use this issue to track updating these placetypes' language properties, then use https://github.com/whosonfirst-data/whosonfirst-data/issues/290 to track the larger issue of crawling each repo to apply all existing language properties to all placetypes.

**Comment by stepps00** [comment]
[Here](https://github.com/whosonfirst-data/whosonfirst-data/files/3980980/missing_lang_codes.csv.txt) is a list of any macroregion, region, or macrocounty record that is currently missing a `wof:{lang}_x_*` property.

I'll file PRs in the per-country repos to fix, close this issue, then focus on other placetypes through #290.

**Comment by stepps00** [comment]
This is complete - any follow-up lang work will take place through #290.
