### ISSUE TITLE
Update the geometry of Quebec 

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1719]
<img width="1206" alt="Screen Shot 2019-10-01 at 10 40 22 AM" src="https://user-images.githubusercontent.com/18567700/65986073-fff39b00-e437-11e9-8353-eedd0a7bceed.png">

When using the region geometries to reverse geocode various lat/long values in Canada, I noticed the geometry of Quebec was simplified and did not include large portions of Montreal.

QA the various geometries WOF stores for Quebec and either update the geometry or ensure that the reversegeo geometry is correctly being stored (and has coverage over all of Montreal).

**Comment by thisisaaronland** [comment]
Shouldn't the "reversegeo" polygon include the river around the island (of Montreal)? Imagine you are on a boat traveling up the river: You are still "in" the province of Quebec.

**Comment by stepps00** [comment]
I'll be updating the default geometry shortly, using a geometry from `statcan`. The existing `whosonfirst` geometry will be moved to an alt and the [existing QS alt geometry](https://github.com/whosonfirst-data/whosonfirst-data-admin-ca/blob/master/data/136/251/273/136251273-alt-quattroshapes.geojson) will be stored as the reversegeo geometry (it contains the Saint Lawrence River).

Quebec:
<img width="632" alt="Screen Shot 2019-12-11 at 3 29 41 PM" src="https://user-images.githubusercontent.com/18567700/70669589-ae337200-1c2b-11ea-851a-084f7e1ba2c3.png">

Montreal area:
<img width="786" alt="Screen Shot 2019-12-11 at 3 30 08 PM" src="https://user-images.githubusercontent.com/18567700/70669590-ae337200-1c2b-11ea-9f3a-1a334a1603ab.png">
