### ISSUE TITLE
duplicate locality Malmö Sweden

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1720]
heya,

we have two `locality` records for Malmö Sweden:
- https://spelunker.whosonfirst.org/id/101752283/
- https://spelunker.whosonfirst.org/id/1293243501/

The first one (101752283) seems preferable due to:
- polygon is better
- `ö` has not been transliterated for English keyboards (`oe`)

would it be possible to remove 1293243501?

**Comment by missinglink** [comment]
oh also found this one https://spelunker.whosonfirst.org/id/1209799385/ which seems invalid?

**Comment by missinglink** [comment]
slightly related, but different place, these two seem to represent the same place:
- https://spelunker.whosonfirst.org/id/101913105/
- https://spelunker.whosonfirst.org/id/1310647841/

**Comment by stepps00** [comment]
Thanks for these, @missinglink - these all look like legitimate, though the third "Malmo" (wof:id 1209799385) is a different, legitimate Malmo.

I'll take a look and supersede records accordingly.
