### ISSUE TITLE
duplicate localadmin Luxemburg WI

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1721]
heya,

we have two `localadmin` records for Luxemburg WI:
- https://spelunker.whosonfirst.org/id/404493339/
- https://spelunker.whosonfirst.org/id/404493341/

The first one (404493339) seems preferable due to:
- polygon is better

would it be possible to remove 404493341?

**Comment by stepps00** [comment]
Thanks for the issue @missinglink.. these places are actually correct as-is. 4044933439 is fully contained within 404493341, they're two distinct places that share the same name.. one is a "village", one is a "town" - see:

- https://en.wikipedia.org/wiki/Luxemburg,_Wisconsin
- https://en.wikipedia.org/wiki/Luxemburg_(town),_Wisconsin

There are a few similar cases in Wisconsin and neighbouring states, so not an uncommon theme at the localadmin placetype.
