### ISSUE TITLE
potential incorrect eng_x_preferred label 

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1722]
heya,

I was looking at https://spelunker.whosonfirst.org/id/1209028451/ which has a `name: eng_x_preferred` value of `"Dadra and Nagar Haveli"`.

I couldn't find anything online about why this label would apply to a record where the `wof:name` is `"Nekowal"`.

This name can cause confusion with this region of India by the same name: https://spelunker.whosonfirst.org/id/85672163/

**Comment by stepps00** [comment]
This name value comes from the GeoNames "Alternate Names" property: https://www.geonames.org/1381494/nekowal.html

I agree it is a bunk name that can be removed, so I'll add a PR to fix soon.
