### ISSUE TITLE
Add a CHANGELOG.md file to this repo

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1727]
I'd like to propose adding a monthly "changelog" to this repository to detail each commit that lands in the `whosonfirst-data-*` repositories.

Since the administrative data has split into ~260 per-country repositories, it can be challenging to track each change. Adding a changelog with brief commit/PR descriptions would shed a bit of light on what updates have been done each month.

**Comment by thisisaaronland** [comment]
That would be great!
