### ISSUE TITLE
Add wof:repo property to all alt files

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1729]
Ex: https://github.com/whosonfirst-data/whosonfirst-data-admin-fr/blob/master/data/112/608/293/3/1126082933-alt-qs_pg.geojson

It looks like some alt files do not have a `wof:repo` property. The https://github.com/whosonfirst/go-whosonfirst-sqlite-features-index tools will require this property in each alt file, so let's go through each repo to backfill the `wof:repo` property on all alt files.

**Comment by missinglink** [comment]
FYI the `wof:repo` prop isn't documented here: https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/README.md

**Comment by stepps00** [comment]
Also ensure alts contain: 

```
'wof:geomhash'
'wof:id'
'src:geom'
'wof:repo'
'src:alt_label'
```

**Comment by stepps00** [comment]
Repo country codes with issues in alt files:

['ch', 'gb', 'ro', 'au', 'rs', 'no', 'ps', 'fr', 'it', 'us', 'de', 'sx', 'ko', 'lu', 'pl', 'es', 'sk', 'in']

**Comment by stepps00** [comment]
Re https://github.com/whosonfirst-data/whosonfirst-data/issues/1729#issuecomment-550174858: https://github.com/whosonfirst/whosonfirst-properties/pull/95

**Comment by stepps00** [comment]
This is complete and https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/README.md has been updated to include the `wof:repo` property.
