### ISSUE TITLE
OSMNames as data source?

### ISSUE THREAD

**Issue by pathmapper** [whosonfirst-data/whosonfirst-data#1731]
Came across some hamlets which are not available in `WOF` (and also not in `GeoNames`), e.g.:

https://www.openstreetmap.org/node/5733860856
https://www.openstreetmap.org/node/5733870295
https://www.openstreetmap.org/node/5110535548

These are included in `OSM Names`:
https://osmnames.org/
https://osmnames.org/download/
https://github.com/osmnames/osmnames

What about using `OSM Names` as data source for `WOF`? 
(Sorry if this has already been discussed, found no issue related to this question).

**Comment by stepps00** [comment]
Thanks @pathmapper - if you are able to find `CC0`/`CC-BY` equivalently licensed source for these hamlets, feel free to reopen this issue
