### ISSUE TITLE
Update locality records in Pakistan

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1735]
https://spelunker.whosonfirst.org/id/1108692273/descendants/?exclude=nullisland&placetype=locality

The county of Lahore has several hundred locality descendants, though many of these likely represent neighbourhoods (under a locality of Lahore). Let's QA these records and update geometries.

**Comment by stepps00** [comment]
Noting that the locality of Lahore was updated through https://github.com/whosonfirst-data/whosonfirst-data-admin-pk/pull/12/ and given a [new polygon geometry](https://github.com/whosonfirst-data/whosonfirst-data-admin-pk/blob/3820eab23c87a1ce923e25461230bcfddf04696f/data/421/204/525/421204525.geojson).

**Comment by nvkelso** [comment]
@stepps00 do we still need to evaluate if any of the implicated locality point records around Lahore should be converted to `neighbourhood` placetypes?

**Comment by stepps00** [comment]
> @stepps00 do we still need to evaluate if any of the implicated locality point records around Lahore should be converted to neighbourhood placetypes?

We do, yes.. I'm in the process of merging open PRs to update megacities. Once complete, I plan on filing a follow-up issue to update all descendant records of megacities.. I'll link that issue here.

**Comment by stepps00** [comment]
Updating this task to include updates to more than just the Lahore area.

I will be using this issue to track updates to ~435 locality records, ~1150 neighbourhood records, and updated/new localizations in Urdu for these records.
