### ISSUE TITLE
Update neighbourhoods of Istanbul, Turkey

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1737]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [ ] **Deprecate / supersede** WOF features
- [ ] **Draft review**
- [ ] **Draft revisions** based on review comments
- [ ] **Final review**
- [ ] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by justinelliotmeyers** [comment]
@nvkelso do you need these: https://revolutionarygis.wordpress.com/2019/06/12/turkey-mahalle-shapefile-2019/

Not sure what your take on the license files is - I can try to figure that out before I submit any data to make sure it is in the clear.

Cheers

**Comment by stepps00** [comment]
If we can confirm the license on that dataset, that would be _great_! Looks like district/neighbourhood-level data for the whole [Istanbul region](https://spelunker.whosonfirst.org/id/85679237/).

Thanks @justinelliotmeyers!

**Comment by justinelliotmeyers** [comment]
source: https://sehirharitasi.ibb.gov.tr/
The initial splash has something pop up. These are typically TOS - but I'm not seeing in chrome or firefox.

**Comment by stepps00** [comment]
Noting here that the locality of Istanbul has been updated via https://github.com/whosonfirst-data/whosonfirst-data-admin-tr/pull/16.

Through this work, we should also consider updating the counties in Istanbul. The locality/region are coterminous in this case and both geometries are quite large. We'll need to QA all records in the area to make sure each place is categorized at the appropriate placetype.

**Comment by stepps00** [comment]
<img width="1254" alt="Screenshot 2023-02-27 at 10 37 09 AM" src="https://user-images.githubusercontent.com/18567700/221653271-dd8ad100-4c84-4070-9285-f94fdbbcc2ed.png">

We've been working to create new neighbourhood shapes in Istanbul, screenshot above. These _roughly_ align with the "mahalles" division, and include attributes that can be used to build district shapes, too. We'll be working to update WOF records in a PR, I'll link to that once its been created.

**Comment by nvkelso** [comment]
🔥
