### ISSUE TITLE
Insert 3rd Administrative Level for Portugal

### ISSUE THREAD

**Issue by Guilherme-B** [whosonfirst-data/whosonfirst-data#1740]
LocalAdmin (municipalities) data for Portugal is missing from WOF.

Here are the links for official sources:
- [Mainland](http://www.dgterritorio.pt/ficheiros/cartografia/caop/caop_download/caop_2016_0/ficheiros_em_formato_kml_correspondentes_aos_limites_administrativos_das_freguesias_do_continente)
- [Autonomous Region of Madeira](http://www.dgterritorio.pt/ficheiros/cartografia/caop/caop_download/caop_2016_0/ficheiros_em_formato_kml_correspondentes_aos_limites_administrativos_das_freguesias_da_regiao_autonoma_da_madeira)
- [Autonomous Region of Azores - Central Cluster](http://www.dgterritorio.pt/ficheiros/cartografia/caop/caop_download/caop_2016_0/ficheiros_em_formato_kml_correspondentes_aos_limites_administrativos_das_freguesias_da_regiao_autonoma_dos_acores___grupo_central)
- [Autonomous Region of Azores - Eastern Cluster](http://www.dgterritorio.pt/ficheiros/cartografia/caop/caop_download/caop_2016_0/ficheiros_em_formato_kml_correspondentes_aos_limites_administrativos_das_freguesias_da_regiao_autonoma_dos_acores___grupo_ocidental)
- [Autonomous Region of Azores - Western Cluster](http://www.dgterritorio.pt/ficheiros/cartografia/caop/caop_download/caop_2016_0/ficheiros_em_formato_kml_correspondentes_aos_limites_administrativos_das_freguesias_da_regiao_autonoma_dos_acores___grupo_oriental)

The source is [Direcção Geral do Território](http://www.dgterritorio.pt/), the Portuguese State Organism in charge of territorial planning.

**Comment by nvkelso** [comment]
Nice, thanks for the tip! @stepps00 can investigate integrating with existing data for Portugal, sometimes this is a quick process, sometimes it takes some untangling.

**Comment by stepps00** [comment]
Thanks for the info, @Guilherme-B. I took a look at the data in QGIS and it does look like we can import this placetype into WOF fairly simply.

WOF already have 102 localadmin records in Portugal, mostly coming by way of a previous Quattroshapes Point Gazetteer import: https://spelunker.whosonfirst.org/id/85633735/descendants/?exclude=nullisland&placetype=localadmin

This new source has substantially more records with boundaries, concordance values, and localized names. A bit of work needs to be done to convert the source file's exploded multi-part geometries, but once we're able to match the existing batch of localadmin records in WOF with this new source data, the import should be straightforward.

Once this is done, the locality placetype should be updated, too, but this is a great first start.

Mainland coverage:
<img width="455" alt="Screen Shot 2019-11-14 at 10 43 38 AM" src="https://user-images.githubusercontent.com/18567700/68886675-7f79b880-06cc-11ea-9f2b-a6cae2a2df7b.png">

Some of the non-mainland coverage:
<img width="1323" alt="Screen Shot 2019-11-14 at 10 44 08 AM" src="https://user-images.githubusercontent.com/18567700/68886677-7f79b880-06cc-11ea-89d0-d2c0f0de49df.png">

**Comment by stepps00** [comment]
@Guilherme-B - would you happen to have a link to the data source for these five files? I'm able to find a copyright notice for the DGT site, but it does not specifically reference the boundary data.

I'm also noticing the data links above link to 2016 boundary files, not the newer 2018 files. Are the files linked above the most recent release by DGT?

**Comment by justinelliotmeyers** [comment]
http://mapas.dgterritorio.pt/ATOM-download/CAOP-RAA/ArqAcores_GCentral_AAd_CAOP2018.zip
http://mapas.dgterritorio.pt/ATOM-download/CAOP-RAM/ArqMadeira_AAD_CAOP2018.zip
http://mapas.dgterritorio.pt/ATOM-download/CAOP-RAA/ArqAcores_GOcidental_AAd_CAOP2018.zip
http://mapas.dgterritorio.pt/ATOM-download/CAOP-RAA/ArqAcores_GOriental_AAd_CAOP2018.zip
http://mapas.dgterritorio.pt/ATOM-download/CAOP-Cont/Cont_AAD_CAOP2018.zip

*they all have a unique prj I believe

**Comment by Guilherme-B** [comment]
@justinelliotmeyers was faster, thanks for the help!

Does that answer all your questions @stepps00 ?

**Comment by stepps00** [comment]
The new files do include the newest boundaries that are referenced on the DGT site, but I'll still need to find a data license specific to these files, rather than the site's copyright notice.

**Comment by stepps00** [comment]
I dug into the 2018 CAOP files a bit more and tried to find data license(s) directly related to the boundary files listed here: https://github.com/whosonfirst-data/whosonfirst-data/issues/1740#issuecomment-554146746. It looks like the data is released under the following terms and conditions:

> Whenever the user publishes and / or discloses, by analog or digital means, geographic information owned by the Directorate-General of the Territory, even if partially adapted, he / she shall be credited with the inclusion of the text "Geographic information provided by the Directorate-General of the Territory".

> No restrictions

See: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/78860e37-8b72-4df9-9fbc-7fbd130243a2

@Guilherme-B - are you familiar with additional license terms? Either way, I'll start modifying the data for import, as the license terms seem to be [`CC BY`](https://creativecommons.org/licenses/by/3.0/)-equivalent.

See also:
- http://www.dgterritorio.pt/dados_abertos/caop/
- http://www.dgterritorio.pt/cartografia_e_geodesia/cartografia/carta_administrativa_oficial_de_portugal_caop/

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/pull/8/ added and updated the localadmin records in Portugal with new properties and geometries.

I'll close this issue, but let's track additional follow-up issues separately.
