### ISSUE TITLE
Add official data for Romanian localities

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1741]
I saw new Romanian locality shapes from Justin here: https://revolutionarygis.wordpress.com/2019/11/04/romania-localitati-polygon-shapefile-ancpi/

Which come from official source:

- [Romania Localitati Polygon Shapefile ANCPI](https://geoportal.ancpi.ro/geoportal/catalog/download/download.page)

I corresponded with their contact email, and the data is available under open license! (formatted for legibility)

```
Wed, Nov 6, 1:06 AM
dsig@ancpi.ro
to marinela.buzatu

Hello,
We inform you that you can download the administrative limits from the following link:

- http://geoportal.ancpi.ro/portal/apps/webappviewer/index.html?id=faeba2d173374445b1f13512bd477bb2

Probably mid-next year the WMS service will be available at the following link:

- http://geoportal.gov.ro/arcgis/apps/sites/#/inspire/

For other information please contact us at the email address dsig@ancpi.ro

Sincerely

Directorate of Geographic Information Systems
National Agency for Cadastre and Land Registration
Splaiul Independenței, nr.202A, sector 6, Bucharest
```

License file:

- https://geoportal.ancpi.ro/portal/sharing/rest/content/items/8077dd16e957477d9cc9b457f5f17cac/data
- [Google Translate into English](https://gist.github.com/nvkelso/f0e6ba175445bb8540b664d1173e1881)

**Comment by stepps00** [comment]
Coverage:
<img width="1158" alt="Screen Shot 2019-11-14 at 10 13 13 AM" src="https://user-images.githubusercontent.com/18567700/68884197-7fc38500-06c7-11ea-9f86-59e9e1e090f8.png">

Data includes localized names for each locality, as well as parent admin names and concordance codes that we can store in the `wof:concordances` property. Aside from Bucharest, which is split into the five borough-level divisions, these shapes match what WOF maintains at the locality placetype in Romania.

**Comment by stepps00** [comment]
Updates are being tracked in https://github.com/whosonfirst-data/whosonfirst-data-admin-ro/pull/16/, starting with new boroughs in Bucharest: https://github.com/whosonfirst-data/whosonfirst-data-admin-ro/pull/16/commits/0fa45de12cb72ebe98b0b76ef1bb833feec075f0.

Data source added in https://github.com/whosonfirst/whosonfirst-sources/pull/168.
