### ISSUE TITLE
Update Norway regions and counties to reflect 2020 boundary changes

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1757]
I will add additional sources as I find them, but Norway is restructuring admin1 and admin2 boundaries on January 1, 2020. At first glance, it looks like divisions will merge, resulting in _fewer_ divisions.

https://www.regjeringen.no/no/aktuelt/nye-kommune--og-fylkesnummer-fra-2020/id2576659/

**Comment by justinelliotmeyers** [comment]
https://kartkatalog.geonorge.no/metadata/norske-fylker-og-kommuner-illustrasjonsdata-2020-(klippet-etter-kyst)/7408853f-eb7d-48dd-bb6c-80c7e80f7392

**Comment by stepps00** [comment]
Thanks @justinelliotmeyers - the geonorge link above contains the new divisions, which map to WOF region and localadmin placetypes. I'm working through superseding work now and will have a PR to fix this week.

- https://en.wikipedia.org/wiki/Counties_of_Norway (region)
- https://en.wikipedia.org/wiki/List_of_municipalities_of_Norway (localadmin)
