### ISSUE TITLE
Duplicate Washington, D.C.s

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1758]
Looks like there are two records for Washington, D.C.:

- https://spelunker.whosonfirst.org/id/85931779/
- https://spelunker.whosonfirst.org/id/1141909429/

Both have reasonably good data, but only the first has a geometry. I'm guessing that the second one came in through the Geonames import.

**Comment by stepps00** [comment]
Nice, thanks for the issue @orangejulius. This is a simple fix, so I'll adjust the records in a PR and link it here.
