### ISSUE TITLE
Update Puerto Rico geometry

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1780]
Dependency of Puerto Rico: https://spelunker.whosonfirst.org/id/85633729/

The dependency geometry is overly simplified and should be updated to at least include major sections of San Juan that it currently does not cover. The [US State Department](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/us-dshiu.json) has a polygon for Puerto Rico that looks slightly better, but needs investigation.

The [superseded region](https://spelunker.whosonfirst.org/id/85687331/) of Puerto Rico has a buffered geometry, let's make sure this issue also tracks proper storage of that buffered polygon as a revgeo shape.

**Comment by Guilherme-B** [comment]
Here's another source, https://data.pr.gov/en/widgets/fvqe-f7x9 click on the Menu button > download. Seems pretty accurate.
Data on [municipalities and neighborhoods](http://www.gis.pr.gov/descargaGeodatos/Delimitaciones/Pages/Limites-legales.aspx).
