### ISSUE TITLE
"Devli" looks to be a duplicate of Delhi

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1784]
Record [1125783031](https://spelunker.whosonfirst.org/id/1125783031/) looks to be a locality record with no geometry in the area of Delhi, India.

It looks like it can probably be removed or merged with [Delhi (102029189)](https://spelunker.whosonfirst.org/id/102029189/).
![Screenshot_2020-01-14_07-15-59](https://user-images.githubusercontent.com/111716/72356220-bd2f9900-369d-11ea-8deb-decb0f2ef78f.png)

**Comment by stepps00** [comment]
Good catch.. the Spelunker hasn't indexed recent changes in India, which superseded the Delvi locality point into a new neighbourhood:

- Delvi point locality: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-in/master/data/112/578/303/1/1125783031.geojson

- Delvi point neighbourhood: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-in/master/data/151/139/078/9/1511390789.geojson

Either way, I agree.. the Delvi records need to be superseded into the current Delhi locality record.
