### ISSUE TITLE
Remove newline in wof:name value

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1796]
https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-fr/master/data/110/894/624/9/1108946249.geojson

This neighbourhood record has an "\n" at the beginning of the `wof:name` value.

>    "wof:name":"\nLes Pentes croix-roussiennes",

Crawl repos to find other cases, list them here.

**Comment by missinglink** [comment]
Heya,

Here's some SQL which lists all the string properties which begin or end with `linefeed` (10) `carriage return` (13) or `space` (32):

```sql
SELECT
  geojson.id,
  tree.fullkey,
  '"' || tree.value || '"',
  '"' || TRIM(tree.value, char(10) || char(13) || char(32)) || '"'
FROM
  geojson,
  json_tree(geojson.body) AS tree
WHERE tree.type = 'text'
AND TRIM(tree.value, char(10) || char(13) || char(32)) != tree.value
```

**Comment by missinglink** [comment]
There are a total of [2031 properties worth checking](https://gist.github.com/missinglink/cad8545d6123edf0dfc56e6074d07b8f) for whitespace issues.

For `wof:name` specifically there are only 17 🎉 

```
85801073|$.properties.wof:name|"Vivier d'Oie
1108700485|$.properties.wof:name|"Patía "|"Patía"
1108700755|$.properties.wof:name|"Carmen Del Darién "|"Carmen Del Darién"
1108946249|$.properties.wof:name|"
1108946301|$.properties.wof:name|"
1444833453|$.properties.wof:name|"Fosse de l'Aumone
1444829719|$.properties.wof:name|"
85673071|$.properties.wof:name|"Preah Vihéar "|"Preah Vihéar"
1158804481|$.properties.wof:name|" Colmschate-Zuid"|"Colmschate-Zuid"
1108943237|$.properties.wof:name|"Tosko Celo
1108943249|$.properties.wof:name|"Zgornja Hrusica
1108943285|$.properties.wof:name|"Spodnja Zadobrova
1108943287|$.properties.wof:name|"Zgornja Zadobrova
1108943373|$.properties.wof:name|"Dobrava pri Crnucah
1108950881|$.properties.wof:name|"
1108808409|$.properties.wof:name|"Kyankwanzi "|"Kyankwanzi"
1108832055|$.properties.wof:name|"Buena Vista Park "|"Buena Vista Park"
```

**Comment by stepps00** [comment]
I've just pushed a commit to each of the per-country repos to fix the 2031 cases of bunk new lines/whitespaces. Once I merge the commits, I'll close this issue.

Example in the `whosonfirst-data-admin-gb` repo: https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/commit/f97cb820ccac5a38f107358777c252d7e23baf99

**Comment by ImreSamu** [comment]
@stepps00: 
my pg import is found other cases ... in the `-admin-ae` repo:
and crashed with this message :
```
ERROR:  invalid input syntax for type json
DETAIL:  Character with value 0x0a must be escaped.
CONTEXT:  JSON data, line 1: ...bel:ara_x_preferred_longname":["دبا الحصن
COPY tempadmin_ae, line 217, column data: "{"id":1376826387,"type":"Feature","properties":{"edtf:cessation":"uuuu","edtf:inception":"uuuu","geo..."
```
debugging:
* https://github.com/whosonfirst-data/whosonfirst-data-admin-ae/blob/master/data/137/682/638/7/1376826387.geojson

and the   [raw geojson](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-ae/master/data/137/682/638/7/1376826387.geojson) contains `\n` char ; see :
```
{
"id": 1376826387,
....
"label:ara_x_preferred_longname": [
"دبا الحصن\n"
],
```

**Comment by stepps00** [comment]
@ImreSamu - I just checked this record in the branch with updates in the `admin-ae` repo, it is fixed:

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-ae/stepps00/crawl-names/data/137/682/638/7/1376826387.geojson

I should have this wrapped up shortly, but ping this issue if you find other cases.

**Comment by ImreSamu** [comment]
@stepps00: 
ok, please ping me, if this is finished ..

--------------
other:

I have found an another strange token problems .. postgres json parser error :
```
ERROR:  invalid input syntax for type json
DETAIL:  Token "ח" is invalid.
CONTEXT:  JSON data, line 1: ...erred":["Fatah"],"name:heb_x_preferred":["פת"ח...
COPY tempadmin_af, line 17896, column data: "{"id":1277060739,"type":"Feature","properties":{"edtf:cessation":"uuuu","edtf:inception":"uuuu","geo..."
Time: 1342.476 ms (00:01.342)
```
debugging:
*  https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-af/master/data/127/706/073/9/1277060739.geojson
```json
{
"id": 1277060739,

"name:heb_x_preferred": [
"פת\"ח"
],

```

maybe a quote problem ? .. strange ..

**Comment by stepps00** [comment]
@ImreSamu - I realize I closed this issue too early, sorry for the confusion. This issue should now be fixed.

**Comment by stepps00** [comment]
Re: https://github.com/whosonfirst-data/whosonfirst-data/issues/1796#issuecomment-617468670

Thanks for the note.. that is strange, but that name was not added as part of this work. That name was added ~9 months ago as part of a similar crawl to add name translations. The name should be fixed, though, so I'll update that single name property right now.

@ImreSamu - if you find additional bunk characters in `name` properties in the admin repos, could you open a new issue, please?

**Comment by ImreSamu** [comment]
@stepps00 : 
* the " bunk characters" problem was in my side .. I have to add some extra parameters for the postgres  JSON import to fix it. 
  Sorry for the noise
* now I can import the WOF admin data to the Postgres database .. 

Thank you !
