### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by laszbalo** [whosonfirst-data/whosonfirst-data#1800]
Hello,

I am trying to build SQLite databases from the most up-to-date admin repositories.
For that I am using the `go-whosonfirst-dist` tool.

While it seems to be able to build the SQLite databases, it shows me warnings like this one:
```shell
13:43:05.884287 [wof-dist-build] WARNING build (buildDistributionsForRepo) for repo whosonfirst-data-admin-af failed: Failed crawl callback for /home/x/dev/wof-data/whosonfirst-data-admin-af/data/131/003/598/9/tmpde8oT3: Unable to load /home/x/dev/wof-data/whosonfirst-data-admin-af/data/131/003/598/9/tmpde8oT3, because unexpected end of JSON input (unexpected end of JSON input)
```

Also, while being empty, the above [file](https://github.com/whosonfirst-data/whosonfirst-data-admin-af/blob/master/data/131/003/598/9/tmpde8oT3) does not seem to adhere to the usual naming convention that is used for the GeoJSON files. Based on its name it rather looks like some kind of temporary file. Should that file be the part of the repository? Is it needed somewhere?!

EDIT:
also, there is an other file with strange name, but this one has content in it: [tmpx9PjC0](https://github.com/whosonfirst-data/whosonfirst-data-admin-af/blob/master/data/131/032/704/5/tmpx9PjC0)

**Comment by stepps00** [comment]
Thanks for the issue @laszbalo - it looks like both files you linked to were incorrectly added via the same recent commit. They are erroneous, so I'll remove them shortly. It looks like the geojson files in those directories contain the correct WOF records.

If you find any others, feel free to link them here.

**Comment by missinglink** [comment]
@laszbalo FYI https://data.geocode.earth/wof/dist/sqlite/inventory.json
