### ISSUE TITLE
Missing wof:name property from alt file

### ISSUE THREAD

**Issue by laszbalo** [whosonfirst-data/whosonfirst-data#1803]
Hi,

I am trying to build an SQLite database for Switzerland with the `go-whosinfirst-dist` tool, however it fails to do so, because it is unable to load [this](https://github.com/whosonfirst-data/whosonfirst-data-admin-ch/blob/master/data/117/561/115/1/1175611151-alt-quattroshapes.geojson) alternative geojson file, because of the missing `wof:name` property.

**Comment by stepps00** [comment]
Hey @laszbalo - take a look at [this](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/creating_alt_geometries.md#what-rules-must-alt-geometries-follow) documentation about how to create a Who's On First file. The `wof:name` property is not a required property for alt-geometry files, and most of the existing alt-geometries in Who's On First do not contain that property.

If you do need the `wof:name` for that alt-geometry ("Croy"), I would recommend looking in the default [1175611151.geojson](https://github.com/whosonfirst-data/whosonfirst-data-admin-ch/blob/master/data/117/561/115/1/1175611151.geojson) file.
