### ISSUE TITLE
Auckland City Centre needs parent locality

### ISSUE THREAD

**Issue by henrylyne** [whosonfirst-data/whosonfirst-data#1811]
https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/blob/master/data/857/823/51/85782351.geojson
Auckland City Centre has no parent

Parent should be set to Auckland locality - 101914257
https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/blob/master/data/101/914/257/101914257.geojson

Cheers

**Comment by missinglink** [comment]
Looks like you're on a roll 😎

These tasks might be a good fit for the write field editor?
https://writefield.nextzen.org/

My guess is child features would need to be reparented afterwards, I'm not sure if write field can do that.

**Comment by henrylyne** [comment]
That editor looks great, I would love to use that but I don't see that it supports updating/editing the Parent ID

**Comment by stepps00** [comment]
Hey @henrylyne - we recently updated the localadmin, locality, and neighbourhood placetypes in New Zealand via https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/12.

This PR introduced new localities and corrected many hierarchies of neighbourhoods in the process. This issue is fixed, so I'll close.

**Comment by henrylyne** [comment]
Thanks for the update @stepps00 
I did a spotcheck on Auckland City Center up to Auckland Localadmin and the hierarchy looks good.

It looks like Spelunker has an updated record for Auckland City Center, but the parent, and its parent, is not yet present. Maybe that's expected, but just wanted to let you know in case its not. https://spelunker.whosonfirst.org/id/85782351/
