### ISSUE TITLE
Estonian administrative data is outdated

### ISSUE THREAD

**Issue by iSudo** [whosonfirst-data/whosonfirst-data#1825]
Hi, the regional info in Estonia is outdated in various places f.e:
Lihula town
[https://www.openstreetmap.org/search?query=lihula#map=14/58.6851/23.8314](https://www.openstreetmap.org/search?query=lihula#map=14/58.6851/23.8314)

I'm not sure if there is anything I can do to help update Estonian data. If there is just let me know.

**Comment by missinglink** [comment]
Hi @iSudo, do the Estonian government publish any data released under a CC-BY, CC0, or equivalent license which could be used here?

**Comment by iSudo** [comment]
I will query, and find out, btw, how was estonian data generated previously?

**Comment by missinglink** [comment]
Stephen will be able to tell you more about where the original data was sourced from, I had a quick look at one and it said 'quattroshapes' which was another gazetteer so I'm not sure.

There is an excellent page at https://whosonfirst.org/docs/licenses/ which mentions all the sources, there is an Estonia section listed under Quattroshapes named 'Maaamet', I'm not familiar, could that be the source?

related https://github.com/whosonfirst-data/whosonfirst-data/issues/25

**Comment by iSudo** [comment]
I think we don't have anything ourselves, so may be the best case, is to simply update it like it was done last time, is it possible?

**Comment by justinelliotmeyers** [comment]
they update every year:
https://geoportaal.maaamet.ee/eng/Spatial-Data/Administrative-and-Settlement-Division-p312.html

**Comment by iSudo** [comment]
Oh, great, and since who's on first data on estonia last updated on summer, last year, is it possible to update it, to match Maaamet's state?

**Comment by stepps00** [comment]
Thanks for the issue @iSudo 

> Oh, great, and since who's on first data on estonia last updated on summer, last year, is it possible to update it, to match Maaamet's state?

Yes, we can update the existing Estonia admin data using the data in the link provided by @justinelliotmeyers. License:

> The use of administrative and settlement units data is not restricted, but the reference to the data source (i.e. Estonian Land Board) and validity date must be made!
For example: "Administrative and settlement units, Estonian Land Board 01.11.2019"

Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1550

**Comment by iSudo** [comment]
Excellent, thanks a bunch! If there is anything I can do please just let me know.

**Comment by iSudo** [comment]
One more thing, we need to plan on when to rebuild our addresses, when can we expect who's on first data to be updated?

**Comment by stepps00** [comment]
@iSudo - There is no immediate plan to update the locality geometries in Estonia, but I'll put this on the list of shorter-term "to do" items. Let me poke around the Estonia repo, visualize the current coverage and get back to you later this week/early next week with more detail.

**Comment by iSudo** [comment]
Yhank you :)

**Comment by iSudo** [comment]
Hei @stepps00 is there a way to switch wof off for the time being ? By that i mean prevent it from even being downloaded and used anywhere in pelias

**Comment by stepps00** [comment]
Hey @iSudo - that is a question for the Pelias team, perhaps @missinglink can suggest a workaround for you.

As for an update on this issue, I'm working through some updates to our administrative data in Romania right now, but hope to revisit this issue within the next month or so. There are some easy wins here, like merging duplicate region records and adding better translations for places in Estonia, so I hope to have another update soon.

**Comment by missinglink** [comment]
Hi @iSudo this repo is maintained by a different team to Pelias, I'm happy to help you out over on our GitHub org if you have more questions.

It's not currently possible to run Pelias without whosonfirst, so while you can filter and blacklist certain entries from being imported to Pelias you can't completely opt-out of whosonfirst.

We have plans to make Pelias gazetteer-agnostic at some point to allow use of OSM for administrative areas but that work has been delayed due to the pandemic and probably won't happen until the end of the year.

**Comment by iSudo** [comment]
okay, but do you know which containers use whos on first data, its the pip-service right(which serves wof data)?
