### ISSUE TITLE
Unincorporated community of Wayne, PA is missing

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1831]
There's an unincorporated community called [Wayne, PA](https://en.wikipedia.org/wiki/Wayne,_Pennsylvania) that is in [Geonames](https://www.geonames.org/5218270/wayne.html), but not WOF as far as I can tell.

I would have expected a record to have come in via the Geonames import from a while back, but that's not the case.

@stepps00 pointed out that this is likely because the WOF record for [Wayne Heights, PA](https://spelunker.whosonfirst.org/id/101720183/) (a different town) incorrectly lists the Wayne, PA Geonames record as a concordance. This also explains why Wikidata [points to the Wayne Heights WOF record](https://www.wikidata.org/wiki/Q3891562).

**Comment by stepps00** [comment]
Thanks @orangejulius - A bunk concordance, coupled with the GeoNames import caused various issues with Wayne/Wayne Heights records in PA. A couple things:

- This [Wayne Heights](https://spelunker.whosonfirst.org/id/1193035205/) record:
  - Should be flagged as not current
  - Should be superseded into [101720183](https://spelunker.whosonfirst.org/id/101720183/)
- This [Wayne Heights](https://spelunker.whosonfirst.org/id/101720183/) record:
  - Needs an updated `gn:id` concordance (it should be [4562065](https://www.geonames.org/4562065/wayne-heights.html))
  - Should get all `gn:` properties from the [1193035205](https://spelunker.whosonfirst.org/id/1193035205/) record
  - Should supersede [1193035205](https://spelunker.whosonfirst.org/id/1193035205/)
- A new WOF record should be created for this [Wayne, PA](https://www.geonames.org/5218270/wayne.html)

Once that is done, the concordances and names on the records should be QA'd, too.

**Comment by stepps00** [comment]
Fixed in: https://github.com/whosonfirst-data/whosonfirst-data-admin-us/commit/37c3d24e39f140f3f2ec180a8af049a89a6069b3, https://github.com/whosonfirst-data/whosonfirst-data-admin-us/commit/6316c95c517687ef287d66d70b29fc1a28841e8e, https://github.com/whosonfirst-data/whosonfirst-data-admin-us/commit/570b1249e7e9547d16b1ec469d8ce7e398609a11.
