### ISSUE TITLE
Canadian locality with USA hierarchy

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1832]
I just found this today: https://spelunker.whosonfirst.org/id/1125946947
Looks like the locality is actually part of CA, not US.

The following IDs may also be affected (although I suspect not all of them):
> These are IDs parented by the USA where OSM mappers mapped a Canadian postcode, usually near the border

```
85979733
85978679
85978259
85978103
85951543
85950967
85949107
1327250525
1242877063
1242813653
1242593273
1226556035
1126057229
1126002335
1125946947
1125877877
1125830351
101730679
101728445
```

**Comment by stepps00** [comment]
Nice, thanks for the list @missinglink 

These can be taken care of for the US <> Canada mismatches, but I'm curious about a larger list of any WOF record that has a `wof:country` that mismatches the country in the record's hierarchy. I should be able to crawl repos to craft a bigger list.
