### ISSUE TITLE
Manama, Bahrain

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1842]
Heya,

I was investigating a change today to our capital cities test cases.
We had https://spelunker.whosonfirst.org/id/890440103/ for `Manama, Bahrain`

The spelunker shows "this record has been both deprecated and superseded by: 421190647"
However [421190647](https://spelunker.whosonfirst.org/id/421190647/) says "this record has been superseded by: 890440103"

https://www.instagram.com/p/Bz6MyFLjlCa/

**Comment by missinglink** [comment]
Also worth noting that there is also https://spelunker.whosonfirst.org/id/85669053/ as another potential candidate.

**Comment by missinglink** [comment]
Just checked this today and the data looks fixed to me 👍 

The spelunker is a bit misleading, I think maybe the data is out-of-date?

<img width="359" alt="Screenshot 2020-08-20 at 15 58 10" src="https://user-images.githubusercontent.com/738069/90779306-f39d5880-e2fd-11ea-8e7a-13e04fd748ab.png">

**Comment by stepps00** [comment]
Oh nice, thanks for confirming!

Yeah, I think the Spelunker is out of date in this case. There's an open issue about that here: https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/145
