### ISSUE TITLE
"wof:id" properties encoded as strings

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1845]
Short-term I can trap and handle this in code but it appears we have a bunch of `wof:id` properties that are encoded as strings:

```
~/go-whosonfirst-findingaid-github]$ go run -mod vendor cmd/catalog/main.go -cache-uri 'sqlite://?dsn=wof.db' -prefix whosonfirst-data-admin-
2020/05/21 21:18:47 Time to index https://github.com/whosonfirst-data/whosonfirst-data-admin-ad.git: 380.335527ms
2020/05/21 21:18:48 Time to index https://github.com/whosonfirst-data/whosonfirst-data-admin-ae.git: 666.333804ms
2020/05/21 21:18:57 Failed to index https://github.com/whosonfirst-data/whosonfirst-data-admin-af.git: json: cannot unmarshal string into Go struct field geojson_properties.properties.wof:id of type int64
2020/05/21 21:18:57 Time to index https://github.com/whosonfirst-data/whosonfirst-data-admin-af.git: 8.896173951s
2020/05/21 21:18:57 Time to index all: 24.870897949s
2020/05/21 21:18:57 json: cannot unmarshal string into Go struct field geojson_properties.properties.wof:id of type int64
exit status 1
```

**Comment by stepps00** [comment]
Hmm, looks like this is affecting alt files.. I'll crawl the per-country repos to update and link the PRs to this issue.

**Comment by stepps00** [comment]
List of ids: [string_ids.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/4691627/string_ids.txt)

Looks like this impacts alt files of ~130 country records, likely added when we improved country polygons.

**Comment by stepps00** [comment]
@thisisaaronland - this issue should be resolved now, I just pushed commits to ~100 per-country admin repos to fix `wof:id` string values in alt files. I'll crawl repos once more to confirm, then close.

**Comment by thisisaaronland** [comment]
Huzzah!

**Comment by stepps00** [comment]
Confirming this is fixed with the most recent commits to `master`.
