### ISSUE TITLE
Missing Ireland Data

### ISSUE THREAD

**Issue by henrylyne** [whosonfirst-data/whosonfirst-data#1849]
https://www.cso.ie/en/census/census2016reports/census2016smallareapopulationstatistics/
It would be good to add the 4 provinces of Ireland to your data, along with the counties and small settlement data. There is probably other useful data at that link also.

The general hierarchy should be:
- The island of Ireland
- the Republic of Ireland(Independent State), Northern Ireland(UK)
- 4 provinces, 1(Ulster) shared by Northern and Republic
- 32 counties: 6 in Northern Ireland, 26 in Rep. of Ireland
- Cities and towns

https://en.wikipedia.org/wiki/Ireland

**Comment by nvkelso** [comment]
Historical, ceremonial counties for everyone!

**Comment by stepps00** [comment]
Related (dupe?): https://github.com/whosonfirst-data/whosonfirst-data/issues/1443

**Comment by henrylyne** [comment]
Ceremonial counties? I have no idea what they are, but they don't sound as important as having the current counties of Ireland well represented in the place hierarchy.

I fixed the link at the top, to link to Irish Census data that is hopefully useful for adding provinces, counties, cities and towns(aka settlements). The data for settlements looks especially useful for adding population and polygons for places.
https://www.cso.ie/en/census/census2016reports/census2016smallareapopulationstatistics/

**Comment by stepps00** [comment]
Neighbourhood and campus placetypes aside, WOF currently has the following data / placetype structure for Ireland:

- **Country**: 1 record, maps to https://en.wikipedia.org/wiki/Republic_of_Ireland
- **Region**: 31 records, maps to https://en.wikipedia.org/wiki/Administrative_counties_of_Ireland
- **Localadmin**: 960 records, map to "Settlements" 
- **Locality**: 9,462 records, map to "Settlements" and "Urban Areas" including these places https://data-osi.opendata.arcgis.com/datasets/2de2edc7c47e4f2dbd56089b3d05ecc2_0/explore?location=53.380906%2C-8.235306%2C7.66

My suggestion for an updated placetype structure in Ireland:
- **Country**: 1 record, maps to https://en.wikipedia.org/wiki/Republic_of_Ireland (no changes)
- **Macroregion**: 4 records, maps to these historical counties: https://en.wikipedia.org/wiki/Provinces_of_Ireland (new)
- **Region**: 31 records, maps to https://en.wikipedia.org/wiki/Administrative_counties_of_Ireland (no changes)
- **Localadmin**: 0 records, not a valid placetype
- **Locality**: X records, map to "Settlements" and "Urban Areas" including these places https://data-osi.opendata.arcgis.com/datasets/2de2edc7c47e4f2dbd56089b3d05ecc2_0/explore?location=53.380906%2C-8.235306%2C7.66

I'd propose:
- Adding new `macroregions` for the historical provinces of Ireland
- Deprecating / flagging all of the `localadmin` as not current
- Updating and adding new `locality` polygons

This would not give WOF a continuous fabric of locality coverage, but this would clean up various placetypes and update ~1k locality polygons in the country. Open to thoughts and suggestions here..

**Comment by nvkelso** [comment]
Sounds good!

**Comment by henrylyne** [comment]
I see a few problems with your suggestions Stephen. Starting with Ireland, the island, it is made up of 2 different countries(Republic of Ireland and Northern Ireland) and they share a province Ulster. So some counties in Ulster belong to Northern Ireland and some belong to the Republic.This would seem to create problems for a simple linear hierarchy. So maybe it is easier to omit province as a region or macroregion , or else have two Ulster entries, one for each country.

My suggestions for **Country**: **1** - Republic of Ireland
**Region**: **0 or 4** - see above, maybe leave this out
**County**: **26** - should have 26 records that are made up of the distinct entries in the column titled County here,  https://data-osi.opendata.arcgis.com/datasets/55824a181fb94c8294048af90f5880a2_3/explore?showTable=true
**LocalAdmin**: **31** - should consist of the 31 records of the column marked English(weird name) here https://data-osi.opendata.arcgis.com/datasets/55824a181fb94c8294048af90f5880a2_3/explore?showTable=true
**Locality**: **873** - should consist of the records found here with value SETTL_NAME here https://data-osi.opendata.arcgis.com/datasets/2de2edc7c47e4f2dbd56089b3d05ecc2_0/explore?location=53.345147%2C-8.235306%2C7.66&showTable=true One fix to make to the SETTL_NAME is that the major cities have values of "Cork city and suburbs" or "Galway city and suburbs", it would be better to drop the " and suburbs" if you use them as place names.

Not sure I chose all the place types appropriately above.

**Comment by justinelliotmeyers** [comment]
**BE CAREFUL W SETTLEMENTS HERE - NOT A FULL DATASET - MISSING A LOT OF TOWNS/ CITIES** BASED ON A PREVIOUS DEV I DID SEVERAL YEARS AGO - These are also a fun little stick in the spokes: https://data.gov.ie/en_GB/dataset/townlands-osi-national-statutory-boundaries1?package_type=dataset

**Comment by henrylyne** [comment]
@justinelliotmeyers any examples of towns or cities missing? I can see villages that are missing from the list I linked to above, so I wonder if it is only smaller localities that are omitted. Some examples I found are Eyeries and Allihies, which are less than a thousand people.

**Comment by justinelliotmeyers** [comment]
@henrylyne I'd have to go back and look. This was several years ago - I just know it was a handful of small towns, probably like you mentioned. If I have time I will poke around and see if I can find dev notes/ data.

**Comment by stepps00** [comment]
Thanks for the discussion! A few comments:

> So some counties in Ulster belong to Northern Ireland and some belong to the Republic.This would seem to create problems for a simple linear hierarchy. So maybe it is easier to omit province as a region or macroregion , or else have two Ulster entries, one for each country.

Who's On First does support multiple hierarchies, so this shouldn't be an issue.. see [New York](https://spelunker.whosonfirst.org/id/85977539/) for an example. That being said, I'm not sure if the historical counties belong in / are worth importing into Who's On First.

Aside from that, I generally agree with your placetype structure. I missed that there are slight differences between COUNTY and ENGLISH names in the `Administrative_Areas_Generalized` file. I'm also using the 2015 Settlements data at the locality placetype (in addition to existing GeoNames data for rural areas); the `Townlands` dataset looks like a mix of what Who's On First would consider neighbourhoods and other placetypes so I'm not sure that's worth anything.

I'm going to suggest:

**Country**: **1** - Republic of Ireland
**Macroregion**: **0 or 4** - provinces, maybe
**Region**: **26** - should have 26 records that are made up of the distinct entries in the column titled County here,  https://data-osi.opendata.arcgis.com/datasets/55824a181fb94c8294048af90f5880a2_3/explore?showTable=true
**County**: **31** - should consist of the 31 records of the column marked English(weird name) here https://data-osi.opendata.arcgis.com/datasets/55824a181fb94c8294048af90f5880a2_3/explore?showTable=true
**Locality**: **873+** - should consist of the records found here with value SETTL_NAME here https://data-osi.opendata.arcgis.com/datasets/2de2edc7c47e4f2dbd56089b3d05ecc2_0/explore?location=53.345147%2C-8.235306%2C7.66&showTable=true One fix to make to the SETTL_NAME is that the major cities have values of "Cork city and suburbs" or "Galway city and suburbs"... in addition to GeoNames-sourced Point data for rural areas

**Comment by henrylyne** [comment]
Some tweaks to your suggestion. Ignore the provinces, have county map to the commonly known 26 counties of the Republic of Ireland. Ignore the 31 county council areas, or include as Localadmin as suggested earlier, these are not the commonly recognized counties of Ireland.

Country: 1 - Republic of Ireland
County: 26 - should have 26 records that are made up of the distinct entries in the column titled County here, https://data-osi.opendata.arcgis.com/datasets/55824a181fb94c8294048af90f5880a2_3/explore?showTable=true
Locality: 873+ - should consist of the records found here with value SETTL_NAME here https://data-osi.opendata.arcgis.com/datasets/2de2edc7c47e4f2dbd56089b3d05ecc2_0/explore?location=53.345147%2C-8.235306%2C7.66&showTable=true One fix to make to the SETTL_NAME is that the major cities have values of "Cork city and suburbs" or "Galway city and suburbs"... in addition to GeoNames-sourced Point data for rural areas

This is a much simpler and linear hierarchy. The county council areas are somewhat confusing to include, especially for Dublin county and city.

**Comment by stepps00** [comment]
Who's On First has "common" placetypes, that are maintained globally, `region` being one of them.. so we should at minimum have `country`, `region`, `county`, and `locality`. I think that would mean keeping 26 regions and 31 counties (which is close to what WOF already maintains in the country at the `region` placetype).

**Comment by henrylyne** [comment]
I'm going to be a stickler on this and insist that there are exactly 26 counties in the Republic of Ireland, any other number is wrong. If you want to include Regions, I think the 4 provinces make more sense. So it would look like

**Country: 1** Republic of Ireland
**Region: 4** - provinces https://en.wikipedia.org/wiki/Provinces_of_Ireland
**County: 26** - distinct entries in the column titled County here, https://data-osi.opendata.arcgis.com/datasets/55824a181fb94c8294048af90f5880a2_3/explore?showTable=true
**Locality: 873+**

**Comment by stepps00** [comment]
@henrylyne I agree that the 26 counties should be in Who's On First. The counties of Ireland are the first-level admin1 of the country, which maps to the Who's On First placetype of `region`. Who's On First will store the localized name for these divisions (in this case "county") in the `wof:placetype_local` property. So these features will definitely be in WOF, they'll just need to conform to WOF's placetype standard.

Since there are no official admin2 in the country, I will propose to essentially duplicate the admin1, with some exceptions to handle divisions in Dublin, Galway, and Cork. This will mean Who's On First will maintain 31 county records (26 regions + 5 subdivisions), some info on those in the [change history here](http://www.statoids.com/uie.html).

The end result should be the same, with all 26 counties in Ireland being represented in Who's On First.. we just need to ensure we're using WOF's placetypes appropriately and storing the localized names for each.

https://en.wikipedia.org/wiki/Counties_of_Ireland#List_of_counties

**Comment by henrylyne** [comment]
Great, thanks @stepps00 
I trust you know the right placetypes to use, way better than I do.

Let me know if I can help in some other way.

**Comment by stepps00** [comment]
Thanks @henrylyne.. I've opened a pull request (work in progress) to fix this issue, here: https://github.com/whosonfirst-data/whosonfirst-data-admin-ie/pull/25

I'll let you know when this is ready for merge, it would be great to get your opinion on the changes.
