### ISSUE TITLE
README.KNOWN.KNOWNS.md link in README.md is broken

### ISSUE THREAD

**Issue by blackmad** [whosonfirst-data/whosonfirst-data#1853]
in https://github.com/whosonfirst-data/whosonfirst-data/blob/master/README.md

"We've add a separate document called README.KNOWN.KNOWNS.md that lists the current state of known knowns and other gotchas you might encounter working with the Who's On First data."

README.KNOWN.KNOWNS.md goes to https://github.com/whosonfirst-data/whosonfirst-data/blob/master/README.KNOWN.KNOWNS.md which 404s

**Comment by nvkelso** [comment]
@stepps00 can you sort out where that file got migrated to? It probably went missing in the great Github repo migration of 2019...

**Comment by stepps00** [comment]
Yeah.. this file wasn't retained when the repo split into 260 per-country repos, unfortunately. I may be able to dig up a copy of that file and re-upload, but it will take some time to find.

**Comment by missinglink** [comment]
IIRC there wasn't much in that file, maybe one or two lines.

- https://github.com/whosonfirst-data/whosonfirst-data/issues/160
- https://github.com/whosonfirst-data/whosonfirst-data/pull/373

**Comment by missinglink** [comment]
```bash
ls -lah whosonfirst-data/README.KNOWN.KNOWNS.md
-rw-rw-r--  1 peter  staff   789B Jul  6  2018 whosonfirst-data/README.KNOWN.KNOWNS.md
```

```bash
cat whosonfirst-data/README.KNOWN.KNOWNS.md
# There are known knowns...

## Some records have no geometry or a centroid of 0,0

Which the exception of [Null Island](https://whosonfirst.mapzen.com/spelunker/id/1/) these are records that need to be researched and updated. We use a default centroid of `0,0` to ensure as a way of tracking records that are still in need of editorial love and so that there is at least something to keep the more conversative GeoJSON parsers out there happy.

## Some polygon records contain 'buffered point' geometry

Some records represent point data as polygon data, such as: https://whosonfirst.mapzen.com/spelunker/id/101873779, these records can be distinguished from actual geometries using the tag `qs:type="buffered point"`.

## See also

* https://en.wikipedia.org/wiki/There_are_known_knowns
```

**Comment by stepps00** [comment]
Thanks @missinglink!

I've opened https://github.com/whosonfirst-data/whosonfirst-data/pull/1854 to add the file back.
