### ISSUE TITLE
Albania Update

### ISSUE THREAD

**Issue by justinelliotmeyers** [whosonfirst-data/whosonfirst-data#1857]
https://geoportal.asig.gov.al/en/data/datasets

**Comment by stepps00** [comment]
Thanks, @justinelliotmeyers!

Current coverage in WOF: https://spelunker.whosonfirst.org/id/85632405/descendants/?exclude=nullisland

**Comment by justinelliotmeyers** [comment]
Hello,

These data can only be downloaded by Albanian Public Administration employees.
Sorry but we can't help you with this situation.

Have a nice day!
