### ISSUE TITLE
Paso Robles English name is 'El Paso de Robles'

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1858]
Looks like a data error, this certainly shouldn't be the preferred English name, should it?

https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/3a1ad36a041181ec1bbde58fda2a1e9c0f044cdb/data/859/223/13/85922313.geojson#L46-L48

**Comment by stepps00** [comment]
The full name of this locality is "El Paso de Robles", but typically just referred to as "Paso Robles". I think the current name is a combo of the actual place name + the commonly used name in parentheses.

Suggesting the following:

```
...
"name:eng_x_preferred":[
    "Paso Robles"
],
"name:eng_x_variant":[
    "El Paso de Robles (Paso Robles)",
    "El Paso de Robles",
    "El Roble"
],
...
"wof:name":"Paso Robles",
...
```

**Comment by orangejulius** [comment]
That should be perfect.

As a side note, I'm working on a blog post about names and geocoding. This will be another perfect example (like "The City and County of San Francisco") of names that are _too_ official for regular use. We still have to record them of course :)

**Comment by stepps00** [comment]
@orangejulius - As @nvkelso pointed out in https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/69, [Ventura, CA](https://spelunker.whosonfirst.org/id/85923223/) is another case.
