### ISSUE TITLE
Martinique

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1861]
Heya,

WOF has a point-based geometry [1243100949](https://spelunker.whosonfirst.org/id/1243100949/) for Martinique in the `locality` placetype and also [85671191](https://spelunker.whosonfirst.org/id/85671191/) as the `region` of Martinique.

I'm not super familiar with the area but I don't think there is actually a town/city called Martinique there?

Can we possibly deprecate/delete 1243100949?

**Comment by missinglink** [comment]
I've attempted a PR in https://github.com/whosonfirst-data/whosonfirst-data-admin-mq/pull/7 using the writefield editor.

**Comment by stepps00** [comment]
Thanks @missinglink! This slipped through the cracks, but the PR looks good.
