### ISSUE TITLE
missing wof:superseded_by

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1863]
Heya,

I noticed that [1158831797](https://spelunker.whosonfirst.org/id/1158831797/) supesedes [101751843](https://spelunker.whosonfirst.org/id/101751843/) but 1158831797 is missing the `wof:superseded_by` reference.

1158831797 correctly has `wof:supersedes` set with 101751843 in it, so something must have happened where only one side of the relationship was updated.

Not sure how common/rare this is, I'll do some digging.

**Comment by stepps00** [comment]
@missinglink - I'll go ahead and take care of this case as a one-off and link it to the issue. 

I can also craft a script to check for more cases, but let me know if you do see this occur in other records.
