### ISSUE TITLE
"Southern Tip" neighbourhood on Liberty Island

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1867]
When debugging a recent [Pelias issue](https://github.com/pelias/api/pull/1438#issuecomment-636086478) I came across the neighbourhood [Southern Tip](https://spelunker.whosonfirst.org/id/85869681/):

![Screenshot_2020-07-14_10-10-57](https://user-images.githubusercontent.com/111716/87455456-56425c80-c5ba-11ea-862b-48c491344eac.png)

I don't think this is a real neighbourhood. It comes from Zetashapes, so perhaps @blackmad can chime in as well.

If it's not a real place, should we remove it? Looks like it _is_ already marked `mz:is_funky`, so perhaps Pelias should not import it for that reason alone (@missinglink what do you think?).

**Comment by nvkelso** [comment]
Tilezen skips is_funky neighbourhood records for display on tiles. I can see you not including them in PIP hierarchy generation, but still including them in search result lists? When we know a place is wrong we deprecate it, but when it seems odd but we can't verify one way or another in time allotted then it's marked thus.

**Comment by stepps00** [comment]
Here's the Liberty Island neighbourhood that represents this area: https://spelunker.whosonfirst.org/id/907131683/

I'm fine with keeping the "Southern Tip" neighbourhood as-is since it's been flagged as funky, but it could use a new label centroid.

**Comment by orangejulius** [comment]
Great. I swear we've had the `is_funky` discussion within Pelias many times, but I just opened https://github.com/pelias/whosonfirst/issues/513 to resolve it in a recorded discussion. So  we're fine if there are no changes to this record in WOF.
