### ISSUE TITLE
Add West SOMA

### ISSUE THREAD

**Issue by louh** [whosonfirst-data/whosonfirst-data#187]
The node in OSM: http://www.openstreetmap.org/node/2297131599
Related, the planning area as defined by the City of SF: http://www.sf-planning.org/index.aspx?page=3545

**Comment by thisisaaronland** [comment]
The exclusion of those two rows of buildings between 4th/5th and Folsom/Harrison is a nice touch...

**Comment by thisisaaronland** [comment]
Is there a pre-existing shapefile for this somewhere (like on the sf.gov site) ?

**Comment by louh** [comment]
I couldn't find anything that's not in a PDF :-/

**Comment by nvkelso** [comment]
How is this different than regular SoMa?
https://whosonfirst.mapzen.com/spelunker/id/85865939/

**Comment by nvkelso** [comment]
Looks like Eastern SoMa is a thing... but these seem like two microhoods of a general SoMa? Both of these feel like a planning region, not necessarily a full on neighbourhood, though?

**Comment by nvkelso** [comment]
Proposal: SoMa the neighbourhood contains:

* East SoMa
* West SoMa
* Financial District South
* Rincon Hill
* Showplace Square

But excluding:

* Mission
* Potrero Hill
* Mission Bay
* Central Waterfront

**Comment by thisisaaronland** [comment]
Showplace Square? That is simultaneously depressing and apt. I wonder how all the College of Arts students feel about that name...

**Comment by thisisaaronland** [comment]
Assigning to @dphiffer which means that it won't happen until he's a little further along the learning curve but this will be a good "wax on, wax off" exercise.

**Comment by stepps00** [comment]
All microhood / neighbourhood / macrhood work for San Francisco was done in Issue https://github.com/whosonfirst-data/whosonfirst-data/issues/316.

Once the geojson files from that issue are imported, the microhood / neighbourhood / macrohood features in San Francisco should be up-to-date.

**Comment by nvkelso** [comment]
@stepps00 Does the work in #316 fix this West Soma issue? If it does, let's close this issue now (considering this a forward dup of #316).

**Comment by stepps00** [comment]
@nvkelso A record for "West SOMA" record was not included in the import GeoJSON files... 

If its easiest, I can update the SF files so they contain the following microhoods within the "South of Market" neighbourhood record:

* East SoMa
* West SoMa
* Financial District South
* Rincon Hill
* Showplace Square

Probably easiest to close this issue and condense all SF hood work into #316.

**Comment by nvkelso** [comment]
Yes, please.

**Comment by stepps00** [comment]
Closing. 

All of the work outlined in this issue will be taken care of in #316 - see that issue for updates.
