### ISSUE TITLE
Duplicate US Localities

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1875]
We're running some new types of bulk address tests, and in the process are sometimes coming across some duplicate records.

Here's some, identified manually. I hope we can come up with a way to automate finding a bunch more.

| City name | Proposed kept record | Proposed deleted record |
| --- | --- | --- |
| Litchfield Park, AZ | https://spelunker.whosonfirst.org/id/85917495/ | https://spelunker.whosonfirst.org/id/1209230747/ |
| Gary, IN | https://spelunker.whosonfirst.org/id/85941813/ | https://spelunker.whosonfirst.org/id/1243083701/ |

**Comment by nvkelso** [comment]
Nice! Agree those are dups, keep in coming :)
