### ISSUE TITLE
Update the Greek names in the Athens locality record

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1877]
https://spelunker.whosonfirst.org/id/1175612731/

WOF stores the following Greek names in the Athens locality record:

```
    "name:ell_x_preferred":[
        "Ath\u00ednai"
    ],
    "name:ell_x_variant":[
        "Αθήναι",
        "Αθηναι",
        "Αθήνα",
        "Αθηνα"
    ],
```

The preferred name is actually a transliterated form of the English "Athens" name, so we should update the variant and preferred names. I'd suggest:

```
    "name:ell_x_preferred":[
        "Αθήνα"
    ],
    "name:ell_x_variant":[
        "Αθήναι",
        "Αθηναι",
        "Αθηνα",
        "Ath\u00ednai"
    ],
```

Though we do have the ability to [store "script" and "region" variants](https://github.com/whosonfirst/whosonfirst-names#rfc-5646-bcp-47-comformance), so maybe something like:

```
    "name:ell_x_preferred":[
        "Αθήνα"
    ],
    "name:ell_x_variant":[
        "Αθήναι",
        "Αθηναι",
        "Αθηνα"
    ],
    "name:ell_en_x_variant":[
        "Ath\u00ednai"
    ],
```

**Comment by nvkelso** [comment]
Second example works for me.
