### ISSUE TITLE
New Zealand Localities

### ISSUE THREAD

**Issue by justinelliotmeyers** [whosonfirst-data/whosonfirst-data#1878]
https://github.com/justinelliotmeyers/NEW_ZEALAND_FIRE_SERVICE_SHAPEFILE_DATA

@nvkelso enjoy! This took me years to get...

**Comment by nvkelso** [comment]
Nice! 

@missinglink does this jive with your local knowledge?

**Comment by justinelliotmeyers** [comment]
@nvkelso I have three contacts there. All confirm names, neighborhood data, and official Maori names that have been updated. This data is the cream of the crop. Like I said, took me years to get it.

**Comment by nvkelso** [comment]
The ZIP archive has file inside it that also have `.zip` extensions and looks like split into segments that are ~10 MB each. @justinelliotmeyers what software did you use / suggest using to extract the contents? Normally macOS operates on ZIPs fine but it's barfing on these.

![image](https://user-images.githubusercontent.com/853051/89813816-160dc580-daf7-11ea-8e65-03f9faf3f099.png)

**Comment by justinelliotmeyers** [comment]
https://data.linz.govt.nz/layer/104830-fire-and-emergency-nz-localities/

**Comment by nvkelso** [comment]
Looks great, jives with my trip there.

Two notes:

- Neighbourhoods / macrohoods / boroughs in the big cities would need to be dissembled.
- Water areas are included (like around Picton) where the Arm is a super locality with different reaches and bays as localities. Not wrong, but also not standard.

Some screenshots:

![image](https://user-images.githubusercontent.com/853051/89815451-aea54500-daf9-11ea-97d9-9db5863f4596.png)

![image](https://user-images.githubusercontent.com/853051/89815469-b5cc5300-daf9-11ea-8677-f968163e1fb0.png)

![image](https://user-images.githubusercontent.com/853051/89815457-b238cc00-daf9-11ea-933c-03ba6a439880.png)

![image](https://user-images.githubusercontent.com/853051/89815485-b9f87080-daf9-11ea-8486-5bf248034ae2.png)

**Comment by stepps00** [comment]
Thanks @justinelliotmeyers, this data looks great.. and has a `CC BY 4.0` license:

```
Licensing
The Fire and Emergency NZ Localities dataset is available under a Creative Commons Attribution 4.0 International licence (CC BY 4.0). However, an additional request has been made to users of this dataset.

Important: This dataset is used by Fire and Emergency New Zealand in the delivery of emergency services and helps in confirming where to send emergency services. As such, the factual accuracy of this data is very important.

Fire and Emergency New Zealand therefore requests that you do not:

- alter the data in any way that changes its factual accuracy. For example, do not change suburb boundaries and/or naming conventions; and

- knowingly make any misrepresentations or misstatements about the data or Fire and Emergency New Zealand; and

- knowingly do anything that adversely reflects on the data, or the reputation of Fire and Emergency New Zealand.
```

**Comment by justinelliotmeyers** [comment]
Kia ora 🇳🇿

**Comment by missinglink** [comment]
Yeah this is great, looks tip top to me 🥝 

I haven't found an Open data source as good as this which covers, the Hauraki Gulf, for instance.

<img width="901" alt="Screenshot 2020-08-17 at 12 30 23" src="https://user-images.githubusercontent.com/738069/90387148-f261f680-e085-11ea-9f2c-3968ee3ecc88.png">

A huge improvement over what we currently have: 
https://spelunker.whosonfirst.org/id/101916761/

I didn't get a chance to do a check for dual named places:
https://en.wikipedia.org/wiki/List_of_dual_place_names_in_New_Zealand

There is a trend in NZ towards moving away from Colonial names and spelling back to traditional Māori place names.
Because of that you'll find that some places have two official names, for instance "Aoraki / Mount Cook" which is fairly straight forward for WOF as they are mi/en, but in other places there's alternate spellings of places such as 'Whanganui' vs 'Wanganui' where the govt has tried in recent years to correct the spelling. 

see: https://www.youtube.com/watch?v=E8DAqCScpyE

**Comment by justinelliotmeyers** [comment]
@stepps00 awesome!! still working on the Chile license - will update asap - trying to keep you busy ;) lmk if you need anything else!

**Comment by stepps00** [comment]
Agree with @nvkelso that there is some work to do around the `neighbourhood`/ `borough` placetypes and making sure we ditch some `type` values before import.

I need to investigate a bit more before crafting a PR, but my approach would be to:

- Ditch any feature with a `type` of "COASTAL BAY", "INLAND BAY", "LAKE", or "PARK_RESERVE" 
- Dissolve remaining features on the `city_name` attribute. Match these dissolved features to existing WOF localities and update the locality placetype.
- In original file, find neighboring features with the same `city_name` attribute. These _should_ be neighbourhoods. Use them to update the neighbourhood placetype.
- Investigate `borough` records, splitting names, and importing the water features as WOF records with `mz:is_landuse_aoi` property of "1".

This should mostly work, though the "ISLAND" `type` features would need to be double-checked. With @missinglink 's Waiheke Island example, all features on Waiheke Island have a `city_name` of "Waiheke Island", but six have a "SUBURB" `type` and one has an "ISLAND" `type`. Shouldn't be an issue, just something that should be called out and verified before starting to update WOF records.

**Comment by nvkelso** [comment]
Some of the "bays" we could mark as neighbourhoods with `mz:landuse_aoi` = 1 so we have them but they don't get a map label?

**Comment by stepps00** [comment]
Tracking the import of this data here: https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/12.
