### ISSUE TITLE
Hungary

### ISSUE THREAD

**Issue by justinelliotmeyers** [whosonfirst-data/whosonfirst-data#1885]
http://inspire.fomi.hu/inspire/atom/data/AdministrativeUnits_hu_v1.1.zip

**Comment by stepps00** [comment]
Thanks @justinelliotmeyers!

Since we are already tracking Hungary updates in [a separate issue](https://github.com/whosonfirst-data/whosonfirst-data/issues/28), I'm going to close this out.. but I've added a comment to that issue with this source.
