### ISSUE TITLE
"Schönefeld To Become Part Of New Berlin Airport"

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1886]
https://simpleflying.com/scho%cc%88nefeld-to-become-part-of-new-berlin-airport/

**Comment by missinglink** [comment]
I believe Tegel will close around the same time, it was scheduled to close this year and then it wasn't, now with Covid maybe it is again, who can keep up 🤷‍♂️

**Comment by missinglink** [comment]
The new airport is named "Brandenburg Airport" and I believe it will replace Tegel and absorb Schönefeld (which is adjacent).

**Comment by thisisaaronland** [comment]
This is what we've got now:

* https://spelunker.whosonfirst.org/id/102549025/ (Berlin-Schonefeld International Airport)
* https://spelunker.whosonfirst.org/id/1360695651/ (Berlin Brandenburg Willy Brandt Airport)
* https://spelunker.whosonfirst.org/id/102548985/ (Berlin Tegel Airport)

**Comment by missinglink** [comment]
Oh interesting, I haven't heard to it referred to as Willy Brandt until now.

**Comment by thisisaaronland** [comment]
* 102548985 (TXL) : moved from `-admin-xy` to `-admin-de`; updated cessation date and `iso/wof:country; flag as `mz:is_current=0`
* 102549025/ (SXF) : moved from `-admin-xy` to `-admin-de`; updated cessation date and `iso/wof:country`; flag as `mz:is_current=0`
* 1360695651 (BER) : updated inception date; flag as `mz:is_current=1`
