### ISSUE TITLE
Incorrect region in the hierarchy on Kennett, MO

### ISSUE THREAD

**Issue by thismakessand** [whosonfirst-data/whosonfirst-data#1889]
The region in the hierarchy on all three of these records is Arkansas but it should be Missouri (the shapes and attributes appear correct otherwise):

Kennett, MO: https://spelunker.whosonfirst.org/id/85971121/
Dunklin County: https://spelunker.whosonfirst.org/id/102086175/
Independence Twp: https://spelunker.whosonfirst.org/id/404515999/

**Comment by thismakessand** [comment]
If the fix is just to update the region_id in the hierarchy on the three records and parent_id as well on the county record, then let me know and I'm happy to put in a PR.

**Comment by nvkelso** [comment]
@stepps00 can you look into why the hierarch is wrong? Does the PIP revGeo point need to be fixed?

**Comment by stepps00** [comment]
Ah, interesting. This all stems from the [Dunklin County](https://spelunker.whosonfirst.org/id/102086175/), Missouri record. The centroid of that record falls _just_ outside it's geometry, giving it a hierarchy that (incorrectly) includes Arkansas.

Thanks for the issue, @thismakessand - we'll file a PR to fix shortly. Can I ask what project/work led you to finding this issue?

**Comment by thismakessand** [comment]
@stepps00  thanks!  I came across it while using the WOF admin polygons (via pelias pip-service) as a sanity check on some POI data I have (to verify my points are where they say they are).

**Comment by thekuiperbelt** [comment]
Hopefully Malden MO will also be resolved with this fix. Thanks all!
https://spelunker.whosonfirst.org/id/85971119/

**Comment by stepps00** [comment]
Thanks @thekuiperbelt - the Malden, MO record also has the Dunklin County record in its hierarchy, so this record would be fixed as part of this work, too.
