### ISSUE TITLE
Update Hochzeitsfeier record

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1894]
Via https://github.com/whosonfirst-data/whosonfirst-data-admin-de/issues/27 / @RealDolos

https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/420/784/285/420784285.geojson

Berlin-Wedding lists:

    "name:deu_x_preferred":[
        "Hochzeitsfeier"
    ],
    "name:deu_x_variant":[
        "Wedding",
        "Berlin-Wedding"
    ],
name:deu_x_preferred is what you get when you put Wedding into google translate. It is wrong. The German for Berlin "Wedding" is "Wedding", i.e. it already is the German name and does not need a translation, it's not about people getting married at all (it was named after Rudolf de Weddinge according to wikipedia).

it looks like most/all the other _x_preferreds are wrongly translated as well.
E.g.

    "name:cym_x_preferred":[
        "Seremoni briodas"
    ],
No, Wedding is not a "bridal ceremony" 😉 .

I have no idea how exactly this is curated or where the problematic translation comes from, thus I am not making a PR, just reporting this as an issue.

I'd guess other places would be affected by such mistaken translations as well...

**Comment by missinglink** [comment]
Possibly related: https://github.com/whosonfirst-data/whosonfirst-data/issues/799#issuecomment-304257029

**Comment by nvkelso** [comment]
Oh wow.
