### ISSUE TITLE
Switzerland - Coastal municipalities have lakes as parent localadmin

### ISSUE THREAD

**Issue by SilvrDuck** [whosonfirst-data/whosonfirst-data#1897]
Hey,
While setting up a [pelias](https://github.com/pelias/pelias) instance for Switzerland, I noticed something peculiar. When looking up addresses close to _Lake Geneva_ (locally called _Lac Léman_), they would come with the `localadmin` of the lake rather than the municipality I’d expect. Digging deeper, the issue seemed to come from the _whosonfirst_ hierarchy.

# Concrete example

Take the address `Rue de la Gare, Morges`. Pelias returns the correct coordinate (`6.49633/46.508176`). Using _pelias’ point in polygon_ service we get the following hierarchy:
```
continent : Europe
country : Switzerland
county : Vaud (unincorporated)
localadmin : Lac Léman
locality : Morges
region : Vaud
```
The correct `localadmin` should be `Morges`, and not Lac Léman.

The Morges locality clearly extends in the lake ([Morges, locality 101853887](https://spelunker.whosonfirst.org/id/101853887/)):
![Screenshot 2020-10-07 at 15 57 01](https://user-images.githubusercontent.com/11034210/95340699-c1e44f00-08b5-11eb-8338-6facf265358f.png)

And thus we get this ([Lac Léman, localadmin 404567693](https://spelunker.whosonfirst.org/id/404567693/)):
![Screenshot 2020-10-07 at 15 59 16](https://user-images.githubusercontent.com/11034210/95340969-138cd980-08b6-11eb-80a4-26871701d8f2.png)
(notice that this is only the part of the lake that is in the Vaud county)

But this is what I would have expected ([Morges, localadmin 404571775](https://spelunker.whosonfirst.org/id/404571775/)):
![Screenshot 2020-10-07 at 16 04 39](https://user-images.githubusercontent.com/11034210/95341770-ebea4100-08b6-11eb-9c3f-65a57487c9c3.png)

# A more general problem

Using some swiss addresses dataset, I found the same issue in at least 200 other municipalities around the following lakes:
- Lac Léman
- Lac de Neuchâtel
- Lac de Morat
- Bodensee
- Zürichsee
- Herzogenbuchsee
- Bielersee

# Solution ?

I’m not sure if the issue is on _whosonfirst’s_ or _pelias’_ side, but the fact that [the Morges locality](https://spelunker.whosonfirst.org/id/101853887/) displays _Lac Léman_ in its hierarchy in the spelunker makes me think that here is the correct place.

Thanks, have a lovely day.

**Comment by zifeo** [comment]
Hey @stepps00, we are continuing the usage of WOF and just faced that issue. Does that sound something we could contribute/help? Is there a quick fix possible in the usage?

**Comment by stepps00** [comment]
Thanks for the issue @SilvrDuck 

There are a couple things to track here:
1. Some localities have "lake" features as their parent_id values and in their hierarchies
2. These "lake" features need to be QA'd to ensure the appropriate `mz` property flags are set appropriately

> Does that sound something we could contribute/help? Is there a quick fix possible in the usage?

For the first item, if you were able to provide a file that has the `wof:id` value of any affected locality record, as well as a point location (provided as latitude / longitude) that falls within the correct parent feature over land, that would be great.

And for the second item, we could QA these quickly if you were able to provide a list of `wof:id` values for any "lake" feature.

Would that work?

**Comment by SilvrDuck** [comment]
Thanks for your prompt answer @stepps00!

I’ve already done part of the work of identifying those. I will run a few more experiment to make sure the list is correct and comprehensive. I’ll get back to you when it is done.

**Comment by SilvrDuck** [comment]
Hey @stepps00 

Here’s a csv of the `localities` that have a `localadmin parent` beeing a lake. Note that the lat/lon is the `lbl` field on whosonfirst. I visually checked them to see if they fell into the correct parent `localadmin`. It was the case for all **except Paudex which was on a lake**. This might be something else to correct. Below I replaced Paudex’s position with the corresponding `localadmin's` instead.
```
name,source_id,lat,lon
Erlach,1125851677,47.04297,7.0996
Horn,1125778753,47.49279,9.4609
Altenrhein,1125823529,47.49037,9.55216
Rorschach,101854277,47.479397,9.491976
Rorschacherberg,1126036705,47.47313,9.51116
Goldach,101854275,47.474243,9.468308
Steinach,1125952657,47.49431,9.4352
Staad,1126028013,47.48055,9.53253
Arbon,101854457,47.512702,9.433829
Güttingen,1126026583,47.60386,9.28691
Frasnacht,1293725371,47.52983,9.40583
Romanshorn,101854459,47.565097,9.379257
Berlingen,1125851865,47.67388,9.01969
Landschlacht,1125958781,47.62759,9.24545
Kesswil,1125909341,47.59336,9.31809
Mannenbach-Salenstein,1126009031,47.67267,9.05351
Uttwil,1125804023,47.5836,9.3424
Münsterlingen,1125820851,47.63089,9.23495
Rivaz,1125823935,46.47629,6.77878
St-Sulpice,1125851639,46.51047,6.55897
Allaman,1125922513,46.47008,6.3964
Cully,1125801883,46.48892,6.72945
Morges,101853887,46.510864,6.499978
Paudex,1394290727,46.508266,6.673546
La Tour-de-Peilz,101828593,46.453923,6.86267
Corseaux,1125787557,46.467833,6.832333
Bursinel,1125859623,46.43957,6.30581
Vevey,101828591,46.46411,6.841284
Salavaux,1125887685,46.91968,7.02324
Cortaillod,101875973,46.94711,6.846093
Bevaix,101854001,46.929219,6.811281
Marin-Epagnier,1225875245,47.01017,6.99941
Neuchâtel,101853995,46.998431,6.939407
Chez-le-Bart,1125911851,46.89914,6.78296
Auvernier,1125889093,46.97545,6.87903
Vaumarcus,1125915653,46.87601,6.74683
Areuse,1293236643,46.95346,6.85382
Cheseaux-Noréaz,1126047043,46.785761,6.665954
Chabrey,1125962171,46.92694,6.98164
Cudrefin,1125873599,46.95577,7.01855
Chevroux,1125911829,46.88835,6.90692
Concise,1125930161,46.85027,6.71968
Richterswil,101876053,47.209098,8.707041
Uerikon,1125918247,47.23672,8.7573
Feldbach,1125908497,47.23964,8.78472
```

Regarding the problematic `localadmins`, here is the list I could gather:
```
source_id,name
404573493,Bielersee
404568157,Bielersee
1394254039,Bodensee
404568897,Bodensee
404568359,Brienzersee
1394254187,Greifensee
404567693,Lac Léman
404570447,Lac de Morat
404567833,Lac de Neuchâtel
404568131,Lac de Neuchâtel
1394254151,Lac de Neuchâtel
1394254121,Lac de Joux
404568093,Thunersee
1394253973,Zürichsee
```

**What would be the next steps now?**

_A note on the methodology:
I gathered the most comprehensive list of swiss lakes I could (138 names, multilingual, mostly from wikipedia). I then checked whosonfirst for `localadmins` matching the names (in a fuzzy way). I then checked which `localities` had any of those as parents. As the number is low, I could manually curate the final result to remove some unnecessary outputs._

Best

**Comment by stepps00** [comment]
Nice, thank you! I'll take a look at these records soon and propose a PR with updates.

I'll flag both of you when that PR is ready for review.

**Comment by missinglink** [comment]
@SilvrDuck you may find this UI helpful
https://spatial.demo.geocode.earth/explore/pip#11/46.954605/7.394937

You can pan the map around to view WOF polygon coverage (desktop only).

**Comment by zifeo** [comment]
@stepps00 @missinglink Great thanks, is this fix something we could contribute ourself?

**Comment by SilvrDuck** [comment]
@stepps00 great, thanks. I’ll be waiting for the PR 👍 

@missinglink thanks as well, I’ll take a look.

**Comment by missinglink** [comment]
FWIW this issue exists in OSM too and you can see the borders on the basemap:
- https://www.openstreetmap.org/relation/1702421#map=9/46.5884/6.6565
- https://www.openstreetmap.org/relation/1685017

<img width="471" alt="Screenshot 2020-10-09 at 16 43 09" src="https://user-images.githubusercontent.com/738069/95597111-8630bd00-0a4e-11eb-9e2e-e4ebf6f2c873.png">

**Comment by nvkelso** [comment]
Sometimes we have separate geoms for display and reverse geocoding. Technically the water portion is correct, but can be confusing to some end-users.

**Comment by SilvrDuck** [comment]
> Sometimes we have separate geoms for display and reverse geocoding. Technically the water portion is correct, but can be confusing to some end-users.

Sure, the water portion is correct. The issue was that when reverse geocoding an address on land, the water portion was considered to be the municipality instead of the land one.

**Comment by zifeo** [comment]
I think there is a bit of confusion, do we precisely know what is the issue? Currently querying a lat/lng can return a lake as a localadmin, instead of the correct one. Is that only relate to the correctness `mz` flag or could something else be in the middle (where we can also help to fix)?

**Comment by stepps00** [comment]
> do we precisely know what is the issue?

Two issues here:
- Some localities have "lake" features as their parent_id values and in their hierarchies
- These "lake" features need to be QA'd to ensure the appropriate mz property flags are set appropriately

To fix, I'm going to use the list of records you sent over to hand-curate new centroids for some records that will be used during the hierarchy building process. These new centroids should fix hierarchy issues in records that incorrectly have lake records in their hierarchies. This should, in turn, fix the issues you're seeing when querying lat/lngs.

This involves spinning up a point-in-polygon service (some info about that [here](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/setting_up_pip_service.md)). I'm hoping to get to this issue soon, so once I've given this a shot, I'll link a PR to this issue so we can discuss.

**Comment by zifeo** [comment]
@stepps00 if you require an updated list (no sure if more records could go wrong), feel free to ask.

**Comment by nvkelso** [comment]
This is scheduled for December.

**Comment by stepps00** [comment]
Thanks for the patience on this issue, everyone. I'm starting admin updates in the above linked PR to fix this issue, I hope to have this complete in the coming days.

**Comment by stepps00** [comment]
@SilvrDuck @zifeo the PR to fix this issue was merged today. Please let us know if you're still experiencing any issues with these records in Switzerland.

**Comment by zifeo** [comment]
@stepps00 Awesome! We will check starting on Monday so the dataset has be the time to be refreshed.

**Comment by SilvrDuck** [comment]
Hey @stepps00, 

Through more investigation, I found the following `localities` that have the same issue of having a lake as a `localadmin`.

```
source_id,name,lat,lon
101748449,Lausanne,46.520381,6.63141
101767399,St-Prex,46.475663,6.447215
101853861,Montreux,46.43423,6.911558
101853877,Lutry,46.503453,6.686783
101853885,Rolle,46.458885,6.338641
101854463,Egnach,47.544059,9.382679
1125773569,Chardonne,46.47676,6.8268
1125807373,Mammern,47.64625,8.91519
1125823961,Clarens,46.44055,6.89233
1125834091,Coppet,46.31682,6.19114
1125883875,Préverenges,46.51854,6.52682
1125887713,Territet,46.42863,6.92122
1125937761,Tolochenaz,46.50504,6.47279
1125944999,Perroy,46.46821,6.36622
1125990725,Buchillon,46.46705,6.41128
1126014611,St-Saphorin,46.47329,6.79601
1193046703,Prangins,46.39518,6.2496
1226579363,Engelberg,47.10387,7.17877
1259814947,Dully,46.43143,6.29461
1327462329,Villette,46.49575,6.70901
1394292823,Crans-près-Céligny,46.36056,6.21453
1394298067,Pully,46.510121,6.659839
```

Do you want me to open a new issue at [whosonfirst-data/whosonfirst-data-admin-ch](https://github.com/whosonfirst-data/whosonfirst-data-admin-ch)?

**While investigating that, I also found another interesting issue:**

Some localities have their `fra_x_preferred` translations wrong. It looks that it was automatically translated because the names looked like English words. For example, the village of “Egg” (in german) was translated in french to “Œuf“, which means egg, as related to a chicken. This is obviously wrong. I found these:

```
id,actual_name,wrongly_translated
404328441,Rain,Pluie
404328467,Root,Racine
404568785,Bullet,Balle
404568957,Egg,Œuf
404569029,Lens,Lentille optique
404570185,Gland,Glande
404570789,Arch,Arc
```
It looks that many languages are affected, but French is more critical here as it is a national language.

**Where would be the correct place to fix that? Should I also open an issue on data-admin-ch?**

**Comment by stepps00** [comment]
Hey @SilvrDuck - thanks for the info. I'll use your comment to spin off into a new issue.. let's chat about the problem in that new issue.
