### ISSUE TITLE
Wrong translations for some localities in Bucharest / Ilfov, Romania

### ISSUE THREAD

**Issue by mihaicosareanu-bolt** [whosonfirst-data/whosonfirst-data#1902]
Creating this issue to have support for a PR. The description came from a bigger issue: https://github.com/whosonfirst-data/whosonfirst-data/issues/1899

Copying and pasting the relevant part:

Translations are off for some places. Example: https://spelunker.whosonfirst.org/id/101753931/ . "Parcu Voluntarilor" does not exist and shouldn't be a translation, especially for english

**Comment by mihaicosareanu-bolt** [comment]
PR is ready here: https://github.com/whosonfirst-data/whosonfirst-data-admin-ro/pull/18/files

**Comment by stepps00** [comment]
Hi @mihaicosareanu-bolt - this work was taken care of via https://github.com/whosonfirst-data/whosonfirst-data-admin-ro/pull/19, so I'll close this issue out. Please let us know if you notice additional issues in Romania.
