### ISSUE TITLE
Move Finland to the admin-fi repo

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1908]
https://spelunker.whosonfirst.org/id/136253047/

Currently lives in the `whosonfirst-data-admin-xy` repo, here: https://github.com/whosonfirst-data/whosonfirst-data-admin-xy/blob/master/data/136/253/047/136253047.geojson

This country record for Finland should live in the `whosonfirst-data-admin-fi` repo.

**Comment by nvkelso** [comment]
This is for the `empire`? Are the other `empire` records in their respective country code repos?

**Comment by stepps00** [comment]
Ah, I'm going to close this. I glossed over the placetype and assumed this was the `country` record. The `empire` records should live in the `admin-xy` repo, so we're good here.
