### ISSUE TITLE
Update locality data in Saudi Arabia

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1909]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1111

WOF maintains ~2600 [locality records](https://spelunker.whosonfirst.org/id/85632253/descendants/?exclude=nullisland&placetype=locality) in Saudi Arabia, the vast majority contain Point geometries and come from GeoNames.

An example: https://spelunker.whosonfirst.org/id/1310124023/

Opening this issue to investigate a new, openly-licensed source of locality data in Saudi Arabia.

**Comment by justinelliotmeyers** [comment]
whats the source amigo!? @stepps00 gracias!

**Comment by stepps00** [comment]
@justinelliotmeyers unfortunately no source yet, I'm opening this as a place-holder for when data becomes available. But feel free to share any tips if you come across any locality data in Saudi Arabia! 😉

**Comment by stepps00** [comment]
This I've opened https://github.com/whosonfirst-data/whosonfirst-data-admin-sa/pull/19 to tackle this issue.. the PR won't touch all locality records in Saudi Arabia, but I think that's okay; the work will leave a good deal of locality points as is, but will improve locality coverage in the country, add missing neighbourhood records, and ensure that all populous localities have an accurate, hand-curated polygon.

This work will also add localizations (mostly Arabic) to updated records.
