### ISSUE TITLE
Update admin records in Iraq

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1910]
Iraq: https://spelunker.whosonfirst.org/id/85632191/

Descendant region records: https://spelunker.whosonfirst.org/id/85632191/descendants/?exclude=nullisland&placetype=region
Descendant county records: https://spelunker.whosonfirst.org/id/85632191/descendants/?exclude=nullisland&placetype=county
Descendant locality records: https://spelunker.whosonfirst.org/id/85632191/descendants/?exclude=nullisland&placetype=locality
Descendant neighbourhood records: https://spelunker.whosonfirst.org/id/85632191/descendants/?exclude=nullisland&placetype=neighbourhood

Opening this issue to track updates to/review of:

- Region, county, "large" locality geometries
- Neighbourhood updates in Mosul, Baghdad, and other major localities
- Label and name translations
- Label centroids/min_zoom values
- Name updates (QAing GeoNames names, if possible)

As of today, I'm not aware of an openly licensed dataset for these updates, but I will add one if found.

**Comment by nvkelso** [comment]
With all the American "intervention" in Iraq the last couple decades there _must_ be some open geo data out there...

**Comment by justinelliotmeyers** [comment]
@nvkelso FOIA the NGA! The NGA actually shared out tons of Iraq data like 8 years ago - I have it on an external - every road, city, admin, etc
