### ISSUE TITLE
GB postalcode sync November 2020

### ISSUE THREAD

**Issue by tomtaylor** [whosonfirst-data/whosonfirst-data#1915]
@stepps00 @thisisaaronland @vicchi 

I've synced https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb against the [November 2020 ONS Postcode Directory](https://geoportal.statistics.gov.uk/datasets/ons-postcode-directory-november-2020). The update is on a branch on my fork: https://github.com/tomtaylor/whosonfirst-data-postalcode-gb/tree/sync-nov-2020.

This repo is a real beast to handle now. It seems to be too big to generate a PR for. I kept running out of memory running `git add` on a 16GB machine so ended up using a 64GB VM.

7633 features created, 2630739 files updated.

Some postcode centroids have moved, very slightly, as the boundary has changed. I've re-piped all the records to make sure they're up to date.

**Comment by thisisaaronland** [comment]
@tomtaylor Can we interest you in writing a blog post about the UK postcodes work?

**Comment by tomtaylor** [comment]
@thisisaaronland as per our Slack chat, it's on the list! :D

**Comment by stepps00** [comment]
Thanks @tomtaylor. We had some back-and-forth in your previous PRs (like the one [here](https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/4) from last February). Was the same logic used to update the postalcode records using the Nov 2020 ONS directory?

If so, we should be able to QA a bit, then push your fork to our master branch.

**Comment by tomtaylor** [comment]
@stepps00 that's right - I used https://github.com/whosonfirst/wof-sync-os-postcodes as before.

**Comment by stepps00** [comment]
@tomtaylor - my apologies, this slipped through the cracks.

I QA'd the changes and the updates look great.. I'll work on merging your fork ASAP.

**Comment by tomtaylor** [comment]
@stepps00 thanks! (sorry for the slow reply!)

**Comment by missinglink** [comment]
I believe `SW18 1AG` is a newer postcode which might serve well as a test case.
