### ISSUE TITLE
Update neighbourhood records around Yongin, South Korea

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1916]
QAing some of our neighbourhood data in South Korea, I noticed two records that need to be updated:

This neighbourhood is likely bogus and should be deprecated: https://spelunker.whosonfirst.org/id/890475109/
This neighbourhood should be updated with a new geometry: https://spelunker.whosonfirst.org/id/85925883/

**Comment by justinelliotmeyers** [comment]
@stepps00 @nvkelso South Korea is just like China. Changes occur monthly - and there are two systems of administrative boundaries. (HJD (행정동 ) and BJD (법정동))

this somewhat keeps track of them, but not always 100% current or correct: https://github.com/vuski/admdongkor
