### ISSUE TITLE
Various NZ locality fixes

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1920]
heya,

I'd like to deprecate/remove "Lower Hutt" https://spelunker.whosonfirst.org/id/101914319/

I think the correct record here is https://spelunker.whosonfirst.org/id/102079337/ which is at the `county` level rather than the `locality` level.

The [wikipedia](https://en.wikipedia.org/wiki/Lower_Hutt) entry defines `Lower Hutt` as a City (ie. `county` in WOF) containing a bunch of Suburbs (ie. `locality` in WOF).

**Comment by missinglink** [comment]
Semi related (same repo at least) is https://spelunker.whosonfirst.org/id/101918677/ which is an incorrect spelling of https://spelunker.whosonfirst.org/id/101914287/ and can also be deprecated/removed.

**Comment by missinglink** [comment]
One more from NZ, this locality which seems to be two places combined into one:
https://spelunker.whosonfirst.org/id/101915063/

**Comment by missinglink** [comment]
Also https://spelunker.whosonfirst.org/id/101916599/ can be superseded by https://spelunker.whosonfirst.org/id/101915581/, the latter of the two being sourced from the recent LINZ locality import and better represents the peninsula.

**Comment by missinglink** [comment]
I found these errors after investigating which `locality` records in NZ are not `src:geom=nz-linz`:

```
101914319|locality|whosonfirst
101915063|locality|quattroshapes
101915887|locality|quattroshapes
101916599|locality|quattroshapes
101918677|locality|quattroshapes
```

**Comment by missinglink** [comment]
The last one on the list [Leithfield Beach](https://spelunker.whosonfirst.org/id/101915887/) is very similar to [Amberley Beach](https://spelunker.whosonfirst.org/id/101916487/) farther north, except "Leithfield Beach" is still "mz:is_current" whereas Amberley Beach isn't.

Was that possibly missed in this commit?
https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/commit/ca5aa9f0ccebb26640bae02bd324703059b740fb#diff-820b00e6b6193fb39fb2b96954cc7b64df1a3d50a61dd25d5ff5db6f30bc31a9

**Comment by stepps00** [comment]
Hmm.. thanks for these comments @missinglink 

It's possible that a handful of records were missed during the working in https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/12. I'll pull out all locality records in NZ to figure out what issues are present and reply here.

If you see additional issues in NZ, feel free to append them to this issue.

**Comment by stepps00** [comment]
So, I've exported all "current" admin records in the `whosonfirst-data-admin-nz` repo for review and can confirm that each of these five records need to be corrected:

- https://spelunker.whosonfirst.org/id/101914319
- https://spelunker.whosonfirst.org/id/101915063
- https://spelunker.whosonfirst.org/id/101915887
- https://spelunker.whosonfirst.org/id/101916599
- https://spelunker.whosonfirst.org/id/101918677

Through https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/12, the last four records were flagged with a `"mz:is_funky":1` property ([info on that property here](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/is_funky.json)), but _should_ have simply been flagged as not current. The first record (Lower Hutt) was not updated, but should have been, too. 

I need to QA a bit more to untangle some superseding in these cases, but I agree that changes are needed. I'll file a PR to fix and link this issue once complete. Thanks @missinglink!

**Comment by missinglink** [comment]
Thanks @stepps00 I'm back in NZ until April now or until the pandemic eases up enough to return home, so you might see some more of these NZ issues coming in from me as I spot check like a 🥝 🇳🇿
