### ISSUE TITLE
Normalize Features

### ISSUE THREAD

**Issue by Guilherme-B** [whosonfirst-data/whosonfirst-data#1923]
Bundles seem to be getting quite large, for instance, the US dist is now 3.6GB uncompressed.

If features were normalized into the third form, we could easily decrease their size, either creating whole or split identifiers, e.g:
- "src:label" could be ID 1
- or split into two, category and type "src" category 1, and "label" type 1

Is this something worthwhile considering?

On a side note, what is the recommended Go module for handling distributions?

**Comment by missinglink** [comment]
Hi @Guilherme-B, as the publisher of https://geocode.earth/data/whosonfirst I'll chip in my 2c

The goal of the bundles wasn't to provide as small a download as possible, it was to provide an easy way to download the data which was faithful to what's in Github, that way it can benefit the widest group of people and foster adoption and contribution to the project.

If your goal is to provide the *smallest* possible download size then I'd suggest a few things which will give you a lot of gains without changing the format:

- remove `superseded` and `deprecated` records, if you don't need change history
- drop any SQL tables you're not using such as `names`
- remove any placetypes you're not using in your application (such as `marketarea` etc.)
- perform a `VACUUM` on the database to reclaim the disk pages

I think you'll be pleasantly surprised at the reduction in disk space used by the database.

**Comment by pdavis156879** [comment]
Hi @missinglink,

Well, that clears it up, I really thought bundles were the go-to resource for downloading the data and GitHub was merely the repository used to generate the consumables (bundles).

On a side note, are you aware of which is the proper Go package for handling/manipulating SQLLite distributions?

**Comment by missinglink** [comment]
> GitHub was merely the repository used to generate the consumables

No, Github is the authoritative 'source of truth' when it comes to the data, the distributions are read-only point-in-time snapshots of Github in one form or another.

TBH I am still not understanding what you wrote in the issue description and what exactly you're trying to solve by 'normalizing features' 'into the third form'.

I believe maybe you're referring to a custom encoding possibly a binary encoding for the purposes of reducing the download filesize?

I think the repo you're looking for is:
https://github.com/whosonfirst/go-whosonfirst-sqlite-features-index

**Comment by Guilherme-B** [comment]
That is exactly what I was referring to.

But given the bundles are merely a presentation layer and size is of no concern, I will close the issue.
