### ISSUE TITLE
Typo in Holbaek, Denmark

### ISSUE THREAD

**Issue by c960657** [whosonfirst-data/whosonfirst-data#1925]
There is a typo in [Holbaek, Denmark](https://spelunker.whosonfirst.org/id/1159297717/).

It's _Holbaek/Holbæk_, not _Holaek_. See e.g. https://en.wikipedia.org/wiki/Holb%C3%A6k_Municipality.

PR here: https://github.com/whosonfirst-data/whosonfirst-data-admin-dk/pull/14

**Comment by stepps00** [comment]
Thanks @c960657 - we'll take a look.
