### ISSUE TITLE
Update Switzerland locality records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1931]
Hey @stepps00, 

Through more investigation, I found the following `localities` that have the same issue of having a lake as a `localadmin`.

```
source_id,name,lat,lon
101748449,Lausanne,46.520381,6.63141
101767399,St-Prex,46.475663,6.447215
101853861,Montreux,46.43423,6.911558
101853877,Lutry,46.503453,6.686783
101853885,Rolle,46.458885,6.338641
101854463,Egnach,47.544059,9.382679
1125773569,Chardonne,46.47676,6.8268
1125807373,Mammern,47.64625,8.91519
1125823961,Clarens,46.44055,6.89233
1125834091,Coppet,46.31682,6.19114
1125883875,Préverenges,46.51854,6.52682
1125887713,Territet,46.42863,6.92122
1125937761,Tolochenaz,46.50504,6.47279
1125944999,Perroy,46.46821,6.36622
1125990725,Buchillon,46.46705,6.41128
1126014611,St-Saphorin,46.47329,6.79601
1193046703,Prangins,46.39518,6.2496
1226579363,Engelberg,47.10387,7.17877
1259814947,Dully,46.43143,6.29461
1327462329,Villette,46.49575,6.70901
1394292823,Crans-près-Céligny,46.36056,6.21453
1394298067,Pully,46.510121,6.659839
```

Do you want me to open a new issue at [whosonfirst-data/whosonfirst-data-admin-ch](https://github.com/whosonfirst-data/whosonfirst-data-admin-ch)?

**While investigating that, I also found another interesting issue:**

Some localities have their `fra_x_preferred` translations wrong. It looks that it was automatically translated because the names looked like English words. For example, the village of “Egg” (in german) was translated in french to “Œuf“, which means egg, as related to a chicken. This is obviously wrong. I found these:

```
id,actual_name,wrongly_translated
404328441,Rain,Pluie
404328467,Root,Racine
404568785,Bullet,Balle
404568957,Egg,Œuf
404569029,Lens,Lentille optique
404570185,Gland,Glande
404570789,Arch,Arc
```
It looks that many languages are affected, but French is more critical here as it is a national language.

**Where would be the correct place to fix that? Should I also open an issue on data-admin-ch?**

_Originally posted by @SilvrDuck in https://github.com/whosonfirst-data/whosonfirst-data/issues/1897#issuecomment-803023941_

**Comment by zifeo** [comment]
@stepps00 Do you have an ETA for handling those cases? Happy to give a shot if you can point me in the right direction as always :)

**Comment by stepps00** [comment]
Hi @zifeo, thanks for pinging this issue.. we have not taken a look at this issue recently, but we'll investigate.

If a PR was crafted in the Switzerland admin repo, would you mind reviewing and offering your thoughts on the changes?

**Comment by zifeo** [comment]
@stepps00 Eager to learn & review :)
