### ISSUE TITLE
Poland - Myslowice polygon is incorrect

### ISSUE THREAD

**Issue by mihaicosareanu-bolt** [whosonfirst-data/whosonfirst-data#1934]
Hello there!

We noticed that the polygon of Myslowice is incorrectly defined, it is way bigger than the city itself. Here is the spelunker link: https://spelunker.whosonfirst.org/id/101752123/

Can we correct the polygon for this city?

Thank you!

**Comment by nvkelso** [comment]
Thanks for the report! Is there a better source of data we should be using, and could you help integrate it?

@stepps00 can you verify if the Spelunker shape is accurate vis-a-vis what's in Github?

**Comment by stepps00** [comment]
Here's the shape in GitHub: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/blob/master/data/101/752/123/101752123.geojson

The shapes look the similar, but I think there are slight differences due to clipping/alignment to the [pl-gugik](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/pl-gugik.json) source. It may be worthwhile to review locality shapes again, as our Poland data is now a mix of Quattroshapes-sourced data and Poland's Office of Geodesy and Cartography data.

**Comment by mihaicosareanu-bolt** [comment]
I played a bit with Poland's geo portal which seems to have a much more accurate polygon, although I didn't find any way of exporting it. Will look around a bit more and if I find something, I'll add a comment. https://mapy.geoportal.gov.pl/imap/Imgp_2.html?gpmap=gp0&locale=en

The ux on the geoportal is a bit weird, you need to locate the Search -> General and then type the city name "Myslowice"

**Comment by mihaicosareanu-bolt** [comment]
Is this data usable or should I look for something else? I'm not sure how you guys are looking for this kind of data sources, some docs would be useful to understand better :)

**Comment by stepps00** [comment]
> I played a bit with Poland's geo portal which seems to have a much more accurate polygon, although I didn't find any way of exporting it. Will look around a bit more and if I find something, I'll add a comment. https://mapy.geoportal.gov.pl/imap/Imgp_2.html?gpmap=gp0&locale=en

Thanks for this link @mihaicosareanu-bolt, I'm taking a look at this source now.

> Is this data usable or should I look for something else?

Who's On First requires a `CC0`, `CC-BY`, or equivalent license for import for new data imports. Poking around the geoportal link you provided, I am noticing links back to the same [pl-gugik](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/pl-gugik.json) source that was used for the initial admin updates in Poland. So I suspect this data is workable for Who's On First.

I will update this issue when I'm able to compare this data with the data in Who's On First, but feel free to add more examples of issues you're seeing in Poland in the meantime.

**Comment by mihaicosareanu-bolt** [comment]
Hey Stephen! Any updates on this issue? We are still receiving complaints from our users due to incorrect locality attribution

**Comment by stepps00** [comment]
Hey @mihaicosareanu-bolt thanks for flagging this one. We haven't had a chance to review this record; I'll try to look into this issue this week and reply with a comment/fix. Thanks for your patience here.

**Comment by stepps00** [comment]
I've noticed a few other issues with locality geometries in Poland, so I took a look at the `miast` data for the country. I see this shape for Mysłowice (highlighted):

<img width="1148" alt="Screen Shot 2022-09-20 at 2 52 43 PM" src="https://user-images.githubusercontent.com/18567700/191371735-ee3b35df-7b33-486d-b511-d8ccf0da896b.png">

I'm going to prioritize this issue, and work to correct additional locality geometries.. @mihaicosareanu-bolt are there other issues you're seeing with the WOF data in Poland? I'd like to tackle them in a single PR.

**Comment by stepps00** [comment]
I've identified ~100 additional localities in Poland that have inaccurate polygons.. examples are Sochocin, Jaworzno, and Będzin.

Poland's miasto and gmina divisions may cause a bit of work around the localadmin placetype, too, but I'll link to a PR for this issue next week so we can chat about the changes there.

**Comment by stepps00** [comment]
I've linked to the PR with fixes above. There were actually two different locality records representing Myslowice. 101752123 will be superseded into 101913709 so WOF only maintains a single record for this place. 

101752123:
- Current state: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/blob/master/data/101/752/123/101752123.geojson
- Updated: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/blob/stepps00/admin-updates/data/101/752/123/101752123.geojson

101913709:
- Current state: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/blob/master/data/101/913/709/101913709.geojson
- Updated: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/blob/stepps00/admin-updates/data/101/913/709/101913709.geojson
