### ISSUE TITLE
Add Kukes International Airport

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1938]
* https://www.airport-technology.com/news/albania-kukes-international-airport/
* https://github.com/whosonfirst-data/whosonfirst-data-admin-al

**Comment by ImreSamu** [comment]
* https://www.wikidata.org/wiki/Q1431804  "Kukës International Airport"
* https://en.wikipedia.org/wiki/Kuk%C3%ABs_International_Airport

**Comment by thisisaaronland** [comment]
* https://github.com/whosonfirst-data/whosonfirst-data-admin-al/commit/c49dd3ecc9fb455a75b04f07faa90d41c731ee65
* https://github.com/whosonfirst-data/whosonfirst-data-admin-al/commit/a0dc5b56de5281566b01d548d17662ed6cb46acc
* https://github.com/whosonfirst-data/whosonfirst-data-admin-al/commit/3885eedadaceba886543d66524b9ff64c5734371
