### ISSUE TITLE
Combine Prospect Park Sout(h)

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst-data/whosonfirst-data#194]
These are referring to the same place and should be combined:
https://whosonfirst.mapzen.com/spelunker/id/85865585/
https://whosonfirst.mapzen.com/spelunker/id/85869607/

**Comment by stepps00** [comment]
This issue will be fixed once #384 is closed. I'll update this issue once the import is complete.

**Comment by nvkelso** [comment]
Forward dup of #384, closing.
