### ISSUE TITLE
County Poznan appears as "Loredan Popa"

### ISSUE THREAD

**Issue by veskiii** [whosonfirst-data/whosonfirst-data#1943]
Poznań has the name "Loredan popa" in all languages except Polish.
<img width="583" alt="Screenshot 2021-06-04 at 17 38 21" src="https://user-images.githubusercontent.com/56825599/120827365-aa03be80-c55b-11eb-9c42-44b5fc3df951.png">

**Comment by stepps00** [comment]
Place: https://spelunker.whosonfirst.org/id/102079921/

It looks like these names are coming in from Wikidata. Who's On First maintains [Q6680284](https://www.wikidata.org/wiki/Q6680284) as the Wikidata concordance for this place, which is incorrect.

We'll file a PR to fix the concordance and names shortly.

**Comment by nvkelso** [comment]
Will be fixed via related PR https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/pull/35.
