### ISSUE TITLE
Southern Ocean

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1944]
https://www.nationalgeographic.com/environment/article/theres-a-new-ocean-now-can-you-name-all-five-southern-ocean

**Comment by nvkelso** [comment]
I was part of those debates long ago and preemptively created https://spelunker.whosonfirst.org/id/404528707/ already ;)

**Comment by thisisaaronland** [comment]
Go us! You should write a blog post about this.
