### ISSUE TITLE
Localadmin for Porto, Portugal

### ISSUE THREAD

**Issue by cafsenra** [whosonfirst-data/whosonfirst-data#1949]
The city of Porto has seven localadmin:
- Aldoar, Foz do Douro e Nevogilde
- Bonfim
- Campanhã
- Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória
- Lordelo do Ouro e Massarelos
- Paranhos
- Ramalde

Nevertheless, it seems that all neighbourhood appears to belong to "Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória".
For example, if we check neighbourhood "Bonfim" (https://spelunker.whosonfirst.org/id/1126068879/) it has localadmin "Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória", but it should have localadmin "Bonfim" (https://spelunker.whosonfirst.org/id/1125358961/).
In my understanding, the "Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória" localadmin definitions are overriding others localadmin for the city of Porto.

**Comment by missinglink** [comment]
hi @cafsenra, a couple quick observations:

This polygon: https://spelunker.whosonfirst.org/id/1125358961/ doesn't seem to match the shape of the one on wikipedia 

<img width="250" alt="Screenshot 2021-07-08 at 10 33 08" src="https://user-images.githubusercontent.com/738069/124890008-b7650a80-e02b-11eb-9257-26d273b850a1.png">

<img width="280" alt="Screenshot 2021-07-08 at 10 33 37" src="https://user-images.githubusercontent.com/738069/124890086-c9df4400-e02b-11eb-94d3-42b338dde03c.png">

This makes me wonder if the shapes are correct 🤔 

The association from `neighbourhood` to `localadmin` works by performing a point-in-polygon check, [1126068879](https://spelunker.whosonfirst.org/id/1126068879/) is a point based geometry at `-8.58688, 41.15417`.

If the parent geometries are incorrect then the `neighbourhood` can be associated to the wrong `localadmin`.

<img width="732" alt="Screenshot 2021-07-08 at 10 36 08" src="https://user-images.githubusercontent.com/738069/124890408-22164600-e02c-11eb-8816-40dbf539de76.png">

**Comment by cafsenra** [comment]
Hi @missinglink, thank you for your observations ;)
Indeed, there might be issues at the parent geometries. For the city of Porto all neighbourhood are wrongly associated to localadmin Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória. Another example is Ramalde neighbourhood (https://spelunker.whosonfirst.org/id/1126095623/) who is wrongly associated to localadmin Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória, instead of localadmin Ramalde. This bring issues when importing data to pelias: all streets of Porto appears associated wrongly to Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória!

**Comment by cafsenra** [comment]
Others examples are "Paranhos" neighbourhood (https://spelunker.whosonfirst.org/id/1126085087/), "Campanhã" (https://spelunker.whosonfirst.org/id/85798957/), "Aldoar" (https://spelunker.whosonfirst.org/id/1126064737/), etc.
They shouldn't be "Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória" localadmin, but they should be respectively "Paranhos", "Campanhã" and "Aldoar, Foz do Douro e Nevogilde" localadmin.
Like @jaimeventura said, we're working closely with the municipality of Porto, and we are available to help fixing this!

**Comment by missinglink** [comment]
Hi folks, so Stephen Epps is the maintainer, he's based in us-west, since I'm in eu-central I can give you some pointers.

You can use a filter on the spelunker to list things like:
- [all the localadmin records](https://spelunker.whosonfirst.org/search/?iso=pt&placetype=localadmin)
- [all the neighbourhood records](https://spelunker.whosonfirst.org/search/?iso=pt&placetype=neighbourhood)

With your local knowledge it would be nice to have the `localadmin` records (in particular) checked for validity.
Maybe just in Porto/Lisbon/etc to begin with, to save time.

Can you please confirm that the shape of those geometries looks correct?

Secondly it would be nice to have your local knowledge on a handful of the `neighbourhood` records, do these points look like they are in the right place or should some/all of them be moved? if so, how far off are they generally from where they should be?

There are a couple of things you should know about the Spelunker:
- it's not always up-to-date, the 'source of truth' is Github, so you can hit the 'View on Github' or 'Raw data (GeoJSON)' links to see the latest version
- the map view displays two geometries on it, it shows the geometry you expect and also the immediate parent geometry, this can sometimes be confusing when the place is a point (displayed as a green dot) and the parent is a large blue polygon behind it.

**Comment by missinglink** [comment]
I believe the data was sourced from https://www.dgterritorio.gov.pt/dados_abertos/caop/
Is that the best open data to use?

If you're working with them could you please mention that link has an invalid SSL cert and returns 404 😄

**Comment by justinelliotmeyers** [comment]
@missinglink I have more granular data for Portugal from official sources. what is the easiest format for you to work with? I can upload so you can look.

Cheers,
Justin

**Comment by justinelliotmeyers** [comment]
[Desktop.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/6784154/Desktop.zip)

here are the centroids in shapefile format - if you think these will assist you or @stepps00 I can get you my working polygons or raw data as well. I plan on fully developing these soon, but need to wrap up a few other projects.  Cheers!

**Comment by missinglink** [comment]
Is there a link to the official license text, I could only find [legal restrictions](https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/198497815bf647ecaa990c34c42e932e) with a big "Open Data" stamp on it 😄 

<img width="1041" alt="Screenshot 2021-07-08 at 16 41 42" src="https://user-images.githubusercontent.com/738069/124941821-33c51100-e05f-11eb-8659-9e86f6f8bca6.png">

**Comment by stepps00** [comment]
@cafsenra - thanks for the issue.. and thanks all for the links/comments.

~Two years ago, Who's On First gained new localadmin geometries from Portugal's "Directorate-General for the Territorial Development of Portugal" ([source information](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/pt-dgt.json)), as part of https://github.com/whosonfirst-data/whosonfirst-data/issues/1740.

The localadmin in Who's On First should represent the parishes in the country. Other placetypes in Portugal have not been updated in some time, so I'm not surprised to see some issues with the neighbourhood geometries in/around Porto.

Similar to other large cities/capital cities, what I suspect needs to happen is Who's On First should review the neighbourhood, borough, locality, and localadmin placetype coverage in Porto to fix this issue. My guess is we can re-use geometries at more than one placetype to fix issues like [Bonfim](https://spelunker.whosonfirst.org/id/1126068879/) being parented by [Bonfim](https://spelunker.whosonfirst.org/id/1125358961/).

We can take a look at the sources listed in this issue + the source used to update the localadmin records and propose a fix for this neighbourhood issue. @cafsenra if you have additional examples of issues with neighbouhroods, they'd be helpful. Thanks!

**Comment by justinelliotmeyers** [comment]
@missinglink always the other pain to figure out. So after some digging: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/198497815bf647ecaa990c34c42e932e

does this work for you?

**Comment by cafsenra** [comment]
@missinglink and @stepps00 is there any updates on this issue? There is a timeline for solving this issue? How can we help?

I provided several examples on the city of Porto, it is hard to provide more, specially outside Porto, but I think the examples I provided are enough to see the problem. Please let me know if you are blocked and what you need to go further.

Thanks!

**Comment by stepps00** [comment]
Hey @cafsenra - thanks for flagging this issue. I've taken another look at all current WOF records in/around Porto, some notes about what needs to be done, below. Let me know your thoughts.

- The locality of [Porto](https://spelunker.whosonfirst.org/id/101752093) has a geometry sourced from Quattroshapes, which doesn't fully cover the extent of all of the seven parishes in Porto. This geometry should be updated.
- IMO, the seven localadmin in Porto could also be classified as [boroughs](https://github.com/whosonfirst/whosonfirst-placetypes/#borough), so we could create seven new borough records in Porto that are [coterminous](https://github.com/whosonfirst/whosonfirst-properties/blob/main/properties/wof/coterminous.json) with the localadmin records.
- The neighbourhood records in Porto are currently maintained with Point geometries. There seem to be duplicates ([Foz do Douro](https://spelunker.whosonfirst.org/id/85798999) and [Foz do Douro](https://spelunker.whosonfirst.org/id/1126102223) as an example), as well as missing records at this placetype. To fix the issues called out in your initial issue comment, I'll suggest we update/addnew neighbourhood records with new Polygon geometries using one of the sources linked to in above comments.

I can craft a PR with data changes and add you as a reviewer to help QA changes. This should fix issues in Porto, but I'll suggest we open a new issue for country-wide fixes if this is a problem seen in more areas of Portugal. I suspect there are other areas in Portugal that could be reviewed to update neighbourhood and locality coverage.

**Comment by cafsenra** [comment]
Hey @stepps00 - thanks for the reply.
I fully agree with your notes. I am available to have a role as reviewer to help QA changes. Please let me know when can you craft a PR with data changes.
Also agreed that might exists a problem in more areas of Portugal. If it is that the case, we might open a new issue for country-wide fixes later.

**Comment by stepps00** [comment]
@cafsenra would you happen to have a source for neighbourhood polygon data in Porto? I've reviewed links in this issue, which point back to the data we're using for localadmin places, but unable to find neighbourhood geometries. I've looked through datasets on [Porto's Open Data portal](https://opendata.porto.digital/), but I am unable to find that data.

cc @justinelliotmeyers

**Comment by cafsenra** [comment]
@stepps00 I am currently on vacations, however @jaimeventura had contacted the city hall in order to get the information we need. Please stay tuned, we will deliver this information counting that this information exists on city hall side (and we expect that it does).

**Comment by stepps00** [comment]
Thanks for the update - worth noting that it would be very helpful to include the data license along with any data provided by City Hall... we're looking forward to seeing neighbourhood shapes.

**Comment by jaimeventura** [comment]
After contacting the appropriate city service, i was told that there are small differences between the national chart and the municipality's chart, and, for legal issues, the national chart should be used.

Having that said, they provided the direct link to the info on the same website you mentioned before:
http://mapas.dgterritorio.pt/ATOM-download/CAOP-Cont/Cont_AAD_CAOP2020.zip

The person i talked to admitted it wasn't easy to get to this url from the website.
He also filtered the info on that file in order to extract Porto's data specifically   (as both shapefile and geojson, attached), although i believe you would like to update wof's database for the whole country and not just for Porto.

As im not proficient on this subject, feel free to ask for additional info and i'll bridge you to your contact in the municipality.

Thank you,

[shp_porto.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/6980306/shp_porto.zip)
[porto.json.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/6980327/porto.json.zip)

**Comment by stepps00** [comment]
Thanks for reaching out to them @jaimeventura 

Reviewing the files you provided, it looks like these geometries are identical to what WOF already has at the localadmin placetype (and what I propose we adds as boroughs, too). Are there additional files for smaller divisions in Porto that we'd be able to import as neighbourhoods?

**Comment by cafsenra** [comment]
Hi @stepps00,

If the geometries are identical to what WOF already has at localadmin, then something is wrong, cause there is seven localadmin, and the WOF only shows one localadmin. These are the seven localadmin (Freguesia):

```shell
➜  ~ cat ~/Downloads/porto.json | jq | grep Freguesia
        "Freguesia": "Ramalde",
        "Freguesia": "Paranhos",
        "Freguesia": "União das freguesias de Lordelo do Ouro e Massarelos",
        "Freguesia": "Bonfim",
        "Freguesia": "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória",
        "Freguesia": "Campanhã",
        "Freguesia": "União das freguesias de Aldoar, Foz do Douro e Nevogilde",
```

Can you identify in the json what you propose as neighbourhoods as I done to the localadmin?

**Comment by stepps00** [comment]
> If the geometries are identical to what WOF already has at localadmin, then something is wrong, cause there is seven localadmin, and the WOF only shows one localadmin. These are the seven localadmin (Freguesia):

The seven localadmin that represent the Freguesias of Porto are here:

- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/151/168/038/5/1511680385.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/151/168/037/5/1511680375.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/151/168/032/5/1511680325.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/151/168/035/9/1511680359.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/151/168/035/7/1511680357.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/112/535/896/1/1125358961.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/blob/master/data/112/540/991/5/1125409915.geojson

I realized the Spelunker tool is out of sync with GitHub as I gathered these records, which is why you're not seeing all seven of these records populate when looking through descendants of Porto in that tool. This issue is being tracked [here](https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/145).

> Can you identify in the json what you propose as neighbourhoods as I done to the localadmin?

I was actually hoping for some help with this myself.. as I look through various sources, I'm not able to find data representing the neighbourhood divisions (I'm only able to find the Freguesia, which are already in WOF).

**Comment by cafsenra** [comment]
Ok I think that the neighbourhood are actually the same of localadmin for "Ramalde", "Paranhos", "Bonfim" and "Campanhã", but not for "União das freguesias de Aldoar, Foz do Douro e Nevogilde", "Freguesia": "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória" and "União das freguesias de Aldoar, Foz do Douro e Nevogilde", cause those localadmin aggregates neighbourhood, for example on "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória", the neighbourhood are "Cedofeita", "Santo Ildefonso", "Sé", "Miragaia", "São Nicolau" and "Vitória". Not sure if I was clear, but I hope that this helps you.

**Comment by stepps00** [comment]
@cafsenra @jaimeventura I took a shot at creating new neighbourhood shapes for Porto using the existing localadmin geometries as a baseline. Take a look at them here: https://gist.github.com/stepps00/11ccb8af26dceb84b525c52ff62182df

I used existing WOF data, satellite imagery, streetlines, and Wikipedia pages to estimate where the boundaries roughly are, so these aren't perfect.. but curious what you think. If these shapes are a improvement to WOF's current coverage, I'd like to update records with these new geometries.

**Comment by missinglink** [comment]
I just had a quick look and noticed the neighbourhood named `Sé`, is that the correct name to use?

> Baixa / Sé, commonly known as Downtown Porto or simply as “Baixa”, is the neighborhood just above Ribeira.

<img width="259" alt="Screenshot 2021-09-08 at 13 00 15" src="https://user-images.githubusercontent.com/738069/132498049-397e9d0b-629d-4864-99bb-c31b7e8e8bf6.png">

**Comment by cafsenra** [comment]
Hi @missinglink,

Yes, the correct name is "Sé", which is located on Downtown Porto. However, Downtown Porto ("baixa"), which is the historic centre of Porto, has others neighborhoods like "Cedofeita", "Santo Ildefonso", "Miragaia", "São Nicolau" and "Vitória".

**Comment by cafsenra** [comment]
Please note that localadmin for "Sé" neighborhood is "União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória".

**Comment by nvkelso** [comment]
@stepps00 please remember to keep the water parts for a revgeo polygon, but the default shape should clip to the shore. Otherwise LGTM as an improvement over what's there! Some of the smaller neighbourhoods could be added as microhoods later, and maybe a few macrohoods as well? But "better than yesterday".

**Comment by stepps00** [comment]
I've clipped these geometries to the coastline and updated the gist.. @cafsenra let me know your thoughts on these shapes. I'm curious if these shapes more or less line up with local expectations. If they look good, I'll craft a PR this week and merge the changes.

**Comment by cafsenra** [comment]
Hi @stepps00,
According to the information that we have in our possession I believe that this shapes are ok. For sure it is an improvement of the previously version. As a Porto city native, I don't find any issue and the shapes looks good to me.

**Comment by cafsenra** [comment]
Hi @stepps00,
I have a second look to you map and I found some diferences with the map I had:

![image](https://user-images.githubusercontent.com/55795848/132858755-48b07db6-854a-4675-ad92-494b1b83a7b6.png)

**Comment by cafsenra** [comment]
Hi @stepps00,

Have you looked into the map diferences? I understand that it can be frustrating working with few information, however we supplied all the information that we had. Hope that you can do improvements with the information we gatherer. The map above is a map supplied in a document from city hall.

**Comment by cafsenra** [comment]
Hi @stepps00,

We are going to ask to city hall if they can supply data for the neighbourhoods. Please hold on your changes until that. Thank you.

**Comment by stepps00** [comment]
Thanks @cafsenra - we'll hold off on changes until the city responds. If they do not provide a data source, we can reference the map above to fine-tune our geometries.

**Comment by jaimeventura** [comment]
Hey @stepps00 ,
Ive just receive a reply from the municipality services.
Hope the file attached helps.
Thanks you for your effort
[freguesias.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/7199076/freguesias.zip)
.

**Comment by stepps00** [comment]
Thanks @jaimeventura - do you happen to have information about the data license for this `freguesias_porto.shp` file? Ideally the file is openly licensed (CC0 or CC-BY equivalient) and can be imported directly into Who's On First.

**Comment by jaimeventura** [comment]
Very pertinent question.
I've asked the municipality, and although that wouldn't be a problem, we/you may take a different approach.

Until 2013, neighbourhoods were split (meaning each neighbourhood was also a localadmin). In 2013, some neighbourhoods ( i.e. “aldoar”, “foz do Douro”, “nevogilde”) were merged as localadmins (“União de freguesias de aldoar, foz do Douro e Nevogilde”)

So, a workaround is to use the CAOP from 2012 (https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/DT73_20121.zip) and  (https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/Cont_AAd_CAOP20121.zip)  in Datum73 e ETRS89 respectively.

These files hold data for the whole country. If you consider Porto specifically, the municipally filtered the data, producing the attached file (WGS84).

[porto2012.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/7202595/porto2012.zip)

Hope this helps

**Comment by cafsenra** [comment]
Hi @stepps00 ,

Have you the opportunity to look to the files above? Does that help you? Is there any prediction on when can you have those changes reflected in the WOF?

Note: I am embracing a new challenge but @jaimeventura will continuous to give us all the support from municipally.

**Comment by stepps00** [comment]
Hi all, we've updated the neighbourhood (and localadmin + locality) records in Porto with new `whosonfirst`-sourced geometries in https://github.com/whosonfirst-data/whosonfirst-data-admin-pt/pull/17; they'll likely be merged soon. If follow-up work is needed, let's open a new PR to track.
