### ISSUE TITLE
Wrong population figure for Detroit, Illinois (85939649)

### ISSUE THREAD

**Issue by assaflavi** [whosonfirst-data/whosonfirst-data#1951]
Population for this tiny village in Illinois is listed as 680250, probably taken from the record for Detroit, Michigan.

Best data I could find for this locality is 81, taken from US Census Bureau (2019):
https://www2.census.gov/programs-surveys/popest/tables/2010-2019/cities/totals/SUB-IP-EST2019-ANNRES-17.xlsx

**Comment by stepps00** [comment]
Fixed through https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/100.
