### ISSUE TITLE
San Francisco neighborhood name mispelled 

### ISSUE THREAD

**Issue by evanhobbs-burner3** [whosonfirst-data/whosonfirst-data#1962]
The correct name should be "Parnassus" but I'm seeing "Panassus" in places: https://github.com/whosonfirst-data/whosonfirst-data-admin-us/search?q=panassus

https://www.google.com/search?q=parnassus+san+francisco&oq=parnassus+san+fran&aqs=chrome.0.0i512j69i57j0i22i30l5j69i60.2457j0j7&sourceid=chrome&ie=UTF-8

**Comment by stepps00** [comment]
Thanks @evanhobbs-burner3 - we'll update those neighbourhood names shortly.
