### ISSUE TITLE
Backfill name properties with IATA/ICAO codes

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1963]
In many cases, airport campus records maintain IATA and ICAO codes as variant names, a few examples:

- https://spelunker.whosonfirst.org/id/102532251/ (PDX and KPDX are English name variants)
- https://spelunker.whosonfirst.org/id/102531023/ (MIA and KMIA are English name variants)

However, the IATA / ICAO codes are not listed as variant names in others. Examples:

- https://spelunker.whosonfirst.org/id/102524321/
- https://spelunker.whosonfirst.org/id/102549355/

These name properties could be backfilled using existing `iata:code` and `icao:code` concordances, when available.

**Comment by stepps00** [comment]
@thisisaaronland I'm considering crawling admin repos to backfill `name:eng_x_variant` properties with the IATA and ICAO concordances, when available, for airport campuses.. thoughts? Is that a fair approach?

**Comment by thisisaaronland** [comment]
👍
