### ISSUE TITLE
What CRS does whosonfirst use?

### ISSUE THREAD

**Issue by mmz15** [whosonfirst-data/whosonfirst-data#1969]
I'm doing a spatial join with a point that has a lng, lat of -73.883669, 40.725833 with the expectation that it'll map to Middle Village, NY, which has an `id` of `420529699` and `path` of `420/529/699/420529699.geojson`. Instead, it's mapped to Elmhurst, NY (`85817879`, `858/178/79/85817879.geojson`). I suspect this might be caused by the CRS (coordinate reference system) used. Is there a field that specifies the CRS?

**Comment by thisisaaronland** [comment]
Hi @mmz15, 

Who's On First documents are GeoJSON documents so `WSG-84`:

https://datatracker.ietf.org/doc/html/rfc7946#page-12

**Comment by mmz15** [comment]
Oh wow didn't know that WSG-84 applies to all GeoJSON. Thank you!
