### ISSUE TITLE
Sort out multiple records for Cleveland Museum of Art

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#1978]
* https://spelunker.whosonfirst.org/id/706601219/
* https://spelunker.whosonfirst.org/id/706608439/
* https://spelunker.whosonfirst.org/id/706599119/
* https://spelunker.whosonfirst.org/id/706600581/

This one should be kept, the others deprecated:

* https://spelunker.whosonfirst.org/id/706599119/

**Comment by straup** [comment]
Fixed in https://github.com/whosonfirst-data/whosonfirst-data-venue-us-oh/commit/e0681f444b32d008aea29dd010c33eca37c839ba
