### ISSUE TITLE
"San Francisco" ghost town in Minnesota

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#1987]
Hi folks!

I noticed today that we have a record for the town of San Francisco in Minnesota, of all places.

[WOF record on GitHub](https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/172/946/250/7/1729462507.geojson)

According to Wikipedia, this is a [Ghost town](https://en.wikipedia.org/wiki/San_Francisco%2C_Minnesota).

What's the best way to represent this in WOF? Should we add a `cessation` date? Mark it as `is_funky`?  Something else?

**Comment by orangejulius** [comment]
Ok great, that should be taken care of in https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/118 (after a few false start PRs)

**Comment by thisisaaronland** [comment]
Oh, I forget to suggest adding a Wikidata concordance for the record as well. As in:

```
wof:concordances.wd:id=Q7413896
```

* https://www.wikidata.org/wiki/Q7413896
