### ISSUE TITLE
invalid json - whosonfirst-data-admin-ie repo

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1989]
There is an alt geom in the `whosonfirst-data-admin-ie` repo which is invalid JSON:

```bash
jq . data/174/665/215/1/174665215-alt-ie-gov.geojson
parse error: Unmatched ']' at line 10, column 1
```

cc @stepps00 this is unfortunately breaking the builds, I'm going to add some code to skip these records but it would great to have this fixed soon if possible 🙏

**Comment by missinglink** [comment]
I ran a script to check the rest of the `whosonfirst-data-admin-ie` repo and this was the only feature suffering this issue.

**Comment by stepps00** [comment]
Thanks @missinglink - I've fixed this in https://github.com/whosonfirst-data/whosonfirst-data-admin-ie/pull/26, and merged the PR. This shouldn't have slipped by.

I mentioned in the PR comments that we use the validation tools before merging PRs. This bunk json either slipped by somehow, or the validation tool wasn't used correctly. I'll have to review the workflow so this sort of thing doesn't happen again.

**Comment by missinglink** [comment]
awesome thanks, this is a quick script I wrangled together to check that all files in the `data/` dir are valid JSON, we could add something like that to a git precommit hook or github action.

```bash
for i in $(find data -name \*.geojson); do
  cat $i | jq . &>/dev/null;
  if [ $? -eq 1 ]; then
    echo "$i JSON encoding invalid";
  fi;
done
```

**Comment by thisisaaronland** [comment]
I am not opposed to commit hooks but I would prefer to roll this sort of thing in to tools/packages in https://github.com/whosonfirst/go-whosonfirst-validate

At least that way we can generate pre-compiled binaries and not make `jq` and everything needed to install it a dependency.

**Comment by missinglink** [comment]
builds have all been regenerated today, I manually removed that one file but it'll come back in on the next build in a few hours now it's fixed.

unfortunately I'm not able to recover from these errors in the bundling code since it uses a streaming JSON parser, when it hits invalid tokens there's no way for the parser to know how many subsequent tokens to discard to resume the stream at the next record.

:+1: for some sort of basic pre-commit validation, the `jq` command above takes several minutes so it will be a little annoying TBH.

**Comment by thisisaaronland** [comment]
Okay, the `wof-validate` tool in `whosonfirst/go-whosonfirst-validate` has been updated to ensure a known-valid WOF URI that can be parsed as valid GeoJSON: 

https://github.com/whosonfirst/go-whosonfirst-validate/blob/main/cmd/wof-validate/main.go#L44-L60

The remaining validation tests (there is currently only one for name tags) continue to be optional. More validations are welcome.

This would benefit from the necessary GitHub action files to build precompiled binaries on commit if anyone wants to tackle that before I do.
