### ISSUE TITLE
Incorrect locality in search results in WI, USA (North America project)

### ISSUE THREAD

**Issue by artemChernitsov** [whosonfirst-data/whosonfirst-data#1992]
Just enter in search "639 Baxter Drive Mukwonago"
https://pelias.github.io/compare/#/v1/autocomplete?text=639+Baxter+Drive+Mukwonago

**Expected behavior**
Locality must be Mukwonago, not Waterford.

Looks like this is due to there being two overlapping polygons by this issue https://github.com/pelias/docker/issues/281:

https://spelunker.whosonfirst.org/id/101732271/
https://spelunker.whosonfirst.org/id/101732227/
both claim to be sourced from uscensus which usually doesn't have overlapping polygons 🤔
note there is also the localadmin -> https://spelunker.whosonfirst.org/id/404495653/

**Comment by missinglink** [comment]
Actually on closer inspection these polygons don't actually overlap, I think this issue might be on the Pelias end, sorry for the noise.

<img width="610" alt="Screenshot 2022-01-20 at 11 07 11" src="https://user-images.githubusercontent.com/738069/150317792-6ddd5aba-2380-424b-bd0f-e8a986c22d0f.png">

**Comment by missinglink** [comment]
confirmed it's a Pelias issue, this can be closed 🙇

**Comment by nvkelso** [comment]
No worries!
