### ISSUE TITLE
Cleanup default feature names on 4 countries

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#20]
1. Faroe Islands
	85633153	FO	Foroyar#Faroerne 
	data/856/331/53/85633153.geojson
	
	Default to:
	Faroe Islands
	
	add Faroerne 
	to u'name:unk_s'

2. Aland

	85632789	XX	Landskapet Aland#Ahvenanmaan maakunta	
	data/856/327/89/85632789.geojson
	
	Default to:
	Aland
	
	alt name: Åland Islands

3. Spratly Islands

	85632177	XX	Spratly Is.							
	data/856/321/77/85632177.geojson
	
	Default to:
	Spratly Islands

4. Tanzania

	85632227	TZ	United Republic of Tanzania				
	data/856/322/27/85632227.geojson
	
	Default to:
	Tanzania

**Comment by stepps00** [comment]
Closing - https://github.com/whosonfirst-data/whosonfirst-data/pull/323 to fix this issue was merged to master.
