### ISSUE TITLE
Invalid lang tag in 1393596465

### ISSUE THREAD

**Issue by slaperche-zenly** [whosonfirst-data/whosonfirst-data#2003]
In in [1393596465 .geojson](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-de/master/data/139/359/646/5/1393596465.geojson) there is an invalid lang tag:

```
"name:lat_x_":[
    "Balderschwang"
],
```

Should be `name:lat_x_variant` I think.

**Comment by nvkelso** [comment]
@stepps00 can you take a look, please?

**Comment by stepps00** [comment]
This is interesting.. looks like this was introduced as a one-off via [this commit](https://github.com/whosonfirst-data/whosonfirst-data-admin-de/commit/4f32a0dad76fb07160cdd4660d4ed2e250316beb). I'll update this single record shortly, but curious if you see this elsewhere @slaperche-zenly

**Comment by missinglink** [comment]
I had a look through all the admin data and it appears to be a one-off
