### ISSUE TITLE
Invalid concordance source in 102541661

### ISSUE THREAD

**Issue by slaperche-zenly** [whosonfirst-data/whosonfirst-data#2006]
The entry [102541661](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-jp/136fea14782154c5bd1a1e26070b527bd3921583/data/102/541/661/102541661.geojson) in whosonfirst-data-admin-jp is using the key `wikidata` instead of `wd:id` for the Wikidata ID

**Comment by missinglink** [comment]
<img width="314" alt="Screenshot 2022-07-12 at 14 43 54" src="https://user-images.githubusercontent.com/738069/178492633-aa141341-c5df-4eac-a9dd-be9ef634b299.png">

looking at another record, the wikipedia concordance should also be `wk:page` instead of `wikipedia`

**Comment by stepps00** [comment]
Thanks for the issue - we've opened two issues (above). One updates the single record with these concordance issues, and one will add a list of existing concordances to the properties repo.

**Comment by thisisaaronland** [comment]
> Is there a list of ~values~ keys for this field? ref: https://github.com/whosonfirst/whosonfirst-properties/tree/main/properties/wof#concordances

@missinglink FYI: https://github.com/whosonfirst/whosonfirst-properties/issues/110#issuecomment-1182631422
