### ISSUE TITLE
Canary Islands are missing all hierarchy

### ISSUE THREAD

**Issue by riordan** [whosonfirst-data/whosonfirst-data#201]
https://whosonfirst.mapzen.com/spelunker/id/404227369/

**Comment by nvkelso** [comment]
Can you describe what are you looking for in more detail?

**Comment by thisisaaronland** [comment]
![screen shot 2016-02-01 at 10 26 25](https://cloud.githubusercontent.com/assets/12658759/12726817/7884bd6c-c8ce-11e5-8b76-4ed8067bfb89.png)

Attached screenshot – the reason being that the reverse geocoder / PIP logic a) isn't loading bodies of water and b) is basically just biased to land-features really.

This is a good use case for kicking the tires...

**Comment by stepps00** [comment]
Once the PR above is merged to `master`, the next round of PIP-ing should update descendant hierarchies in the Canary Islands.
