### ISSUE TITLE
Monaco (MC) Label point

### ISSUE THREAD

**Issue by Joxit** [whosonfirst-data/whosonfirst-data#2020]
Hi there!

I just noticed that the Monaco country label was misplaced [85633285](https://spelunker.whosonfirst.org/id/85633285/)

![image](https://user-images.githubusercontent.com/5153882/211575935-a41ae41c-872e-4f2f-ad71-1c2cfa1be674.png)

**Comment by nvkelso** [comment]
Thanks for the report. It looks like an easy fix. @stepps00 can you take a look, please?

**Comment by stepps00** [comment]
Thanks @joxit - the PR linked above should fix this issue.

**Comment by Joxit** [comment]
Thank you both for your quick fix :smile: everything is working now !
