### ISSUE TITLE
DE/AT Encoding problem with umlaut (special vowls)

### ISSUE THREAD

**Issue by arnesetzer** [whosonfirst-data/whosonfirst-data#2022]
There is an encoding problem with converts all ß/ä into Ã
For example
https://spelunker.whosonfirst.org/id/102063389/ 
|Category| current name| correct name|
| ------------- | ------------- | ------------- |
|deu_x_preferred_longname |Landkreis WeiÃenburg-Gunzenhausen|Landkreis Weißenburg-Gunzenhausen|
|eng_x_preferred_longname|WeiÃenburg-Gunzenhausen District|Weißenburg-Gunzenhausen District|

It's also appears on venues in Austria which are doctors office.
Just search for "Ã" (https://spelunker.whosonfirst.org/search/?q=Ã) and you get 41 pages of where this happend.

Eg. https://spelunker.whosonfirst.org/id/1092413765/
|Category| current name| correct name|
| ------------- | ------------- | ------------- |
|orig_category|	Fettabsaugung, Ã„rzte / FachÃ¤rzte F Plastische Chirurgie |Fettabsaugung, Ärzte / Fachärzte für Plastische Chirurgie|

**Comment by missinglink** [comment]
this issue is caused during import when a document is interpreted assumed to be encoded `ISO 8859-1` but is actually encoded `UTF-8`.

more information with examples can be found here (German language): https://floern.com/;;/umlautproblem/

**Comment by missinglink** [comment]
<img width="382" alt="Screenshot 2023-02-08 at 17 19 48" src="https://user-images.githubusercontent.com/738069/217588736-5dca8a4a-b0f0-49f4-9b4f-6af8b9cc4d7a.png">

**Comment by missinglink** [comment]
cc @thisisaaronland, we could probably fix this algorithmically as thankfully the German language doesn't have many glyphs outside the ASCII range?

**Comment by thisisaaronland** [comment]
If we can generate a list of suspect names to eyeball/validate first, that would be great. cc @stepps00

**Comment by stepps00** [comment]
Looks like there are a dozen or so affected records in the admin-de repo, list of ids here:  [de-encoding.csv.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/10700436/de-encoding.csv.txt)

There are 65k+ affected records in the venue-at repo, seems these are `sg:` properties tough. List of ids here:  [at-encoding.csv.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/10700665/at-encoding.csv.txt)


The admin records can be updated in a PR, do we also want to fix these `sg:` properties in venue records?

**Comment by nvkelso** [comment]
If its easy to do both, then yes. But priority is the admin records.

**Comment by stepps00** [comment]
A [PR](https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/83) was merged to fix this in the admin repo.. since the affected properties in the venue records are `sg:` source properties, I've left them as-is for now.
