### ISSUE TITLE
DE Wrong supersede for Forchheim

### ISSUE THREAD

**Issue by arnesetzer** [whosonfirst-data/whosonfirst-data#2023]
The https://spelunker.whosonfirst.org/id/1343563669/ has been superseded by https://spelunker.whosonfirst.org/id/101827055/

That's incorrect since https://spelunker.whosonfirst.org/id/1343563669/ is a neighboorhod of https://spelunker.whosonfirst.org/id/101782067/ like https://spelunker.whosonfirst.org/id/1377794697/

The superseded object is a locality ~65km away (https://www.luftlinie.org/49.71854177664908,11.059277639817196/49.16119302261263,11.33282372567487) and they have nothing in common execpt the name.

**Comment by nvkelso** [comment]
@stepps00 can you take a look, please?

**Comment by stepps00** [comment]
Thanks @arnesetzer, agreed this supersedes link is incorrect. We've opened https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/82 to fix this issue.
