### ISSUE TITLE
Upton Park (420781657) in `admin-xy` repo, not `admin-gb`

### ISSUE THREAD

**Issue by tomtaylor** [whosonfirst-data/whosonfirst-data#2024]
This is probably one for @stepps00. Upton Park ([Spelunker](https://spelunker.whosonfirst.org/id/420781657/)) is a neighbourhood in London, but is in the `admin-xy` repo, instead of `admin-gb`. I'm not sure how this happened, but I think it should be moved?

**Comment by thisisaaronland** [comment]
It should be moved, yes. It happened during the "Great Admin Repo Migration" where things whose country could not be easily and automatically inferred where placed in the `-xy` repo:

https://whosonfirst.org/blog/2019/05/09/changes/

**Comment by stepps00** [comment]
Yeah, agree this record should be moved.. should be straightforward to move this single record.

I do think the majority of records in the `admin-xy` could be reviewed and rehoused.. probably worth PIP-ing these records against WOF country polygons to figure out which repo they belong in.

**Comment by tomtaylor** [comment]
I've got a PR to move this record, and others, over: https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/pull/86

**Comment by tomtaylor** [comment]
This has merged and is now resolved.
