### ISSUE TITLE
admin-de 101913427 data inconsistency

### ISSUE THREAD

**Issue by arnesetzer** [whosonfirst-data/whosonfirst-data#2028]
Hi
https://spelunker.whosonfirst.org/id/101913427/ https://github.com/whosonfirst-data/whosonfirst-data-admin-de/blob/master/data/101/913/427/101913427.geojson is quite weird.

The name suggests the city "Schärding" in austria https://de.wikipedia.org/wiki/Sch%C3%A4rding but this city is already coverd by https://spelunker.whosonfirst.org/id/1108836071/

The geometry suggests the neighboorhood "Vornbach", but this is coverd by https://spelunker.whosonfirst.org/id/1393612031/

The a0 record is austria, the a1 record is bavaria (which is clearly not a part of austria). 

I don't know what to do but since in any case the data is not quite right I think something should be done. 😅

**Comment by stepps00** [comment]
A few comments:

- The https://spelunker.whosonfirst.org/id/1108836071/ record looks ok as-is
- The geometry of [this record](https://spelunker.whosonfirst.org/id/101913427/) should be moved to [this record](https://spelunker.whosonfirst.org/id/1393612031/)
- [This record](https://spelunker.whosonfirst.org/id/101913427/) should be superseded into to [this record](https://spelunker.whosonfirst.org/id/1393612031/) and flagged as not current.

Looks like this boils down to some incorrect name<>geometry assignments from Quattroshapes, the source being used in the 101913427 record.
