### ISSUE TITLE
NYC neighborhood "Beekman" exhibiting irrational exuberance

### ISSUE THREAD

**Issue by meetar** [whosonfirst-data/whosonfirst-data#203]
https://whosonfirst.mapzen.com/spelunker/id/85869109/

Current area of this alleged neighborhood is mostly East River. If this neighborhood exists it is most likely the "Beekman Place" neighborhood surrounding Beekman Place, adjacent FDR between 49th and 51th, as per https://en.wikipedia.org/wiki/Beekman_Place.

**Comment by riordan** [comment]
![](http://static1.squarespace.com/static/50153ad624ac88637fa8be79/t/50290e8b24ac029f0fed9c24/1344867980348/beakman.jpeg)

**Comment by nvkelso** [comment]
Such a great show :)

**Comment by stepps00** [comment]
Linking Issue https://github.com/whosonfirst-data/whosonfirst-data/issues/384. This issue should be taken care of once we update all NYC neighbourhood records.

**Comment by nvkelso** [comment]
Forward dup of: https://github.com/whosonfirst-data/whosonfirst-data/issues/384
