### ISSUE TITLE
United States - Swedish preferred name

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2037]
The preferred name for the United States in Swedish is currently the abbreviation "USA".

Not 100% sure but I think the correct name is "Amerikas förenta stater"

<img width="237" alt="Screenshot 2023-03-26 at 23 10 49" src="https://user-images.githubusercontent.com/738069/227804823-72b60d7d-eb09-44b8-a850-9c9fad027850.png">

```bash
85633793|country|US|swe||||||colloquial|Amerikas Foerenta Stater|1617828565
85633793|country|US|swe||||||colloquial|Amerikas Forenta Stater|1617828565
85633793|country|US|swe||||||colloquial|Foerenta Staterna|1617828565
85633793|country|US|swe||||||colloquial|Forenta Staterna|1617828565
85633793|country|US|swe||||||colloquial|USA|1617828565
85633793|country|US|swe||||||preferred|USA|1617828565
85633793|country|US|swe||||||variant|Amerikas Förenta Stater|1617828565
85633793|country|US|swe||||||variant|Förenta Staterna|1617828565
```

**Comment by nvkelso** [comment]
That is odd. @stepps00 can you have a look? Probably Title Case the suggestion?

**Comment by stepps00** [comment]
Thanks @missinglink - just filed a PR to fix. Looks like this also impacts Norwegian and Danish, too.

https://www.wikidata.org/wiki/Q30
