### ISSUE TITLE
Retire and otherwise cleanup bunk WOF admin repos for non-existent country codes

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2084]
@missinglink and I were looking at the Geocode.Earth download page for WOF distributions [here](https://geocode.earth/data/whosonfirst/), which has a big grid of country codes:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/853051/233462062-79ad4391-0d9e-44f8-9f0b-06e059e58e26.png">

Some of the 2-character "country codes" aren't actually valid and have basically no data included. 

Digging into this more, this list is generated from the collection of active WOF admin repos. So research why we have these repos and consider retiring (deleting) them – after all content has been moved to a more appropriate repo.

One example is country code `AN`. if you attempt to download the file it will return a 404

> curl --head https://data.geocode.earth/wof/dist/shapefile/whosonfirst-data-admin-an-shapefiles.zip
> HTTP/2 404

This is because `AN` was for The Netherlands Antilles, which in ~ 2010 was divided into Bonaire, Saint Eustatius and Saba (BQ, BES, 535), Curaçao (CW, CUW, 531) and Sint Maarten (Dutch part) (SX, SXM, 534). But otherwise doesn't exist anymore.

There are some other cases, to investigate:

- `AN` – see above, retired, shouldn't have any contents
- `DN` - is unassigned, very odd
- `KO` – is a valid code – like maybe its reserved if North and South Korea ever reunite? but not right now, should be empty?
- `TU` – country code is unassigned, should be removed
- `UK` – country code is exceptionally reserved but unused (because of the name space collisions between United Kingdom and - Ukraine)

Others worth reviewing:

- `GP` – consider if this should be in `FR` instead since it's an overseas region of France? If so move items.
- `GF` – consider if this should be in `FR` instead since it's an overseas region of France? If so move items.
`SJ` – investigate
Ukraine), so should also be removed
- `UM` – country code is valid for United States Minor Outlying Islands... but investigate where it should go
- `UN` – country code is valid for the United Nations, and has some contents correctly
- `XK` – valid "custom" country code, since ISO doesn't do a Kosovo country code yet? 
- I'm not sure about some of these odd balls: `XN` , `XS`
- While XX , XY , XZ are all valid WOF "weird stuff here, disputed areas, etc" codes

**Comment by thisisaaronland** [comment]
`XN` are things "visiting" Null Island:

* https://github.com/whosonfirst/whosonfirst-placetypes#xn

`XS` is Somaliland

* https://github.com/whosonfirst/whosonfirst-placetypes#xs

It's probably worth making a `whosonfirst-countries` repo along the lines of `whosonfirst-properties` and `whosonfirst-sources` to document all of these and discuss the relationship (and differences) between `wof:country` and `iso:country`.

**Comment by nvkelso** [comment]
Looks like this is a duplicate of https://github.com/whosonfirst-data/whosonfirst-data/issues/1814.

I'll continue the conversation there...

Related: 

- https://github.com/whosonfirst-data/whosonfirst-data/issues/1460
