### ISSUE TITLE
Spain: Madrid and Barcelona should have localadmin records

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2130]
For a continous fabric, even if it's marked hiearchy_label = 0 and statistical gore...

<img width="804" alt="image" src="https://user-images.githubusercontent.com/853051/234475629-2c1977f3-296e-4efd-8877-0d62858df0ef.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/853051/234475820-3ffd6c61-650c-44a7-ad0a-b77c2f3f5ad7.png">

**Comment by stepps00** [comment]
I think this is expected - when localadmin were updated in Spain, the [Barcelona](https://spelunker.whosonfirst.org/id/101748323/) and [Madrid](https://spelunker.whosonfirst.org/id/101748283/) localities were both given a `wof:placetype_alt` of localadmin.

**Comment by nvkelso** [comment]
@missinglink when filtering the shapefile export by placetype, can you look at both placetype and placetype_alt?

**Comment by nvkelso** [comment]
Fixed via #2152 and related Pelias / Geocode.Earth work

<img width="897" alt="image" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/853051/beb02998-d93b-4737-96ba-454b1a5563da">

<img width="859" alt="image" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/853051/73bbfc97-34c6-4307-8b1c-25b21554a3e2">

<img width="875" alt="image" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/853051/238b6e8c-98cc-4366-9a98-d660d1ca544a">

While most of the features in that layer are still just `localadmin`:

<img width="878" alt="image" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/853051/9de2fe02-bc8d-4cdd-ba8e-df1736af15aa">

**Comment by nvkelso** [comment]
Thank you @missinglink!
