### ISSUE TITLE
Reclassify Carnegie Hill as a microhood

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#214]
https://whosonfirst.mapzen.com/spelunker/id/85869159/descendants/

And update all its descendants accordingly. Here we go...

**Comment by thisisaaronland** [comment]
Start with issue #215 because there are fewer descendents to update...

**Comment by stepps00** [comment]
Linking Issue https://github.com/whosonfirst-data/whosonfirst-data/issues/384. This issue should be taken care of once we update all NYC neighbourhood records.

**Comment by nvkelso** [comment]
Forward dup of #384, closing.
