### ISSUE TITLE
1495165801 supersedes and superseded by both deprecated and superseded 101751923

### ISSUE THREAD

**Issue by f4rk4sh** [whosonfirst-data/whosonfirst-data#2148]
1. Circular reference: `1495165801` supersedes and superseded by the same `101751923`.

https://spelunker.whosonfirst.org/id/1495165801/ :

```
this record has been superseded by: 101751923
this record supersedes: 101751923 
```

2. The superseder `101751923` is deprecated and superseded.

https://spelunker.whosonfirst.org/id/101751923/ :

```
this record has been both deprecated and superseded
```

**Comment by nvkelso** [comment]
Oops, that's odd. @stepps00 can you take a look, please?

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data-admin-no/commit/0aa7b558e0e1e9d00e5fb9813c0cd6cdcdcdb1dc

When the new `1495165801` record was created as part of this commit, the supersedes/superseded_by properties were set incorrectly. https://github.com/whosonfirst-data/whosonfirst-data-admin-no/pull/41 should fix the issue - @f4rk4sh mind taking a look?

**Comment by f4rk4sh** [comment]
@stepps00 Looks good. Thank you!
