### ISSUE TITLE
US: Watertown Town

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2150]
This locality has a preferred English label of "Watertown Town" when it should be "Watertown"

https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/859/503/35/85950335.geojson

**Comment by nvkelso** [comment]
Good catch!

I tried to use Write Field to edit the names but got some permission errors about making the PR 🙃

@stepps00 do you have better luck?

**Comment by stepps00** [comment]
Yep - names have been updated in https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/147, once that PR is merged this issue should be fixed.

**Comment by missinglink** [comment]
Thank you kind sir 🎩 💁‍♂️
