### ISSUE TITLE
Shapefile distro: placetype_alts are missing

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2152]
There are several thousand `locality` features in the United Kingdom that are also **wof:placetype_alt** of `localadmin`. For example: [Birmingham](https://spelunker.whosonfirst.org/id/101750467/) with **wof:id** = [101750467](https://spelunker.whosonfirst.org/id/101750467/).

When loading the Shapefile distribution these features should appear in BOTH the `localadmin` and the `locality` files. Instead they only appear in the `locality` file.

This Shapefile export bug also affects other countries, like in Spain for [Barcelona](https://spelunker.whosonfirst.org/id/101748323/) and [Madrid](https://spelunker.whosonfirst.org/id/101748283/) in https://github.com/whosonfirst-data/whosonfirst-data/issues/2130.

The fix is to evaluate both `wof:placetype` and `wof:placetype_alt` on export for any given "placetype" cut. This means that a single feature (with a single WOF ID) may appear in more than one "placetype" shapefile export file, and that's OK.

@missinglink can you take a look, please?

**Comment by missinglink** [comment]
This is resolved and the new shapefile distributions will be available in the next 12 hours or so.

Worth noting that while both `wof:placetype` & `wof:placetype_alt` are evaluated, only the *primary* placetype is exported.

Therefore you will find that a file named `whosonfirst-data-admin-gb-localadmin-polygon.shp` may now include values other than the string `"localadmin"` in the placetype field.

**Comment by nvkelso** [comment]
Woot! Verified for Madrid and Barcelona, and for Birmingham. Thanks @missinglink!

I'll file a new data quality issue as WOF is missing the right properties on a few more UK features...
