### ISSUE TITLE
Shapefile distro: add new calculated placelocal property

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2153]
Who's On First organizes itself using **placetype** enums, like `country`, `region`, `county`, `localadmin` and so on.... But those terms are (a) in English and (b) don't actually match what locals call those types of features. 

**Proposed psuedocode for new Shapefile `placelocal` property:**

- 1st prefer: `label:{wof:lang_x_official[0]}_x_preferred_placetype` where `{wof:lang_x_official[0]}` is the first element in `wof:lang_x_official` property array.
- 2nd fallback to: `label:eng_x_preferred_placetype`
- 3rd fallback to: `wof:placetype_local`

_NOTE: Shapefile DBF column names are limited to 10-characters in length thus the shorter property name._

**Further discussion:**

This is actually true even in the United States where WOF `region` are mostly `"state"`, sometimes `"commonwealth"`, and even `"district"` in legally and in day-to-day conversation! Some Who's On First end-users would like to query the database by these more friendly / colloquial terms to select the features that interest themselves. Since this is for "in-country" users, the name in their character set is more appropriate than a latinized variant (which WOF sometimes has available, see examples below). 

Who's On First bridges this gap with a common-optional _"placetype_local"_ property. Meaning it's a newer concept so it's on some WOF records but not all. Because of localization, we migrated to [label:{lang}_x_preferred_placetype](https://github.com/whosonfirst/whosonfirst-properties/blob/main/properties/label/%7Blang%7D_x_preferred_placetype.json) for this (from deprecated [wof:placetype_local](wof/placetype_local)). Sometimes one, or the other, or both are present on records.

**Definition of `label:{lang}_x_preferred_placetype`:**

> A feature's preferred placetype label (exclusive of place name and hierarchy), in practice a single element list. While wof:placetype was an enumerated value, this localized value is a string.

The complication is it's hard to know what the "local" `{lang}` language should be! This is the same problem we have with `wof:name` being preferred English or ASCII7, but then we don't know the "local" name for the place without an additional `wof:lang_x_official` lookup.

**Example features:**

- [California](https://spelunker.whosonfirst.org/id/85688637/), USA – which only has `wof:placetype_local` = `state`.
    - Expected `placelocal` value of `state`
- [Makkah](https://spelunker.whosonfirst.org/id/85676857/), Saudi Arabia – which only has `label{lang}_x_preferred_placetype` values, like:
    - `lang:ara_latn_x_preferred_placetype` = `muhafazah`
    - `lang:ara_x_preferred_placetype` =`مقاطعة`
    - `lang:eng_x_preferred_placetype` = `region`
    - Expected `placelocal` value of `مقاطعة`
- [Manchester](https://spelunker.whosonfirst.org/id/1360698893/), England, UK – which only has `wof:placetype_local` = `metropolitan borough`.
    - Expected `placelocal` value of `metropolitan borough`
- [Glasgow](https://spelunker.whosonfirst.org/id/1360698797/), Scotland, UK – which only has `wof:placetype_local` = `unitary district`
    - Expected `placelocal` value of `unitary district`
- [Madrid](https://spelunker.whosonfirst.org/id/85682783/), province in Spain – 
    - `label:eng_x_preferred_placetype` = `province`
    - `label:spa_x_preferred_placetype` = `provincia`
    - `wof:placetype_local` = `autonomous community` –– oops, this value in error and should be fixed in the data (property removed)
    - Expected `placelocal` value of `provincia`
- [Madrid](https://spelunker.whosonfirst.org/id/404227387/), autonomous community in Spain (parent of the province) – lacks any of these properties
    - Expected `placelocal` value of `` (empty string / NULL)

_NOTE: There will be separate work via data PRs under https://github.com/whosonfirst-data/whosonfirst-data/issues/2154 to improve the fill rate for these properties, at least for the top 50k to 100k features at the `country`, `macroregion`, `region`, `county`, and `localadmin` levels._

**Comment by nvkelso** [comment]
@missinglink Another Shapefile request for you, please

**Comment by missinglink** [comment]
resolved via the linked PR, the dist files will update around 19:00 CET

**Comment by nvkelso** [comment]
Verified in today's distro build, thanks @missinglink !

<img width="629" alt="image" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/853051/9d2acbaa-24c8-442c-91fd-29d23ed92fa9">
