### ISSUE TITLE
Improve fill rate for localized placetype label properties

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2154]
Paired with https://github.com/whosonfirst-data/whosonfirst-data/issues/2153 for Shapefile distribution, this issue focuses on auditing and adding more placetype local values on individual WOF records.

Who's On First organizes itself using **placetype** enums, like `country`, `macroregion`, `region`, `county`, `localadmin` and so on.... But those terms are (a) in English and (b) don't actually match what locals call those types of features. 

This is actually true even in the United States where WOF `region` are mostly `"state"`, sometimes `"commonwealth"`, and even `"district"` in legally and in day-to-day conversation! Some Who's On First end-users would like to query the database by these more friendly / colloquial terms to select the features that interest themselves. Since this is for "in-country" users, the name in their character set is more appropriate than a latinized variant (which WOF sometimes has available, see examples below). 

Who's On First bridges this gap with a common-optional _"placetype_local"_ property. Meaning it's a newer concept so it's on some WOF records but not all. Because of localization, we migrated to [label:{lang}_x_preferred_placetype](https://github.com/whosonfirst/whosonfirst-properties/blob/main/properties/label/%7Blang%7D_x_preferred_placetype.json) for this (from deprecated [wof:placetype_local](wof/placetype_local)). Sometimes one, or the other, or both are present on records.

**Definition of `label:{lang}_x_preferred_placetype`:**

> A feature's preferred placetype label (exclusive of place name and hierarchy), in practice a single element list. While wof:placetype was an enumerated value, this localized value is a string.

The goal of this issue is to make sure these properties are filled in for the most important WOF records at the coarser placetypes, in English and the local language.

**Example features:**

- [California](https://spelunker.whosonfirst.org/id/85688637/), USA – which only has `wof:placetype_local` = `state`.
    - Expected `placelocal` value of `state`
- [Makkah](https://spelunker.whosonfirst.org/id/85676857/), Saudi Arabia – which only has `label{lang}_x_preferred_placetype` values, like:
    - `lang:ara_latn_x_preferred_placetype` = `muhafazah`
    - `lang:ara_x_preferred_placetype` =`مقاطعة`
    - `lang:eng_x_preferred_placetype` = `region`
- [Manchester](https://spelunker.whosonfirst.org/id/1360698893/), England, UK – which only has `wof:placetype_local` = `metropolitan borough`.
- [Glasgow](https://spelunker.whosonfirst.org/id/1360698797/), Scotland, UK – which only has `wof:placetype_local` = `unitary district`
- [Madrid](https://spelunker.whosonfirst.org/id/85682783/), province in Spain – 
    - `label:eng_x_preferred_placetype` = `province`
    - `label:spa_x_preferred_placetype` = `provincia`
    - `wof:placetype_local` = `autonomous community` –– oops, this value in error and should be fixed in the data (property removed)
- [Madrid](https://spelunker.whosonfirst.org/id/404227387/), autonomous community in Spain (parent of the province) – lacks any of these properties

**Comment by nvkelso** [comment]
There has been some prior work in this area with the following two tables:

- https://github.com/whosonfirst/whosonfirst-cookbook/blob/main/definition/placetypes_by_country.md
- https://github.com/whosonfirst/whosonfirst-cookbook/blob/main/definition/placetype_counts_by_country.md

@stepps00 have you generated a similar table but for intended "placetype local" values by WOF `placetype`?

**Comment by missinglink** [comment]
resolved via the linked PR, the dist files will update around 19:00 GMT

**Comment by nvkelso** [comment]
Who's On First's openly licensed raw **Statoids** data includes localized placetypes for around ~50k features. While some of those were imported circa 2016, it looks like only 50% of the `county` Statoid properties were imported for unknown reasons. 

So 🤞 easy to fix – and can include Statoids review of `country`, `dependency`, `macroregion`, and `region` as well :)

Partly this is because we imported Statoids before we had a full set of `county` records in WOF via **Mesoshapes**. During the Mesoshapes imports circa [2016](https://whosonfirst.org/blog/2016/12/08/mesoshapes/) and [2017](https://whosonfirst.org/blog/2017/09/19/introducing-statoids/) we did add Statoids HASC IDs to most of these features. This should enable basic concordance ID data joins between the two datasets to import (a) Statoids properties including populations and (b) set "placetype local" labels.

In 2017 we wrote:

> As of today, Who’s On First has added properties for 256 top-level administrative entities (country and dependency records). Additionally, 3,811 primary administrative divisions were updated with new properties and concordances and 22,993 secondary administrative divisions were updated with new properties and concordances. Take a look at the new statoids:* properties and all the concordances we now have! Links to selected updated records at the country, region, and county placetypes are below.

The potential additional Statoids properties to import are:

```
src:population
statoids:area_km
statoids:area_mi
statoids:capital
statoids:country
statoids:as_of_date
statoids:hasc
statoids:name
statoids:population
statoids:statoid
statoids:timezone
statoids:type
wof:population
wof:population_rank
src:population
wof:placetype_local
various name:* properties
```

Notably Statoids only includes English placetype local labels, so a further solution will also be needed.

**Comment by nvkelso** [comment]
Summary of changes:

- +4.3k `wof:concordances["hasc:id"]` for statoids (increasing fill rate from 40% to 50%)
    - Most of these are in FR and BR
    - My guess is you could eek out another 1-3% with a lot of manual review of the names and Statoids tables, but...
    - Remaining nulls are almost all county placetypes in FR (when the name is set to NULL so ¡¿?!), BR because Statoids doesn't do that level, AM for same, AO for same, AT because new features and needed implosions, AU because new features?, TW because no Statoids at this level, PL, FI, IQ, JP, RU because new features?, PL because fussy level, CA because no Statoids at that level, KP and KR same, SE at that level, GB region because no Statoids at that level (ceremonial county), and smattering of others mostly because Statoids is older vintage by like 10 years now. 
- +1.7k `statoids:*` property sets from 27.6k (increasing fill rate from 59% to 63%)
    - This was mostly in Philippines and Belarus and Russia  where Martin had accidentally added a _ to the end of the Mesoshapes statoids concordance property and we didn't catch that in our earlier imports. :shrug: 
- +8.5k of 46.8k coarse admin `label:eng_x_placetype_local` backfilled (+23% from 81% to 100%)
    - 91% of all backfill placetype local were at the county level
    - I have partial research on other languages but that might need to wait for another day to keep this moving...
    - 1.6k of those change the current value of `label:eng_x_placetype_local` to a different value. This is almost exclusively in Russia (raion & etc versus always district before) and Sudan (district instead of county)
    - I also backfilled 2k new `name:eng_x_preferred` as it makes more logical sense to have them to construct the English label long names... and to fix a few non-English values, too; deal with " City" postfixes & etc
- +8k to 46.0k coarse admin `label:eng_x_preferred_longname` backfilled (+14% from 86% to 98%)
    - Includes 2k value changes
    - Excludes country and dependency placetypes (but placetype local is now set on them)
- I backfilled 383 `wof:population` values From Statoids, Natural Earth, and Wikidata
    - This improves fill rate for `country` and `dependency` in particular which should have ~ 100% fill rate now (~206 of 249)

**Still outstanding:**

- IN PROGRESS: I need to do the same operation as above for localadmin placetype
    - I'm limiting that to just a dozen countries that have polygons (many more have points)
- IN PROGRESS: Post script to the toolbox / cookbook repo

**Related:** 

- If a given country has polygons for a coarse child admin placetype, we should probably deprecate any Point geometries in that country at the same placetype? This deserves it's own issue and discussion...

**Comment by nvkelso** [comment]
See related PRs in the GH.com interface (above).

Thanks to @stepps00 for reviewing. I've made changes and should be good for merging...

**Comment by nvkelso** [comment]
All the coarse admin PRs have been merged. I'll followup with a dozen or so `localadmin` PRs next, then this issue can be closed.

**Comment by nvkelso** [comment]
I filed a followup for the Shapefile property calculation logic in https://github.com/pelias/wof/pull/48:

1. Sometimes the official language for a place is not in a latin character set, but WOF has (yet another) property that we can use to add a parenthetical so locales and non-locals can still read the value.
2. Sometimes there is no official language placetype translation, but there is an English preferred placetype. When that's available then backfill the exported property with the English value. 
    - NOTE: For the ~50k coarse admin places (country, dependency, macroregion, region, macrocounty, county) there is nearly 100% fill rate for `label:eng_x_preferred_placetype` because of recent WOF data work.

**Comment by nvkelso** [comment]
The `localadmin` data PRs have been merged, closing.
