### ISSUE TITLE
Missing Nottingham, MD 21236

### ISSUE THREAD

**Issue by dgearhart** [whosonfirst-data/whosonfirst-data#216]
Submitted issue against pelias (https://github.com/pelias/pelias/issues/269) because it was not returning the proper city - I came to WOF to verify if it is correct but I could not find Nottingham, MD here

USPS link shows Nottingham and Baltimore are valid for postal code=21236
https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=21236&zip=

Please add Nottingham, MD

Address in OSM to verify results:
http://www.openstreetmap.org/way/298505457

**Comment by nvkelso** [comment]
Thanks for the report! Nottingham is not an Incorporated or Census Designated Place, so we don't have a ready polygon for it from US Census, which Quattroshapes & Who's On First sourced US polygons from. 

What you're suggesting is WOF add "postal" cities, which we can and should do. That work is covered under https://github.com/whosonfirst/whosonfirst-data/issues/202.

Keeping this issue open until #202 is resolved.

**Comment by dgearhart** [comment]
thank you @nvkelso - yes, adding postal cities is what I am asking. Adding postal cities might fix pelias/pelias#184 too - where a truncated township name is returned instead of the postal city.
@trescube what do you think?

**Comment by talllguy** [comment]
Back when I worked for Baltimore County, the land of zero incorporated towns, we ran into this issue often. I once made a map of the CDPs and postal cities to help people find the right location. Hope this helps.

[BaCoCDP2000.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/409097/BaCoCDP2000.zip)
[OfficePubDef.pdf](https://github.com/whosonfirst-data/whosonfirst-data/files/409098/OfficePubDef.pdf)

**Comment by dgearhart** [comment]
Thanks @talllguy 
@nvkelso @thisisaaronland @dianashk any idea when we will have us postal cities returned in mapzen search? In Pennsylvania - it is very confusing to see a truncated township name instead of the postal city name

**Comment by talllguy** [comment]
Elsewhere in Baltimore County, I'm getting a watershed, (or something) returned as the locality name. I'd love to help out with Baltimore County admin shapes if I can in anyway! I also have some neighborhood association boundaries.
https://whosonfirst.mapzen.com/spelunker/id/85870083/#10/39.5468/-76.6171
![whosonfirst-spelunker-1470756177320](https://cloud.githubusercontent.com/assets/1827881/17522064/a3ad151c-5e23-11e6-99aa-f44e4f50fb1f.png)

**Comment by stepps00** [comment]
Noting here that WOF now has a Nottingham `locality` record: https://whosonfirst.mapzen.com/spelunker/id/1125996559/

**Comment by orangejulius** [comment]
This issue is fixed :) The Nottingham locality record looks correct and Pelias is correctly able to associate records with it
