### ISSUE TITLE
"Abu Dhabi International Airport (AUH) will officially be renamed Zayed International Airport." (2024-02)

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#2169]
https://onemileatatime.com/news/zayed-international-airport/

https://spelunker.whosonfirst.org/id/102558455/

**Comment by stepps00** [comment]
Fixed in https://github.com/whosonfirst-data/whosonfirst-data-admin-ae/commit/2f77e37774383cd8616ffc7b58ac6842901c5534
