### ISSUE TITLE
Append 'County' or 'Parish' to placetype=county records

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#217]
US counties in WOF are missing part of their names.  For example, Lancaster County is named only "Lancaster".  This is important for label generation in Pelias.  This is not just a description of the administrative type, it's actually part of the official name of these places.  I researched appending either 'County' or 'Parish' (for Louisiana) but it gets far more complicated than that:

- All counties in Louisiana should have 'Parish' appended
- Counties in Alaska are one of:
  - Borough (Denali Borough)
  - Census Area (Dillingham Census Area)
  - Municipality (Municipality of Anchorage)
  - City and Borough (City and Borough of Sitka)
- All other states should have 'County' appended with the exception of:
  - City of Baltimore (in Maryland, this is actually the county name.  there's still a Baltimore County and a city named Baltimore)
  - 38 Virginia counties that are called "independent cities" that should be prepended with "City of" (eg - City of Virginia Beach).  Note that there are 2 counties with the same name that are different: "City of Fairfax" and "Fairfax County".  

I noticed that `qs.a2_alt` contains the correct full name, at least for the records I spot-checked.  Algorithmically prepending/appending the correct prefix/suffix is very fraught with peril so would it be possible to modify the name in data?  Alternatively, would you recommend that we use `qs.a2_alt` during import?

**Comment by nvkelso** [comment]
I'm not excited about modifying the `name` of the feature to include it's full legal name. As you point out, the original Quattroshapes value in `qs.a2_alt` (and similar alts) is available in Who's On First for this. This was a deliberate design decision for Quattroshapes and for Who's On First. 

But I do agree we should consider elevating the QS name alts to a full `name:label` (proposed) property so you don't need to dip into the QS values there, useful for text based disambiguation (not an automatic process). But dipping into the QS alt value during this phase of integration should suffice?

Background: The same thing can be seen in Germany and Australia where the country or state a place is in will sometimes be `Placename (County)`. But the name of the feature is `Placename` and that's what should end up in the `name` property.

**Comment by thisisaaronland** [comment]
This feels like an easy way to kick the tires on things prefixed with `label:` ?

If the criteria is: in the `US`; is a `county`; use whatever is in `qs.a2_alt` then I can bang that out pretty quickly.

`label:legal` sounds both dumb and not intuitive. Suggestions?

**Comment by dianashk** [comment]
I would be ok with a new property and the name of it isn't a big deal. I'm curious how it would work with multiple languages, however. A place can have `name:ru` and `label:ru`? `label:legal` sounds strange. Maybe `label:default` is a good start? If we kept it under `name:label` it would be harder to namespace labels away from alt_names.

@thisisaaronland, the rule is that simple and is currently what @trescube has implemented as a workaround in our importers.

**Comment by thisisaaronland** [comment]
For labels and multiple languages, we would follow the same convention (BCP-47 w/ WOF-specific variants) that we do for names, described here:

https://github.com/whosonfirst/whosonfirst-names

Having said that in as much as as we have `wof:name` as the default name label we could just standardize on `wof:label`. The one consideration for Pelias to have a think about is that there is an open ticket to standardize all default names as 7-bit ASCII transliterated English (see below) so we'd want to do the same for `wof:label`.

@trescube - if you can send me a CSV file with labels and WOF IDs before I get around to implementing anything else then... uh, it will happen faster :-)

https://github.com/whosonfirst/whosonfirst-data/issues/183

**Comment by stepps00** [comment]
[This file](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20217/Issue217_USCountyUpdates_Import.csv) in our WOF S3 Dropbox contains new `wof:label` names and associated `wof:id` fields. The `wof:label` names were derived from the `qs:a2_alt` attribute field of each County record.

As mentioned above:
- All counties in Louisiana have `Parish` appended
- Counties in Alaska one of the following appended: `Borough`, `Census Area`, `Municipality`, `City and Borough`
- All other states have `County` appended with the exception of:
  - City of Baltimore
  - 38 Virginia counties that are called "independent cities" that should be prepended with `City of`.


**To all involved:** the csv file contains updates to 3,140 `county` records, though [the Spelunker shows the US with 3,128 dependent `county` records`](https://whosonfirst.mapzen.com/spelunker/id/85633793/descendants/?&placetype=county#8/17.916/-66.920). This discrepancy of 78 records comes from the `county` records in Puerto Rico. Do we also want a new `wof:label` field for the Puerto Rican records?

`County` records in Puerto Rico have a `qs_a2_loc` value similar to the record for [Hormigueros](https://whosonfirst.mapzen.com/spelunker/id/102080407/#13/18.1322/-67.1188) (`qs_a2_loc` field is `Hormigueros Municipio`). If we add a new `wof:label` field for Puerto Rican records, would we do the following?

`Hormigueros Municipio` -> `Municipio de Hormigueros`

**Comment by nvkelso** [comment]
@thisisaaronland Is `wof:label` localizable like names are?

The default `wof:name` and the `wof:label` should be in the same language. And since Spanish is spoken there I think it's okay to promote the `qs_a2_loc` value to the `wof:label` value. 

We could also add the longer English (`Hormigueros Municipio`) as a name variant.

**Comment by stepps00** [comment]
Per requirements for S3 files, [the .csv file](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%20217/Issue217_USCountyUpdates_Import.csv) in the S3 misc folder was updated to include the following fields:

* `wof:id`
* `wof:name`
* `wof:label` **(new field)**
* `wof:parent_id`
* `wof:country`
* `wof:placetype`

In addition, the records in Puerto Rico (those that have a `wof:country` of PR have a `name:spa_x_variant` field, per the suggestion above. 

@nvkelso - I don't see a `qs_a2_loc` field that has the correct `wof:label` information, but I do see that the `qs:a2_alt` field could be the `wof:label` value we need. If this is the case, I will swap out the `wof:label` values in the .csv file with the existing `qs:a2_alt` value.

**Comment by nvkelso** [comment]
Sounds good.

**Comment by nvkelso** [comment]
@stepps00 Can turn this into a PR, please?
