### ISSUE TITLE
Heath (Wales) incorrect hierarchy

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2170]
As reported in https://github.com/pelias/pelias/issues/962.

The Borough of Heath in Cardiff Wales has been given a hierarchy in England:
https://spelunker.whosonfirst.org/id/1360887587/

<img width="421" alt="Screenshot 2023-11-22 at 17 31 11" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/738069/33a8c8a8-a705-4b06-8c7a-bfb09af005f6">

**Comment by missinglink** [comment]
<img width="343" alt="Screenshot 2023-11-22 at 17 37 01" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/738069/ce232b37-fa7c-406d-bf4a-839e1e672965">

**Comment by stepps00** [comment]
This was fixed in https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/pull/92
