### ISSUE TITLE
GB: wof:concordances field type mismatch

### ISSUE THREAD

**Issue by wazazaby** [whosonfirst-data/whosonfirst-data#2175]
Hi!

There is a type mismatch for the GB geojson files for the field `wof:concordances`, usually it is an object (`{}`) but on some files it is represented as an (empty) array (`[]`).

Here are two examples using an object :
* https://github.com/whosonfirst-data/whosonfirst-data-admin-fo/blob/master/data/124/271/311/1/1242713111.geojson?short_path=415e820#L44
* https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/772/967/579/772967579.geojson?short_path=7d17061#L183
All of the files follow this typing.

And are two examples of the GB geojson using an array :
* https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/blob/master/data/188/076/205/1/1880762051.geojson?short_path=4b94f84#L233
* https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/blob/master/data/188/076/218/7/1880762187.geojson?short_path=8244c94#L161

Most file with this mismatch are under `data/188/076` for GB.

**Comment by wazazaby** [comment]
Happy to raise a PR if needed :)

**Comment by nvkelso** [comment]
A PR would be greatly appreciated, thanks! I have time to review this week but less time for authoring.

**Comment by nvkelso** [comment]
PR is merged, let's wait for a new distro and then verify and close this issue. 

FYI @missinglink as I think you noticed this, too?
