### ISSUE TITLE
Postalcode in Switzerland with bad hierarchy

### ISSUE THREAD

**Issue by slvlirnoff** [whosonfirst-data/whosonfirst-data#2177]
Hello everyone, I was investigating some strange results from Pelias for Switzerland. It appears that the postalcode dataset has been updated a rather long time ago ~2017

Since then, the admin database has been greatly improved in 2019.

As a result many postalcodes have a wrong locality/localadmin attached to their hierarchy. For instance 1815 (Clarens/Montreux) has "Lac Léman" as a direct parent, or 1020 Renens has Lausanne as direct parent.

From what I understood navigating the various repository and past issues, it seems that the hierarchy of the postalcodes should be updated (by running pip using the updated admin dataset?). Is there some documentation on how to do that and propose an update? Or would someone have an existing setup that would make this action relatively easy?

Please let me know what would be the best way forward to improve this point 🙂

**Comment by nvkelso** [comment]
Hi @slvlirnoff, thanks for your interest in WOF and great question about interaction between postalcode and admin data here. 

Do you think (a) the existing postalcode shapes and coverage is sufficient now but the hierarchy reverse geocoding needs to be improved (because it's out of synch with the newer WOF admin data), or (b) the postalcodes themselves need to be updated (and pre-PIP'd)?

PIPing is relatively straight forward for Stephen to jump on, but he's busy the next few weeks with limited connectivity, so I'm answering here now to keep things moving.

For PIPing things yourself it's mostly a matter of doing the point-in-polygon work which can be done with WOF tools or normal GIS tools, and then recorded into the wof admin hierarchy properties on the records.

**Comment by slvlirnoff** [comment]
Hello @nvkelso thanks a lot for your answer. Yes the postalcodes geometry looks good enough. Potentially it could be updated but I don't think it changed significantly since the last importation. However for a) the hierarchy seems out of date and indeed needs to be synchronized with the new admin data.

Some examples:
- https://spelunker.whosonfirst.org/id/538930673/

Or here: all these postalcodes descendants of the lake https://spelunker.whosonfirst.org/id/404567693/descendants/?exclude=nullisland
Like this one:
https://spelunker.whosonfirst.org/id/538931777/

Doing a pip request for the centroid of these postalcodes seems to return the right admin info.

Potentially venues and also neighbourhood/lower administrative levels could be updated too: c.f. https://spelunker.whosonfirst.org/id/85800439/


For the pip update, running the service is likely fine. I'm running pelias/spatial on the side and it should be pretty similar I guess. However, are there any tools/scripts that go through all features in a collection and iteratively update them? Also are there any tools to help review the changes? If Stephen isn't available, I'm happy to give it a go :-) but I was a bit lost with all the wof repositories.

**Comment by slvlirnoff** [comment]
@nvkelso sorry to bump this, do you have any pointers on tools/scripts for mass piping?

**Comment by slvlirnoff** [comment]
@stepps00 I see that you are potentially back, could you potentially input on this? 🙃

**Comment by nvkelso** [comment]
Hey @slvlirnoff thanks for your patience while @stepps00 gets back to you.

In the meantime, @thisisaaronland wrote a blog post about using PMTiles to do the PIP:

- https://millsfield.sfomuseum.org/blog/2022/12/19/pmtiles-pip/

Is there enough in the blog post for you to get started?

**Comment by jmporchet** [comment]
Hello @stepps00 
This would be super helpful for us as we're using it for a mobile application.
Any way we could help move this forward somehow?

**Comment by stepps00** [comment]
Hey @slvlirnoff and @jmporchet - we wrote [this doc](https://github.com/whosonfirst/whosonfirst-cookbook/blob/main/how_to/setting_up_pip_service.md) a few years ago, which lists the steps you can take to set up a PIP machine locally using existing Python tools. There are newer PIP tools written in Go (I believe they're [here](https://github.com/whosonfirst/go-whosonfirst-spatial)), and additional pointers in the SFO Museum blogpost above.

IMO the simplest solution would be to run each of the postalcodes against parent admin features using the PIP tools, and open a PR in the `whosonfirst-data-postalcode-ch` repository with the hierarchy changes. Would you like to take a shot at setting up those tools and opening a PR?
