### ISSUE TITLE
Investigate official Australian boundary data

### ISSUE THREAD

**Issue by riordan** [whosonfirst-data/whosonfirst-data#218]
- [x] postcode
- [x] region (in PR)
- [ ] localadmin
- [ ] locality
- [ ] neighbourhood (wards), is this usable?
- [ ] constituency

Feb 26 2016

https://www.psma.com.au/publications/news/psma-responds-australian-governments-release-g-naf-public

**Comment by stepps00** [comment]
[Link](http://data.gov.au/dataset/psma-administrative-boundaries) to administrative data (CC BY 4.0)

**Comment by rowanwins** [comment]
Let me know if you require any local input into deciphering these datasets @stepps00

**Comment by stepps00** [comment]
**Notes, per placetype:**

Who's On First | PSMA | Note 
---|---|---
country | country | No action. No work to do at this placetype.
region | state boundaries | No action. In PR.
county |  local government areas | Update WOF features with newer 2016 data.
localadmin | N/A | Data available from ABS.
locality | locality | Only a portion of this PSMA data is in WOF. Check placetype, supersede work likely.
neighbourhood | N/A | Find data.
postalcode | postalcode | No action. Imported.
constituency | electoral district | Create new constituency records with electorcal district data.

**Comment by nvkelso** [comment]
Let's look at this one together, sooner or later.

**Comment by stepps00** [comment]
@stepps00 - Find names for all features that have a proposed placetype change. 
@nvkelso - Double check the approach is correct.

**Comment by stepps00** [comment]
**Related:**
```
aus_adm0.shp:
    ogr2ogr -overwrite -f "ESRI Shapefile" -lco ENCODING="UTF-8" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'adm0' as qs_level, 'Australia Census' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0 FROM TR_2012_AUST" aus_adm0.shp ../nma/australia/1270055003_tr_2012_aust_shape/TR_2012_AUST.shp

    #dissolve-shapes.py -i aus_adm0.shp -o aus_adm0.shp -f qs_adm0_a3,qs_adm0,qs_level,qs_a0
    
aus_adm1.shp:
    ogr2ogr -overwrite -f "ESRI Shapefile" -lco ENCODING="UTF-8" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'adm1' as qs_level, 'Australia Census' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0, ste_name11 as qs_a1, ste_code11 as qs_a1_lc FROM TR_2012_AUST" aus_adm1.shp ../nma/australia/1270055003_tr_2012_aust_shape/TR_2012_AUST.shp

    #dissolve-shapes.py -i aus_adm1.shp -o aus_adm1.shp -f qs_adm0_a3,qs_adm0,qs_level,qs_a0,qs_a1,qs_a1_lc

aus_adm2.shp:
    ogr2ogr -overwrite -f "ESRI Shapefile" -lco ENCODING="UTF-8" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'adm2' as qs_level, 'Australia Census' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0, lga_name12 as qs_a2, lga_code12 as qs_a2_lc, ste_code11 as qs_a1_lc, ste_name11 as qs_a1 FROM LGA_2012_AUST" -t_srs "+proj=longlat +datum=WGS84 +no_defs" -s_srs EPSG:4283 aus_adm2.shp ../nma/australia/1270055003_lga_2012_aust_shape/LGA_2012_AUST.shp

    #dissolve-shapes.py -i aus_adm2.shp -o aus_adm2.shp -f qs_adm0_a3,qs_adm0,qs_level,qs_a0,qs_a1,qs_a1_lc,qs_a2,qs_a2_lc

aus_localadmin.shp:
    ogr2ogr -overwrite -f "ESRI Shapefile" -lco ENCODING="UTF-8" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'localadmin' as qs_level, 'Australian Bureau Of Statistics' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0, SSC_NAME as qs_la, SSC_CODE as qs_la_lc, STATE_CODE as qs_a1_lc, STATE_NAME as qs_a1 FROM SSC_2011_AUST" -t_srs "+proj=longlat +datum=WGS84 +no_defs" -s_srs EPSG:4019 aus_localadmin.shp ../nma/australia/2011_SSC_shape/SSC_2011_AUST.shp

aus_localities.shp:
    ogr2ogr -overwrite -f "ESRI Shapefile" -lco ENCODING="UTF-8" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'locality1' as qs_level, 'Australian Bureau Of Statistics: state suburbs file selection' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0, state_code as qs_a1_lc, state_name as qs_a1, ssc_name as qs_la, ssc_code as qs_la_lc, name as qs_loc FROM SSC_2011_AUST_custom WHERE locality IN (1,2,3)" -t_srs "+proj=longlat +datum=WGS84 +no_defs" -s_srs EPSG:4019 aus_localities.shp ../nma/australia/2011_SSC_shape/SSC_2011_AUST_custom.shp
    ogr2ogr -append -f "ESRI Shapefile" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'locality1' as qs_level, 'Australian Bureau Of Statistics: state suburbs file with customization' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0, state_code as qs_a1_lc, state_name as qs_a1, ssc_name as qs_la, ssc_code as qs_la_lc, name as qs_loc FROM SSC_2011_AUST_custom_union_splits WHERE locality_1 IN (10)" -t_srs "+proj=longlat +datum=WGS84 +no_defs" -s_srs EPSG:4019 aus_localities.shp ../nma/australia/2011_SSC_shape/SSC_2011_AUST_custom_union_splits.shp
    ogr2ogr -append -f "ESRI Shapefile" -sql "SELECT 'AUS' as qs_adm0_a3, 'Australia' as qs_adm0, 'locality1' as qs_level, 'Australian Bureau Of Statistics: urban areas and localities selection' as qs_source, 'AU' as qs_iso_cc, 'Australia' as qs_a0, name as qs_loc, ucl_code as qs_loc_lc, adm1_lc as qs_a1_lc, adm1 as qs_a1 FROM UCL06aAUST_region_custom_join WHERE locality IN (1)" -t_srs "+proj=longlat +datum=WGS84 +no_defs" -s_srs EPSG:4019 aus_localities.shp ../nma/australia/2006_UCL_AUST_ESRI_Shapefile/UCL06aAUST_region_custom_join.shp
```

See: https://github.com/foursquare/quattroshapes/blob/master/open_administrative_data/Makefile

**Comment by nvkelso** [comment]
It looks like [Statoids](http://www.statoids.com/yau.html) considers the LGA level the adm2 level (and calls them `shires` – but in practice those seem more akin to the `localadmin` placetype in Who's On First, but locals seem to expect (requires verification) LGAs as WOF `locality`, and the AUS-PSMA's `locality` as WOF  `neighbourhood`. Same words, such different meeting. So muddled.

**Comment by nvkelso** [comment]
@rowanwins can you verify if the proposal in https://github.com/whosonfirst-data/whosonfirst-data/issues/218#issuecomment-288513846 matches your expectations for how this data should be (re)-imported into Who's On First, please?

To summarize from that chart: 

- Change placetype on existing WOF `county` records to `locality` (2012 data, we could also update to 2016), and 
- Remove existing WOF `locality` records completely, they were a customized version of a 2011 `SSC_2011_AUST.shp` file via Quattroshapes. Do you have experience with that `SSC` source and it's customizations?
- Import AUS-PSMA `locality` as WOF `neighbourhood` (reduplicating with existing WOF neighbourhood records).

This seems a little weird to me as an outsider being more used to United States admin hierarchy:

- To not have `county` level at all,
- Out-of-sync with rest of WOF where LGAs are usually imported as WOF `localadmin`.
- Are there never more than one "city" inside an LGA?
- Are "urban" localities "neighbourhoods" and "rural" localities actually localities?
- What do locals use in practice when talking about where they live, and sending postal mail to one another?

**Comment by rowanwins** [comment]
Gday @nvkelso and @stepps00 

Thanks for reaching out. Below are a some comments and examples that hopefully provide input into most of your questions

- Australia has 3 tiers of government being federal (captured in `country`), state (captured in `region`) and local 
  - Local Government Areas appear to be captured in `county` at the moment. No-one really uses the term 'county' in Australia and I think these would best be moved in `localadmin` as they are the lowest recognised administrative boundary (eg you pay rates to your local government and they have elections)
    - For example [Blackburn](https://whosonfirst.mapzen.com/spelunker/id/101932611/#14/-37.8215/145.1520) (which is what we'd call a suburb) is in the local government area called the 'City of Whitehorse' (which is listed as the `county`)
    - A similar example is found with [Albury](https://whosonfirst.mapzen.com/spelunker/id/101929375/#14/-36.0735/146.9167), which is a suburb that falls in the 'City of Albury'

- In regards to a `county` level I don't think there is anything consistent across Australia.
    - For example 'Blackburn' listed above could possibly be part of a `county` called the 'Eastern Suburbs', but the 'Eastern Suburbs' is just a generic description for anything in the eastern suburbs of Melbourne, it doesn't have a clearly defined boundary.
   - In some areas however there are more clearly defined areas that could align to something like `county`. For example the suburb/`locality` [Wanniassa](https://whosonfirst.mapzen.com/spelunker/id/101938911/#14/-35.3974/149.0893) is part of a greater area called ['Tuggeranong'](https://whosonfirst.mapzen.com/spelunker/id/85771243/#14/-35.4114/149.0605) (a better map is found on [wikipedia](https://en.wikipedia.org/wiki/Tuggeranong) as well as a rationale for the boundary which most people would be unaware of)
   - I can't think of a national dataset that would provide this in a consistent manner.

- In regards to `locality` I think you've got it right, in Australia we'd call these 'suburbs'.
    - These are where most people would align themselves to living at the level above street 
    - I wouldn't reassign these to `neighbourhood` as they are generally quite large areas and the term 'suburb' is used pretty consistently across metro and regional australia
       - Speaking of which, in a couple of places there might be a concept of a smaller scale `neighbourhood`, but again it's not consistent, it would typically be a grouping of a couple of streets with no formal boundary but some locals might it.


If asked to describe where they live 90% of aussies would say something like 
Dean St (referring to the street), Albury (referring to the suburb/`locality`), NSW (referring to the `region`)
People wouldn't describe the place they live using the `localadmin` boundary although most of them would know it.

Occasionally someone might include a `county` type descriptor like 'Tuggeranong` or the `Eastern Suburbs`, this might be used in conversation if you were trying to give people a general location if the weren't familiar with the suburb/`locality`

Hopefully that helps, let me know if I can clarify anything

**Comment by nvkelso** [comment]
Another Australian wrote in:

> It is tricky, I agree. And I can't understand everything in the links you sent since I'm not in the loop with WOF.

> As you've noticed, many of the Local Govt Areas in urban areas are called "cities". But they're not really separate cities. They're just administrative areas. So
Boston:Newton as Melbourne:Boroondarra.

> But what people talk about is their locality, e.g. Kew and Hawthorn. It helps, at least for me, to understand the history. Kew and Hawthorn (where Nick Cave grew up) used to be their own towns. Then in the 1990s the Victorian premier (akin to governor) "amalgamated the councils" so now our garbage gets collected by the City of Boroondarra. https://en.m.wikipedia.org/wiki/Local_government_in_Victoria

> We don't have counties. We have only local/state/federal. 

> In country areas the Local Government Areas are called Shires, but again, no none talks about these issues unless they're worried about why their rubbish hasn't been collected or why their planning application hasn't been approved. At the moment I'm writing to you from Olinda, a village that's been around for yonks but that is now part of the Shire of Yarra Ranges. 

> I find that google maps captures it well. Search on Boroondarra and Kew and you'll see how they relate in size. And of course they're both part of metro Melbourne.

**Comment by nvkelso** [comment]
Related name changes in **Australia** for `county` and `localadmin`:

- https://github.com/whosonfirst-data/whosonfirst-data/pull/1140
- https://github.com/whosonfirst-data/whosonfirst-data/pull/1141

**Comment by missinglink** [comment]
We had a request today via Pelias for better coverage of `Hamilton Island` in Queensland.

I see that WOF added a point geometry for it recently in [1343393995](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/134/339/399/5/1343393995.geojson).

It should be possible to bring in some actual geometries for these islands from the PSMA dataset, the `Hamilton Island` geom is in
`2016 Urban Centre and Locality - Section of State - Significant Urban Area MAY 2018/standard/QLD_UCL_2016_POLYGON_shp.shp`

...with additional data in:
`2016 Urban Centre and Locality - Section of State - Significant Urban Area MAY 2018/standard/QLD_UCL_2016_POLYGON_shp.shx`

<img width="553" alt="screenshot 2019-02-05 at 16 37 10" src="https://user-images.githubusercontent.com/738069/52252130-83babd80-2965-11e9-9a81-477b91977b2e.png">

bringing in the whole dataset sounds like a lot of work, is there any plan to tackle PSMA in 2019?

**Comment by NickStallman** [comment]
I'm happy to assist with this task. I have prior experience with the PSMA datasets. I also need to do a bunch of conflating work anyway especially to wikidata, Wikipedia and OSM.

The approach I'll be taking is to make a script to compare the various datasets and automatically match up each datasets ids. Anything that isn't matched can then be dumped in to a separate list to either be created or to manually match.

When I'm done I'm happy to share the lists and modified geojson files to contribute back.

**Comment by stepps00** [comment]
Thanks for the notes, @missinglink. This is a task we're hoping to tackle in the next month.

There are a few issues to deal with when updating the Australia records, the biggest being the current placetypes not representing the places they should. The country and region records are correctly classified, but the county, localadmin, and locality placetypes need tweaking. 
[This comment](https://github.com/whosonfirst-data/whosonfirst-data/issues/218#issuecomment-288513846) tries to map the existing placetypes to what they _should_ be, using the PSMA data.

@NickStallman - we're more than happy with any contributions. The branch to fix this will include superseding work with new records, but the GeoJSON file(s) and match work that you'd provide would help with that.

I'll probably circle back to this issue at the end of this week/early next week and update with progress.

**Comment by rowanwins** [comment]
Hi @stepps00 & @missinglink

I now work at PSMA so feel free to hit me up for anything if you need a sanity check.

Cheers

**Comment by NickStallman** [comment]
I've completed comparing the ABS 2016 dataset to WOF.
[abs_wof.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/2863435/abs_wof.zip)

The matches spreadsheet has the following headings:
ABS SSC ID, ABS Name, Cleaned Name, WOF ID, WOF Name
5833 were successfully matched

The suburbs which didn't match sheet has the following headings:
ABS SSC ID, ABS Name, Cleaned Name, WOF Polygons that overlap the ABS polygon
9448 couldn't be matched.

A few notes:
1. Comparison is done by finding all WOF locality polygons which intersect the ABS polygon, then comparing cleaned names.
2. Both WOF and the ABS dataset have brackets in some names, I believe these are present when there are duplicate names in the same state to disambiguate them, however these should be eliminated from the WOF database, hence the Cleaned Name column. All comparisons were made excluding bracketed portions of names.
3. I haven't checked how many WOF localities in Australia exist that weren't matched. I'll do this over the next couple of days. There were a lot of ABS suburbs that were not matched so it'll be curious to see how many WOF localtities are also not matched.
4. We probably need a concordances ID for the ABS IDs. Something like "AU:ABS2016" would be suitable (each Census every 4 - 5 years brings a new dataset). The IDs are useful and Wikidata does use these IDs as well so they are reasonably standard and stable (2011 IDs are still available).
5. These matched ones can probably be put to the side now and further analysis performed on the missed suburbs and how to best deal with them. Is the overall goal to use these polygons as the authoriative polygons and discard all the old ones? If so how do we start doing that for the matches?
6. There are a ton of misses which never hit another locality polygon. I might need to see if they are miscategoried as localadmin or are on other layers. I think it's safe to say that every suburb should be a locality in WOF?

By the way @rowanwins there is a disucssion in https://github.com/pelias/pelias/issues/777#issuecomment-463448719 about postcodes/localities and the hierarchy in Australia. It would be interesting if PSMA has any further insight how suburbs belong to a postcode in Australia.

**Comment by nvkelso** [comment]
Nice analysis @NickStallman, thanks!

I wonder about rerunning the analysis agains the `localadmin` placetype in Australia? I think that should have better match rate... /cc @stepps00.

**Comment by NickStallman** [comment]
I did think of that. :) Here are the results. By the way I continued it for county but got zero matches.
[data.zip](https://github.com/whosonfirst-data/whosonfirst-data/files/2868592/data.zip)
WOF Locality - 5833
WOF LocalAdmin - 2061
WOF Unmatched - 7386

Still approx 50% of localities aren't getting matched. I think I'll need to do some spot checks to see if I can figure out why, whether data is missing, is wrong or if something has gone haywire.

**Comment by nvkelso** [comment]
> Both WOF and the ABS dataset have brackets in some names, I believe these are present when there are duplicate names in the same state to disambiguate them, however these should be eliminated from the WOF database, hence the Cleaned Name column. All comparisons were made excluding bracketed portions of names. 

Fixed in https://github.com/whosonfirst-data/whosonfirst-data/pull/1483/commits/14a57e295e8a9291ff7021fb94f7e564616085e6.
