### ISSUE TITLE
UK town of Aldershot is missing

### ISSUE THREAD

**Issue by tomtaylor** [whosonfirst-data/whosonfirst-data#2180]
The UK town of Aldershot, in Hampshire, is missing: https://en.wikipedia.org/wiki/Aldershot

**Comment by stepps00** [comment]
Going to close this one out as a duplicate of https://github.com/whosonfirst-data/whosonfirst-data/issues/1760.

The record for Aldershot was marked with `"mz:is_current":0` back in 2019, my guess is this was done in error but will need to review coverage in the area..
