### ISSUE TITLE
SIMB Bangalore

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2189]
Record [locality:890500991](https://spelunker.whosonfirst.org/id/890500991/) labelled `SIMB Bangalore` seems to refer to [Symbiosis Institute of Business Management Bengaluru](https://www.sibmbengaluru.edu.in/) but is classified as a `locality`.

Is it possible that maybe the acronym `SIMB` refers to something else?

<img width="506" alt="Screenshot 2024-04-19 at 12 45 36" src="https://github.com/whosonfirst-data/whosonfirst-data/assets/738069/6a05f29e-2fbe-4987-9037-8d2f2d5ae490">

**Comment by stepps00** [comment]
Agreed.. this SIMB Bangalore record comes from GeoNames, specifically this record: https://www.geonames.org/6957410/sibm-bangalore.html, which is a college. It now has a "spot, building, farm" code, and is not a populated place. The record could be superseded into a new campus record to fix.

Longer term, it would be helpful to refresh GeoNames data using a more recent version of the dataset.. I'm sure there are other cases like this that could be caught.
