### ISSUE TITLE
Albacete ES

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2198]
It looks like the labels "Araba / Álava" don't belong on the record for "Albacete", they are causing confusion with Alava in Basque Country

- https://spelunker.whosonfirst.org/id/85682615
- https://www.geonames.org/3130717/araba-alava.html

**Comment by nvkelso** [comment]
The WOF record [85682615](https://spelunker.whosonfirst.org/id/85682615) appers to be `Araba / Álava` but confusingly also includes many name variants for `Albacete`. Those should be removed / adjusted.

The IRL record [85682621](https://spelunker.whosonfirst.org/id/85682621) for `Albacete` appears to be fine as-is (no change needed).

**Comment by nvkelso** [comment]
Fixed via https://github.com/whosonfirst-data/whosonfirst-data-admin-es/pull/42.
