### ISSUE TITLE
Add alternate geometries for Null Island

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#2199]
Per this:

* https://stamen.com/the-many-lives-of-null-island/

Data files:

* https://stamen.github.io/null-island/data/null-island-nixta.geojson
* https://stamen.github.io/null-island/data/null-island-natural-earth-v4.geojson
* https://stamen.github.io/null-island/data/null-island-original.geojson
* https://stamen.github.io/null-island/data/null-island-natural-earth-v1.geojson

TBD: Are we already using one of those geometries as the current consensus geometry? Paging @nvkelso

**Comment by nvkelso** [comment]
Super fun blog post :)

WOF currently uses the `null-island-original` for the default consensus geometry on `wof:id` = [1](https://spelunker.whosonfirst.org/id/1):

<img width="1319" alt="image" src="https://github.com/user-attachments/assets/bfb95ac9-9ff0-4da5-89f0-a6c25ee5e1e3">

**Comment by nvkelso** [comment]
Fixed via https://github.com/whosonfirst-data/whosonfirst-data-admin-xn/pull/10.
