### ISSUE TITLE
Consider removing Japanese city postfix in English localization (also Korea?)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2207]
These `-shi` name postfixes are probably not necessary in English, and can cause name based data joins to fail (though should be preserved as name variants).

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/d932198e-a990-4e9e-befb-9205dd62fdd3">

**Comment by nvkelso** [comment]
For example, Sendai-shi https://spelunker.whosonfirst.org/id/102031919

**Comment by nvkelso** [comment]
@stepps00 The variant I see in South Korea is `-si` like [Gangneung-Si](https://spelunker.whosonfirst.org/id/102026435) and sometimes `-gun` like [Ganghwa-gun](https://spelunker.whosonfirst.org/id/102026437) (sometimes without the hypen like ` gun` in [102026269](https://spelunker.whosonfirst.org/id/102026269) and then there are the funny ` County` ones like [102026433](https://spelunker.whosonfirst.org/id/102026433). 

In North Korea I see a variant like `-ŭp` see [Yonggang-ŭp](https://spelunker.whosonfirst.org/id/890428931) and `-ni` like [421182723](https://spelunker.whosonfirst.org/id/421182723) and `-tong` like [890416363](https://spelunker.whosonfirst.org/id/890416363) and ` County` (which is a up) like [890444171](https://spelunker.whosonfirst.org/id/890444171).

NOTE: The postfixes are sometimes Titlecase and sometimes lowercase, for example `-si` (instead of `-Si`) like [102026299](https://spelunker.whosonfirst.org/id/102026299).

There are plenty of ` City`, ` County`, and ` District` postfixes to strip in mainland China and Taiwan, too. 

In (almost?) all of these, we have a parent admin for the place of the same name. Reviewing them heads up the locality features are on the main population center of that same name. So it's our convention to remove the placetype postfix except in rare circumstances. It's better to move these all to variant, and strip the default English names. They can be added back case-by-case if needed.

<img width="792" alt="image" src="https://github.com/user-attachments/assets/1361e140-467f-4d2a-a1c9-56ded067a241">

<img width="952" alt="image" src="https://github.com/user-attachments/assets/4efa1556-3cf1-4ca7-a2f6-8c95c23f6a1e">

**Comment by stepps00** [comment]
Reopening.. I think the linked pull request closed this automatically.

Fixes for the other examples should be straightforward. I'll crawl repos of N Korea, S Korea, Japan, China, and Taiwan for postfixes and tie a few pull requests to this issue. There were a few other postfixes in Japan, too, not just `-shi` - any thoughts on additional work in Japan here?

**Comment by nathaniel-kelso-ai** [comment]
Good question re Japan postfixes. Do you have any you'd like to nominate?

**Comment by thisisaaronland** [comment]
So I want to know what `https://github.com/nathaniel-kelso-ai` is?

**Comment by nvkelso** [comment]
Oops! My alter ego day job account (last two chars are company name abbreviated).

**Comment by stepps00** [comment]
So I crawled the repos for Taiwan, Japan, N Korea, S Korea, and China to find similar cases to the examples you shared and came up with this list, per repo:

```
tw: ['City', 'kung', 'District']
jp: ['Tokyo', 'ku', 'ōsaka', 'Naka', 'alps', 'onji', 'oshima', 'takata', 'yo', 'ei', 'onsen', 'mura', 'chō', 'machi', 'rinkan', 'son', 'renjaku']
cn: ['La', 'County', 'City', 'La Xian']
kp: ['bukto', 'namdo', 'do', 'City', 'dong', 'si', 'ŭp']
kr: ['neung', 'ri', 'myeon', 'eup', 'dong', 'myŏn', 'gu', 'ŭp', 'gun', 'si', 'City']
```

These are a mix of postfixes (dong, gun, si) and placetypes (city, district, county), and many seem to be false positives. I think I'd suggest name updates for the following:

- " City" (except in Taiwan)
- " District" (except in Taiwan)
- " County" (except in Taiwan)
- "-si" and " si"
- "-gun" and " gun"
- "-son" and " son"
- "-machi" and " machi"
- "-ŭp" and " ŭp"
- "-do" and " do"
- "-mura" and " mura"
- "-chō" and " chō"
- "-ni" and " ni"
- "-tong" and " tong"
- "-gu" and " gu"
- "namdo" (replace with "North")
- "bukto" (replace with "South")

In Korean, "dong" refers to essentially a neighbourhood, but I don't see references to these place names without "-dong" included. So I'm inclined to keep those as-is.

Between Korean `wof:name` values, mismatching `wof:name` and English name values, and various spacing/dashes, and keeping label properties consistent, the logic behind some of these name swaps will be a little tricky, but I can create branches if this list looks okay.

**Comment by nvkelso** [comment]
Sounds like a good plan. As long as it's better than yesterday and we store the variants then edit forward.

**Comment by stepps00** [comment]
@nvkelso the five pull requests above should take care of each of the cases outlined in this issue but if you see other postfixes that need to be reviewed I can take a look before merging.

**Comment by nvkelso** [comment]
Looks good to me, thanks!
