### ISSUE TITLE
Košice-okolie county has wrong name in sk 

### ISSUE THREAD

**Issue by andreicibotaru** [whosonfirst-data/whosonfirst-data#2211]
Issue description
Seems Košice-okolie county has a wrong name assigned in sk and some other languages as well.
The name is Peder which corresponds to a city belonging to the county, but somehow ended up as a preffered name for the county.

How to reproduce
We just noticed the inconsitency by chance.

Possible Solution/Data Source
Judging from what we've seen in spelunker I'd suggest changing Peder to Košice-okolie for the preferred name.
[Peder city](https://spelunker.whosonfirst.org/id/1259991217/)
[Košice-okolie](https://spelunker.whosonfirst.org/id/102080557/)
Please file any admin data related issues in our primary data repository:
https://github.com/whosonfirst-data/whosonfirst-data/issues/new.

###License of Proposed Data Source
N/A

###Related Issues
N/A

Posted issue on [whosonfirst-data-admin-sk](https://github.com/whosonfirst-data/whosonfirst-data-admin-sk) as well.
https://github.com/whosonfirst-data/whosonfirst-data-admin-sk/issues/18

Let me know if Im missing anything.

Thanks,

**Comment by nvkelso** [comment]
Resolved via https://github.com/whosonfirst-data/whosonfirst-data-admin-sk/pull/21. 

Will be live in distributions sometime in the next 6 hours.
