### ISSUE TITLE
San Diego County (Venezuela) has wikidata concordance to San Diego (United States)

### ISSUE THREAD

**Issue by happyleavesaoc** [whosonfirst-data/whosonfirst-data#2214]
https://spelunker.whosonfirst.org/id/421180477

Currently: [Q16552](https://www.wikidata.org/wiki/Q16552)
Should be: [Q2071710](https://www.wikidata.org/wiki/Q2071710)

**Comment by nvkelso** [comment]
Fixed via https://github.com/whosonfirst-data/whosonfirst-data-admin-ve/pull/18 using Write Field web editor.

Thanks for the report!
