### ISSUE TITLE
San Francisco (Cebu, Philippines) and San Francisco (Lempira, Honduras) have wikidata concordance to San Francisco (United States)

### ISSUE THREAD

**Issue by happyleavesaoc** [whosonfirst-data/whosonfirst-data#2215]
Currently: Q62

https://spelunker.whosonfirst.org/id/890432303 should be Q316332
https://spelunker.whosonfirst.org/id/421203419 should be Q1645805

**Comment by nvkelso** [comment]
Completed via https://github.com/whosonfirst-data/whosonfirst-data-admin-ph/pull/28 and https://github.com/whosonfirst-data/whosonfirst-data-admin-hn/pull/18 using the Write Field editor tool.

FYI: For any record in the Spelunker, there's a self-service "Edit in Write Field" link in the right sidebar.

**Comment by nvkelso** [comment]
And thanks for the reports!
