### ISSUE TITLE
Muir Army Air Field has a label geometry but actual geometry lies at Null Island.

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#2216]
[Muir Army Air Field](https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/102/525/173/102525173.geojson) has a label geometry but actual geometry lies at Null Island.

```
"lbl:latitude":40.43481,
"lbl:longitude":-76.56941,
```

```
"geometry": {"coordinates":[0.0,0.0],"type":"Point"}
```

**Comment by stepps00** [comment]
There are a handful of other cases like this, all in the US repo:

```
102533669
102533641
102533665
102532245
102532295
102532625
102528473
102527545
102527981
102529199
102530103
102530159
102530053
102531065
102525731
102525173
102525213
```

The PR above should fix this issue, thanks @missinglink
