### ISSUE TITLE
Two locality record for Évora, Portugal

### ISSUE THREAD

**Issue by gmarti** [whosonfirst-data/whosonfirst-data#2220]
Seems there is two locality recorded for Évora in Portugal

Same place but different localadmin

https://spelunker.whosonfirst.org/id/101777039
https://spelunker.whosonfirst.org/id/1125872571

**Comment by nvkelso** [comment]
Agree these are the same place – one from the Quattroshapes point gazetteer and another from the Quattroshapes Europe locality urban grid polygon source. The final condensed record's revgeo lat lng (really label centroid) should move to the center of the city, which is in a 3rd localadmin (self titled). The resulting record should have the polygon as default geom, and not preserve the point gazetteer's erroneous location.
