### ISSUE TITLE
Needs PR review and approval for small changes.

### ISSUE THREAD

**Issue by iaroslavzif** [whosonfirst-data/whosonfirst-data#2223]
Hello!

Please review and approve the following PR: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/pull/58

Thank you!

**Comment by nvkelso** [comment]
Left a review!

**Comment by iaroslavzif** [comment]
Hi nvkelso!

Unfortunately I cannot merge the changes...

Thank you!

**Comment by nvkelso** [comment]
Remade the PR using Write Field and merged that PR: https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/pull/60, closing.
