### ISSUE TITLE
Bunk encoding for wof:id 1796406463

### ISSUE THREAD

**Issue by straup** [whosonfirst-data/whosonfirst-data#2224]
`wof:id` property for 1796406463 is recorded as a string not an int(64).

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-pl/8baf2fbad6362b4cacf16eb27eca0eedd5505783/data/179/640/646/3/1796406463.geojson

https://data.whosonfirst.org/id/1796406463

**Comment by nvkelso** [comment]
That's odd. Fixed in https://github.com/whosonfirst-data/whosonfirst-data/issues/2224.

**Comment by nvkelso** [comment]
Noting that WOF Write Field was happy to use the Python exportify which doesn't enforce ints in the "id" or "wof:id" properties. Didn't we talk about this / fix that before?

**Comment by straup** [comment]
I don't remember. It's probably time to revisit the question of whether its practical to export `go-whosonfirst-export` as a WASM (or wasip2) binary and run it from inside a Python processor. I have not kept tabs on the state of WASM runtime support in Python lately.
