### ISSUE TITLE
Toscany English Translation

### ISSUE THREAD

**Issue by alex-habrock-SHG** [whosonfirst-data/whosonfirst-data#2225]
Why is the Toscany the preferred English translation for the Toscana Macroregion of Italy?  It seems that it is much more common to see the Tuscany spelling to the point that Google autocorrects if you put in Toscany.

**Comment by nvkelso** [comment]
Fixed via https://github.com/whosonfirst-data/whosonfirst-data-admin-it/pull/36 using the Write Field editor.

Probably the way we got Toscany originally in WOF is we imported the Italian data for macroregions, and that's what it's called there so the default name was Toscany, and later when we localized the names that value was preserved and the Tuscany added as variant.

The related PR swaps those around. Thanks!

**Comment by ghost** [comment]
Thanks for getting this addressed!
