### ISSUE TITLE
Investigate and fix Bosnia & Herzegovina regions

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#23]
We have the 10 cantons + 1 district (Brcko Distrikt).

For reference, Statoids lists 2 entities and 1 district as the primary subdivisions for Bosnia & Herzegovina. Additional subdivisions include communes (105) and cantons (10)

This country is more complicated and we have some extra features that are questionable in WOF now.  Seems like we have a mix of the cantons, plus a few of the communes which are subdivisions. 

Requires more research to determine corrective action.

**Comment by nvkelso** [comment]
The regions are probably in the Quattroshapes admin-1-regions file and need to be imported still. The communes and cantons needs further research.

**Comment by nvkelso** [comment]
See import of admin-1-regions here: https://github.com/whosonfirst/whosonfirst-data/issues/34

**Comment by stepps00** [comment]
This issue was taken care of in https://github.com/whosonfirst-data/whosonfirst-data/commit/5fce59f5d01752f2e0317c45e85bdc6e0926dae9. Will close the issue once this commit is pushed to `master`.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/commit/5fce59f5d01752f2e0317c45e85bdc6e0926dae9 was merged to `master`, closing issue. All `admin1` records for Bosnia & Herzegovina have been updated.
