### ISSUE TITLE
[marketarea] Some sort of macro-metropolian area from FCC

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#235]
US FCC has released updated Partial Economic Area (PEA) geographies as part of the 2015 / 2016 Spectrum Auction. These are similar to the old DMA metro areas based on broadcast media markets. 

**THESE ARE NOT METRO AREAS** – more like groups of metropolitan and micropolitan and rural areas.

See also: 
- http://transition.fcc.gov/oet/info/maps/areas/
- https://www.fcc.gov/document/wtb-provides-details-about-partial-economic-areas
- https://apps.fcc.gov/edocs_public/attachmatch/DA-14-759A4.pdf
- https://apps.fcc.gov/edocs_public/attachmatch/DA-14-759A2.pdf
- https://blogs.esri.com/esri/esri-insider/2016/02/22/what-you-need-to-know-to-prepare-for-the-fcc-600-mhz-auction/

[FCC_PEAs_Website.zip](https://github.com/whosonfirst/whosonfirst-data/files/192658/FCC_PEAs_Website.zip)

![screen shot 2016-03-28 at 17 06 40](https://cloud.githubusercontent.com/assets/853051/14094143/7166db62-f508-11e5-8b3b-271fe4a1e66f.png)

**Comment by thisisaaronland** [comment]
We can just add "Partial Economic Area" as a placetype if necessary. Do we know whether these cross state boundaries?

**Comment by nvkelso** [comment]
- 176 economic areas (versus 210 for designated market areas)
- 416 partial economic areas

**Comment by nvkelso** [comment]
Let's add a new `marketarea` that's different than the planned work around the existing but empty [`metroarea`](https://github.com/whosonfirst/whosonfirst-placetypes#metroarea) to track [DMAs](https://en.wikipedia.org/wiki/Media_market), and there should be similar subcategory similar to `wof:association` for constituencies that allows for multiple levels / types, with this subtype being `mediamarket` (eg DMA).

**Comment by thisisaaronland** [comment]
What is the rationale for a distinct placetype?

**Comment by nvkelso** [comment]
These span multiple metropolitan areas and are sometimes disjoint. They're more for TV, radio, and other media related purposes. They're more about economic geography than cultural, political, or physical geography.

**Comment by stepps00** [comment]
FWIW, map of DMAs: https://www.thevab.com/wp-content/uploads/2018/05/2017-2018-TV-DMA-Map.pdf

**Comment by nvkelso** [comment]
Closing this issue via https://github.com/whosonfirst-data/whosonfirst-data/pull/1328.

Continuation for non-USA in https://github.com/whosonfirst-data/whosonfirst-data/issues/1742.
