### ISSUE TITLE
Investigate and fix Burkina Faso regions

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#24]
There should be 13 régions. We currently have the provinces, not the régions.  

The regions are now the primary subdivisions.

**Comment by nvkelso** [comment]
The regions are probably in the Quattroshapes admin-1-regions file and need to be imported still.

**Comment by nvkelso** [comment]
See import of admin-1-regions here: https://github.com/whosonfirst/whosonfirst-data/issues/34

**Comment by stepps00** [comment]
This issue was taken care of in https://github.com/whosonfirst-data/whosonfirst-data/commit/2cd5c01610f785f06c53c2232d7a6397ab1ce8ef. Will close the issue once this commit is pushed to `master`.

**Comment by stepps00** [comment]
[This commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/2cd5c01610f785f06c53c2232d7a6397ab1ce8ef) was recently merged to `master` and included the thirteen `region` records in Burkina Faso.

It also superseded the existing `region` records with `county` records, as they were misclassified. 

Admin data in Burkina Faso should be up-to-date, closing issue.
