### ISSUE TITLE
Investigate and fix Estonia

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#25]
WOF has 33 features containing duplicates that need to be reviewed.

For reference, Statoids lists 15 counties, subdivided into 241 urban and rural municipalities.

Many of the WOF names are similar to the Statoids data with what appear to be suffixes i.e. Harju could be what WOF has as Harjumaa.  Hiiu could be what WOF has as Hiiumaa.

**Comment by hugovk** [comment]
"Maa" is Estonian for things like land, country, earth. 

"Harju County (Estonian: Harju maakond), or Harjumaa (German: Harrien, Latin: Harria) is one of the 15 counties of Estonia."
https://en.wikipedia.org/wiki/Harju_County

"Hiiu County (Estonian: Hiiu maakond), or Hiiumaa, is one of 15 counties of Estonia, being the smallest county both in terms of area and population."
https://en.wikipedia.org/wiki/Hiiu_County

("Maakond" means "county".)

**Comment by stepps00** [comment]
Closing in preference of #1825 and #1550.
