### ISSUE TITLE
regions should not be parented by... regions

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#26]
./scripts/ensure-parent.py /usr/local/mapzen/whosonfirst-data/meta/wof-region-latest.csv
Hainan (85669759) parent is a region but expected one of: dependency,disputed,country
Null Island (85681319) parent is a continent but expected one of: dependency,disputed,country
Serranilla Bank (85681363) parent is a continent but expected one of: dependency,disputed,country
St. Martin (85673879) parent is a region but expected one of: dependency,disputed,country
Bari (85677235) parent is a region but expected one of: dependency,disputed,country
Mudug (85677279) parent is a region but expected one of: dependency,disputed,country
Nugaal (85677283) parent is a region but expected one of: dependency,disputed,country
Banja Luka (85669253) parent is a region but expected one of: dependency,disputed,country
Sarajevo-romanija (85669271) parent is a region but expected one of: dependency,disputed,country
Bijeljina (85669261) parent is a region but expected one of: dependency,disputed,country
Trebinje (85669279) parent is a region but expected one of: dependency,disputed,country
Vlasenica (85669267) parent is a region but expected one of: dependency,disputed,country
Foča (85669275) parent is a region but expected one of: dependency,disputed,country
Doboj (85669249) parent is a region but expected one of: dependency,disputed,country
Brčko Distrikt (85669257) parent is a region but expected one of: dependency,disputed,country

**Comment by nvkelso** [comment]
Some of these are already addressed by other issues, for instance:

Serranilla Bank: https://github.com/whosonfirst/whosonfirst-data/issues/15
St. Martin: https://github.com/whosonfirst/whosonfirst-data/issues/13

Others are because we don't have the admin-1-regions from Quattroshapes as a common optional level between WOF regions and WOF countries: https://github.com/whosonfirst/whosonfirst-data/issues/34.

Guessing fixes those will resolve more than 1/2 of the reported errors.

**Comment by nvkelso** [comment]
Hainan is also tied up in:
Hainan	12578020	931674	Hainan	quattroshapes	1439838274		85632557	CN

**Comment by stepps00** [comment]
I reran the `ensure-parent.py` script, the only region records that are parented by regions are non-current regions in Bosnia and Herzegovina that have been superseded into new (correctly parented) records. 

Output:

```
python ./scripts/ensure-parent.py ./meta/wof-region-latest.csv 
Doboj (85669249) parent is a region but expected one of: macroregion,dependency,disputed,country
Banja Luka (85669253) parent is a region but expected one of: macroregion,dependency,disputed,country
Brčko Distrikt (85669257) parent is a region but expected one of: macroregion,dependency,disputed,country
Bijeljina (85669261) parent is a region but expected one of: macroregion,dependency,disputed,country
Vlasenica (85669267) parent is a region but expected one of: macroregion,dependency,disputed,country
Sarajevo-romanija (85669271) parent is a region but expected one of: macroregion,dependency,disputed,country
Foča (85669275) parent is a region but expected one of: macroregion,dependency,disputed,country
Trebinje (85669279) parent is a region but expected one of: macroregion,dependency,disputed,country
```
