### ISSUE TITLE
Investigate and fix Ireland

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#29]
WOF has counties + a few extras + so many duplicates i.e. 7 Galways, 7 Mayos, etc

This may be a single part vs multi part polygon problem.

For reference, Statoids has 26 counties.

**Comment by stepps00** [comment]
This is a multi-part polygon issue with the `county` (also commonly referred to as `region`) records in Ireland. 

Closing this issue in preference of #115.
