### ISSUE TITLE
Update ISO-639-3 codes

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#291]
Basically crawl the entire dataset and parse things with language codes using `pycountry` looking for failures. This includes all the `name:` fields and values in `wof:lang*`

Known knowns as of this writing include:
- `dut` -> `nld`
- `fre` -> `fra`
- `chi` -> `zho`
- `ger` -> `deu`

**Comment by stepps00** [comment]
cc @ndcartography

**Comment by stepps00** [comment]
This work is also being tracked in https://github.com/mapzen/data-tasks/issues/33.

Re-assigning myself to verify that all four language codes are updated (Dutch not covered in that issue).
