### ISSUE TITLE
Norway localities seem to be off

### ISSUE THREAD

**Issue by dianashk** [whosonfirst-data/whosonfirst-data#298]
Please update with authoritative data here: http://data.kartverket.no/download/content/geodataprodukter?korttype=3597&aktualitet=All&datastruktur=All&dataskema=All

**Comment by stepps00** [comment]
The above URL links to a dataset of "place names" - a point dataset that looks like:

<img width="812" alt="screen shot 2016-08-17 at 12 25 54 pm" src="https://cloud.githubusercontent.com/assets/18567700/17750183/d52c92ea-6475-11e6-930b-3fec735ab4d8.png">

It seems to include much more than just locality records. I'll keep this issue open and look for another locality polygon source; the `data.kartverket.no` site has other administrative polygon data that may be useful for `region` records.

**Comment by stepps00** [comment]
Most of the locality-level issues were cleared up during the [GeoNames import](https://github.com/whosonfirst-data/whosonfirst-data/issues/108) and the [import of localadmin](https://github.com/whosonfirst-data/whosonfirst-data/issues/1107) in Norway, but there are additional corrections we need to make. Specifically, we need to:

- Flag coterminous localadmin/locality records (see: Oslo)
- Rework locality/neighbourhood points that fall within existing locality polygons
- Clip any existing locality polygons to parent localadmin boundaries (again, see: Oslo)
- Update `mz:hierarchy_label` properties as needed

In addition, we have other issues related to name translations and labels tracked via #1640 and #1445.

I'll rework some of the records in Norway and use this issue to track them.
