### ISSUE TITLE
Update Neighbourhood, Macrohood, and Borough records in Helsinki

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#315]
In continuation of Issue #99:

Neighbourhood, macrohood, and borough records need to be updated in Helsinki; this work should be completed in a separate PR from other Finnish geometry/record updates. As discussed in the previous issue:

> Unfortunately no common neighbourhood info exists for the whole country, and not that many records exist in WoF [today](https://whosonfirst.mapzen.com/spelunker/id/85633143/descendants/?placetype=neighbourhood&page=1#6/62.246/24.941). However, the records in Helsinki are a bit [wonky](https://whosonfirst.mapzen.com/spelunker/id/85907887/#12/60.1454/24.9612) and could be replaced with the official data for [Helsinki](http://koti.kapsi.fi/~hannes/Neighborhoods_Helsinki.geojson.zip) which is provided by [the city](http://www.hri.fi/en/dataset/helsingin-kaupunginosat) under CC-BY-4.0.

**Comment by stepps00** [comment]
S3 Dropbox _misc_ folder now contains geojson file with eight boroughs of Helsinki. 
The file is: `Issue315_NewBoroughs.geojson`.

**Comment by stepps00** [comment]
S3 Dropbox _misc_ folder now contains geojson file with 60 macrohoods of Helsinki. These macrohood records map cleanly to [this list](https://en.wikipedia.org/wiki/Subdivisions_of_Helsinki#Neighbourhoods) of neighbourhoods of Helsinki, with the exception of `Aluemeri`, the southern area that covers a portion of the Gulf of Finland.

The file is: `Issue315_NewMacrohoods.geojson`.

**Comment by thisisaaronland** [comment]
@stepps00 - all places _except_ neighbourhoods have been imported. Would you please create a new issue for the remaining placetypes.

**Comment by stepps00** [comment]
@thisisaaronland - separate issues have been opened and referenced above. I will close this issue, unless we're missing something.
