### ISSUE TITLE
Update SF Neighbourhood Records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#316]
_(See: [this comment](https://github.com/whosonfirst-data/whosonfirst-data/issues/316#issuecomment-239514084) for most recent files)_

Starting where #125 left off.

The current neighbourhood records in San Francisco need to be updated to reflect neighbourhood boundaries provided by the City of San Francisco. This, in turn, will require udates at the `macrohood`, `neighbourhood`, and `microhood` levels. 

To do for each `wof:placetype`:

**1. Macrohoods**

A .geojson file with three macrohoods (`Sunset`, `Richmond`, and `Downtown`) was created _with_ IDs (the IDs correspond to current `neighbourhood` records that should be promoted to `macrohood` records). This .geojson will be imported and the following will need to occur:
- Find all "contained by" records and rebuild the hierarchy (in order of placetype).
- Reindex the PIP server (PIP to PostGIS)

**2. Updated Neighbourhoods**

A .geojson file (_with_ an ID field) was created for `neighbourhood` records that have new geometries. This .geojson will be imported and the following will need to occur:
- Find all "contained by" records and rebuild the hierarchy (in order of placetype).
- Reindex the PIP server (PIP to PostGIS)

**3. New Neighbourhoods**

A .geojson file (_without_ an ID field) was created for new `neighbourhood` records that have not been assigned a current WOF ID. This .geojson will be imported and the following will need to occur:
- Find all "contained by" records and rebuild the hierarchy (in order of placetype).
- Reindex the PIP server (PIP to PostGIS)

**4. Microhoods**

A .geojson file (_with_ an ID field) was created for current `neighbourhood` records that will be "demoted" to `microhoods`. The .geojson will be imported and the following will need to occur:
- Find all "contained by" records and rebuild the hierarchy (in order of placetype).
- Simple `supersedes` and `supersedes_by` updates
- Reindex the PIP server (PIP to PostGIS)

These four .geojson files will be placed in the S3 WOF/misc bucket.

Additional one-offs (deprecating two records and updating parenting of two records that fall outside of San Francisco (Westlake and Fort Winfield Scott)) will occur in separate PR(s).

**Comment by stepps00** [comment]
Note: Consider adding a `macrohood` record for The Mission that parents the `neighbourhood` record of The Mission and other adjacent neighbourhoods of interest.

**Comment by stepps00** [comment]
`Macrohood`, updated `neighbourhood`, new `neighbourhood`, and `microhood` geojson files are ready for import and are now in the [S3 Dropbox](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%20316)

**Comment by nvkelso** [comment]
I'm fine with creating a new macrohood record for the Mission, let's make sure it's min_zoom shows up early.

**Comment by stepps00** [comment]
New `macrohood` record for the Mission District was placed in the [S3 Dropbox](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%20316). This `macrohood` contains the `neighbourhoods` of the Mission District and Mission Dolores. 

This new `macrohood` is different from the other `macrohood` records because it will need a new Brooklyn Integer; this record is not a current `neighbourhood` record that will be promoted to a `macrohood`. 

Continuing the list above:

**5. New macrohood**

A .geojson file (without an ID field) was created for new a macrohood record that has not been assigned a current WOF ID. This .geojson will be imported and the following will need to occur:

* Find all "contained by" records and rebuild the hierarchy (in order of placetype).
* Reindex the PIP server (PIP to PostGIS)

**Comment by stepps00** [comment]
Added in a [sixth geojson file](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20316/6%20MicrohoodNew_Import.geojson) to the S3 Dropbox. The file contains four **new** microhood records with a `wof:name` field and `parented_by` id (when available).

**Comment by stepps00** [comment]
New files are now in the S3 `misc/Issue 316 folder`; the comments above are no longer relevant.

All files will have the following attributes:

_**wof:id**_
_**wof:placetype**_
_**wof:name**_
_**wof:country**_
_**wof:parent_id**_

Notes about specific files in the S3 misc folder:

**SF_Bad_Neighbourhood_Points.geojson**

- Contains neighbourhood points that are no longer current.
- Includes `edtf:cessation`, `wof:superseded_by` and `mz:is_current` fields.

**SF_Bad_Neighbourhood_Polygons.geojson**

- Contains neighbourhood polygons that are no longer current.
- Includes `edtf:cessation`, `wof:superseded_by` and `mz:is_current` fields.

**SF_Macrohoods.geojson**

- Contains new macrohood records for San Francisco. 
- `min_zoom` and `max_zoom` fields included for import.
- This file was given `lbl` coordinates (from Mapshaper) for import.
- Includes features with newly-minted Brooklyn Integers and features that already exist in WoF (but have had their placetypes changed from neighbourhood to macrohood).

**SF_Microhoods.geojson**

- Contains new microhood records for San Francisco. 
- `min_zoom` and `max_zoom` fields included for import.
- This file was given `lbl` coordinates (from Mapshaper) for import.
- Includes features with newly-minted Brooklyn Integers and features that already exist in WoF (but have had their placetypes changed from neighbourhood to microhood).

**SF_New_Neighbourhoods.geojson**

- Contains new neighbourhood records for San Francisco.
- `min_zoom` and `max_zoom` fields included for import.
- This file was given `lbl` coordinates (from Mapshaper) for import.
- Includes features with newly-minted Brooklyn Integers. 

**SF_Updated_Neighbourhoods.geojson**

- Contains updated neighbourhood records for San Francisco.
- Includes features that already have an existing `wof:id`.

The `parent_id` field is present in these geojson files, as are the `wof:supersedes` and `wof:superseded_by` fields. Descendant ids are not included.

**Comment by stepps00** [comment]
Per #187:

GeoJSON files in this issue need to be updated to include neighbourhood and microhood work in SOMA. The following microhoods _should_ fall within the "South of Market" neighbourhood record:

*    East SoMa
*    West SoMa
*    Financial District South
*    Rincon Hill
*    Showplace Square

Links: 

- http://www.socketsite.com/archives/2008/08/eastern_neighborhoods_eir_not_just_for_wonks_anymore.html

- http://www.sf-planning.org/index.aspx?page=3545

**Comment by stepps00** [comment]
Reassigning myself for updates to SF records.

**Comment by stepps00** [comment]
Note to self: Import the new clipped locality shape as a new alt_geometry. Do not include it in the S3 files.

**Comment by nvkelso** [comment]
Please toss the new shapes into S3.

**Comment by stepps00** [comment]
SF neighbourhood files are in the S3 `misc/Issue 316` folder.

**Comment by stepps00** [comment]
Neighbourhood (and associated) features have been updated in SF, closing issue.
