### ISSUE TITLE
Investigate and fix Madagascar

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#33]
WOF has 22 regions.

For reference, Statoids lists 6 provinces subdivided into 22 regions.  WOF is missing the provinces.

**Comment by nvkelso** [comment]
See import of admin-1-regions here: https://github.com/whosonfirst/whosonfirst-data/issues/34

**Comment by stepps00** [comment]
Closing this issue.

Statoids data for Madagascar is out of date; provinces of Madagascar were dissolved as of 2007 ([source](https://en.wikipedia.org/wiki/Provinces_of_Madagascar)). Now, Madagascar is divided into [22 regions](https://en.wikipedia.org/wiki/Regions_of_Madagascar) and [114 districts](https://en.wikipedia.org/wiki/Districts_of_Madagascar). 

WOF now has correct counts for both [regions](https://whosonfirst.mapzen.com/spelunker/id/85632223/descendants/?exclude=nullisland&placetype=region) and [districts](https://whosonfirst.mapzen.com/spelunker/id/85632223/descendants/?exclude=nullisland&placetype=county).

Follow-up issue for Madagascar: https://github.com/whosonfirst-data/whosonfirst-data/issues/616
