### ISSUE TITLE
NYC neighbourhoods either `is_funky` or `tier_locality` < 6

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#334]
We recently started filtering out neighbourhoods from our admin lookup process for OA/OSM data that are `mz:is_funky` = 1 or `mz:tier_locality` < 6.  Below is a list of NYC neighbourhoods that are either of those.  These may be completely legitimately invalid/suspicious neighbourhoods but 1 that sticks out is [Greenwich Village](https://whosonfirst.mapzen.com/spelunker/id/420529189/#15/40.7314/-73.9968).  I don't know NYC well enough to comment on others.  

Manhattan:
420529187: [Central Park](https://whosonfirst.mapzen.com/spelunker/id/420529187/)
420529189: [Greenwich Village](https://whosonfirst.mapzen.com/spelunker/id/420529189/)
420782815: [Greenwich Village](https://whosonfirst.mapzen.com/spelunker/id/420782815/)
420782817: [Peter Cooper Village](https://whosonfirst.mapzen.com/spelunker/id/420782817/)
420782819: [Hudson Yards](https://whosonfirst.mapzen.com/spelunker/id/420782819/)
420782821: [Diamond District](https://whosonfirst.mapzen.com/spelunker/id/420782821/)
420782825: [Le Petit Senegal](https://whosonfirst.mapzen.com/spelunker/id/420782825/)
420782849: [Manhattan](https://whosonfirst.mapzen.com/spelunker/id/420782849/)
85831579: [Lower Manhattan](https://whosonfirst.mapzen.com/spelunker/id/85831579/)
85865455: [Liberty State Park](https://whosonfirst.mapzen.com/spelunker/id/85865455/)
85865677: [Hamilton Hights](https://whosonfirst.mapzen.com/spelunker/id/85865677/)
85865689: [East Harlem](https://whosonfirst.mapzen.com/spelunker/id/85865689/)
85865693: [Carnegie Hills](https://whosonfirst.mapzen.com/spelunker/id/85865693/)
85865695: [York Ville](https://whosonfirst.mapzen.com/spelunker/id/85865695/)
85865701: [Midtown South](https://whosonfirst.mapzen.com/spelunker/id/85865701/)
85867071: [City Hall Area](https://whosonfirst.mapzen.com/spelunker/id/85867071/)
85868035: [Governor Alfred e Smith Houses](https://whosonfirst.mapzen.com/spelunker/id/85868035/)
85868043: [Loisaida](https://whosonfirst.mapzen.com/spelunker/id/85868043/)
85868047: [San Juan Hill](https://whosonfirst.mapzen.com/spelunker/id/85868047/)
85869109: [Beekman](https://whosonfirst.mapzen.com/spelunker/id/85869109/)
85869429: [Little Germany](https://whosonfirst.mapzen.com/spelunker/id/85869429/)
85869439: [LoHo](https://whosonfirst.mapzen.com/spelunker/id/85869439/)
85869467: [Medical Centre](https://whosonfirst.mapzen.com/spelunker/id/85869467/)
85869699: [Spura](https://whosonfirst.mapzen.com/spelunker/id/85869699/)
85882229: [East Side](https://whosonfirst.mapzen.com/spelunker/id/85882229/)
85882233: [Midtown West](https://whosonfirst.mapzen.com/spelunker/id/85882233/)
85882243: [West Side](https://whosonfirst.mapzen.com/spelunker/id/85882243/)
85892909: [Bellevue](https://whosonfirst.mapzen.com/spelunker/id/85892909/)
85892937: [Gramercy-Flatiron](https://whosonfirst.mapzen.com/spelunker/id/85892937/)
85892947: [LoDel](https://whosonfirst.mapzen.com/spelunker/id/85892947/)
85892963: [St. Nicholas Terrace](https://whosonfirst.mapzen.com/spelunker/id/85892963/)

Brooklyn:
420558599: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420558599/)
420558701: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420558701/)
420782855: [Brooklyn](https://whosonfirst.mapzen.com/spelunker/id/420782855/)
420782905: [Marine Park](https://whosonfirst.mapzen.com/spelunker/id/420782905/)
420782907: [Borough Park](https://whosonfirst.mapzen.com/spelunker/id/420782907/)
420782909: [Beverley Square East](https://whosonfirst.mapzen.com/spelunker/id/420782909/)
420782911: [Beverley Square](https://whosonfirst.mapzen.com/spelunker/id/420782911/)
420782915: [Carroll Gardens](https://whosonfirst.mapzen.com/spelunker/id/420782915/)
85807739: [Broadway Junction](https://whosonfirst.mapzen.com/spelunker/id/85807739/)
85836777: [New Utrecht](https://whosonfirst.mapzen.com/spelunker/id/85836777/)
85840193: [Paerdegat](https://whosonfirst.mapzen.com/spelunker/id/85840193/)
85865539: [Prospect Hights](https://whosonfirst.mapzen.com/spelunker/id/85865539/)
85865581: [Windsor Terrace](https://whosonfirst.mapzen.com/spelunker/id/85865581/)
85865595: [Crown Hights](https://whosonfirst.mapzen.com/spelunker/id/85865595/)
85865599: [Mill Island](https://whosonfirst.mapzen.com/spelunker/id/85865599/)
85865605: [East Williasburg](https://whosonfirst.mapzen.com/spelunker/id/85865605/)
85865611: [Down Town](https://whosonfirst.mapzen.com/spelunker/id/85865611/)
85865617: [Tulton Ferry](https://whosonfirst.mapzen.com/spelunker/id/85865617/)
85865621: [Starrett City](https://whosonfirst.mapzen.com/spelunker/id/85865621/)
85865627: [Cypres Hills](https://whosonfirst.mapzen.com/spelunker/id/85865627/)
85865873: [Homecrest](https://whosonfirst.mapzen.com/spelunker/id/85865873/)
85866221: [Manhattan Terrace](https://whosonfirst.mapzen.com/spelunker/id/85866221/)
85868661: [Eastern Parkway](https://whosonfirst.mapzen.com/spelunker/id/85868661/)
85868663: [South Brooklyn](https://whosonfirst.mapzen.com/spelunker/id/85868663/)
85868665: [Adelphi](https://whosonfirst.mapzen.com/spelunker/id/85868665/)
85869507: [Morgan Avenue](https://whosonfirst.mapzen.com/spelunker/id/85869507/)
85892915: [BoCoCa](https://whosonfirst.mapzen.com/spelunker/id/85892915/)
85892925: [Crown Heights South](https://whosonfirst.mapzen.com/spelunker/id/85892925/)
85892935: [Floyd Bennett](https://whosonfirst.mapzen.com/spelunker/id/85892935/)
85892945: [Little Odessa](https://whosonfirst.mapzen.com/spelunker/id/85892945/)
85892951: [North Williamsburg - North Side](https://whosonfirst.mapzen.com/spelunker/id/85892951/)
85892959: [South Midwood](https://whosonfirst.mapzen.com/spelunker/id/85892959/)
85892971: [West Brighton](https://whosonfirst.mapzen.com/spelunker/id/85892971/)

Queens:
420529695: [Kew Gardens](https://whosonfirst.mapzen.com/spelunker/id/420529695/)
420529697: [Queens Village](https://whosonfirst.mapzen.com/spelunker/id/420529697/)
420529699: [Middle Village](https://whosonfirst.mapzen.com/spelunker/id/420529699/)
420529701: [Ozone Park](https://whosonfirst.mapzen.com/spelunker/id/420529701/)
420529703: [North Beach](https://whosonfirst.mapzen.com/spelunker/id/420529703/)
420529705: [Floral Park](https://whosonfirst.mapzen.com/spelunker/id/420529705/)
420558349: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420558349/)
420558371: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420558371/)
420559115: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420559115/)
420560043: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420560043/)
420560117: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420560117/)
420782853: [Queens](https://whosonfirst.mapzen.com/spelunker/id/420782853/)
420782861: [Floral Park](https://whosonfirst.mapzen.com/spelunker/id/420782861/)
420782863: [Jamaica Estates](https://whosonfirst.mapzen.com/spelunker/id/420782863/)
420782865: [Flushing Chinatown](https://whosonfirst.mapzen.com/spelunker/id/420782865/)
420782867: [Long Island Koreatown](https://whosonfirst.mapzen.com/spelunker/id/420782867/)
420782869: [Broadway-Flushing](https://whosonfirst.mapzen.com/spelunker/id/420782869/)
420782871: [Waldheim](https://whosonfirst.mapzen.com/spelunker/id/420782871/)
420782873: [Queens Village](https://whosonfirst.mapzen.com/spelunker/id/420782873/)
420782875: [Hollis Hills](https://whosonfirst.mapzen.com/spelunker/id/420782875/)
420782879: [Kew Gardens](https://whosonfirst.mapzen.com/spelunker/id/420782879/)
420782881: [South Ozone Park](https://whosonfirst.mapzen.com/spelunker/id/420782881/)
420782883: [Ozone Park](https://whosonfirst.mapzen.com/spelunker/id/420782883/)
420782885: [Tudor Village](https://whosonfirst.mapzen.com/spelunker/id/420782885/)
420782887: [The Hole](https://whosonfirst.mapzen.com/spelunker/id/420782887/)
420782889: [Howard Beach](https://whosonfirst.mapzen.com/spelunker/id/420782889/)
420782891: [Rockwood Park](https://whosonfirst.mapzen.com/spelunker/id/420782891/)
420782893: [Forest Hills Gardens](https://whosonfirst.mapzen.com/spelunker/id/420782893/)
420782897: [Rego Park](https://whosonfirst.mapzen.com/spelunker/id/420782897/)
420782899: [Ditmars](https://whosonfirst.mapzen.com/spelunker/id/420782899/)
420782901: [Middle Village](https://whosonfirst.mapzen.com/spelunker/id/420782901/)
420782903: [The Rockaways](https://whosonfirst.mapzen.com/spelunker/id/420782903/)
85803825: [Astoria South](https://whosonfirst.mapzen.com/spelunker/id/85803825/)
85837295: [North Bayside](https://whosonfirst.mapzen.com/spelunker/id/85837295/)
85840703: [Parkside](https://whosonfirst.mapzen.com/spelunker/id/85840703/)
85845413: [Rockaway Point](https://whosonfirst.mapzen.com/spelunker/id/85845413/)
85851955: [Terrace Heights](https://whosonfirst.mapzen.com/spelunker/id/85851955/)
85865565: [Astoria Heights](https://whosonfirst.mapzen.com/spelunker/id/85865565/)
85865575: [Queensboro Hills](https://whosonfirst.mapzen.com/spelunker/id/85865575/)
85865641: [South Corona](https://whosonfirst.mapzen.com/spelunker/id/85865641/)
85865655: [New Gardens Hills](https://whosonfirst.mapzen.com/spelunker/id/85865655/)
85868659: [Fresh Pond Junction](https://whosonfirst.mapzen.com/spelunker/id/85868659/)
85892739: [Arverne-Edgemere](https://whosonfirst.mapzen.com/spelunker/id/85892739/)
85892845: [East Flushing](https://whosonfirst.mapzen.com/spelunker/id/85892845/)
85892847: [Kew Gardens Hill](https://whosonfirst.mapzen.com/spelunker/id/85892847/)
85892849: [Murry Hill](https://whosonfirst.mapzen.com/spelunker/id/85892849/)
85892997: [Neponsit & Belle](https://whosonfirst.mapzen.com/spelunker/id/85892997/)

Bronx:
none

Staten Island:
420529763: [Bay Terrace (Staten Island)](https://whosonfirst.mapzen.com/spelunker/id/420529763/)
420529765: [Park Hill](https://whosonfirst.mapzen.com/spelunker/id/420529765/)
420529767: [Todt Hill](https://whosonfirst.mapzen.com/spelunker/id/420529767/)
420529769: [Oakwood Heights Station](https://whosonfirst.mapzen.com/spelunker/id/420529769/)
420529771: [New Dorp](https://whosonfirst.mapzen.com/spelunker/id/420529771/)
420558383: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420558383/)
420558387: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420558387/)
420560191: [undefined](https://whosonfirst.mapzen.com/spelunker/id/420560191/)
420782857: [Staten Island](https://whosonfirst.mapzen.com/spelunker/id/420782857/)
420782917: [Bay Terrace](https://whosonfirst.mapzen.com/spelunker/id/420782917/)
420782919: [New Dorp](https://whosonfirst.mapzen.com/spelunker/id/420782919/)
420782921: [Todt Hill](https://whosonfirst.mapzen.com/spelunker/id/420782921/)
420782923: [Park Hill](https://whosonfirst.mapzen.com/spelunker/id/420782923/)
420782925: [Stapleton](https://whosonfirst.mapzen.com/spelunker/id/420782925/)
420782927: [Sunnyside](https://whosonfirst.mapzen.com/spelunker/id/420782927/)
85808409: [Bulls Head](https://whosonfirst.mapzen.com/spelunker/id/85808409/)
85892919: [Castleton Corner](https://whosonfirst.mapzen.com/spelunker/id/85892919/)
85892939: [Grand City](https://whosonfirst.mapzen.com/spelunker/id/85892939/)
85892943: [Howland Hook](https://whosonfirst.mapzen.com/spelunker/id/85892943/)

**Comment by nvkelso** [comment]
These are an error (they need to be merged)

* 420529189: Greenwich Village
* 420782815: Greenwich Village

The rest are a mix of several things:

* it's valid to be `is_funky` and have everything else correct, e.g.: https://whosonfirst.mapzen.com/spelunker/id/85892951 as Nat didn't find evidence that this placename was in used in daily practice for that area.
* `tier_locality` could be 0 if Nat created it from scratch, but we still need to backfill the number (in this case all to `7`). I'm not thrilled by needing to maintain this number, though, I'd rather pursue https://github.com/whosonfirst/whosonfirst-data/issues/320.
* `tier_locality` could be a number less than 7 in NYC if the original hierarchy was bad and has since been fixed (and should now be set to `7`). I'm not thrilled by needing to maintain this number, though, I'd rather pursue https://github.com/whosonfirst/whosonfirst-data/issues/320.
* `undefined` names look to be weird Zetashapes crumbs that were imported after Quattroshapes that didn't match to anything in Quattroshapes. They do have a name hiding in the zs prefix that we can promote to a general name. But highly suspicious records. 
* Then there are some inexplicable records like https://whosonfirst.mapzen.com/spelunker/id/420529695 for Kew Gardens and https://whosonfirst.mapzen.com/spelunker/id/420529187 for Central Park which look like it was skipped over and we just don't know anything about it, yet (Central Park should be marked `is_landuse_aoi` true).

**Comment by stepps00** [comment]
cc @ZBSingleton . 

A list of NYC neighbourhoods that have a  `mz:is_funky = 1` or `mz:tier_locality < 6`.

**Comment by nvkelso** [comment]
See also: https://github.com/whosonfirst-data/whosonfirst-data/issues/384 where we'll track "clean room" shapes for NYC.

This issue 334 can be used as a reference for QA/QC pass on 384, but there are other problems afoot in 334 that I don't want to get tangled up in at the moment.

**Comment by nvkelso** [comment]
Forward dup of https://github.com/whosonfirst-data/whosonfirst-data/issues/384.
