### ISSUE TITLE
Add geometries to empires

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#335]
**For a rainy day** and following up from work performed in PR #330 for issue #4, we could create geometries for empires by merging the child geoms together and attaching them to the empires.

**Comment by stepps00** [comment]
This work will be completed through https://github.com/whosonfirst-data/whosonfirst-data/issues/103.

**Comment by stepps00** [comment]
Related: bd990914475d933a7bc4f33a81a0c0c2f66c8d14

**Comment by stepps00** [comment]
[Empire records](https://whosonfirst.mapzen.com/spelunker/placetypes/empire/) all have geometries and the above issues have been merged.

Closing issue.
