### ISSUE TITLE
Tokelau dependency (NZ) is missing

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#348]
Oops.

**Comment by nvkelso** [comment]
Part of the NZ empire.

**Comment by stepps00** [comment]
Looks like we have a record for the [Tokelau Islands](https://whosonfirst.mapzen.com/spelunker/id/890451503/#9/-9.1437/-171.9247), though it is incorrectly classified as a `locality`. 

**To do:**

* Supersede this locality record to a new dependency record 
* (Possibly) create a `region` record, like other dependencies
* Add `name` fields from wikipedia
* Update geometry
* Update the `empire` record

New atoll geometries, as displayed in QGIS:

<img width="828" alt="tokelau" src="https://cloud.githubusercontent.com/assets/18567700/19169737/b9c2efb4-8be3-11e6-92d6-570e808bf695.png">

**Comment by stepps00** [comment]
#946 was merged to master, closing this issue. 

Tokelau: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/115/882/147/3/1158821473.geojson
