### ISSUE TITLE
Kutztown University isn't a locality

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#360]
It's just a university:

https://whosonfirst.mapzen.com/spelunker/id/101719267/#15/40.5113/-75.7848

**Comment by nvkelso** [comment]
This is the right WOF thing to do, but will put us at odds with US Census and derivative products.

**Comment by stepps00** [comment]
I think the best option would be to deprecate the [locality record](https://whosonfirst.mapzen.com/spelunker/id/101719267/#13/40.5156/-75.7712) of Kutztown University, as WOF already has a [venue record](https://whosonfirst.mapzen.com/spelunker/id/621997697/#11/40.4904/-75.7976) for Kutztown University. 

Will file a PR shortly.

**Comment by nvkelso** [comment]
+1
