### ISSUE TITLE
Update bounding box of France

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#364]
(original) The [country record](https://whosonfirst.mapzen.com/spelunker/id/85633147) for France contains geometries of France, as well as dependencies (La Reunion, Guadeloupe, etc). The geometry should be updated to only contain France (and Corsica); `lbl` and `geom` values also need to be updated.

(updated) This issue will be used to update bounding box of France country record.

**Comment by stepps00** [comment]
Instead of changing geometry, just update the **bounding box**. Also update the bounding box for the US while we're at it.

See comments from closed PR: https://github.com/whosonfirst/whosonfirst-data/pull/365

**Comment by nvkelso** [comment]
Could also do Denmark.

**Comment by stepps00** [comment]
Note: Update Denmark, USA, France country record bounding boxes.

In a separate issue, add missing constituant parts of the France empire, namely: [French Southern and Antarctic Lands](https://whosonfirst.mapzen.com/spelunker/id/85632549/#3/-32.63/58.66).

**Comment by nvkelso** [comment]
Is this done?
