### ISSUE TITLE
Investigate and fix Nepal

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#37]
WOF has zones that date back to 1962 through 2002.

For reference, Statoids has 5 development regions subdivided into 75 districts.

**Comment by nvkelso** [comment]
Might be a touch of https://github.com/whosonfirst/whosonfirst-data/issues/34.

**Comment by stepps00** [comment]
Keeping this issue open until the mesoshapes import is complete, but the 75 districts are in a PR. The 5 development regions will be created by dissolving the districts in QGIS (being tracked in https://github.com/whosonfirst-data/whosonfirst-data/issues/486).

WIll close this issue once the mesoshapes work is complete.

**Comment by stepps00** [comment]
There are actually _seven_ development regions listed in Statoids. 

These records have been created and imported into `master` via https://github.com/whosonfirst-data/whosonfirst-data/pull/660/commits/bf29c698f80c4091a9b76410fadd06467e867354.

Closing issue.
