### ISSUE TITLE
Los Angeles, CA is not a megacity

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#372]
I noticed that [Los Angeles, CA](https://whosonfirst.mapzen.com/spelunker/id/85923517/#9/34.0211/-118.4117) is not a megacity but [Lax, CA](https://whosonfirst.mapzen.com/spelunker/id/85886923/#14/33.9611/-118.4511) (the neighborhood) is.  Is this intentional?

**Comment by nvkelso** [comment]
This is an error that will be corrected. Thanks for the tip!

**Comment by stepps00** [comment]
Closing, this issue was taken care of in recent commit: https://github.com/whosonfirst-data/whosonfirst-data/commit/0fd825bc1269ad217344d16fba00ec31c0e94394
