### ISSUE TITLE
Disambiguate qs:id from qs_pg:id in concordances

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#376]
When we originally imported the polygon based Quattroshapes we namespace everything with `qs`, including the concordances which we made up IDs for.

When we subsequently imported the "point gazetteer" files from Quattroshapes this year we smashed them into the same `qs` namespace, which generally works.

But are there any concordance `qs:id` ids that overlap between these "same project, different project" sources? Do we need a new concordance for `qs_pg:id`?

(updated 2017.05.19 re concordance `:` instead of `_`.)

**Comment by nvkelso** [comment]
There are ~255k features in WOF that have a quattroshapes concordance. But looking more closely most of those are from the polygon gazetteer and lack an actual QS id. For example San Francisco has qs:id = 0, but a made up concordance value for quattroshapes.

On the other hand, there are about 72k features that we've imported from the QS point gazeetter that have a concordance:qs &/or a `qs:id` that is not null, not 0.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst/whosonfirst-sources/issues/63

**Comment by stepps00** [comment]
While the concordance values still need to be untangled, it looks like the plan forward includes preferring/converting the `qs:id` concordances to a `qs_pg:id` concordance. I'll add an issue to update the `qs_pg` source file to include GeoPlanet and GeoNames in the `src:via` property.

**Comment by stepps00** [comment]
This was fixed in each per-country repo.
