### ISSUE TITLE
Investigate and fix Papua New Guinea

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#38]
WOF is missing the provinces of Hela & Jiwaka.
WOF has North Solomons, which is the old name for Bougainville.

For reference, Statoids lists 20 provinces, 1 autonomous region and 1 district.

**Comment by stepps00** [comment]
Keeping this issue open until the mesoshapes import is complete, but the 87 districts of Papua New Guniea are in [this PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/467). The provinces will be created by dissolving the districts in QGIS, potentially with HASC code (being tracked in https://github.com/whosonfirst-data/whosonfirst-data/issues/486).

WIll close this issue once the mesoshapes work is complete.

**Comment by stepps00** [comment]
Papua New Guinea now has all `region` descendants, including Hela and Jiwaka.

https://whosonfirst.mapzen.com/spelunker/id/85632347/descendants/?exclude=nullisland&placetype=region

Closing issue.
