### ISSUE TITLE
Backfill existing administrative WOF records with HASC code field

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#380]
Add a new field to existing records in Who's on First that includes HASC codes.

Example of HASC codes for US counties:
http://www.statoids.com/yus.html

Other sources:
http://www.statoids.com/ihasc.html
https://en.wikipedia.org/wiki/Hierarchical_administrative_subdivision_codes

**Comment by thisisaaronland** [comment]
What is the relationship with issue #221

**Comment by stepps00** [comment]
Looking at the [wof-unlocode-subdivisions-todo.csv.txt](https://github.com/whosonfirst/whosonfirst-data/files/159635/wof-unlocode-subdivisions-todo.csv.txt) file in issue #221, it seems the UN-LOCODE for say, Virginia, would be `US-VA`. The HASC code for Virginia is `US.VA`. According to the statoids site, each country has a unique two-letter code, which is the same as its ISO 3166-1 code. Then, each primary subdivision **_and_** each secondary subdivision of a country has a code that is unique within its primary division. 

So, San Francisco County, for example, would have a HASC code of `US.CA.SF`. From my understanding the UN-LOCODE does not include secondary administrative subdivisions.

**Comment by thisisaaronland** [comment]
what is the purpose / function of the HASC code?

**Comment by stepps00** [comment]
Concordance with statoids; mesoshapes (new county and locality polygon import files) will have the HASC code included as an attribute field.

**Comment by thisisaaronland** [comment]
if we can infer the UN/LOCODE from them then so much the better. The UN/LOCODE stuff is necessary for a standardized naming convention for repos.

**Comment by nvkelso** [comment]
They each go in fits and starts, sometimes Statoids leads, sometimes
UN/LOCODE, but the HASC will usually have more details available, and we
have been given permission to use the HASC codes in Who’s On First for
concordances & etc. (Both should lead ISO codes.)

**Comment by thisisaaronland** [comment]
Permissions?

The UN/LOCODEs are complete down to the region - the issue is mostly just geocoding / name matching.

**Comment by stepps00** [comment]
Related to: https://github.com/whosonfirst-data/whosonfirst-data/issues/581

**Comment by nvkelso** [comment]
Forward dup of #581.
