### ISSUE TITLE
Upgrade neighbourhood shapes for Chicago

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#385]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- Chicago Gov't:
  - City has [Community Areas](http://www.cityofchicago.org/city/en/depts/doit/dataset/boundaries_-_communityareas.html) and [Neighbourhoods](https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-Neighborhoods/bbvz-uum9)  
  - The latter seems to be closest to “identity” hoods: 
    - http://www.cityofchicago.org/content/dam/city/depts/doit/general/GIS/Chicago_Maps/Citywide_Maps/City_Neighborhoods_1978_11x17.pdf 
- The “77 Communities” are also important, used unalteringly for statistics for almost 100 years.
- https://www.google.com/maps/d/u/0/viewer?oe=UTF8&msa=0&ie=UTF8&mid=zYiwUHdW8Wmg.kNxj-e0srss0 unofficially breaks down things further.
 - Useful resource: http://yochicago.com/chicago-neighborhoods/ 
    - There were four sources: GIS sets for Community areas, large units unchanged since the 1920s; and Neighborhoods according to the city. The city PDF map of neighborhood has more neighborhood granularity, and a Google MyMap someone else did has somewhat different granularity. Items not on any of these maps I checked on Wikipedia and other reference sources, and most were historic/GNIS disused names. There were a few names on the last (Google MyMaps) that were suspect and so left off. Lots of disagreements amongst sources; I used Wikipedia as adjudicator mostly; it got pretty sparse in the far south.

**Comment by stepps00** [comment]
Per @ZBSingleton, [here](https://github.com/whosonfirst-data/whosonfirst-data/files/462467/Chicago_20160908_2.zip) is the geojson collection of Chicago boroughs, neighbourhoods, and microhoods for import. These files will be moved into S3 once the formatting and fields are verified as correct and wof-readable.

**Comment by stepps00** [comment]
Neighbourhood (and associated) features have been updated in Chicago, closing issue.
