### ISSUE TITLE
Upgrade neighbourhood shapes for Philly

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#386]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- Philly Gov't Data:
  - https://www.opendataphilly.org/dataset/neighborhoods 
from metadata (https://www.arcgis.com/home/item.html?id=021ce36cdc36453c9a82db051dde8556): 
  - Disclaimer: These are general boundaries that historically have been in place around the city. They fall along the lines of development patterns, historic references and known names. They do not follow RCO boundaries and often do not align with community groups. They should not be interpreted as "official" boundaries in any way.
  - “Registered Community Organizations”:
    - http://www.phila.gov/map#id=fa011ca0d2df46b0acb9ed35537dca21 hard map to read. 
    - Data at http://data.phl.opendata.arcgis.com/datasets/efbff0359c3e43f190e8c35ce9fa71d6_0 
- This list of current and historical hoods (see links at bottom) doesn’t differentiate, but does give pretty exact verbal descriptions of boundaries. 
  - http://www.phila.gov/phils/Docs/otherinfo/placname.htm 
- More reference: http://www.dvrpc.org/webmaps/pin/index.htm 
- Manayunk area: https://www.etsy.com/listing/78802730/philadelphia-manayunk-roxborough

**Comment by stepps00** [comment]
New and updated Philadelphia neighbourhood, microhood, and macrohood shapes are complete and in a [compressed file in S3](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20386/Philadelphia_20161018_3.zip). Source file and data review complete.

Over to @thisisaaronland for review/import.

**Comment by stepps00** [comment]
Closing issue - Philadelphia work was imported in commit 6881981.
