### ISSUE TITLE
Upgrade neighbourhood shapes for Los Angeles (city)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#387]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- LA Times has a version: 
    - http://www.latimes.com/local/la-me-map19-2009feb19-story.html
- City has signs marking entrances to some areas:
    - http://ladot.lacity.org/WhatWeDo/Operations/NeighborhoodServices/Neighborhoodsigns/index.htm
- Community Plan Areas: Map 
    - http://planning.lacity.org/
    - GIS source http://planning.lacity.org/MapGallery/MapGallery_GISdata/MapGalleryData.htm
    - http://planning.lacity.org/mapgallery/Image/MapGallery_gif/MapGallery_r5_c7.gif
    - http://planning.lacity.org/mapgallery/Image/Citywide/CPA_apc.pdf for Zoom 13
- laalmanac: 
    - http://www.laalmanac.com/LA/lamap2.htm
- Pendersleigh and Sons:
    - https://www.google.com/maps/d/u/0/viewer?mid=z6RGafGzXhx0.kKvfG2y9Qe08
- Local areas:
  - Downtown official districts:  
      - http://www.experiencela.com/community/page/DowntownLANeighborhoods
  - Skid Row: 
      - https://en.wikipedia.org/wiki/Skid_Row,_Los_Angeles
  - LA-32 note different Hills names: 
      - http://www.la32nc.org/la-32-area-boundaries/
  - Valley: 
    - https://commons.wikimedia.org/wiki/File:LA_sanfernandovalley_map.svg is not a good map, but gives a sense of priority/
  - Brentwood: https://en.wikipedia.org/wiki/Brentwood,_Los_Angeles#Notable_sights list of subhoods
  - Hollywood: http://www.amoeba.com/admin/uploads/blog/Eric_B/PendersleighSonsCartography'sMapofHollywood-3.jpeg

**Comment by stepps00** [comment]
Updated initial comment by @nvkelso after reviewing final LA neighbourhood geojson files.

LA neighbourhood geojson files are in the S3 `misc/Issue 387` folder. Files include new macrohood, neighbourhood, and microhood records as well as existing point and polygon features to deprecate. 

Over to @thisisaaronland for review and import.

**Comment by stepps00** [comment]
Closing issue. This work was completed in commit https://github.com/whosonfirst-data/whosonfirst-data/commit/247a43e208f5a8c1b02dda859f1429833593b950.
