### ISSUE TITLE
Upgrade neighbourhood shapes for Washington DC, Arlington, Alexandria

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#388]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

**Washington DC**

- 131 officially defined hoods: 
  - Wikipedia
    - https://en.wikipedia.org/wiki/Neighborhoods_in_Washington,_D.C.
  - officially located centroids for NBHD names
    - http://opendata.dc.gov/datasets/c4b0cd43d50949e98e57de9f22b455fc_35
- Washingtonpost
  - http://apps.washingtonpost.com/investigative/homicides/

**Alexandria, VA**

- http://alexandriava.gov/uploadedFiles/gis/info/SmallAreaPlans2016.pdf 
- http://www.visitalexandriava.com/plan/neighborhoods/ 
- http://www.actionalexandria.org/neighborhood-civic-associations 
- https://en.wikipedia.org/wiki/List_of_neighborhoods_in_Alexandria,_Virginia  


**Arlington, VA**

- http://gis.arlingtonva.us/Maps/Standard_Maps/Civic_Associations/Civic_Association_map.pdf 
- Data: http://gisdata.arlgis.opendata.arcgis.com/datasets/1ec04543da0546d38b63d8fd8e1019d5_19

**Comment by stepps00** [comment]
Updated and deprecated features for Washington DC, Arlington, and Alexandria are now in S3.
Files are in the [`misc/Issue 388`](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%20388) folder.

**Comment by stepps00** [comment]
Neighbourhood (and associated) features have been updated in DC, Alexandria, and Arlington, closing issue.
