### ISSUE TITLE
Upgrade neighbourhood shapes for Boston

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#389]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- Official neighborhoods: 
  - http://www.cityofboston.gov/neighborhoods/
  - http://www.bostonredevelopmentauthority.org/neighborhoods 
  - BRA data:https://data.cityofboston.gov/City-Services/Boston-Neighborhood-Shapefiles/af56-j7tb) 
- Also there are business districts and unofficial microhoods
  - https://en.wikipedia.org/wiki/Neighborhoods_in_Boston
- Dorchester sub-hoods: 
  - https://en.wikipedia.org/wiki/Neighborhoods_in_Boston#/media/File:Dorchester_MA_Neighborhoods.png
  - http://www.mydorchester.org/civic_meetings 
- Jamaica Plain sub-hoods:
  - https://en.wikipedia.org/wiki/Jamaica_Plain#Sub-neighborhoods
  - http://jamaicaplaingazette.com/jp_neighborhoods_map/
- Ancient list suggests West Roxbury subgroups: 
  - https://groups.google.com/forum/#!topic/westroxburyma/uwgr0AdCEu8

**Comment by nvkelso** [comment]
See also: 

* http://bostonography.com/2015/map-your-neighborhood-again/

**Comment by nvkelso** [comment]
Let's also include **Cambridge**.

**Comment by stepps00** [comment]
Let's _also_ include **Somerville**. 

List of potential sources (above) updated to include Cambridge and Somerville.

**Comment by stepps00** [comment]
Noting that Boston and Cambridge were merged to `master`, but Somerville is awaiting import.

**Comment by stepps00** [comment]
Neighbourhood (and associated) features have been updated in Boston, Cambridge, and Somerville, closing issue.
