### ISSUE TITLE
Upgrade neighbourhood shapes for Minneapolis/St Paul

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#390]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
Possible sources:

**Minneapolis**

- Official neighborhoods and communities (which are macrohoods). 
  - http://www.minneapolismn.gov/www/groups/public/@bis/documents/maps/convert_264339.pdf 
  - Data available from http://opendata.minneapolismn.gov/datasets?q=Boundaries
- Also a number of unofficial neighborhoods: several downtown/near-downtown areas, Uptown, and Dinkytown and 50th & France (shared with Edina). 

**St Paul**

- Official districts are groups of neighborhoods: 
  - https://www.stpaul.gov/departments/city-council/saint-paul-district-council
  - More detail at https://en.wikipedia.org/wiki/Neighborhoods_in_Saint_Paul,_Minnesota
- http://web.saintpaulchamber.com/AssociationsBusiness-Professional
- West side: 
  - neighborhood subset: http://wsco.org/?p=2260
  - Union Park neighborhoods: http://www.unionparkdc.org/our-community/about-our-neighborhoods
  - District 2 (NE corner): http://www.district2council.org/
  - District 1: SE corner: http://www.district1council.org/district.php?district=neighborhoods

**Comment by stepps00** [comment]
Updated neighbourhood records are in S3 in the `misc/Issue 390` folder.

Source: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/stpaulgov.json
Properties: https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/source_data_aliases.json#L88-L90

**Comment by stepps00** [comment]
This was completed per commit 72268ee, closing issue.
