### ISSUE TITLE
Upgrade neighbourhood shapes for Portland, Ore.

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#391]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- neighborhood associations: 
  - https://www.portlandoregon.gov/oni/article/283289	
  - More detailed: https://www.portlandoregon.gov/bps/article/59267	
- For hoods not on official association-based list: 
  - https://en.wikipedia.org/wiki/Neighborhoods_of_Portland,_Oregon#Other_areas_and_communities	
- Linnton villages/subdivisions: 
  - https://www.portlandoregon.gov/bps/article/116874
- South Portland components: 
  - https://en.wikipedia.org/wiki/South_Portland,_Portland,_Oregon

**Comment by stepps00** [comment]
Consider the updates to the Jefferson Street record, seen [here](https://github.com/whosonfirst-data/whosonfirst-data/pull/454/files) when updating Portland neighbourhoods. Jefferson Street is actually a portion of Downtown; Jefferson Street is not an actual neighbourhood in Portland.

**Comment by stepps00** [comment]
Updated initial comment by @nvkelso after reviewing final Portland neighbourhood geojson files.

Portland neighbourhood geojson files are in the S3 `misc/Issue 391` folder. Files include new macrohood, neighbourhood, and microhood records as well as existing point and polygon features to deprecate.

Over to @thisisaaronland for review and import.

**Comment by thisisaaronland** [comment]
Merged.
