### ISSUE TITLE
Upgrade neighbourhood shapes for New Orleans

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#392]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- https://data.nola.gov/Geographic-Base-Layers/NOLA-Neighborhood-Statistical-Areas/ukvx-5dku official districts. 
- Compare to http://www.nola.com/neighborhoods/maps/yatmap/index.html for actual identity.

**Comment by stepps00** [comment]
S3 has been updated with the most recent NOLA neighbourhood update files. 
Files can be found [here](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20392/nola_20161116%202.zip).

**Comment by thisisaaronland** [comment]
Merged.
