### ISSUE TITLE
Upgrade neighbourhood shapes for Atlanta

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#395]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- http://data.coaplan.opendata.arcgis.com/datasets/8cc9a5e1ab5c4c6e952dcfd9606a28ba_0 
- https://en.wikipedia.org/wiki/Luckie_Marietta#/media/File:Walking_Guide_Luckie_Marietta.jpg 
- http://www.buckhead.net/neighborhoods/neighborhood_map.html

**Comment by nvkelso** [comment]
That first link doesn't work anymore :(

Atlanta Department of Planning and Community Development GIS Data

**Comment by stepps00** [comment]
The Atlanta neighborhood data can be found here: 

- https://opendata.arcgis.com/datasets/716f417a1990446389ef7fd2c381d09f_2.zip

**Comment by nvkelso** [comment]
@stepps00 That Atlanta data is top notch, good find!

**Comment by stepps00** [comment]
@ZBSingleton - Atlanta's Office of Parks maintains a list of parks by acreage ([here](http://www.atlantaga.gov/index.aspx?page=258)) that might be useful when upgrading neighbourhood and macrohood records.

**Comment by stepps00** [comment]
Atlanta neighbourhood records have been updated and placed in the `misc/Issue 395` folder.

Source: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/atldpcd.json
Properties: https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/source_data_aliases.json#L82-L87

**Comment by thisisaaronland** [comment]
Merged.
