### ISSUE TITLE
Upgrade neighbourhood shapes for Denver

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#398]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- https://www.denvergov.org/denvermaps/documents/citywide/Neighborhoods.pdf 
- Data: http://data.denvergov.org/dataset/city-and-county-of-denver-statistical-neighborhoods 
- Unofficial: https://en.wikipedia.org/wiki/List_of_neighborhoods_in_Denver#Northeast

**Comment by stepps00** [comment]
We received an inquiry about Denver neighbourhoods from an external contributor - will update this issue once I have more information.

**Comment by stepps00** [comment]
This work will _likely_ include the Denver Metro Area, not just Denver specifically. I recently sent a geojson collection of DMA neighbourhood records to P. Hofmann (GitHub link to come) that included descendants of the following counties:

* City and County of Denver
* Arapahoe County
* Jefferson County
* Adams County
* Douglas County
* City and County of Broomfield
* Clear Creek County
* Gilpin County

Part of the Denver Metro Area, but no neighbourhood records currently in Wof:
* Elbert County
* Park County

**Comment by stepps00** [comment]
S3 has been updated with the most recent Denver neighbourhood update files.
Files can be found [here](https://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20398/Denver_20161121_2.zip).

**Comment by thisisaaronland** [comment]
Merged.
