### ISSUE TITLE
Upgrade neighbourhood shapes for San Diego

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#399]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- Official communities: http://www.sandiego.gov/planning/community/profiles/index.shtml
- Wikipedia
  - [La Jolla](https://en.wikipedia.org/wiki/La_Jolla#Neighborhoods)
  - [Point Loma](https://en.wikipedia.org/wiki/Point_Loma,_San_Diego#/media/File:Pointloma_oceanbeach_map.PNG)
  - [Downtown](https://en.wikipedia.org/wiki/Downtown_San_Diego#/media/File:SanDiegoCentral.gif)
- Each City council member has a “communities” page that shows neighborhoods: http://www.sandiego.gov/citycouncil/

**Comment by stepps00** [comment]
New files are now in S3 in the `misc/Issue 399` folder. 

Over to @thisisaaronland for import.

**Comment by thisisaaronland** [comment]
Merged.
