### ISSUE TITLE
Upgrade neighbourhood shapes for Baltimore

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#400]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- https://data.baltimorecity.gov/Neighborhoods/Neighborhoods-Shape/ysi8-7icr
- http://www.city-data.com/forum/baltimore/455189-disappearing-baltimore-neighborhoods.html

**Comment by talllguy** [comment]
Local data expert here in Baltimore if you need help. I have some contacts in the city gov.

**Comment by talllguy** [comment]
Also, I'm curious about how do you handle overlapping neighborhoods? In Baltimore, I tried [mapping the boundaries](https://gist.github.com/talllguy/201a48aa3113d3fbd225) of what neighborhood associations claim their boundaries to be in my area. I found that some neighborhoods aren't even on the official city map, and other are completely claimed by other neighborhoods.

**Comment by stepps00** [comment]
Hey @talllguy, thanks for the Baltimore neighbourhood info.. a few comments below:

* Though these shapes are derived from a neighbourhood association boundary, some of the shapes look a bit small for neighbourhoods, which makes me think (without researching each shape) that they may be microhoods (see our [placetypes repo](https://github.com/whosonfirst/whosonfirst-placetypes)).

* In terms of overlapping geometries, we should not import any overlapping neighbourhoods into Who's on First.

* [This set of neighbourhoods](https://data.baltimorecity.gov/Neighborhoods/2010-Census-Neighborhoods/r3qj-2ifh) hosted on the OpenBaltimore website has neighbourhood shapes with names, which is a much larger dataset than what's been provided by the neighbourhood associations. You may decide that an open dataset like the one in this link is worth importing, then use the neighbourhood association shapes for modifications (or additional placetype shapes).

If you'd like a neighbourhood "starter kit" for Baltimore, I'd be happy to provide one. [Here](https://github.com/whosonfirst/whosonfirst-docs/wiki/Issue-%23125---A-Guide-to-Updating-Neighbourhood-Records-in-Who's-on-First-%28part-1%29) is a link to our neighbourhood update tutorial.

**Comment by nvkelso** [comment]
Minor clarification: some neighbourhoods do overlap in reality and those
are allowed in Who’s On First. But generally speaking it’s nice to draw a
common border.

**Comment by talllguy** [comment]
@stepps00 I checked with the city government GIS team and they confirmed that the [data](https://data.baltimorecity.gov/Neighborhoods/2010-Census-Neighborhoods/r3qj-2ifh) you found on Open Baltimore is the best available neighborhood data. I recommend proceeding with using that.

Neighborhoods here are only updated decennially with the census, so there will not be another change until 2021 or so.

**Comment by stepps00** [comment]
Baltimore neighbourhood geojson files are in the S3 `misc/Issue 400` folder. Files include new and updated `borough`, `macrohood`, `neighbourhood`, and `microhood` records.

Over to @thisisaaronland for review and import.

**Comment by stepps00** [comment]
Source: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/baltomoit.json

**Comment by thisisaaronland** [comment]
Merged.

**Comment by stepps00** [comment]
hey @talllguy - we've merged new `microhood`, `neighbourhood`, and `macrohood` records for Baltimore into Who's On First! 

Feel free to check them out via our new Bundler tool ([link to descendants of Baltimore](https://whosonfirst.mapzen.com/spelunker/download/85949461/?exclude=nullisland#11/39.2847/-76.6205))

Thanks for the Baltimore info!
