### ISSUE TITLE
Upgrade neighbourhood shapes for Calgary

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#409]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- http://www.myfriendfernando.ca/files/72/Calgary%20MLS%20Map.pdf  2001 MLS map
- Community boundaries (official): 
  - https://data.calgary.ca/OpenData/Pages/DatasetListingAlphabetical.aspx#N
- Wikipedia seems decent

**Comment by stepps00** [comment]
Calgary neighbourhood (and associated) records are updated. Files are in the `misc/Issue 409` folder on S3.

Over to @thisisaaronland

**Comment by stepps00** [comment]
For post-merge clean-up: [calgary_hierarchies_templates.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1029729/calgary_hierarchies_templates.txt)

**Comment by nvkelso** [comment]
SEO: Canada

**Comment by stepps00** [comment]
Note that https://github.com/whosonfirst-data/whosonfirst-data/issues/838 should track any orphaned neighbourhood points in Calgary that were found during the update process.
