### ISSUE TITLE
Upgrade neighbourhood shapes for Paris

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#410]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- http://opendata.arcgis.com/datasets/cdc8415f32b348298050c93999a41478_0 for arrondissements.
- https://fr.wikipedia.org/wiki/Portail:Paris , Quartiers section
- https://en.wikipedia.org/wiki/Quarters_of_Paris
- https://en.wikipedia.org/wiki/Category:Districts_of_Paris (and sub categories)

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/608

**Comment by nlehuby** [comment]
This is not only in Paris, there are also some issues with neighborhood around Paris (such as the ones listed in https://github.com/pelias/wof-admin-lookup/issues/179)

Would it be useful to create some script to check if a neighbourhood is bigger than it's parent ?

**Comment by stepps00** [comment]
@nlehuby - here are all the neighbourhood records in the macroregion of Ile-of-France: https://gist.github.com/stepps00/60ad8c1e56ae01cb00b0348edd6945aa. You'll notice many of these geometries are oversized; generally we clean up surrounding neighbourhood records when upgrading neighbourhoods for a specific locality.

We welcome any contribution to Who's On First, so feel free to create a script to check geometry sizes for these records. In the meantime, I will look into fixes, per: https://github.com/pelias/wof-admin-lookup/issues/179#issuecomment-348279193.

**Comment by nlehuby** [comment]
I've already checked all the neighborhoods in Île-de-France, and only 15 of them are ok. I you can send you a list of the neighborhood that need a fix if you want.
Are they already some QA analysis I can rely on to create a script about this ?

**Comment by stepps00** [comment]
Neighbourhood files are now in the `misc/Issue 410` folder and ready for processing.

**Comment by stepps00** [comment]
Files were imported, closing issue.

**Comment by stepps00** [comment]
Reopening this to track neighbourhood updates in Paris.
