### ISSUE TITLE
Upgrade neighbourhood shapes for London

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#411]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
Possible sources:

- OS District Unitary Region for meta structure. Wards (next admin level down) less useful.
- Rough Guides
- A-Z maps
- Districts: http://londonmap360.com/london-boroughs-map#.VpPhXMArJpk 
- Useful update: http://www.wsj.com/articles/londons-extreme-makeoversfrom-gritty-to-great-1435248653 
- https://en.wikipedia.org/wiki/List_of_districts_in_Southwark  and https://en.wikipedia.org/wiki/London_Borough_of_Southwark#/media/File:Southwark_areas.png 
- Sections of Acton: https://en.wikipedia.org/wiki/Acton,_London 
- Ealing wards: http://www.ealing.gov.uk/download/downloads/id/6883/ealing_overall-ward_boundaries_map

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/225

**Comment by stepps00** [comment]
Another potential source: https://data.london.gov.uk/dataset/statistical-gis-boundary-files-london

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/225

**Comment by stepps00** [comment]
London data is in the S3 `misc/Issue 411` folder.

Adding to the Q4 priority list issue.

**Comment by stepps00** [comment]
Files were merged, closing issue.
