### ISSUE TITLE
Upgrade neighbourhood shapes for Madrid

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#413]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- http://www.ign.es/ign/layoutIn/actividadesBDGbtn100.do Administrative boundaries set for municipal boundaries
- https://en.wikipedia.org/wiki/Districts_of_Madrid

**Comment by stepps00** [comment]
Source file: https://github.com/whosonfirst/whosonfirst-sources/commit/a4b446d659f07916430e3297a1f7d4506863aade

**Comment by stepps00** [comment]
Madrid deliverables include Madrid, Mostoles, Feunlabrada, and Leganes.

Files are in the S3 `misc/Issue413` folder.

**Comment by stepps00** [comment]
Madrid and surrounding localities' neighbourhood records were updated through commits above. Closing issue.
