### ISSUE TITLE
Upgrade neighbourhood shapes for Toronto

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#414]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- Official city Nbhd data: 
  - http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=04b489fe9c18b210VgnVCM1000003dd60f89RCRD&vgnextchannel=75d6e03bb8d1e310VgnVCM10000071d60f89RCRD
- 6 component pieces of current city of Toronto
  - https://en.wikipedia.org/wiki/Toronto#/media/File:Toronto_map.png
- official hoods
  - http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=100c861b9fdb1410VgnVCM10000071d60f89RCRD
- tourism priorities
  - http://www.seetorontonow.com/explore-neighbourhoods
- http://www.torontoneighbourhoods.net/neighbourhoods
- https://en.wikipedia.org/wiki/Riverdale,_Toronto#/media/File:Riverdale_map.PNG 
- https://en.wikipedia.org/wiki/Toronto_Islands#Geography

**Comment by stepps00** [comment]
Toronto files are in the `misc/Issue 414` folder on S3. 

Dual-assigning @thisisaaronland and myself to import.

**Comment by stepps00** [comment]
For post-merge clean-up: [toronto_hierarchies.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1030260/toronto_hierarchies.txt)

**Comment by stepps00** [comment]
@thisisaaronland - Assigning this issue as one of the two neighbourhood issues for manual import.

**Comment by nvkelso** [comment]
SEO: Canada
