### ISSUE TITLE
Upgrade neighbourhood shapes for Barcelona

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#415]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Source: https://github.com/whosonfirst/whosonfirst-sources/commit/7c6c1524d3c712641a81b4efcd100de60179d175

**Comment by stepps00** [comment]
Note that before importing, we will need to include `name:spa_x_preferred` properties to any records in Barcelona.

**Comment by stepps00** [comment]
Noting that Barcelona neighbourhood files are in the S3 `misc/Issue415` folder. 

Assigning myself for import via a pipeline task.

**Comment by stepps00** [comment]
Barcelona neighbourhoods were imported through commits above. Closing issue.
