### ISSUE TITLE
Investigate and fix Spain

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#42]
WOF has the provinces, some missing diacritics, plus there are duplicates for Conjurisdicciones interprovinciales.

For reference, Statoids lists 17 autonomous communities and 2 municipalities.  Additional review of the admin hierarchy for Spain is necessary.  

Ensure name translations and default names are correct for each admin1 and admin2 record.

**Comment by nvkelso** [comment]
We need the regions from https://github.com/whosonfirst/whosonfirst-data/issues/34.
