### ISSUE TITLE
Upgrade neighbourhood shapes for Victoria (BC)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#422]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
There aren't many here, low level of effort, hopefully?

**Comment by nvkelso** [comment]
SEO: Canada

**Comment by stepps00** [comment]
Victoria records have been updated and files are now in the S3 `misc / Issue 422` folder.

Ready for import.
