### ISSUE TITLE
Upgrade neighbourhood shapes for Oakland (East Bay)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#423]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

**Oakland**

- Official : https://data.oaklandnet.com/Property/Oakland-Neighborhoods/7zky-kcq9
- https://en.wikipedia.org/wiki/List_of_neighborhoods_in_Oakland,_California
- http://www.oaklandphoto.org/map/ 

**Alameda**

- https://www.google.com/maps/d/u/0/viewer?mid=z6rKCVOy87Ak.k8eRu7xei2Zo&hl=en 
- https://www.pinterest.com/pin/229261437253544034/ 

**Berkeley**

- https://en.wikipedia.org/wiki/List_of_Berkeley_neighborhoods

**Comment by stepps00** [comment]
**Fremont**

Source: egis.cofgis.opendata.arcgis.com/datasets/044ae5a42d924d9b94dba5c42a539c78_0
License: https://fremont.gov/DocumentCenter/View/28876

**Comment by nvkelso** [comment]
We looked at Berkeley and Mountain View, but no ready GIS data of high quality so calling it done at Oakland alone. Make new issues for additional cities.

**Comment by stepps00** [comment]
Oakland neighbourhood records are finalized and have been placed in the S3 `misc/Issue 423`. Files include new and updated `borough`, `macrohood`, `neighbourhood`, and `microhood` records.

Source used for Oakland: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/oakced.json

**Comment by thisisaaronland** [comment]
Merged. Venues will be pushed to master shortly.

**Comment by nvkelso** [comment]
Awesome!
