### ISSUE TITLE
Upgrade neighbourhood shapes for San Jose, Calif.

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#424]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible sources:**

- Official map
  - https://www.sanjoseca.gov/DocumentCenter/View/757
  - But: “boundaries shown on the map do not necessarily represent commonly recognized neighborhoods, and may differ from what residents perceive as their neighborhood” 
  - So.. Ignore numbers, zoom WAY IN
  - We're currently missing many of these places from WOF :\
- Wikipedia:
  - https://en.wikipedia.org/wiki/San_Jose,_California#Geography 
- Tourism focused:
  - http://www.sanjose.org/maps-more/neighborhoods/
- http://www.fortunebuilders.com/san-jose-real-estate-and-market-trends/
- http://sjdowntown.com/live-here/neighborhoods/ for downtown

**Comment by stepps00** [comment]
Neighbourhood geojson files for San Jose are in the S3 `misc/Issue 424` folder. Files include new and updated `macrohood`, `neighbourhood`, and `microhood` records.

Over to @thisisaaronland for review and import.

**Comment by stepps00** [comment]
Closing this issue, San Jose files have been imported.
