### ISSUE TITLE
Investigate and fix Taiwan

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#43]
WOF has 18 counties with spelling issues and 2 features from the Philippines due to an error in the ISO code supplied by quattroshapes.  See qs:id = 986044 & 212884

For reference, Statoids lists 2 provinces and 5 special municipalities.  The next level down is county (22 of them).

**Comment by nvkelso** [comment]
Might have a hint of https://github.com/whosonfirst/whosonfirst-data/issues/34?

**Comment by stepps00** [comment]
Closing this issue - mesoshapes import for Taiwan is complete and the Statoids import is in progress. 

Who's On First has matching placetype counts with Statoids and a follow-up issue to add additional admin data for Taiwan is being tracked in: https://github.com/whosonfirst-data/whosonfirst-data/issues/638
