### ISSUE TITLE
Duplicate counties in Chile

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#432]
Looks like we have 19 duplicate county records (usually an accent mark off in name from each other). We need to supersede the point one into the polygon one (and copy over properties).

**Comment by stepps00** [comment]
890517525 -> 102063187, Aisen
890517541 -> 102063139, Los Andes
890517873 -> 102063073, Antofagasta
890517963 -> 102063165, Arica
890517459 -> 102063151, Biobio
890517439 -> 102063173, Chacabuco
890518173 -> 102063133, Charanal
890518137 -> 102063179, Choapa
890517437 -> 102063137, Cordillera
890518139 -> 102063147, Curico
890517687 -> 102063119, Provincia de Maipo
890517685 -> 102063117, Provincia de Santiago
890517435 -> 102063181, Provincia de Parinacota
890517457 -> 102063145, Provincia de Iquique
890517689 -> 102063175, Provincia de Huasco
890518353 -> 102063075, Magallanes 
890518069 -> 102063093, Tocopilla 
890518071 -> 02063183, Validivia 
890518141 -> 102063109, Ñuble

**Comment by stepps00** [comment]
Note: logic in the mesoshapes import script will take care of this issue. Leaving open until the new mesoshape features are imported.

**Comment by nvkelso** [comment]
Closing in favor of #494.
