### ISSUE TITLE
Puerto Rican WOF records have US ISO

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#436]
The following 4 WOF records are in Puerto Rico and have ISO `US`:

https://whosonfirst.mapzen.com/spelunker/id/85633729/descendants/?exclude=nullisland&iso=us#11/18.3851/-66.0980

This differs from the rest of the WOF records (397) in Puerto Rico but have ISO `PR`:

https://whosonfirst.mapzen.com/spelunker/id/85633729/descendants/?exclude=nullisland&iso=pr#9/18.2253/-66.0515

Even though WOF treats Puerto Rico as a dependency and not a country, which is the correct ISO?

**Comment by thisisaaronland** [comment]
Well, the first thing to remember is that `iso:country` != `wof:country`

Specifically `iso:country` should reflect what the ISO peeps think is correct, which doesn't always reflect reality – for example Puerto Rico is not _actually_ a country. `wof:country` reflects the truthiness of countries and the hierarchies.

None of which precludes the data is WOF currently being incorrect.

**Comment by trescube** [comment]
That's fine, it's not a huge deal, I just noticed what appears to be an inconsistency.  I don't think this negatively affects Pelias performance.

**Comment by stepps00** [comment]
Thanks @trescube 

Relatively quick fix, PR is out for this issue. This like the same issue as https://github.com/whosonfirst-data/whosonfirst-data/issues/211.. will revisit soon to crawl WoF records to update these mismatches.

**Comment by nvkelso** [comment]
This PR: https://github.com/whosonfirst-data/whosonfirst-data/issues/453

**Comment by nvkelso** [comment]
Closed via #453.
