### ISSUE TITLE
Investigate and fix UK

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#44]
WOF has 232 features.  Some names match the primary subdivisions, some names have # symbols, many names have "City of" prefix.  Thorough review needed.

For reference, Statoids lists 185 divisions.

**Comment by nvkelso** [comment]
We'll need to link in the constituent countries to the hierarchy; those will be imported in https://github.com/whosonfirst/whosonfirst-data/issues/34.

**Comment by stepps00** [comment]
Counts may be slightly off of [what is shown in Statoids](http://statoids.com/ugb.html), but recent UK updates per https://github.com/whosonfirst-data/whosonfirst-data/pull/1368 have corrected counts at placetypes (except locality) in the UK.

Closing in preference of newer issues.
