### ISSUE TITLE
Move NYC borough properties from neighbourhood to borough

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#441]
Now that we have **boroughs**, they are coming thru tiles (good), but without any of the interesting stuff like `mz:min_zoom` and the language variants (sad). 

The existing 5 neighbourhoods (Brooklyn, Queens, Bronx, Manhattan, Staten Island) need to be superseded into their borough equivalents, and relevant properties copied over, too.

Eg: 
- Brooklyn borough: https://whosonfirst.mapzen.com/spelunker/id/421205765/#11/40.6529/-73.9379
- Brooklyn neighbourhood: https://whosonfirst.mapzen.com/spelunker/id/420782855/#11/40.6529/-73.9379

NOTE: For Brooklyn looks like we don't have any language variants. Adding those is a task for another day.

**Comment by stepps00** [comment]
Noting that the copied over attributes and superseding of records occurred in [this branch](https://github.com/whosonfirst-data/whosonfirst-data/commit/1485d6a050ff316e9d8d59e334265c7211481d94). Waiting for #384 to be complete to open a PR (if needed).

**Comment by nvkelso** [comment]
Forward dup of https://github.com/whosonfirst-data/whosonfirst-data/issues/384
