### ISSUE TITLE
Upgrade neighbourhoods in Helsinki, Finland

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#442]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Upgrade** locality record's shape
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
In continuation of https://github.com/whosonfirst-data/whosonfirst-data/issues/315 / https://github.com/whosonfirst-data/whosonfirst-data/issues/99

**Possible sources:**
* [Official data for Helsinki](http://koti.kapsi.fi/~hannes/Neighborhoods_Helsinki.geojson.zip) is provided by [the city of Helsinki](http://www.hri.fi/en/dataset/helsingin-kaupunginosat) under CC-BY-4.0.

**Comment by vesameskanen** [comment]
Hi @stepps00 , I have compiled a data package available at:

 https://drive.google.com/file/d/0Bwdm9jYX7iFWdUxVRl8xb25SRkU/view

It contains neighbourhood geometries for 5 largest cities in Finland +a couple of medium size cities. The zip file includes the following files:
- 7 geojson files for the cities. wof name (which is also name:fin_x_preferred) is stored in the geojson name field, and optional swedish name in name:swe_x_preferred field
- Data sources description file (url, file names etc). All provided data is open and licensed under CC-BY-4.0.
- Update log file in csv format. It explains how to update existing wof neighbourhood entries, which entries should be deleted, and which  are the new entries. There are small set of entries in the log file labeled as 'unknown'; I could not get data for those so they can probably stay as they are now.

Just let me know if I can do something more to assist in the process. We are now using neighbourhood data in our Pelias geocoding service, and the existing really poor quality data damages our service quite a lot.

**Comment by vesameskanen** [comment]
A quick question: I made a couple of test requests to cities, which do not yet publish their map data using an open data license.  It seems to be  fairly easy to get the data. What is your opinion: can you use such contributions if there's no official data license available, but just a permission from the city employees to publish it it whosonfirst?

**Comment by stepps00** [comment]
Note: I've updated the initial issue comments to include a checkbox for updating the `locality` record's shape. The new `locality` shape should be the dissolved boundary of all neighbourhood features.

**Comment by stepps00** [comment]
Hi @vesameskanen (cc @hannesj) - do you have any information on the administrative divisions in Kauniainen? It appears that the `Nimi` fields in the geojson properties are blank. Is there a source you are aware of that lists names for these places?

Thank you!

**Comment by vesameskanen** [comment]
Hello @stepps00 

It's great to hear that you are proceeding with the neighbourhood data!

I checked Kauniainen and found out that it is officially divided into 4 regions, which could be considered as neighbourhoods. Only one of them has a proper name, and others are just numbered as I, II and III.  So, blank names are kind of correct for numbered areas (I guess it is just a techinical way to reference them, and not used by inhabitants of Kauniainen),   

The only named region seems to match the westmost and largest part of the geojson data I provided for you. It is called Kasavuori (name:swe_x_preferred = Kasaberget). 

I hope this helps!

**Comment by hannesj** [comment]
Actually the first three neighborhoods are referred just by their numbers even in speech, i.e. in Finnish "2. osa", which is the equivalent of "2nd neighborhood" in English.

**Comment by stepps00** [comment]
@hannesj and @vesameskanen - thanks, this is helpful. This is a unique case, as all of our imported features should have a `wof:name` field. If the spoken name for the features in Kauniainen are "first neighbourhood" or "second neighbourhood" that will likely go into the `wof:name` space.

Thank you for the name information!

**Comment by vesameskanen** [comment]
Hi @stepps00 , have you made any progress with the neighbourhood data? Just let us know if we can improve the data or help you in some other way. We plan to make a production release by the end of this year, and it would be great to get the data issues fixed before that.

**Comment by nvkelso** [comment]
It should be merged in December. We’re working thru wrangling PIP hierarchy
building on counties first, then will get to this set (and other)
neighbourhoods.

**Comment by vesameskanen** [comment]
Hi again - I'm sorry to push you, but is there any change to get the  Finnish neighborhood data imported in the near future?

**Comment by stepps00** [comment]
@vesameskanen - we are in the process of importing a large amount of `county`-level data into Who's On First and will begin importing updated neighbourhood records soon after. Stay tuned, I will update this issue once that process begins :)

**Comment by stepps00** [comment]
Helsinki neighbourhood geojson files are in the S3 `misc/Issue 442` folder. Files include new and updated `borough`, `macrohood`,`neighbourhood`, and `microhood` records.

Over to @thisisaaronland for review and import.

**Comment by hannesj** [comment]
@thisisaaronland Do you have any estimate when you could have these imported? It would make us very happy, as we are getting quite much feedback on the current neighbourhoods, which are quite bad.

**Comment by hannesj** [comment]
@stepps00 would it be possible to get access to the GeoJSONs generated, if there is a risk that they  will not be merged in the near future?

**Comment by thisisaaronland** [comment]
I can look at merging all of this sometime this week.

**Comment by nvkelso** [comment]
@hannesj The [GeoJSON files on S3](http://whosonfirst.mapzen.com.s3.amazonaws.com/misc/Issue%20442/Helsinki_20161110.zip) that Stephen refers are in an intermediate state, not fully formatted WOF records meaning they can't be slotted into an existing `whosonfirst-data` repo without further processing. But if you want a quick preview they will open in QGIS.

**Comment by thisisaaronland** [comment]
Merged.

**Comment by vesameskanen** [comment]
This is great news for us! Thank You!

**Comment by thisisaaronland** [comment]
@vesameskanen – We spotted some errors where existing placetypes were not getting their geometries updated properly. That should be fixed in a day or so. Apologies for the confusion.

**Comment by hannesj** [comment]
@thisisaaronland It seems there is still duplicate entries, and some new neighbourhoods were incorrectly superseded by the old entries. Could you check the imported data?

Example of duplicate
https://whosonfirst.mapzen.com/spelunker/id/1108726973/
https://whosonfirst.mapzen.com/spelunker/id/1108938477/

Incorrectly superseded:

https://whosonfirst.mapzen.com/spelunker/id/1108727197
https://whosonfirst.mapzen.com/spelunker/id/85898897

**Comment by stepps00** [comment]
Thanks @hannesj - I will take a look shortly.

**Comment by stepps00** [comment]
@hannesj - we've pinpointed the issue of incorrect superseding in Helsinki records and the Spelunker should be updated shortly. In the meantime, the records in Github should have the correct superseding work done:

  - https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/110/872/719/7/1108727197.geojson
  - https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/858/988/97/85898897.geojson

As for the point features, we've imported a few duplicate point records that are being updated and tracked in issue https://github.com/whosonfirst-data/whosonfirst-data/issues/740. Those features will be updated shortly - stay tuned!
