### ISSUE TITLE
Duplicate Pago Pago

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#448]
This [Pago Pago](https://whosonfirst.mapzen.com/spelunker/id/890449627/#13/-14.2836/-170.6444) and this [Pago Pago](https://whosonfirst.mapzen.com/spelunker/id/101734459/#12/-14.2512/-170.7168) appear to be duplicates.  They are both localities.  The former has a complete hierarchy while the latter is just parented by the United States only.

**Comment by stepps00** [comment]
The [Pago Pago record](https://whosonfirst.mapzen.com/spelunker/id/890449627/#13/-14.2836/-170.6444) with a point geometry was superseded (and deprecated) into the [Pago Pago record](https://whosonfirst.mapzen.com/spelunker/id/101734459/#12/-14.2512/-170.7168) with a polygon geometry. All properties were added to the "current" Pago Pago record.

Closing this issue.
