### ISSUE TITLE
Don't forget Yugoslavia

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#45]
https://en.wikipedia.org/wiki/Yugoslavia

We should ensure that we have (n) number of records for the former Yugoslavia if only to kick the tires on the tools around:
- supersedes/superseded_by
- dates – what do we call things?

**Comment by stepps00** [comment]
Note: before merging PR, update Yugoslavia links in: https://github.com/whosonfirst/whosonfirst-dates#yugoslavia
