### ISSUE TITLE
Sanity check hierarchies for string values

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#450]
In a [recent commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/d620add81e9c3dd6f92bfb38eb5bb8420e100a89), several hierarchies were built with strings instead of integers. For example, our [locality record for Luwuk, Indonesia](https://whosonfirst.mapzen.com/data/102/019/927/102019927.geojson) now has the following hierarchy:

```
    "wof:hierarchy":[
        {
            "continent_id":"102191569",
            "country_id":"85632203",
            "locality_id":102019927,
            "region_id":85672111
        }
    ],
```

This problem caused merge conflicts for at least one pull request. I'm not certain if this was the only commit that updated string values to the hierarchy, but we should revert these edits and sanity check all hierarchies for this issue.

Complete this work for **all** records in the data repository.

Links to other features with this issue: [1](https://whosonfirst.mapzen.com/spelunker/id/102020057), [2](https://whosonfirst.mapzen.com/spelunker/id/102020331), [3](https://whosonfirst.mapzen.com/spelunker/id/102020525).

**Comment by stepps00** [comment]
Related: #500

**Comment by stepps00** [comment]
This issue is also occurring in the `wof:supersedes` property (see: [this record](https://data.whosonfirst.org/110/880/610/9/1108806109.geojson)).

**Comment by thisisaaronland** [comment]
cc @vicchi because he is writing Tools for this.

**Comment by vicchi** [comment]
@steps00 @thisisaaronland This is indeed true. 

Several tools in fact, to generate JSON scheme from the properties files, to validate the WOF docs against the scheme (which flags these inconsistencies and many others as well) and to fix those inconsistencies. 

Expect pull requests for all of this to arrive sometime towards the end of this week, free time permitting.

**Comment by vicchi** [comment]
@stepps00 and schema. Sigh. Githubs mobile UI and mobile autocorrect failed me there.

**Comment by stepps00** [comment]
Closing this issue, as #1190 has landed. Will open a new issue(s) if this appears in the future.
