### ISSUE TITLE
merge multiple records for Ramallah PS

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#451]
https://whosonfirst.mapzen.com/spelunker/id/101921943/

https://whosonfirst.mapzen.com/spelunker/id/101921973/
https://whosonfirst.mapzen.com/spelunker/id/101921953/

Let's keep `101921943` since it has the most number of concordances already.

**Comment by nvkelso** [comment]
This will be taken care of by #532, closing this.
