### ISSUE TITLE
Merge Downtown and Jefferson Street neighbourhood records in Portland, OR

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#459]
In response to an [external PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/454), we need a quick-fix for the [Jefferson Street](https://whosonfirst.mapzen.com/spelunker/id/85868953/#15/45.5204/-122.6745) and [Downtown](https://whosonfirst.mapzen.com/spelunker/id/85867131/#14/45.5125/-122.6780) neighbourhood records in Portland, OR. Open a new PR that includes the following:
- Create a new Downtown record that is a copy of the old Downtown record (and all it's properties), adding in the additional shape geometry from this weird Jefferson record (almost doubling Downtown's size). 
- Supersede both old Downtown and Jefferson into the new Downtown
- Mark Jefferson as deprecated since it seems to just be junk.

**Comment by nvkelso** [comment]
Forward dup of #391.
