### ISSUE TITLE
Clean up descendant in Serbia with no wof:name

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#462]
See: https://whosonfirst.mapzen.com/spelunker/id/404228357/#7/43.688/21.044

Supersede, deprecate (or add cessation date) this `macroregion` record in Serbia. All other descendants in Serbia have wof:name field values.

**Comment by stepps00** [comment]
This geometry looks to be a combination of five regions in Serbia, not a valid macroregion. The geometry of this feature covers the regions of _Šumadija, Western Serbia, Eastern Serbia, Southern Serbia,_ and the _Province of Belgrade_. ([Main source](https://en.wikipedia.org/wiki/List_of_districts_of_Serbiahttps://en.wikipedia.org/wiki/List_of_districts_of_Serbia)).

Suggest deprecating the [macroregion with no name](https://whosonfirst.mapzen.com/spelunker/id/404228357/#7/43.688/21.044) in Who's on First and replacing it with the the following macroregions: 

* Šumadija
* Western Serbia
* Eastern Serbia
* Southern Serbia
* Province of Belgrade

We also have:
* [Vojvodina](https://whosonfirst.mapzen.com/spelunker/id/404227537/#7/45.418/20.198) in WoF already, may have to change if we decide to change `wof:placetype` for these features.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/53

**Comment by ndcartography** [comment]
For: https://whosonfirst.mapzen.com/spelunker/id/404228357/#7/43.688/21.044

The new `wof:name` would be Central Serbia, a province of Serbia. 
Sources:
    - https://en.wikipedia.org/wiki/Central_Serbia
    - ![serbian_provinces](https://user-images.githubusercontent.com/24629743/28036180-3a44bc3c-656c-11e7-8fb9-f6256e7c0083.jpg)


This change will be made in: https://github.com/whosonfirst-data/whosonfirst-data/pull/852

**Comment by stepps00** [comment]
This (and others) was fixed once https://github.com/whosonfirst-data/whosonfirst-data/pull/852 was merged.

Other records with missing `wof:name` values are being tracked in https://github.com/whosonfirst-data/whosonfirst-data/issues/53.

Closing issue.
