### ISSUE TITLE
Duplicate Hainan regions in China

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#463]
These possibly refer to the same thing:

https://whosonfirst.mapzen.com/spelunker/id/85669759/#8/19.169/109.825

and 

https://whosonfirst.mapzen.com/spelunker/id/85632557/#8/19.166/109.943

**Comment by nvkelso** [comment]
Confirmed, they are dups. One of them used to be a country, so at least this is an improvement? 😉 

@stepps00 Can you merge these, please?
