### ISSUE TITLE
Centar Župa appears to be a locality, not a region

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#465]
According to [OSM](https://www.openstreetmap.org/relation/6476393) and [wikipedia](https://en.wikipedia.org/wiki/Centar_%C5%BDupa_Municipality), [Centar Župa](https://whosonfirst.mapzen.com/spelunker/id/85674385/#11/41.4637/20.5800) appears to be a locality and not a region.  The population (6,977) seems low for a region and is roughly in agreement with wikipedia (6,519).  According to wikipedia, Centar Župa belongs to a region named Southwestern Statistical Region.

**Comment by stepps00** [comment]
Thanks @trescube.

Upon further inspection, it appears that the [Centar Župa](https://en.wikipedia.org/wiki/Centar_%C5%BDupa) is an actual region. Centar Župa is _also_ the name of a locality (and administrative seat to the region ([source](https://en.wikipedia.org/wiki/Centar_%C5%BDupa))).

Statoids lists 84 "municipalities" in Macedonia, which map cleanly to the [84 Macedonian region records in Who's on First](https://whosonfirst.mapzen.com/spelunker/id/85632373/descendants/?exclude=nullisland&placetype=region#8/41.626/21.481). The confusion is that localities and regions often share names in Macedonia and Who's on First does not currently have abundant locality records for Macedonia. We're also calling the "municipality" subdivisions "regions".

Likely to close this issue, cc'ing @nvkelso for verification.

**Comment by nvkelso** [comment]
Long live unitary geographies!
