### ISSUE TITLE
Improve Australian postcodes

### ISSUE THREAD

**Issue by rowanwins** [whosonfirst-data/whosonfirst-data#472]
Gday WOF team,

I raised an issue over in the data [repo](https://github.com/whosonfirst-data/whosonfirst-data-postalcode-au/issues/1) but I thought I'd replicate it here as it looks like this might be a bit more active.

The Australian Postcodes are currently generated using the Clustr tool however the resulting polygons  look to be pretty coarse and there are potentially alternative sources for this info. For example the[ Australian Bureau of Stats](http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.003July%202011?OpenDocument) has a shp file available from 2013 or some of the [states](https://www.data.vic.gov.au/data/dataset/postcode-boundaries-polygon-vicmap-admin) also publish their postcode data sets.

Anyway I'm not entirely sure how to best tackle updating the features, it doesn't exactly look like a straightforward task so I thought I'd raise it here!

I've also got a few other ideas for some other australian admin boundaries based around[ this open data set](http://data.gov.au/dataset/psma-administrative-boundaries) so if you require any info let me know.

Cheers
Rowan

**Comment by stepps00** [comment]
Hey @rowanwins, thanks for filing the issue!

You're correct about the coarse shapes of our [current Australian postal code records](https://whosonfirst.mapzen.com/spelunker/id/85632793/descendants/?exclude=nullisland&placetype=postalcode#4/-23.59/151.17) - the `src:geom` field indicates these shapes are coming from [OpenAdresses](https://openaddresses.io/).

Ideally, we would map the new shapes from the Australian Bureau of Stats to our existing records. We also have [this issue](https://github.com/whosonfirst-data/whosonfirst-data/issues/218) open to look into importing admin boundaries. We will investigate and get back to you, thanks!

**Comment by rowanwins** [comment]
Gday @stepps00 

I did have a vague idea in mind that it perhaps wouldn't be too hard to update the existing records from the shapefile with a nodejs script and using something like turf to generate things like the bounding box and area etc. Where my lack of understanding ran out was how to generate new records for those postcodes that you haven't already captured. 

Anyway if you'd like me to take a look at a node script to update the existing records from the Burearu of Stats data let me know.

**Comment by stepps00** [comment]
Hey @rowanwins, you're welcome to run the node.js script to test out updating the geometries of the Australian `postalcode` records, but we'd likely import the new shapes in-house. To answer your question about new records that Who's On First does not know about - we would mint a new `wof:id` and create a completely new feature (with new attributes and a new hierarchy) for each new post code.

Not only do we need to update the geometries, but we also have to:

1. Store the existing geometry as an `alt-geometry` record
2. Update the hierarchies of all descendants under each `postalcode` record in Australia (requires running our PIP server).
3. Deprecating "bad" geometries that were never correct to begin with
4. Potential work with the `supersedes` and `superseded_by` fields

As I said, feel free to test out your node.js script, but we have additional steps to take.. I'll keep this Issue open until import, so keep an eye out for updates!

**Comment by rowanwins** [comment]
Gday @stepps00 

Well I have a [first cut ](https://gist.github.com/rowanwins/058a783c86e5b68972f7c5d6a17d7734) of a nodejs script which seems to be working quite well.

So for example we go from something like [this](http://geojson.io/#id=gist:anonymous/365cf01bf42c917549b12c39e35e657a&map=11/-31.1647/150.7551) to [this](http://geojson.io/#id=gist:anonymous/c28a5ae3b254a212fa642b4d66568947&map=11/-31.1662/150.7403)

Attributes I've updated so far
- geometry
- bbox
- geom:latitude
- geom:longitude
- area_square_m

I'd be happy to push up my results to a [fork of the repo](https://github.com/rowanwins/whosonfirst-data-postalcode-au) if you'd like .

It is a bit of a shame that is so hard to contribute to WOF, so many tasks that need to be done :(

**Comment by stepps00** [comment]
Hey @rowanwins, the new geometries look great! Thanks for doing the work to upgrade these features.

The intention is not to make it difficult to contribute to WOF; we encourage you to contribute new geometries for features that could be updated. Are you able to provide a geojson file that includes a `wof:id` and new geometry for each `wof:id` (`bbox` and `geom` fields are fine, too)? 

If so, we can update the current postalcode records in Australia. This would be an easier workflow than forking the repo.

**Comment by stepps00** [comment]
Note: a [new source](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/ausstat.json) has been created for the Australian Bureau of Statistics.

**Comment by nvkelso** [comment]
Looks like there aren't any other interesting attributes to bring in from the source (http://services.land.vic.gov.au/catalogue/metadata?anzlicId=ANZVI0803003025&publicId=guest&extractionProviderId=1#tab2).

**Comment by rowanwins** [comment]
Hi @stepps00 

I've whacked up a [repo](https://github.com/rowanwins/wof-au-postcodes-abs) containing a zip file of all the relevant geojson files, it contains about 2500 files.

And [here is](http://geojson.io/#id=gist:anonymous/aa057abd6ddc4f8e3b5c0fa7f1764049&map=14/-16.0697/136.3086) a sample of what the geojson files look like,

Cheers
R

**Comment by stepps00** [comment]
@rowanwins - Fantastic! Thanks for compiling these new geometries. We'll take a look at these geometries and let you know if we have any questions. I'll update this issue as things progress.

**Comment by stepps00** [comment]
Hey @rowanwins - I wanted to give you an update on the AUS postalcode work. I've created a feature collection of all postalcode records in Australia and am currently working on a script to do the following:

- Import the new geometry to the existing WOF record
- Append the `POA_NAME` attribute to the existing WOF record
- Save the existing geometry in WOF as an `alt-geom` record
- Deprecate any non-matching records in WOF (which looks to be none right now)

Noting: Four source features were new to Who's On First and given new `wof:id`s, they will be imported as new features. Three source features (`9797`, `9494`, and `9191`) will not be imported because they have no geometry and are used by the post service as placeholders for unclassified postal areas.

My goal is to land a PR with these updates this week, so stay tuned.

**Comment by rowanwins** [comment]
Awesome, thanks for the update @stepps00 !

**Comment by stepps00** [comment]
@rowanwins - Australian postalcode records have been updated in https://github.com/whosonfirst-data/whosonfirst-data-postalcode-au/pull/2#issuecomment-259523542. Thanks again for the issue!

**Comment by rowanwins** [comment]
yay, thanks @stepps00 !
