### ISSUE TITLE
Copy `meso:hasc_id` into concordances list

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#479]
For all the Mesoshape imports, we didn't notice ahead of time that `"meso:hasc_id":"CD.KN.KN"` should really also go into the concordance list (as `hasc:id`:*).

Once those PRs are landed, crawl over the features and "make it so".

**Comment by nvkelso** [comment]
Such as: 

- https://github.com/whosonfirst-data/whosonfirst-data/pull/467
- https://github.com/whosonfirst-data/whosonfirst-data/pull/468
- https://github.com/whosonfirst-data/whosonfirst-data/pull/469
- https://github.com/whosonfirst-data/whosonfirst-data/pull/470
- https://github.com/whosonfirst-data/whosonfirst-data/pull/471
& etc

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/480

**Comment by stepps00** [comment]
Related: #515

**Comment by stepps00** [comment]
Looks like this was taken care of in: https://github.com/whosonfirst-data/whosonfirst-data/commit/02831853557f2734e0a49b7be70790a8fb43037b

We should leave this issue open until the mesoshapes imports settle, though, to make sure we catch all `hasc` property fields in all `county` and `region` features.

**Comment by stepps00** [comment]
PR  #869 tracks this issue. Commit 02831853557f2734e0a49b7be70790a8fb43037b took care of #515.
