### ISSUE TITLE
Create new region polygons out of mesoshape county children

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#486]
We are landing 1000s of new high quality polygons for counties, but they are often still parented by not-so-great Natural Earth sourced region polygons. We should dissolve the mesoshape counties together per country and update their parents with new grey matter.

At minimum, each new set of `region` polygons should contain the following fields:
* Name
* HASC 
* Source
* mps_x
* mps_y

**Comment by stepps00** [comment]
Suggesting the following workflow to create region polygons out of mesoshapes county files:

In each country file:
- [ ] Create new field equal to the first five characters in the `HASC` field (ex: `IN.OC`)
- [ ] Dissolve each country files on that new field
- [ ] Admin region field (in most country files) will be used as new `wof:name`
- [ ] **Deprecate / supersede** WOF features
- [ ] **Draft review**
- [ ] **Draft revisions** based on review comments
- [ ] **Final review**
- [ ] **Final revisions** based on review comments
- [ ] **Import** into Who's On First

This will require some modifications to the import script, but the workflow should give us the names, geometries, and concordances we need for WOF.

**Comment by nvkelso** [comment]
For instance, [Megri Shrjan](https://whosonfirst.mapzen.com/spelunker/id/421190417/#13/38.8638/46.2013) should be in Azerbaijan but is listed in Iran currently.

**Comment by nvkelso** [comment]
These would be `"src:geom": "mapzen"` for the default geometry for the records, and preserve existing geom (often from Natural Earth) into an alt.

**Comment by nvkelso** [comment]
We think the following issues will be mostly resolved once this lands (but should be confirmed):

- #67 Investigate and fix Armenia admin-1 region
- #66 Investigate and fix Albania admin-1 region
- #65 Investigate and fix Afganistan admin-1 region
- #64 Investigate and fix and/or add alternate spelling for UAE emirates admin-1 region
- #43 Investigate and fix Taiwan admin-1 region
- #40 Investigate and fix Serbia admin-1 region
- #38 Investigate and fix Papua New Guinea admin-1 region admin-2 county meso
- #37 Investigate and fix Nepal admin-1 region admin-2 county meso
- #33 Investigate and fix Madagascar admin-1 region
- #24 Investigate and fix Burkina Faso regions admin-1 region
- #23 Investigate and fix Bosnia & Herzegovina regions admin-1 region

**Comment by stepps00** [comment]
This was completed through #660.

Closing issue.
