### ISSUE TITLE
non numeric postcodes for Germany

### ISSUE THREAD

**Issue by mtmail** [whosonfirst-data/whosonfirst-data#488]
The https://github.com/whosonfirst-data/whosonfirst-data-postalcode-de repository contains a couple of postcodes which don't follow the 5-digit format. It's surprising all those start with the letter `Z`

```
for f in `find whosonfirst-data-postalcode-de/ -name *.geojson`; do grep 'wof:name' "$f" | perl -nE'/\d{5}/||print'; done
    "wof:name":"Zippelsf\u00f6rde",
    "wof:name":"Zippern",
    "wof:name":"Zippfeld",
    "wof:name":"Zippendorf",
    "wof:name":"Neu Zippendorf",
    "wof:name":"Zipfen",
    "wof:name":"Zipke",
    "wof:name":"Zippelow",
    "wof:name":"Zipplingen",
    "wof:name":"Zips",
    "wof:name":"Zipsendorf",
    "wof:name":"Zipfleck",
    "wof:name":"Zippelkoog",
    "wof:name":"Stadtteil Zipkeleben",
    "wof:name":"St\u00e4dt. Kindergarten Zipfelm\u00fctze",
    "wof:name":"Kinderstube Zipfelm\u00fctze",
    "wof:name":"Kindergarten Zipfelm\u00fctze",
    "wof:name":"Kindergarten Eikita Zippel u Zappel",
    "wof:name":"Stadtteilbibliothek Neu Zippendorf",
```

**Comment by stepps00** [comment]
Hey @mtmail - thanks for filing the issue! We'll take a look and update the issue once resolved.

**Comment by stepps00** [comment]
@mtmail - I'm going to close this issue and refer to [this issue](https://github.com/whosonfirst-data/whosonfirst-data-postalcode-de/issues/1) for non-numeric postalcode name fields.

The records listed above will be deprecated in a PR in the `whosonfirst-data-postalcode-de/` repo. Thanks again for the issue!
