### ISSUE TITLE
admin-2 counties have name encoding errors

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#49]
Turns out there was 17 features with funky names in New Mexico and Puerto Rico (thanks US Census). These features cause import to fail, and while casting them as latin1 or another encoding "fixes" these records, it terribly mangles most other records. 

- [x] debug problem
- [x] draft fix
- [ ] verify fix
- [ ] post fixed file to quattroshapes.org site
- [ ] reimport updated Quattroshapes admin-2 counties to fix name encoding errors

**Comment by nvkelso** [comment]
@missinglink has verified the fix for the 17 features, but needs to also verify the change was positive for all the other records.

**Comment by dianashk** [comment]
Found this encoding issue in a county

[the county of VÃ¶lkermarkt](https://whosonfirst.mapzen.com/spelunker/id/102049685/) should be `Voelkermarkt`

**Comment by stepps00** [comment]
Seems like this is no longer an issue in [New Mexico](https://whosonfirst.mapzen.com/spelunker/id/85688493/descendants/?placetype=county#6/34.167/-106.330) or [Puerto Rico](https://whosonfirst.mapzen.com/spelunker/id/85687331/descendants/?placetype=county&exclude=nullisland&page=1#9/18.2228/-66.7570). 

Discussed this issue with @missinglink, who suggested closing the issue and taking care of encoding issues individually if/when they arise.
