### ISSUE TITLE
New Indian State: Telangana

### ISSUE THREAD

**Issue by tallytalwar** [whosonfirst-data/whosonfirst-data#497]
As of 2nd June, 2014, Indian state [Andhra Pradesh](https://whosonfirst.mapzen.com/spelunker/id/85672141/#6/16.295/80.750) was divided and a new state "Telangana" was formed, previous this was a [locality](https://whosonfirst.mapzen.com/spelunker/id/890501051/#6/16.295/80.750).

Reference Docs: 
https://en.wikipedia.org/wiki/File:India_Telangana_locator_map.svg
https://lists.openstreetmap.org/pipermail/talk-in/2014-May/001963.html
http://www.openstreetmap.org/search?query=telangana#map=4/17.81/97.16
https://en.wikipedia.org/wiki/States_and_union_territories_of_India
https://github.com/geohacker/india/blob/master/state/india_telengana.geojson

**Comment by stepps00** [comment]
[This commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/be538aafe8e77e8be66e03172a3e812faa709a33#diff-6d6e9d064a6d75ef96249d885c9f51b9R17) updates all `region` records in India and includes the new `region` of [Telangana](https://github.com/whosonfirst-data/whosonfirst-data/blob/be538aafe8e77e8be66e03172a3e812faa709a33/data/110/880/597/9/1108805979.geojson). 

Keeping this issue open until the commit is merged to `master`.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/636

**Comment by stepps00** [comment]
We recently imported a new region record for Telengana (!!), but the hierarchy is incorrect.

Leaving this issue open until https://github.com/whosonfirst-data/whosonfirst-data/pull/861 is merged.

**Comment by stepps00** [comment]
Telengana has been imported and the `wof:hierarchy` has been updated to include the correct parents (India, Asia). 

Link to record in GitHub: [Telengana](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/110/880/597/9/1108805979.geojson).

Closing this issue shortly.
