### ISSUE TITLE
geojson files with invalid data

### ISSUE THREAD

**Issue by timfpark** [whosonfirst-data/whosonfirst-data#498]
During an import of the dataset, I noticed that the following files are invalid, either because they are "null set" geometries or are not valid JSON:

data/856/333/45/85633345.geojson
data/136/253/037/136253037.geojson
data/136/253/039/136253039.geojson
data/136/253/045/136253045.geojson
data/136/253/041/136253041.geojson
data/136/253/047/136253047.geojson
data/136/253/051/136253051.geojson
data/136/253/049/136253049.geojson
data/136/253/055/136253055.geojson
data/136/253/053/136253053.geojson
data/136/253/057/136253057.geojson

If fixing them is as simple as deleting them, let me know and I will provide a PR.

**Comment by stepps00** [comment]
@timfpark - thanks for the issue!

Aside from the first GeoJSON in your list, these records are `empire` records that do not currently have geometries...

````
},
  "bbox": [
    0.0,
    0.0,
    0.0,
    0.0
],
  "geometry": {"coordinates":[0,0],"type":"Point"}
}
````

These empire records will eventually get geometries (tracked [here](https://github.com/whosonfirst-data/whosonfirst-data/issues/335)).. these records should all be valid JSON, though.

As for the first record ([New Zealand](https://whosonfirst.mapzen.com/spelunker/id/85633345/)), this should also be a valid JSON file, although the file is _quite_ large. The GeoJSON file itself is ~ 120mb, which may be the cause of your import tagging this record as invalid. We have an [alternate geometry](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/856/333/45/85633345-alt-naturalearth.geojson) for New Zealand, too.

**Comment by stepps00** [comment]
If you'd like to checkout/fetch the New Zealand record (data/856/333/45/85633345.geojson), you can always use `git lfs` since the file is 100mb+. 

Some documentation here: https://github.com/github/git-lfs/wiki/Tutorial

**Comment by timfpark** [comment]
Thanks @stepps00 for the clarification!

**Comment by stepps00** [comment]
No problem - let us know if anything else comes up.
