### ISSUE TITLE
names should be in Titlecase (not ALL CAPS)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#51]
These features should be Acre instead of ACRE.

parent_name name    parent_id   iso id
Brazil  ACRE    85633009    BR  85681873
Brazil  ALAGOAS 85633009    BR  85681879
Brazil  AMAPÁ  85633009    BR  85681891
Brazil  AMAZONAS    85633009    BR  85681885
Brazil  BAHIA   85633009    BR  85681895
Brazil  CEARÁ  85633009    BR  85681907
Brazil  DISTRITO FEDERAL    85633009    BR  85681911
Brazil  ESPIRITO SANTO  85633009    BR  85681921
Brazil  GOIÁS  85633009    BR  85681925
Brazil  MARANHÃO   85633009    BR  85681931
Brazil  MATO GROSSO 85633009    BR  85681955
Brazil  MATO GROSSO DO SUL  85633009    BR  85681947
Brazil  MINAS GERAIS    85633009    BR  85681941
Brazil  PARÁ   85633009    BR  85681959
Brazil  PARAÍBA    85633009    BR  85681967
Brazil  PARANÁ 85633009    BR  85681983
Brazil  PERNAMBUCO  85633009    BR  85681973
Brazil  PIAUÍ  85633009    BR  85681977
Brazil  RIO DE JANEIRO  85633009    BR  85681991
Brazil  RIO GRANDE DO NORTE 85633009    BR  85681999
Brazil  RIO GRANDE DO SUL   85633009    BR  85682015
Brazil  RONDÔNIA   85633009    BR  85682003
Brazil  RORAIMA 85633009    BR  85682011
Brazil  SANTA CATARINA  85633009    BR  85682021
Brazil  SÃO PAULO  85633009    BR  85682041
Brazil  SERGIPE 85633009    BR  85682037
Brazil  TOCANTINS   85633009    BR  85682053
Chile   DE AISEN    85633057    CL  85682189
Chile   DE ANTOFAGASTA  85633057    CL  85682175
Chile   DE ATACAMA  85633057    CL  85682139
Chile   DE COQUIMBO 85633057    CL  85682161
Chile   DE LA ARAUCANIA 85633057    CL  85682179
Chile   DE LOS LAGOS    85633057    CL  85682233
Chile   DE LOS RIOS 85633057    CL  85682171
Chile   DE TARAPACA 85633057    CL  85682245
Chile   DE VALPARAISO   85633057    CL  85682143
Chile   DEL BIO-BIO 85633057    CL  85682155
Chile   DEL LIBERTADOR B OHIGGINS   85633057    CL  85682165
Chile   DEL MAULE   85633057    CL  85682149
Chile   METROPOLITANA   85633057    CL  85682207
Italy   AGRIGENTO   85633253    IT  85685601
Italy   ALESSANDRIA 85633253    IT  85685199
Italy   ANCONA  85633253    IT  85685379
Italy   AREZZO  85633253    IT  85685423
Italy   ASCOLI PICENO   85633253    IT  85685387
Italy   ASTI    85633253    IT  85685195
Italy   AVELLINO    85633253    IT  85685493
Italy   BARI    85633253    IT  85685531
Italy   BARLETTA-ANDRIA-TRANI   85633253    IT  85685731
Italy   BELLUNO 85633253    IT  85685293
Italy   BENEVENTO   85633253    IT  85685483
Italy   BERGAMO 85633253    IT  85685249
Italy   BIELLA  85633253    IT  85685665
Italy   BOLOGNA 85633253    IT  85685351
Italy   BOLZANO/BOZEN   85633253    IT  85685271
Italy   BRESCIA 85633253    IT  85685253
Italy   BRINDISI    85633253    IT  85685543
Italy   CAGLIARI    85633253    IT  85685645
Italy   CALTANISSETTA   85633253    IT  85685605
Italy   CAMPOBASSO  85633253    IT  85685523
Italy   CARBONIA-IGLESIAS   85633253    IT  85685717
Italy   CASERTA 85633253    IT  85685477
Italy   CATANIA 85633253    IT  85685617
Italy   CATANZARO   85633253    IT  85685569
Italy   CHIETI  85633253    IT  85685519
Italy   COMO    85633253    IT  85685235
Italy   COSENZA 85633253    IT  85685565
Italy   CREMONA 85633253    IT  85685263
Italy   CROTONE 85633253    IT  85685687
Italy   CUNEO   85633253    IT  85685187
Italy   ENNA    85633253    IT  85685611
Italy   FERMO   85633253    IT  85685727
Italy   FERRARA 85633253    IT  85685359
Italy   FIRENZE 85633253    IT  85685407
Italy   FOGGIA  85633253    IT  85685527
Italy   FORLI'-CESENA   85633253    IT  85685367
Italy   FROSINONE   85633253    IT  85685473
Italy   GENOVA  85633253    IT  85685219
Italy   GORIZIA 85633253    IT  85685325
Italy   GROSSETO    85633253    IT  85685433
Italy   IMPERIA 85633253    IT  85685209
Italy   ISERNIA 85633253    IT  85685653
Italy   L'AQUILA    85633253    IT  85685505
Italy   LA SPEZIA   85633253    IT  85685225
Italy   LATINA  85633253    IT  85685467
Italy   LECCE   85633253    IT  85685547
Italy   LECCO   85633253    IT  85685669
Italy   LIVORNO 85633253    IT  85685413
Italy   LODI    85633253    IT  85685671
Italy   LUCCA   85633253    IT  85685399
Italy   MACERATA    85633253    IT  85685383
Italy   MANTOVA 85633253    IT  85685269
Italy   MASSA-CARRARA   85633253    IT  85685395
Italy   MATERA  85633253    IT  85685559
Italy   MESSINA 85633253    IT  85685595
Italy   MILANO  85633253    IT  85685243
Italy   MODENA  85633253    IT  85685347
Italy   MONZA E DELLA BRIANZA   85633253    IT  85685723
Italy   NAPOLI  85633253    IT  85685487
Italy   NOVARA  85633253    IT  85685183
Italy   NUORO   85633253    IT  85685637
Italy   OGLIASTRA   85633253    IT  85685707
Italy   OLBIA-TEMPIO    85633253    IT  85685701
Italy   ORISTANO    85633253    IT  85685659
Italy   PADOVA  85633253    IT  85685309
Italy   PALERMO 85633253    IT  85685591
Italy   PARMA   85633253    IT  85685339
Italy   PAVIA   85633253    IT  85685257
Italy   PERUGIA 85633253    IT  85685439
Italy   PESARO E URBINO 85633253    IT  85685375
Italy   PESCARA 85633253    IT  85685513
Italy   PIACENZA    85633253    IT  85685331
Italy   PISA    85633253    IT  85685419
Italy   PISTOIA 85633253    IT  85685403
Italy   PORDENONE   85633253    IT  85685649
Italy   POTENZA 85633253    IT  85685555
Italy   PRATO   85633253    IT  85685683
Italy   RAGUSA  85633253    IT  85685621
Italy   RAVENNA 85633253    IT  85685363
Italy   REGGIO DI CALABRIA  85633253    IT  85685577
Italy   REGGIO NELL'EMILIA  85633253    IT  85685343
Italy   RIETI   85633253    IT  85685455
Italy   ROMA    85633253    IT  85685461
Italy   ROVIGO  85633253    IT  85685313
Italy   SALERNO 85633253    IT  85685497
Italy   SASSARI 85633253    IT  85685633
Italy   SAVONA  85633253    IT  85685215
Italy   SIENA   85633253    IT  85685431
Italy   SIRACUSA    85633253    IT  85685627
Italy   SONDRIO 85633253    IT  85685239
Italy   TARANTO 85633253    IT  85685539
Italy   TERAMO  85633253    IT  85685509
Italy   TERNI   85633253    IT  85685443
Italy   TORINO  85633253    IT  85685169
Italy   TRAPANI 85633253    IT  85685581
Italy   TRENTO  85633253    IT  85685277
Italy   TREVISO 85633253    IT  85685297
Italy   TRIESTE 85633253    IT  85685329
Italy   UDINE   85633253    IT  85685321
Italy   VALLE D'AOSTA   85633253    IT  85685205
Italy   VARESE  85633253    IT  85685231
Italy   VENEZIA 85633253    IT  85685305
Italy   VERBANO-CUSIO-OSSOLA    85633253    IT  85685695
Italy   VERCELLI    85633253    IT  85685177
Italy   VERONA  85633253    IT  85685281
Italy   VIBO VALENTIA   85633253    IT  85685691
Italy   VICENZA 85633253    IT  85685287
Italy   VITERBO 85633253    IT  85685451
San Marino  RIMINI  85633763    IT  85685675
South Africa    EASTERN CAPE    85633813    ZA  85688927
South Africa    FREE STATE  85633813    ZA  85688915
South Africa    GAUTENG 85633813    ZA  85688923
South Africa    KWAZULU-NATAL   85633813    ZA  85688911
South Africa    MPUMALANGA  85633813    ZA  85688895
South Africa    NORTH WEST  85633813    ZA  85688931
South Africa    NORTHERN CAPE   85633813    ZA  85688899
South Africa    NORTHERN PROVINCE   85633813    ZA  85688935
South Africa    WESTERN CAPE    85633813    ZA  85688905

**Comment by stepps00** [comment]
After spot-checking these records, it looks like this is no longer an issue. ALL CAPS -> Titlecase.

@nvkelso OK to close?

**Comment by nvkelso** [comment]
Looks like most of these were fixed up with simple text casing conversion. 

But be mindful of ones like that have filler words like `DO` and `DE` which still need manual cleanup. And there are a few like `BOLZANO/BOZEN` which should be disambiguated / split into the correct languages.

* Brazil MATO GROSSO DO SUL 85633009 BR 85681947
* Brazil RIO DE JANEIRO 85633009 BR 85681991
* Brazil RIO GRANDE DO NORTE 85633009 BR 85681999
* Brazil RIO GRANDE DO SUL 85633009 BR 85682015
* Chile DE AISEN 85633057 CL 85682189
* Chile DE ANTOFAGASTA 85633057 CL 85682175
* Chile DE ATACAMA 85633057 CL 85682139
* Chile DE COQUIMBO 85633057 CL 85682161
* Chile DE LA ARAUCANIA 85633057 CL 85682179
* Chile DE LOS LAGOS 85633057 CL 85682233
* Chile DE LOS RIOS 85633057 CL 85682171
* Chile DE TARAPACA 85633057 CL 85682245
* Chile DE VALPARAISO 85633057 CL 85682143
* Chile DEL BIO-BIO 85633057 CL 85682155
* Chile DEL LIBERTADOR B OHIGGINS 85633057 CL 85682165
* Chile DEL MAULE 85633057 CL 85682149
* Italy BARLETTA-ANDRIA-TRANI 85633253 IT 85685731
* Italy BOLZANO/BOZEN 85633253 IT 85685271
* Italy CARBONIA-IGLESIAS 85633253 IT 85685717
* Italy FORLI'-CESENA 85633253 IT 85685367
* Italy L'AQUILA 85633253 IT 85685505
* Italy LA SPEZIA 85633253 IT 85685225
* Italy MASSA-CARRARA 85633253 IT 85685395
* Italy MONZA E DELLA BRIANZA 85633253 IT 85685723
* Italy PESARO E URBINO 85633253 IT 85685375
* Italy REGGIO DI CALABRIA 85633253 IT 85685577
* Italy REGGIO NELL'EMILIA 85633253 IT 85685343
* Italy VALLE D'AOSTA 85633253 IT 85685205
* Italy VERBANO-CUSIO-OSSOLA 85633253 IT 85685695

https://whosonfirst.mapzen.com/spelunker/id/85685375/

**Comment by nvkelso** [comment]
The Chile regions should receive English names, and reflect their region numbers, too.

https://en.wikipedia.org/wiki/Tarapacá_Region

**Comment by stepps00** [comment]
The records listed in comments above seem to have been taken care of through #71 and 1424, though there are some all-caps names in locality records, most notably in Canada, like:

- https://spelunker.whosonfirst.org/id/101747369/
- https://spelunker.whosonfirst.org/id/101748039/

Using a locality metafile, I'll flag any record with all caps names and update in per-country repo(s),  then we can close this issue out.
