### ISSUE TITLE
Incorrectly labelled locality 'Wellington'

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#510]
The record `101916169` is incorrectly labelled as a `locality`, it's name also seems to be inherited from the city of 'Wellington'.

https://whosonfirst.mapzen.com/spelunker/id/101916169

I'm not sure what exactly it should be, it appears to be a residential road.

**Comment by stepps00** [comment]
Thanks, @missinglink. 

Each of the `locality` features in New Zealand were erroneously split into several features upon import. See : [this list](https://whosonfirst.mapzen.com/spelunker/search/?q=wellington&placetype=locality&iso=nz&region_id=85687233#11/-41.2724/174.7956).

We're tracking the issue [here](https://github.com/whosonfirst-data/whosonfirst-data/issues/118). This issue will be fixed once we "implode" the `locality` features in New Zealand; I'll keep this issue open until that import.

**Comment by stepps00** [comment]
Noting that mesoshapes work will happen once locality features are dissolved, which should take care of this issue.

**Comment by missinglink** [comment]
what's a mesoshape?

**Comment by nvkelso** [comment]
The contractor work to bring in global county shapes, but which has also resulted in some new locality data.

**Comment by stepps00** [comment]
We "imploded" all Wellington records recently, through https://github.com/whosonfirst-data/whosonfirst-data/pull/654. The [current record for Wellington](https://whosonfirst.mapzen.com/spelunker/id/101914285/#13/-41.3003/174.7732) supersedes the bunk record you originally filed the issue for (https://whosonfirst.mapzen.com/spelunker/id/101916169).

Closing this issue.
