### ISSUE TITLE
Add foregn keys to regions

### ISSUE THREAD

**Issue by theKashey** [whosonfirst-data/whosonfirst-data#512]
Lists of regions are useless. Both as in answer from Pelias or string with 'whosonfirst:region:###' within.
Please add ISO3166-codes (geonames, openstreetmap, wikipedia, FIPS and so on), this will gave possibility to merge your data with rest of the world.

**Comment by nvkelso** [comment]
Much of this should already be in the concordances listing.

Is the request to add even more coverage or to expose concordances via Pelias search?

**Comment by theKashey** [comment]
Where to find concordances listings?
I'v just found import.csv https://github.com/whosonfirst-data/whosonfirst-data/issues/371, this geonames id, but there is no corresponding wof id in that file.

The problem with Pelias is very simply - about 50% of regions have wrong names. For examples all states of Russia just written in Cyrillic. The rest also have a lot of misspelling, usage of local names and even typos(Canarias, Corse, Krdzhali, etc).
You have country_a code, please add region_a code – two chars of 3166-2 code, that all i need.

**Comment by thisisaaronland** [comment]
Hi @theKashey 

I am not sure I completely understand the issue, when you say "lists of regions are useless". Can you describe a little more what you're trying to do?

All the WOF records should have both an `iso:country` and a `wof:country` property which are two-letter country codes. Those are also included in the the "meta" CSV files here:

https://github.com/whosonfirst-data/whosonfirst-data/tree/master/meta

As for regional (sometimes called subdivision) codes there is an open ticket to finish up the work to assign UN/LOCODE codes to all the records. That's something which hasn't been worked on in a while but will be soon:

https://github.com/whosonfirst-data/whosonfirst-data/issues/221

**Comment by nvkelso** [comment]
@dianashk Can you comment on @theKashey's request to add a `region_a` code to Pelias response in https://github.com/whosonfirst-data/whosonfirst-data/issues/512#issuecomment-258995678, please? Which repos should that be tracked in?

**Comment by theKashey** [comment]
>Can you describe a little more what you're trying to do?
I am trying to do autocomplete in one form. And perform autocomplete not only for address, but also auto-fill region information.
I collect regions from geonames/openstreetmap/wikipedia and use them to fill data of form (and some "geo" sites, I rule). Next, on autocomplete, I try to find selected region and use it. Unfortunately I'v found, that I can do this only for "english" countries, for rest of them names are different. So I need some external key for merging a data. 
I try yesterday to reverse geocode regions(as long I have my own "admin" geocoder) or perform merge with levenshtein distance functions, but many of compares have fall.

**Comment by theKashey** [comment]
Just publish a little project, about countries, regions, codes and references – https://github.com/esosedi/3166 – unfortunately WOF link is missing for a lot of records.

**Comment by dianashk** [comment]
Hey sorry I missed this earlier. We do already provide region_a as you can see in this example query: http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Pennsylvania

We're testing an improvement on Dev now that will use the name for country and region in the spoken or official language of the area. This might help with some of the errors you're seeing. In the future if you see a record with an incorrect name or have a lot of them somewhere it would be helpful for us to see the specific errors.

**Comment by theKashey** [comment]
@dianashk – may be you provide region_a for US, but not for all possible states.
Example – http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=45%20Edward%20Bennett

**Comment by nvkelso** [comment]
- https://whosonfirst.mapzen.com/spelunker/id/1108746689/#5/37.419/-119.307
  - We already set wof:abbreviation to `CA` for California, which is what Pelias is using.
- https://whosonfirst.mapzen.com/spelunker/id/85681545/#5/-32.954/150.054
  - wof:abbreviation is missing for New South Wales
  - But we could set wof:abbreviation to `NSW` for New South Wales (from `wof:subdivision`:`AU-NSW`)
  - NOTE: often that UN based code isn't actually a postcode so we should do this one-by-one not as a bulk operation.

**Comment by stepps00** [comment]
@theKashey - Are you still experiencing issues related to the `region_a` codes? Pelias should now always return any abbreviations that exist in Who's On First, regardless of placetype.

**Comment by theKashey** [comment]
Will check new behavior asap. Thanks!

**Comment by theKashey** [comment]
By fact - it still does return region_a codes for USA only :(

**Comment by nvkelso** [comment]
Possibly related: https://github.com/whosonfirst-data/whosonfirst-data/pull/1052
