### ISSUE TITLE
Clipping Request: States around the Great Lakes

### ISSUE THREAD

**Issue by binx** [whosonfirst-data/whosonfirst-data#523]
Currently the boundary for states bordering the great lakes extends into a sort of "halfway" line in the lakes. It would be great if these clipped to the land boundary, or offered that as an option

![screenshot 2016-11-15 11 28 57](https://cloud.githubusercontent.com/assets/589151/20320486/d9033aa2-ab26-11e6-8c79-09f3954e38a5.png)

**Comment by stepps00** [comment]
Hey @binx! Thanks for filing the issue. I've opened up a [new issue](https://github.com/whosonfirst-data/whosonfirst-data/issues/524) to track all regions (states) in the US, so I will likely close this issue in preference of this single state issue. 

New shapes will be imported as alt-geometries; check the new issue for updates.

**Comment by dphiffer** [comment]
Progress...
<img width="519" alt="screen shot 2016-11-15 at 4 05 47 pm" src="https://cloud.githubusercontent.com/assets/38114/20324176/81501b14-ab4d-11e6-8aab-e804b5c1bae1.png">

**Comment by binx** [comment]
😍 beautiful

**Comment by dphiffer** [comment]
Actually, I think @stepps00 might have found better geometries for all 50 states...

**Comment by stepps00** [comment]
I found state-level open data provided by the Census that I'll be using as `alt-geom` shapes.. stay tuned.

<img width="1000" alt="screen shot 2016-11-15 at 2 16 19 pm" src="https://cloud.githubusercontent.com/assets/18567700/20327852/da2e606a-ab43-11e6-85c8-4c89bdd79998.png">

**Comment by nvkelso** [comment]
This is related to general alternate geometry wrangling in https://github.com/whosonfirst-data/whosonfirst-data/issues/367.

**Comment by nvkelso** [comment]
@binx are you more interested in the boundary line or the polygon fill?

**Comment by binx** [comment]
@nvkelso boundary line, thanks! @stepps00 this is looking great

**Comment by nvkelso** [comment]
This is a good way to test out alt-geom wrangling, related to #367.

**Comment by stepps00** [comment]
Tested out alt-geom wrangling in https://github.com/whosonfirst-data/whosonfirst-data/pull/539, which was just merged into `master`; closing this issue.
