### ISSUE TITLE
Create clipped alt-geoms for regions of the US

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#524]
In continuation of https://github.com/whosonfirst-data/whosonfirst-data/issues/523, Who's On First should have alt-geometries for regions (states) that are clipped to shorelines. 

Two options:

A. Find a new authoritative source that provides these shapes through an open license.

B. Dissolve existing descendant geometries in each affected region into one single shape. Postalcode records are likely the best option because Who's On First already has country-wide postalcode data and the postalcode shapes are clipped at coastlines.

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/367
