### ISSUE TITLE
Fix-up Russian names (post Mesoshape import)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#529]
Following up from the Russia mesoshape import and PR https://github.com/whosonfirst-data/whosonfirst-data/pull/518 the new names should be `"name:rus_x_variant"`:

- data/110/873/258/9/1108732589.geojson

```
 + "name:und_x_variant":[
 +        "\u0422\u0430\u0448\u0442\u044b\u043f\u0441\u043a\u0438\u0439 \u0440\u0430\u0439\u043e\u043d"
 +    ],
```

Similarly the old `"qs:name":"Tashtypskiy Raion",` that was used for `wof:name` should be preserved as an english language name variant ("name:eng_x_variant"`).

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/307.

**Comment by stepps00** [comment]
admin1 records taken care of here: https://github.com/whosonfirst-data/whosonfirst-data/pull/1038

**Comment by stepps00** [comment]
This was completed in https://whosonfirst.mapzen.com/boundaryissues/pipeline/530/, closing issue.
