### ISSUE TITLE
Name of Barrow, AK changed to Utqiaġvik, AK

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#542]
The record of Barrow, Alaska ([here](https://whosonfirst.mapzen.com/spelunker/id/85915545/#10/71.2856/-156.7825)) should be updated to reflect the new locality's new name - Utqiaġvik.

This is a good use case for the lifecycle document, as the `wof:name` field will be updated without preserving "Barrow" as an alt.

**References:**
- http://www.marketwatch.com/story/alaskan-city-barrow-woke-up-with-a-new-name-today-2016-12-01
- http://www.bbc.com/news/world-us-canada-38165206
- http://www.npr.org/sections/thetwo-way/2016/12/01/503979353/barrow-alaska-changes-its-name-back-to-its-original-utqiagvik

**Comment by nvkelso** [comment]
Will Barrow be preserved as some sort of historical name?

**Comment by stepps00** [comment]
Since the `wof:name` field is being updated, we have a case for superseding the existing `Barrow` record to a new `Utqiaġvik` record (see: [lifecycle doc](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/definition/wof:id_lifecycle.md)).

My thought was to create a new record, complete the superseding work, and update the `name` and `concordance` accordingly. So.. yes, the names will all be preserved in the Barrow record.

**Comment by nvkelso** [comment]
If someone searches for `Barrow`, would they still find it via the new
`Utqiaġvik` result? It’s going to be a 5-10 years before people stop
calling it Barrow generally, and probably a 100 years before that use
really dies out.

I don’t think Pelias refers to expired records, so `Barrow` probably needs
to be listed _somewhere_ in the `Utqiaġvik` record for Pelias search to
resolve.

**Comment by thisisaaronland** [comment]
`name:eng_x_variant`

**Comment by thisisaaronland** [comment]
Or `name:eng_x_historic` – the whole point of the `_x_TYPE` syntax is that we can adapt convention as necessary. It just needs to be written down here:

https://github.com/whosonfirst/whosonfirst-names/

Which is to say it's probably time to create `types/TYPE.json` files that can be used by code to validate things. But for now, just updating the docs in the `whosonfirst-names` repo should be enough.

**Comment by stepps00** [comment]
Are we in agreement that the record for Barrow should stay put, with the new Utqiaġvik name replacing Barrow and Barrow being stored in a `name:eng_x_` property? I like the idea of a `name:eng_x_historic` property for cases such as this.

If so, I will update the record and the `whosonfirst-names` repository.

**Comment by thisisaaronland** [comment]
Barrow should be superseded. The new record should include Barrow as an historic name.
