### ISSUE TITLE
Miaoli missing a geojson file for metadata entry

### ISSUE THREAD

**Issue by cag** [whosonfirst-data/whosonfirst-data#543]
In `meta/wof-macrocounty-latest.csv`, there is an entry:
```
"120.621853854,24.288516124,121.262632967,24.741091053",uuuu,85632403,,4cf9b9e302c8ec2fd64be5a61d63f320,,6423c70412bdc3641994a73237898e6b,24.483912,120.922006,1108498856,uuuu,TW,TW,1473974328,24.51334,120.890412,0,Miaoli,85679575,110/849/885/6/1108498856.geojson,macrocounty,85679575,meso,,,TW
```

This entry is associated with a geojson file which does not exist (`110/849/885/6/1108498856.geojson`)

**Comment by thisisaaronland** [comment]
@stepps00 - did this file get accidentally excluded from the various Mesoshapes PRs?

**Comment by stepps00** [comment]
Hmm.. I see this file in the correct [data/110/849/885/6](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/110/849/886/5/1108498865.geojson) path. 

Maybe this is an issue on Pelias' end as outlined in the referenced link above?

```
Error: ENOENT: no such file or directory, open '/home/dev/pelias-data/whosonfirst/data/110/849/885/6/1108498856.geojson'
```

**Comment by cag** [comment]
I could have sworn that file was missing from the repo earlier...

Anyway, it's not in the S3 store, which is where the importer grabs its stuff: https://whosonfirst.mapzen.com/spelunker/id/1108498856/#18/24.28852/120.62185

**Comment by stepps00** [comment]
Interesting, hence:

```
2016-12-03T01:35:21.679Z error
failed to parse https://s3.amazonaws.com/whosonfirst.mapzen.com/data/110/849/885/6/1108498856.geojson, because SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Looks like the other `macrocounty` records in Taiwan were fetched from S3 successfully. 
Thanks for filing the issue, @cag. We'll take a look and update the record accordingly.

**Comment by stepps00** [comment]
@cag - Mentioned in https://github.com/pelias/whosonfirst/issues/174, this issue is due to Pelias' handling of 10-digit `wof:id` fields. 

Closing this issue in preference of the Pelias issue.

**Comment by stepps00** [comment]
Looks like the `wof:id` was inconsistent; filing a new PR to fix this issue shortly.
