### ISSUE TITLE
Incomplete hierarchy for San Francisco

### ISSUE THREAD

**Issue by cag** [whosonfirst-data/whosonfirst-data#545]
Check out SF: https://whosonfirst.mapzen.com/spelunker/id/102087579/#10/37.7850/-122.7278

It doesn't have California in its hierarchy, though it does say that California parents it.

Though, to be fair, I know this isn't the only case. I am fairly certain I saw one in Egypt somewhere missing a continent in its hierarchy (though then, I did not think of looking at its hierarchy field, and I've since lost the pointer to that record in my wetware :stuck_out_tongue: )

**Comment by orangejulius** [comment]
The locality record for San Francisco has the same issue, thanks for catching this! https://whosonfirst.mapzen.com/spelunker/id/85922583/#10/37.7850/-122.7278

**Comment by stepps00** [comment]
Thanks for the new issue @cag.

This issue affects a few records where the math centroid (`geom:latitude` and `geom:longitude` fields) falls outside of the geometry of it's parent. We are planning on updates to `neighbourhood` and `locality` records in San Francisco that should fix this issue in soon, but I will file a PR to correct this issue and add a correct `parent_id`, update the hierarchy, and belongsto fields.

**Comment by stepps00** [comment]
Closing this issue; a recent commit updated hierarchies for San Francisco.

Locality: https://whosonfirst.mapzen.com/spelunker/id/85922583/#10/37.7854/-122.7290
County: https://whosonfirst.mapzen.com/spelunker/id/102087579/#10/37.7854/-122.7290
