### ISSUE TITLE
Refine Austrian locality polygons

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#546]
via https://github.com/pelias/pelias/issues/466

Christoph has local knowledge of the area and would like to help improve the Austrian polygons.

Could you please reach out and advise what formats/ liscences we accept.

Thanks!

**Comment by stepps00** [comment]
@christophmayrhofer - thanks for the support ticket about our Austrian data. 

We either need to find a new source that is open data with a CC-BY or CC-0 license that allows commercial and derivative works _or_ create new shapes based on local knowledge (and by cross-referencing multiple sources). Ideally, we would then replace the new shapes with our existing shapes and move the existing shapes into an alt-geometry file.

Let me know if you have any questions; I am happy to help you upgrade these geometries.

**Comment by nvkelso** [comment]
@christophmayrhofer we'd love to hear if specific `placetype` (category like region or county) need work generally, or if only specific features need to be improved.

**Comment by christophmayrhofer** [comment]
@nvkelso Good that you mentioned that:

The problem is only with placetype locality. All placetypes of higher hierarchy are based on EuroGlobalMap and have the correct geometry, but the localities have "TCustom EuroGlobalMap + UMZ Urban Polygons + Geonames + GeoPlanet" specified as their source.

I also noticed that searching for "Anthering" yields a record of type postalcode in addition to the locality record.

locality: https://whosonfirst.mapzen.com/spelunker/id/101786767/#15/47.8812/13.0133
postalcode: https://whosonfirst.mapzen.com/spelunker/id/504798173/#12/47.8906/13.0034

They both refer to the same entity (5102 is the postcode of Anthering), but only the postalcode record uses the correct geometry. So it would be great if the geometry could somehow be mapped to the locality.

**Comment by nvkelso** [comment]
Looks like the Austria Open Data portal has municipalities now:

- Newer? https://www.data.gv.at/katalog/dataset/c33d36b0-f184-4f2a-89cc-839ca7fcf88a
- Older? https://www.data.gv.at/katalog/dataset/4a9c8052-9986-4a77-849e-d37cb3d73209

There are around 2100 features, and they form a continuous fabric across the country – so more comparable to the `localadmin` units Who's On First has across the rest of Europe. 

Who's On First already sources some data from the Austria Open Data portal under a comparable CC-BY license (so does OpenAddresses!).

When I open that ZIP I see two different shapefiles with 2101 and 2103 features, and slightly different columns and different projections (and accurate to 1:10,000 scale):

![screen shot 2016-12-05 at 21 16 38](https://cloud.githubusercontent.com/assets/853051/20913969/d12c9598-bb30-11e6-8fb7-cd98145b27ba.png)

![screen shot 2016-12-05 at 21 16 34](https://cloud.githubusercontent.com/assets/853051/20913970/d1564208-bb30-11e6-9edc-782a6f00d38c.png)

<img width="761" alt="screen shot 2016-12-05 at 21 23 59" src="https://cloud.githubusercontent.com/assets/853051/20914013/2d337906-bb31-11e6-818c-e00f51a68af4.png">

**Comment by christophmayrhofer** [comment]
The two links that you provide represent metadata from two different agencies (one local and one national). The download links however, both point to the same dataset. 

Regarding the two shapefiles inside the zip:
Gem_AT_2015sp (sp = simplified) has slightly generalized geometries of the Gem_AT_2015 file.

And the difference in feature count:
There were two fusions of municipalities in 2015. (i.e. 4 features become two new ones). 
The non generalized version Gem_AT_2015 already includes this change and therefore has two less than the other. So we should use this shapefile. If it needs to be processed in someway and you can provide me with a template I will happily do it.

**Comment by nvkelso** [comment]
Thanks for the explanations! The more detailed file is workable for us directly.

This will involve some PIPing to regenerate administrative hierarchy for related / descendent features so will take some time either later in Dec or in January. Also time needed to sort through the below consideration.

As to 'placetype' these still seem like 'localadmin' to me over 'locality'. But some locality are coterminous / unitary with these new features. There's also Pelias' upcoming feature to search locality and localadmin for city names.

**Comment by martinlierschof** [comment]
Hi Guys,
If you don't mind explaining this for me but as I understood within geonames you can actually perform a search for postal codes and get the relevant city for it, and geonames is already included. If you need something I am happy to help.

**Comment by stepps00** [comment]
Below, the green polygons represent the data from Austria Open Data, the red outlines represent the geometry outlines of localities currently in Who's On First. 

Closer inspection suggests these new features from Austia Open Data _are_ localadmin features with only the larger WOF localities matching shapes of the new features. The larger localities (Graz, Salzburg, Vienna, etc) should have the `wof:coterminous` and `wof:placetype_alt` work done.

<img width="884" alt="screen shot 2017-03-20 at 12 48 53 pm" src="https://cloud.githubusercontent.com/assets/18567700/24118605/9bc9890a-0d6b-11e7-89cd-5be6281745e9.png">

**Comment by stepps00** [comment]
The locality data includes the region name in its properties; the image below shows the locality features categorized by region. These features should be dissolved and imported as new region geometries - the dissolved features are more detailed than the current quattroshapes-sourced geometries.

<img width="1003" alt="screen shot 2017-03-20 at 1 03 25 pm" src="https://cloud.githubusercontent.com/assets/18567700/24119216/a514ac90-0d6d-11e7-9a87-eadeb9d91d24.png">

**Comment by nvkelso** [comment]
Great investigations, thank you!
