### ISSUE TITLE
Mesoshape county imports often missing descendants

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#547]
Mesohape county features are often missing their descendant features. Counties have been stripped from some hierarchies, as well. 

For example:
https://whosonfirst.mapzen.com/spelunker/id/421170005/#9/22.2064/-80.4831 does not contain a `county` hierarchy.

https://whosonfirst.mapzen.com/spelunker/id/1091904385/#10/21.9984/-80.2778 does not have any listed descendants.

**Comment by orangejulius** [comment]
I'm not sure if this is completely related, but we noticed in our latest Pelias build that some records are also missing all their hierarchy information when they weren't before. For example, [Nuevo Cristóbal, Panama](https://whosonfirst.mapzen.com/spelunker/id/85763987/#12/9.3651/-79.8981), and [Reparto Vista Alegre, Cuba](https://whosonfirst.mapzen.com/spelunker/id/85793671/#13/20.0172/-75.7924)

**Comment by nvkelso** [comment]
We think fixes in https://github.com/whosonfirst-data/whosonfirst-data/issues/486 will take care of most of this problem.

**Comment by stepps00** [comment]
This should already be fixed, for the most part.

The most recent round of PIP work took care of a bulk of this issue, but once that PR for #660 lands (we know this will rebuild/validate hierarchies for _all_ records in _all_ ~115 meso countries), this issue should be closed.

**Comment by stepps00** [comment]
The records listed above now have hierarchies. This should no longer be a common issue for `meso` records, though it may pop up in isolated cases.

Closing this issue; we can open new issues if null hierarchies are found in the future.
