### ISSUE TITLE
Add polygon geometry to timezones

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#553]
Valhalla uses an external source for this now, but could switch to WOF.

See also:

- https://github.com/valhalla/odin/pull/389#issuecomment-265827972

**Comment by stepps00** [comment]
Who's On First actually maintains geometries in the `timezone` records. A few examples, below:

https://whosonfirst.mapzen.com/spelunker/id/102047345/#2/69.7/52.9
<img width="712" alt="screen shot 2016-12-14 at 5 02 46 pm" src="https://cloud.githubusercontent.com/assets/18567700/21207830/5159744e-c21f-11e6-8bf9-9ec6052495c9.png">

https://whosonfirst.mapzen.com/spelunker/id/102047597/#3/39.57/117.16
<img width="446" alt="screen shot 2016-12-14 at 5 02 57 pm" src="https://cloud.githubusercontent.com/assets/18567700/21207839/5aeb0d06-c21f-11e6-9476-3e23b3a11a35.png">

https://whosonfirst.mapzen.com/spelunker/id/102047459/#4/40.48/-108.24
<img width="584" alt="screen shot 2016-12-14 at 5 03 03 pm" src="https://cloud.githubusercontent.com/assets/18567700/21207843/60305ee2-c21f-11e6-9beb-fbed680d9a8e.png">

**Full list of `timezone` records in Who's On First:**
https://whosonfirst.mapzen.com/spelunker/placetypes/timezone/#6/3.148/-61.354
