### ISSUE TITLE
Merge polygons county Mouscron, Belgium

### ISSUE THREAD

**Issue by Platzii** [whosonfirst-data/whosonfirst-data#557]
Hi,

The county of Mouscron is split in 2 parts that do not intersect eachother. However, I noticed these parts have been given a seperate ID.

The polygons of county ID [102049953](https://whosonfirst.mapzen.com/spelunker/id/102049953/#10/50.7385/3.2530) and [102049955](https://whosonfirst.mapzen.com/spelunker/id/102049955/#10/50.7385/3.2530) should be merged into a multipolygon.

Kind regards,
Simon

**Comment by nvkelso** [comment]
@Platzii Thanks for the report, we'll have a look. It'll either be a quick fix for those 2 polygons or something more wide spread to investigate.

**Comment by stepps00** [comment]
Hey @Platzii, thanks for the tip! 

Mouscron is split into two records, though it should actually be one record, as you suggest. This multi-part polygon issue is also affecting Tongeren, records [here](https://whosonfirst.mapzen.com/spelunker/id/102049939/#12/50.7468/5.7965) and [here](https://whosonfirst.mapzen.com/spelunker/id/102049959/#10/50.8645/5.5007). 

With these two duplicate records removed, our `county` counts will match the list of [Arrondissements of Belgium](http://www.statoids.com/ybe.html), so this is likely a quick-fix for Mouscron and Tongeren.

**Comment by stepps00** [comment]
Thanks again, @Platzii - this issue should now be fixed!
