### ISSUE TITLE
Mesoshape county imports round 2

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#558]
For all the 2nd half delivery from AOTM.

- [x] Angola - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Armenia - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Benin - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Bosnia_Herzegovina - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Burundi (added) - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] CAR - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Djibouti - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Equatorial Guinea - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Eritrea - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Ghana - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Guinea - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Guinea Bissau - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Ivory Coast - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Kazakhstan - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Libya - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Madagascar  - merged (#620)
- [x] Malawi - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Morocco - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Namibia - https://github.com/whosonfirst-data/whosonfirst-data/pull/561
- [x] Philippines
- [x] Qatar - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Sierra_Leone - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Somalia - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Syria - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Taiwan - #469
- [x] Tunisia - https://github.com/whosonfirst-data/whosonfirst-data/pull/555
- [x] Vietnam - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Zambia - https://github.com/whosonfirst-data/whosonfirst-data/pull/559
- [x] Zimbabwe - https://github.com/whosonfirst-data/whosonfirst-data/pull/561

**Comment by nvkelso** [comment]
Future import round 3 would include countries like Canada, Cyprus, & etc.

**Comment by stepps00** [comment]
All countries in this list have had their mesoshapes features imported. 

Closing issue.
