### ISSUE TITLE
Update neighbourhood records in greater Finland

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#568]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Upgrade** locality record's shape
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Related to: https://github.com/whosonfirst-data/whosonfirst-data/issues/442.

From the same data source used to update Helsinki `neighbourhood` records, update `neighbourhood` (and `microhood`/`macrohood` records) the following cities in Finland:

- Espoo
- Kaunianinen
- Kuopio
- Oulu
- Tampere
- Turku
- Vantaa

**Comment by stepps00** [comment]
Neighbourhood geojson files for the cities listed above are in the S3 `misc/Issue 568` folder. Files include new and updated `borough`, `macrohood`, `neighbourhood`, and `microhood` records.

Over to @thisisaaronland for review and import.

**Comment by stepps00** [comment]
Reassigning @ZBSingleton to update files for Greater Finland.

**Comment by stepps00** [comment]
These markets are up-to-date and ready for import. GeoJSON files are in the S3 `misc/Issue 568` folder.

Back to @thisisaaronland for import.

**Comment by stepps00** [comment]
@thisisaaronland - the `issue-568` branch is missing features from the `no_wof_neighbourhoods` files in Tampere, Turku, and Vantaa. 

All other features are included.

**Comment by thisisaaronland** [comment]
That would be because someone mis-spelled "neighbourhoods" :-)

```
/usr/local/data/whosonfirst-work/issue-568/Tampere_20170308> ll
total 1380
-rw-r--r-- 1 acope mapzen 1271572 Mar  8 08:14 no_wof_neigbourhoods.geojson
-rw-r--r-- 1 acope mapzen  117197 Mar  8 08:17 wof_locality.geojson
-rw-r--r-- 1 acope mapzen   19171 Mar  8 08:11 wof_neigbourhoods.geojson
```

I will update things shortly.

**Comment by thisisaaronland** [comment]
cc @dphiffer - Dan this is the kind of thing that the "pipeline" toolchain will need to catch and warn on.

**Comment by stepps00** [comment]
yikes - good catch!

**Comment by stepps00** [comment]
This work was completed in commits  	a2632c6,  	dde45cf,  	fa9a153, and  0dcdd824fe57932b422caa164593882e84e4c6f9  and has been merged to master. Closing issue.

**Comment by hannesj** [comment]
Thanks!
