### ISSUE TITLE
Link up countries and their capital cities

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#57]
- [x] Research which locality should link with which country records
- [ ] New data modeling
- [ ] Apply research

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/58

**Comment by stepps00** [comment]
Who's On First currently has 224 `country` records ([here](https://whosonfirst.mapzen.com/spelunker/placetypes/country/#5/3.701/-14.768)).

[This file](https://github.com/whosonfirst-data/whosonfirst-data/files/720768/capitals_per_country.txt) contains a list of 250 countries and their capital(s), per [this page](https://en.wikipedia.org/wiki/List_of_national_capitals_in_alphabetical_order). Interestingly, several countries have more than one official capital. 

This link can be established by linking the `"wof:id"` of the capital record with the `"wof:id"` of the country record, similar to what we do when superseding records.

@nvkelso - do you have a preferred new property name to add to each country record? `wof:capital`?

**Comment by nvkelso** [comment]
Is there a 'capital_of' property on a few sample records now? What are names of similar existing properties?

**Comment by stepps00** [comment]
It doesn't look like we currently use a `"capital_of"` property. Looking over sample records ([Ottawa](https://whosonfirst.mapzen.com/spelunker/id/101735873/#9/45.2504/-75.8011), [Mexico City](https://whosonfirst.mapzen.com/spelunker/id/857683023/#10/19.3921/-99.1441), [Madrd](https://whosonfirst.mapzen.com/spelunker/id/101748283/#10/40.4234/-3.6825), and [Dublin](https://whosonfirst.mapzen.com/spelunker/id/101751737/#10/53.3354/-6.2780)), there are no similar properties, either. 

For this issue, I can propose a PR with a new `"wof:capital_of"` property for each capital record that includes the country's `"wof:id"`. For example, the following would be added to Mexico City's record:

```
"wof:capital_of":85633293,
```

**Comment by nvkelso** [comment]
Would `85633293` in your example also receive an array of capitals?

**Comment by stepps00** [comment]
Likely, yes. That would especially make sense in countries like Malaysia or Bolivia that have more than one capital city (Kuala Lumpur and Putrajaya / Sucre and La Paz, respectively). 

Mexico's record would receive the following property:

```
"wof:capital":[857683023],
```

**Comment by stepps00** [comment]
[This text file](https://github.com/whosonfirst-data/whosonfirst-data/files/883811/country_capital_ids.txt) contains a list of 215 `country` records in Who's On First, the `wof:id` of that record, as well as the name and `wof:id` of its capital record.

There are additional notes on duplicate features, questionable placetypes, and exploded multi-part features, but this list should take care of the first checkbox in the initial issue comment. 

The next step is to take care of one-off issues, creating a script, and linking these ids through the new `wof:capital` and `wof:capital_of` properties.

**Comment by stepps00** [comment]
**Note:** PR for this issue will need to be merged after https://github.com/whosonfirst-data/whosonfirst-data/pull/654.

**Comment by stepps00** [comment]
This was completed through #735.
