### ISSUE TITLE
Hierarchy issues

### ISSUE THREAD

**Issue by dianashk** [whosonfirst-data/whosonfirst-data#570]
During our regularly-scheduled Pelias builds we ran into several regressions that seem to be related to WOF admin hierarchies. Here is what we found.

1. When searching for `New York, New York` we were expecting it to be parented by Richmond County but are now seeing Kings County   [see here](http://pelias.github.io/compare/#/v1/search%3Fsources=wof&text=New%20York,%20New%20York) and [85977539](https://whosonfirst.mapzen.com/spelunker/id/85977539/#9/40.6979/-73.9797)

2. Another NY county update when searching for Manhattan, used to be within New York County and is now in Kings County [see here](http://pelias.github.io/compare/#/v1/search/structured%3Fborough=Manhattan&locality=New%20York&region=NY) and [421205771](https://whosonfirst.mapzen.com/spelunker/id/421205771/#11/40.7809/-73.9772)

3. This county in China has been deprecated. Any particular reason? Was it superceded by something? [890513061](https://whosonfirst.mapzen.com/spelunker/id/890513061/#6/30.215/107.730)

4. These two records have lost parentage: [85763987](https://whosonfirst.mapzen.com/spelunker/id/85763987) and [85793671](https://whosonfirst.mapzen.com/spelunker/id/85793671)

**Comment by nvkelso** [comment]
We'll look at these today and expect to propose fixes by EOD.

**Comment by nvkelso** [comment]
@dianashk 

- Pelias should update their test for `wof:id` = `890513061` to use `wof:id` = `890513063` instead. See discussion in the PR.
- All the other changes will be addressed in the PR.
