### ISSUE TITLE
Ensure locality records have hierarchy and belongsto properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#572]
Per conversation in https://github.com/whosonfirst-data/whosonfirst-data/pull/571, ensure that `locality` records have `wof:hierarchy` and `wof:belongsto` properties. 

> We'll soon land county polygons [...] but neighbourhoods should keep looking up the place hierarchy until they find a parent at whatever placetype. This is probably a widespread problem with the last round of re-PIPing.

**Comment by thisisaaronland** [comment]
A point of detail: "...a parent at whatever placetype" is not a valid parent ID. That is not the correct behaviour.

The ability to ensure some amount of hierarchy (this neighbourhood is part of region "x") is not the same as a complete hierarchy (this neighbourhood is parented by [a valid parent placetype](https://github.com/whosonfirst/whosonfirst-placetypes/blob/master/placetypes/neighbourhood.json#L5)). The same applies to any place type.

If we can't find a suitable parent for a record the correct behaviour is to flag the `wof:parent_id` as `-1` and not to assign the nearest ancestor as the "parent".

**Comment by stepps00** [comment]
@thisisaaronland - looks like the new hierarchy tool takes care of this issue. The new hierarchy building tool updates locality (and other) placetypes correctly (ex: https://github.com/whosonfirst-data/whosonfirst-data/compare/pr-555), so I'd like to close this issue once #555 is merged.

**Comment by stepps00** [comment]
New hierarchy update tool ensures that these properties will be included in locality records. 

#555 and #571 were merged, no additional action needed here. Closing this issue.
