### ISSUE TITLE
Persist existing min_zoom values onto new neighbourhood imports

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#577]
We've completed almost 30 localities worth of neighbourhoods and posted the intermediate files onto S3, but looks like the `min_zoom` there always defaults to `15`, but if that's the case then it'll overwrite the existing curated values on the record. 

Either we need to add special import logic to not overwrite when it's `15` (varies by placetype, though), or update the new records to have the old record's curated values.

Defaults:
- `borough`:
  - Default: `min_zoom`:`10`, optionally modify up to `9` for important places.
  - Default: `max_zoom`:`13`, rarely modify.
- `neighbourhood`: 
  - Default: `min_zoom`:`15`, optionally modify up to `13` for important places.
  - Default: `max_zoom`:`18`, rarely modify.
- `macrohood`: 
  - Default: `min_zoom`:`13`, optionally modify up to `11` for important places.
  - Default: `max_zoom`:`15`, rarely modify. 
- `microhood`: 
  - Default: `min_zoom`:`16`, rarely modify.
  - Default: `max_zoom`:`18`, rarely modify.

**Comment by nvkelso** [comment]
@stepps00 I think this is process changed now based on what you worked out with Aaron for imports?

**Comment by stepps00** [comment]
@nvkelso - Im comfortable closing this issue.. we've worked out that all zoom level values will be retained during neighbourhood imports unless you specifically change values in a one-off case.
