### ISSUE TITLE
Fix duplicate county records in South Korea

### ISSUE THREAD

**Issue by mattmakesmaps** [whosonfirst-data/whosonfirst-data#578]
Hello. I'm taking a look at county records for `South Korea`.

I've noticed that there appear to be two very similar records for `Cheonansidongnamgu` [1] | [2].

Just flagging this as I'm not sure if these are expected duplicates.

Thank you!

[1]: https://whosonfirst.mapzen.com/spelunker/id/1108746401/#10/36.7597/127.2181
[2]: https://whosonfirst.mapzen.com/spelunker/id/1108746431/#10/36.7597/127.2181

**Comment by stepps00** [comment]
Thanks for filing the issue @mattmakesmaps - we're aware of this issue and have [this pull request](https://github.com/whosonfirst-data/whosonfirst-data/pull/549) out to take care of duplicate `county` features in South Korea.

We expect to merge the pull request soon, so I will keep this issue open until those changes are seen in `master`.

**Comment by stepps00** [comment]
Closing this issue, as https://github.com/whosonfirst-data/whosonfirst-data/pull/549 has been merged to `master`. 

Superseding and deprecating work now appears in referenced `county` features:

https://whosonfirst.mapzen.com/spelunker/id/1108746401/#10/36.7597/127.2181
https://whosonfirst.mapzen.com/spelunker/id/1108746431/#10/36.7597/127.2181
