### ISSUE TITLE
Add Statoids data to properties in admin0, admin1, and admin2 records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#581]
The majority of imported mesoshapes features included a `hasc:id` concordance property that should be used to join to Statoids data, once available. As an example, the [`county` feature of Bago in Myanmar](https://whosonfirst.mapzen.com/spelunker/id/1092044937/#8/17.652/96.562) has the following property:

```
    "wof:concordances":{
        "hasc:id":"MM.BA.BG"
    },
```

The Statoids table of [Myanmar Districts](http://www.statoids.com/ymm.html) includes "MM.BA.BG," which would allow Who's On First to bring in population, area, alt_names, and other properties in Statoids. This work should be done for all `country`, `region`, and `county` features.

**Comment by nvkelso** [comment]
These issues are blockers:

General:

- #671 Import HASC concordance for countries with "terrible" coverage admin-2 county  
- #670 BLOCKED: Import HASC codes for countries with no coverage admin-2 county concordances #669 BLOCKED: Import HASC concordance for countries with "bad" coverage admin-2 county
- #665 Import HASC concordance for countries with "ok" coverage admin-2 county concordances 
- #663 Import HASC concordance for countries with "great" coverage admin-2 county concordances 
- #615 Check validity of HASC codes in countries that did not receive a mesoshapes import admin-0 
- #581 BLOCKED: Add Statoids data to properties in admin1 and admin2 records admin-0 country admin-1 region admin-2 county hasc LOE:High meso

Probably outdated / forward dup: 

- #380 Backfill existing administrative WOF records with HASC code field hasc

Specific countries: 

- #616 Madagascar: Import new HASC codes for admin1 and admin2 features admin-1 region admin-2 
- #589 Qatar: Update HASC codes in admin2 features admin-2 county hasc LOE:Low meso
- #587 Uganda: Update HASC codes for admin2 features admin-1 region admin-2 county hasc 
- #584 Venezuela: Update HASC codes for admin2 features admin-2 county hasc LOE:Low meso
- #583 Sudan: Update HASC codes and boundaries for admin2 features admin-2 county hasc 
- #580 Kosovo: Add HASC codes for admin2 features admin-2 county hasc LOE:Low meso

**Comment by stepps00** [comment]
All `admin0`, `admin1`, and `admin2` data from the mesoshapes work should be imported, so this issue is no longer blocked.

**Comment by stepps00** [comment]
Updates:

- Statoids import for `admin0` complete.

- Statoids import for `admin1` complete, non-matching "leftovers" are being tracked here: https://github.com/whosonfirst-data/whosonfirst-data/issues/900

- Statoids import for `admin2` is in progress.

**Comment by stepps00** [comment]
The first run of Statoids data for `admin0`, `admin1`, and `admin2` records is complete.

Follow-up issues ([1](https://github.com/whosonfirst-data/whosonfirst-data/issues/900), [2](https://github.com/whosonfirst-data/whosonfirst-data/issues/936)) to track discrepencies at the `admin1` and `admin2` placetypes have been filed. These are mostly cases where either Statoids or WOF has outdated data or WOF has a placetype count different than sources show.

Closing issue and tracking future progress through follow up issues.
