### ISSUE TITLE
Reclassify "name:und_x_variant" properties for admin2 features

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#595]
Occasionally, new `admin2` features include a `"name:und_x_variant"` property field (example [here](https://github.com/whosonfirst-data/whosonfirst-data/pull/559/files/63641d50d912b6d2edd9ceea98dac819cb72b7e4..c9250e59f2f85708bdf6c7dfb186d170a3cfdc9e#diff-5c1d0336c44cd886c6f98a80dc85a986)).

Scrub new `admin2` and `admin1` features for the `"name:und_x_variant"` property field and move the value to the correct language variant space. Propose these changes in a new PR.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/531

**Comment by dianashk** [comment]
Seeing a good number of these in South Korean counties.

**Comment by dianashk** [comment]
Related: #528

**Comment by nvkelso** [comment]
@stepps00 can you take a look at this issue this week, please?

- one off fixes for Korea and Thailand
- Report (like pivot table) of country code + und names to see if there is an easy pattern for the rest to fix – if there is an easy pattern also fix in the same PR, else file followup issue.

**Comment by stepps00** [comment]
Re https://github.com/whosonfirst-data/whosonfirst-data/issues/595#issuecomment-337076332: 

https://github.com/whosonfirst-data/whosonfirst-data/pull/1007 and https://github.com/whosonfirst-data/whosonfirst-data/pull/1003 have been merged, taking care of cases in Korea and Thailand `county` records. 

I am filing another PR shortly to fix other records with `und_x_*` name properties. I have spot-checked remaining records and so far, all of the `name:und_x_*` values are stored in another `name:*` property.

**Comment by stepps00** [comment]
This issue should be fixed for all placetypes, not just admin1/admin2. We crawled all WOF records a while back to untangle the `name:und_x_` properties.

If any `und` name was found in another namespace, it was removed from the `und` list. Then, any leftover `und` names were stored in the `name:und_x_variant` property.

We can re-open this if needed.
