### ISSUE TITLE
Disputed areas need generic WOE sourced generic disputed names

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#6]
These disputed features currently show the WOE names from one of the country claimants, when they should instead show the generic "Disputed area" WOE names (see: 85632601 Abu Musa I. for better generic disputed names):
1. 85632447 Shaksam Valley                          data/856/324/47/85632447.geojson
2. 85632701 Arunachal Pradesh                       data/856/327/01/85632701.geojson
3. 85632221 Golan Heights                           data/856/322/21/85632221.geojson
4. 85632707 Ilemi Triangle                          data/856/327/07/85632707.geojson
5. 85632427 Jammu and Kashmir                       data/856/324/27/85632427.geojson
6. 85632197 Korean islands under UN jurisdiction    data/856/321/97/85632197.geojson
7. 85632195 Lawa Headwaters                         data/856/321/95/85632195.geojson
8. 85632445 No Man's Land (Fort Latrun)             data/856/324/45/85632445.geojson
9. 85632589 No Man's Land (Jerusalem)               data/856/325/89/85632589.geojson
10. 85632289 Shebaa Farms                            data/856/322/89/85632289.geojson
11. 85632711 UNDOF                                   data/856/327/11/85632711.geojson

**Comment by nvkelso** [comment]
Another example: `Falkland Islands (Islas Malvinas)` as **wof:name**. Debatable if the English preferred name should also be set to that value.

**Comment by nvkelso** [comment]
This can also apply to **marinearea** for `Persian Gulf (Arabian Gulf)`, and others.

**Comment by stepps00** [comment]
This will be taken care of through https://github.com/whosonfirst-data/whosonfirst-data-admin-xx/pull/12.
