### ISSUE TITLE
Fix hierarchy issues in Paris, FR

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#608]
It looks like many administrative features within Paris contain the [Paris-7E-Arrondissement](https://whosonfirst.mapzen.com/spelunker/id/102068177/#14/48.8551/2.3113) county in their hierarchy. The geometry of Paris-7E-Arrondissement spans an area just south of the Seine River in Central Paris, but it is included in the hierarchies of features that fall far outside of it's boundary.

Some examples of features outside of Paris-7E-Arrondissement that contain Paris-7E-Arrondissement in their hierarchy:

- https://whosonfirst.mapzen.com/spelunker/id/85873903/#12/48.8376/2.4106
- https://whosonfirst.mapzen.com/spelunker/id/420782701/#12/48.8590/2.3200
- https://whosonfirst.mapzen.com/spelunker/id/420782719/#12/48.8590/2.3200
- https://whosonfirst.mapzen.com/spelunker/id/420782687/#12/48.8590/2.3200

A list of the descendants of Paris-7E-Arrondissement:

- https://whosonfirst.mapzen.com/spelunker/id/102068177/descendants/?exclude=nullisland#12/48.8619/2.3609

Also, other `county` features in Paris **do not** have the expected adminsistrative descendants. For instance, [the descendants of Paris-19E-Arrondissement](https://whosonfirst.mapzen.com/spelunker/id/102070247/descendants/?exclude=nullisland#14/48.8815/2.3977) only include `venue` records. The only `county` record in Paris with administrative descendants is `Paris-7E-Arrondissement`; it seems to have taken over as the `county` hierarchy placetype for all places in Paris.

**Comment by nvkelso** [comment]
It’s the old problem where the Paris locality is parented by that “county”,
so anything that was geocoded to the locality would get that county,
instead of individually geocoding.

- https://whosonfirst.mapzen.com/spelunker/id/101751119/#12/48.8588/2.3200

That said, seems the “county” data here is super odd and should be cleaned
up.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/issues/410 was closed with new geometries and hierarchy updates added through that issue.

That work fixed this issue, too. Closing.
