### ISSUE TITLE
Create new country polygons out of mesoshape county children

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#611]
Similar to https://github.com/whosonfirst-data/whosonfirst-data/issues/486, we should dissolve the mesoshape counties together per country and import them as new alt-geometries at the `country` level.

**Comment by stepps00** [comment]
To do:

- [ ] Batch dissolve all `admin1` features to create dissolved country polygon
- [ ] Batch remove silver polygons and/or delete holes on dissolved country polygon
- [ ] Use alt_geom script to import new country geometries

@nvkelso - will these new dissolved mesoshapes country polygons fall into the default record or into a new alt_geom file?

**Comment by nvkelso** [comment]
The current adm0 country shapes are sourced from a pretty good US State
Department product now. So let’s store these into an alt geometry until we
can give them TLC.
