### ISSUE TITLE
Check validity of HASC codes in countries that did not receive a mesoshapes import

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#615]
The mesoshapes import included new features for 122 countries and _most_ of those features included a HASC code. In countries that did not receive a mesoshapes import, add the HASC id concordance.

In places like the U.S. and France, we can use the FIPS code to join to Statoids data and import the HASC id as a new concordance. 

Keep this issue open until we've gone through all `admin0`, `admin1`, and `admin2`.

- ~[ ] Country 1~
- ~[ ] Country 2~
- ~[ ] Country 3~

**Comment by nvkelso** [comment]
@stepps00 Please list the X number of countries this issues applies to as a checklist here.

**Comment by stepps00** [comment]
This has already been completed for `admin0`, `admin1`, and the majority of `admin2`records. 

No specific PR for this issue will be opened; this work is being done in parallel with the statoids import work. Will close once statoids imports are complete.

**Comment by stepps00** [comment]
Statoids import PRs have been merged, closing issue.
