### ISSUE TITLE
Merge Jämtland multi-polygon region in Sweden

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#618]
Sweden should only have 21 top-level `region` features, but we report 22 due to a duplicate `Jämtland`.

- The good one: https://whosonfirst.mapzen.com/spelunker/id/85688461/#6/63.397/14.487
- The leftover sliver that should be merged with `461`: https://whosonfirst.mapzen.com/spelunker/id/85688443/#13/62.0201/15.3904

**Comment by nvkelso** [comment]
Related: 

- https://github.com/whosonfirst-data/whosonfirst-data/issues/617

**Comment by stepps00** [comment]
The current [Jämtland record](https://whosonfirst.mapzen.com/spelunker/id/85688461/#6/63.397/14.487) now contains the geometry of the smaller, deprecated [Jämtland record](https://whosonfirst.mapzen.com/spelunker/id/85688443/#13/62.0201/15.3904).

The superseding work/deprecating happened in a prior commit (https://github.com/whosonfirst-data/whosonfirst-data/commit/5941e41a0a98dc9643d71c464db08d0b61312422). Closing issue.

**Comment by stepps00** [comment]
Noting that Sweden also correctly has 21 `region` descendants now, too.. 

https://whosonfirst.mapzen.com/spelunker/id/85633789/descendants/?exclude=nullisland&placetype=region
