### ISSUE TITLE
Something something Neptune Memorial Reef™

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst-data/whosonfirst-data#623]
I guess this should be in Who's On First?

> The Neptune Memorial Reef™ is the largest man-made reef ever created, located 3.25 miles east of Key Biscayne in Miami, Florida. It’s GPS are coordinates N25º 42.036′, W80º 05.409′. Forty feet beneath the ocean’s surface, the Memorial Reef is an artistic representation of the Lost City of Atlantis. The reef serves as an underwater mausoleum for cremated remains, as well as a home for a growing marine habitat, fulfilling its mission of “creating life after life”.
Engineering the Memorial Reef required passing strict regulations, such as the ability to withstand the strongest storm of the last 100 years.

https://www.neptunesociety.com/memorial-reef

**Comment by nvkelso** [comment]
This sounds like a venue feature.

**Comment by stepps00** [comment]
Location: N25° 42.036' W80° 05.409'
Converted to: **25.7006000, -080.0901500**

Source: http://www.nmreef.com/dive-memorial-reef.html

**Comment by stepps00** [comment]
Created record through Boundary Issues that includes `edtf:inception`, `name:eng_x_variant`, and `wof:tags`:

https://whosonfirst.mapzen.com/boundaryissues/id/1125413993/#16/25.7007/-80.0902
