### ISSUE TITLE
Upgrade neighbourhood shapes for Amsterdam

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#625]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Prep for import**
  - [x] Sources repo PR
  - [x] Properties repo PR
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Data source: [Statistics Netherlands](https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische%20data/wijk-en-buurtkaart-2016)

Cities/municipalities are called **Gemeenten**.
Neighborhoods are called **(Woon-)Wijken**. Amsterdam calls these **Buurtcombinaties**.
Microhoods are called **Buurten**.

**Comment by nvkelso** [comment]
(Looks like the national source has full rural coverage, but with funny named features. So worth it for big urban places like Amsterdam but use caution in rural areas.)

**Comment by nvkelso** [comment]
@stepps00 was Amsterdam merged to master?

**Comment by stepps00** [comment]
@nvkelso no, Amsterdam and surrounding localities are in S3

**Comment by stepps00** [comment]
Amsterdam neighbourhood work is complete ( 	b1d9abd) and was merged to master. Closing issue.
