### ISSUE TITLE
Cleanup Helsinki neighbourhoods to only have 2d geom coord

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#631]
The 3d coords are causing problems on ingest into vector tiles. Technically they are "correct" and Tilezen needs to update, but practically the 3d coords are not necessary and we should make them 2d in the source data.

**Comment by stepps00** [comment]
List of feature `wof:id`s that are affected by this issue:
`1108727331`, `1108727335`, `1108727337`, `1108727339`, `1108727347`, `1108727349`, `1108727355`, `1108727357`, `1108727359`, `1108727363`, `1108727369`, `1108727371`, `1108727373`, `1108727375`, `1108727377`, `1108727381`, and `1108727383`
