### ISSUE TITLE
Incorrect parent for Pathankot airport

### ISSUE THREAD

**Issue by tallytalwar** [whosonfirst-data/whosonfirst-data#640]
While working on an election map for the state of Punjab, India, I noticed following was incorrect:

https://whosonfirst.mapzen.com/spelunker/id/102556027/#5/31.819/77.287

Feature Name: Pathankot Airport
Ideally should be placed under ["Pathankot"](https://whosonfirst.mapzen.com/spelunker/id/102029059/#9/32.2686/75.6519), which is under ["Punjab"](https://whosonfirst.mapzen.com/spelunker/id/85672195/#7/31.050/75.376).

On a slightly tangential issue, wof has 20 districts/county for the state of Punjab (https://burritojustice.github.io/wof-descender/?wof_id=85672195&wof_level=county). As per [2011 census](http://goidirectory.gov.in/district.php) Punjab has [22 districts](http://goidirectory.gov.in/district_categories1.php?ou=PB). 2 missing ones are:
- Pathankot: https://whosonfirst.mapzen.com/spelunker/id/102029059/#9/32.2686/75.6519
- Fazilka: https://whosonfirst.mapzen.com/spelunker/id/890504853/#7/31.050/75.376

I am not able to find any shape files for these anywhere on the web, and was not able to convert the `.shx` and `.shp` shapefiles [here](https://github.com/datameet/maps/tree/master/Districts/Census_2011).

**Comment by tallytalwar** [comment]
Second part of this is covered under: https://github.com/whosonfirst-data/whosonfirst-data/issues/636

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/commit/b96acc77547e5c323d7e1907d7d833114c6554a4

**Comment by stepps00** [comment]
The airport record should now have the correct geometry and hierarchy, closing this issue.

https://whosonfirst.mapzen.com/spelunker/id/102556027
