### ISSUE TITLE
Add unlc:subdivision to wof:concordances property

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#641]
Many features, like [Calvados, FR](https://whosonfirst.mapzen.com/spelunker/id/85683579/#9/49.0919/-0.3567) have a `unlc:subdivision` property. This property value should instead be stored in the `wof:concordances` property.

Propose a PR with all affected features that adds this field to the `wof:concordances`.

**Comment by stepps00** [comment]
@thisisaaronland - I think you added this property to WOF features, am I understanding this right?

**Comment by thisisaaronland** [comment]
I did. It may or may not be treated as a concordance but it should not otherwise be removed, because this: https://github.com/whosonfirst-data/whosonfirst-data/issues/221
