### ISSUE TITLE
PDX (and friends)

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#643]
https://whosonfirst.mapzen.com/spelunker/id/1108721307/ <-- I love airports but I am pretty sure they are not neighbourhoods...

not to mention https://whosonfirst.mapzen.com/spelunker/id/102532251/

**Comment by thisisaaronland** [comment]
Okay, what's going on here...

* Oakland: https://whosonfirst.mapzen.com/spelunker/id/1108794155/
* Atlanta: https://whosonfirst.mapzen.com/spelunker/id/1108798501/

PDX, OAK and ATL are all from Zach's imports. Zetashapes does it to but that doesn't make it correct:

* https://whosonfirst.mapzen.com/spelunker/id/85870675

These are **not** neighbourhoods. They have better geometries than the existing airport/campus records so we should update accordingly but these records should be deprecated. Are there other instances like this in the remaining neighbourhood imports?

https://whosonfirst.mapzen.com/spelunker/search/?name=Airport&placetype=neighbourhood

**Comment by thisisaaronland** [comment]
SJC... not a neighbourhood:

https://whosonfirst.mapzen.com/spelunker/id/1108779019/

**Comment by thisisaaronland** [comment]
https://whosonfirst.mapzen.com/spelunker/search/?name=Airport&placetype=campus

**Comment by nvkelso** [comment]
This setup follows the template and workflow guidance, so it's on me to defend the rational or change the rational. I'll follow up next week..

**Comment by thisisaaronland** [comment]
Bump.

**Comment by nvkelso** [comment]
Fixed via https://github.com/whosonfirst-data/whosonfirst-data/issues/677.
