### ISSUE TITLE
EDTF dates

### ISSUE THREAD

**Issue by rmarianski** [whosonfirst-data/whosonfirst-data#644]
Some records have invalid [edtf dates](http://www.loc.gov/standards/datetime/pre-submission.html). For example, in [420517943](https://whosonfirst.mapzen.com/spelunker/id/420517943/) the `edtf:deprecated` field is `2017/01/03` and it should be `2017-01-03`.

Based on some tile logs, these look to be the affected ids, although I'm not 100% confident it's everything:

* 420517887
* 420517943
* 420781713
* 85808173
* 85837101
* 85851825
* 85866899
* 85866915
* 85872043

The fields that tiles processes look at are:

* edtf:inception
* edtf:cessation
* edtf:deprecated

**Comment by rmarianski** [comment]
Related to https://github.com/tilezen/tilequeue/pull/154

**Comment by stepps00** [comment]
@rmarianski - thanks for the issue.. PR is a work in progress; a few additional records were found with this issue. I will update [the PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/647) once complete.

**Comment by ZBSingleton** [comment]
@stepps00 these should be the last of the features needing updates in master, sorry for the long list!

- 85804751
- 85807911
- 85812215
- 85816191
- 85816501
- 85825631
- 85830819
- 85832987
- 85837709
- 85837755
- 85852255
- 85872047
- 85872099
- 85872117
- 85872131
- 85872133
- 420558565
- 420558673
- 420558851
- 420558853
- 420558873
- 420558877
- 420559055
- 420559629
- 420559943

- 85819463
- 85839789
- 85844921
- 85866907
- 85872057
- 85872107
- 85889947
- 85889983
- 420517729
- 420517883
