### ISSUE TITLE
places with the name 'Street'

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#646]
the following wof records have the name 'Street' which, albeit possible, are unlikely the correct name:

```
Street|default|101852537
Street|default|404439545
Street|eng|101852537
Street|eng|404439545
```

**Comment by stepps00** [comment]
Research of Street, Somerset suggests there is nothing actionable for this issue. The records listed above ([101852537](https://whosonfirst.mapzen.com/spelunker/id/101852537/#13/51.1282/-2.7426) and [404439545](https://whosonfirst.mapzen.com/spelunker/id/404439545/#13/51.1282/-2.7426)) represent a valid, current location in England.

Street "is a large village and civil parish in the county of Somerset, England." ([source](https://en.wikipedia.org/wiki/Street,_Somerset)).

Additional references:
- [DMOZ](https://www.dmoz.org//Regional/Europe/United_Kingdom/England/Somerset/Street/)
- [Office for National Statistics](http://neighbourhood.statistics.gov.uk/dissemination/LeadTableView.do?a=7&b=11129232&c=Street&d=16&e=61&g=6461405&i=1001x1003x1032x1004&m=0&r=1&s=1487017562715&enc=1&dsFamilyId=2491&nsjs=true&nsck=false&nssvg=false&nswid=1440)
- [Somerset Guide](http://www.somersetguide.co.uk/Street/)

**Comment by stepps00** [comment]
Over to @nvkelso before I close this issue.

**Comment by nvkelso** [comment]
The world is weird and wonderful! :)

**Comment by dphiffer** [comment]
Yo @nvkelso I'm gonna steal that as the title for a conference talk proposal.
