### ISSUE TITLE
Investigate and fix Afganistan

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#65]
Two duplicate province names (Parwan & Uruzgan) and two missing province names (Daykundi & Panjshir) in the WOF data.  

Review WOF spellings.

**Comment by stepps00** [comment]
Keeping this issue open until the mesoshapes import is complete, but the 400 districts of Afghanistan are in [this PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/471). The provinces will be created by dissolving the districts in QGIS, potentially with HASC code (being tracked in https://github.com/whosonfirst-data/whosonfirst-data/issues/486).

WIll close this issue once the mesoshapes work is complete.

**Comment by stepps00** [comment]
The referenced PR was merged and the provinces were updated. WOF now has records for Daykundi and Panjshir.

https://whosonfirst.mapzen.com/spelunker/id/85632229/descendants/?exclude=nullisland&placetype=region

Closing issue.
