### ISSUE TITLE
Investigate and fix Albania

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#66]
WOF is missing Tirana, and has a duplicate for Durrës

Albania is undergoing territorial reform in 2015.  It impacts the subdivisions of these regions.
Maps and other details about the reform on the [Reforma Administrative Territoriale Website](http://www.reformaterritoriale.al/en/)

**Comment by stepps00** [comment]
Albanian `region` records have been updated through work done in #486 and #660. The duplicate record for Durres was deprecated and the missing record for Tirana was created and imported.

https://whosonfirst.mapzen.com/spelunker/id/85632405/descendants/?exclude=nullisland&placetype=region

Closing issue.
