### ISSUE TITLE
Import HASC concordance for countries with "great" coverage

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#663]
In anticipation of the Statoids data join, verify that all `admin2` features in the following countries have complete and accurate `hasc` concordance coverage.

- [x] Yemen - No additional HASC work needed.
- [x] Tajikistan - No additional HASC work needed.
- [x] Swaziland - No additional HASC work needed.
- [x] Suriname - No additional HASC work needed.
- [x] South Africa - No additional HASC work needed.
- [x] Senegal - One record updated (in commit).
- [x] Rwanda - No additional HASC work needed.
- [x] Peru - No additional HASC work needed.
- [x] Papua New Guinea - No additional work needed.
- [x] Palestine - No additional HASC work needed.
- [x] Oman - No additional HASC work needed.
- [x] Niger - Four records updated (in commit).
- [x] Nepal - No additional HASC work needed.
- [x] Lebanon - No additional HASC work needed.
- [x] Israel - No assitional HASC work needed.
- [x] Haiti - No additional HASC work needed.
- [x] Gambia - No additional HASC work needed.
- [x] French Guiana - No additional HASC work needed.
- [x] Costa Rica - Two records updated (in commit).
- [x] Cameroon - One record updated (in commit).
- [x] Burkina Faso - No additional HASC work needed.
- [x] Belarus - No additional HASC work needed.

Preliminary look suggests these countries all have "great coverage;" make changes for `admin2` features in the countries listed above in a single PR.

**Comment by nvkelso** [comment]
Please push your local branch for this issue (the 3 countries noted above).

**Comment by stepps00** [comment]
Branch is here: https://github.com/whosonfirst-data/whosonfirst-data/compare/stepps00/hasc-great

Holding off on creating a PR for this branch until all outstanding meso PRs land in `master`. There may be additional countries with "great" hasc coverage to track.
