### ISSUE TITLE
Import HASC concordance for countries with "ok" coverage

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#665]
In anticipation of the Statoids data join, verify all `admin2` features in the following countries so have complete and accurate `hasc` concordance coverage.

- [x] Argentina
- [x] Bhutan
- [x] Bolivia
- [x] Chile
- [x] Colombia
- [x] Cuba
- [x] Dominican Republic
- [x] Ecuador
- [x] El_Salvador
- [x] Gabon
- [x] Georgia
- [ ] Iran (skipping)
- [x] Israel
- [x] Kyrgyzstan
- [x] Laos
- [ ] Liberia (skipping)
- [x] Malaysia
- [x] Mali
- [x] Mauritania
- [ ] Mongolia (skipping)
- [x] Mozambique
- [x] Myanmar
- [x] New Zealand
- [x] Nicaragua
- [x] Nigeria
- [x] Panama
- [x] Saudi Arabia

Preliminary look suggests these countries all have "ok coverage;" make changes for `admin2` features in the countries listed above in a single PR.

**Comment by stepps00** [comment]
Notes from above: 

- Skipping Iran and Mongolia because there are no additional properties from Statoids to import into Who's On First.
- Skipping Liberia because the list of `admin2` features is out-of-date on Statoids.

**Comment by nvkelso** [comment]
In conversation, the checkboxes in the main issue description are "ready for HASC join & import".

**Comment by stepps00** [comment]
Statoids imports for these countries are being tracked here: https://github.com/whosonfirst-data/whosonfirst-data/pull/920

**Comment by stepps00** [comment]
Closing issue.

Fixed, via: #920.
