### ISSUE TITLE
Import HASC concordance for countries with "bad" coverage

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#669]
In anticipation of the Statoids data join, update all `admin2` features in the following countries so have complete and accurate `hasc` concordance coverage.

- ~[ ] Afghanistan~
- ~[ ] Cambodia~
- ~[x] Chad~
- ~[ ] China~
- ~[ ] Egypt~
- ~[x] Ethiopia - several features do not match research/statoids, thus do not have hasc.~
- ~[x] Guyana - "Unorganized" give "NO DATA" values.~
- ~[ ] Honduras~
- ~[ ] India~
- ~[ ] Indonesia~
- ~[ ] Japan~
- ~[ ] Pakistan~
- ~[x] Paraguay - several features do not match research/statoids, thus do not have hasc.~
- ~[ ] Philippines~
- ~[ ] Russia - Gotta love 1000s of features.~
- ~[x] South_Sudan~
- ~[x] Sri Lanka~
- ~[ ] Thailand~
- ~[ ] Turkey~
- ~[ ] Uganda~
- ~[ ] Ukraine~
- ~[ ] Venezuela~

Preliminary look suggests these countries all have "bad coverage;" make changes for `admin2` features in the countries listed above in a single PR.

**Comment by nvkelso** [comment]
Blocked by:

- #652 Postmeso updates - Ukraine admin-2 county merge-me meso sanity-check
- #569 Mesoshapes county 1.0 cleanup - Indonesia merge-me meso sanity-check

**Comment by stepps00** [comment]
Statoids imports for these countries are being tracked here: https://github.com/whosonfirst-data/whosonfirst-data/pull/920

**Comment by stepps00** [comment]
Closing issue.

Fixed, via: https://github.com/whosonfirst-data/whosonfirst-data/pull/920
