### ISSUE TITLE
Investigate and fix Armenia

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#67]
WOF has Erevan, which could be an alternate spelling.  Yerevan is the English spelling.  It's also the capital.

See official [government website](http://www.gov.am/en/regions/).

**Comment by stepps00** [comment]
Armenia `admin2` data is sparce, so new `admin1` features will not be created for this country. Who's On First already has coverage at the `admin1` level in Armenia, so a simple update to the `wof:name` and preferred name field should be sufficient to fix this issue.
