### ISSUE TITLE
Import HASC codes for meso countries with "no" coverage

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#670]
In anticipation of the Statoids data join, update all `admin2` features in the following countries so have complete and accurate hasc concordance coverage.

- [x] Angola
- [x] Armenia
- [x] Azerbaijan
- [x] Belize
- [x] Benin
- [x] Bosnia
- [x] Burundi
- [x] Canada
- [x] Central African Republic
- [x] Cyprus
- [x] Djibouti
- [x] Dominica
- [x] Equatorial_Guinea
- [x] Eritrea
- [x] Ghana
- [x] Guinea
- [x] Guinea Bissau
- [x] Ivory Coast
- [x] Jamaica
- [x] Kenya
- [x] Kosovo
- [x] Macedonia
- [x] Madagascar
- [x] Malawi
- [x] Mauritius
- [x] Morocco
- [x] Namibia
- [x] Qatar
- [x] Serbia
- [x] Sierra Leone
- [x] Somalia
- [x] Somaliland
- [x] Syria
- [x] Taiwan
- [x] Tunisisa
- [x] Uruguay
- [x] Vietnam
- [x] Zambia
- [x] Zimbabwe

These countries all have no coverage; make changes for `admin2` features in the countries listed above in a single PR.

**Comment by nvkelso** [comment]
There are a lot here, fine to track in one issue but let’s break the PRs up
into 5-10 countries per PR.

**Comment by nvkelso** [comment]
In conversation today we think that some of these will **gain** HASC after earlier Mesoshapes PRs merge, so will update the list above (use ~~strikeout~~ to remove from list).

**Comment by nvkelso** [comment]
Blockers:

- #561 Mesoshapes County Import - Round 2.2 admin-2 county merge-me meso sanity-check
- #555 Mesoshapes County Import - Round 2.0 merge-me meso sanity-check

**Comment by stepps00** [comment]
No longer blocked.

This work will be taken care of in upcoming `admin2` statoids imports - no specific PR will be created for this issue.

**Comment by stepps00** [comment]
Taken care of in https://github.com/whosonfirst-data/whosonfirst-data/pull/921.

Closing issue.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/921 merged.
