### ISSUE TITLE
Append "District" to the end of Airport neighbourhood names

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#672]
In previous areas where we have completed neighbourhood upgrade work (and for all future neighbourhood imports), the `wof:name` of each neighbourhood representing an airport should have ` District` appended to the end of the name. 

As an example, the record for the [Portland International Airport](https://whosonfirst.mapzen.com/spelunker/id/1108721307/#13/45.5840/-122.5910) neighbourhood should actually have a `wof:name` of `Portland International Airport District`.

Go back through each market, update the Airport neighbourhood record in a branch, and propose a PR.

**Comment by nvkelso** [comment]
@stepps00 for markets already merged and to update workflow docs.
@ZBSingleton for markets that haven't been merged yet (and future workflows).

**Comment by stepps00** [comment]
Related to: https://github.com/whosonfirst-data/whosonfirst-data/issues/673

**Comment by nvkelso** [comment]
This is a fix for https://github.com/whosonfirst-data/whosonfirst-data/issues/643.

**Comment by nvkelso** [comment]
Closed via https://github.com/whosonfirst-data/whosonfirst-data/issues/677
