### ISSUE TITLE
Update geometries for Airport campus records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#673]
In previous areas where we have completed neighbourhood upgrade work (and for all future neighbourhood imports), the geometry of each campus representing an airport should have a new geometry, which should be the same shape as the neighbourhood feature for that airport district. 

As an example, the campus record for the [Portland International Airport](https://whosonfirst.mapzen.com/spelunker/id/102532251/#13/45.5848/-122.5826) should actually have a geometry equal to the [Portland International Airport](https://whosonfirst.mapzen.com/spelunker/id/1108721307/#13/45.5840/-122.5910) neighbourhood.

Go back through each market, update the Airport campus record in a branch, and propose a PR.

**Comment by nvkelso** [comment]
For new workflow we’ll want to add a (proposed) geom_id`  property and set
it to the airports campus `wof:id` value, and @thisisaaronland will need to
add new feature to import script to support that.

**Comment by nvkelso** [comment]
For new workflow we’ll want to add a (proposed) `geom_id` property and set
it to the airports campus `wof:id` value, and @thisisaaronland will need to
add new feature to import script to support that.

**Comment by thisisaaronland** [comment]
I am going to parrot back what I think I understand here:

* If I see a property called `geom_id` (and I would like to propose that it be `mz:geom_id` at least by the time it reaches code (so something something something property aliases) just to ensure that everything is namespaced) then:

* Update the geometry of the thing referenced by `mz:geom_id` with the current geometry
* Remove the `mz:geom_id` property (before exporting the current record)

Correct?

**Comment by nvkelso** [comment]
Yes :)

**Comment by stepps00** [comment]
FYI - [properties alias](https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/property_aliases.json#L212) and the [external editor option](https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/scripts/wof-csv-to-feature-collection#L104) have been updated to include the `mz:geom_id` prop.
