### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by rjpereira** [whosonfirst-data/whosonfirst-data#674]
Hi.
Is there a guide/page somewhere describing how to contribute to the dataset ? As a start I'd like to contribute some localities that I see missing from my country, but not sure how to exactly start....
Thanks

**Comment by rjpereira** [comment]
Arghhh...the how to was a link on the page while submitting :-) Sorry

**Comment by stepps00** [comment]
@rjpereira - don't hesitate to ping us if you have any questions!
