### ISSUE TITLE
Is there an easy way to get a subset of data from a GeoJSON file?

### ISSUE THREAD

**Issue by davidbarratt** [whosonfirst-data/whosonfirst-data#676]
I ran into a place, [Australia](https://whosonfirst.mapzen.com/spelunker/id/85632793/), that has a 54MB (!) response size:
```
$ curl --compressed -so /dev/null https://whosonfirst.mapzen.com/data/856/327/93/85632793.geojson -w '%{size_download}'
54141806
```

All I need out of this response is the `parent_id` and the translated names, everything else is extraneous data for the application I'm building. Is there an easy way to reduce this response size to something manageable?

The only thing I could come up with is to have an application that would work as a reverse proxy and fetch this data and strip out the extraneous data and then cache the response somewhere. Any other ideas or is this the best solution?

**Comment by nvkelso** [comment]
We'd like to get the response size down to < 2mb (e.g. https://github.com/whosonfirst-data/whosonfirst-data/issues/131), but it sounds like even that is excessive for your use case. 

@thisisaaronland good test candidate for WOF API early access?

**Comment by davidbarratt** [comment]
@nvkelso well that would certainly be an improvement. I was going to have clients (browser) download the geojson so they could get the properly translated name of the place, but that doesn't sound like a good idea (even at 2mb... probably not a good idea on a mobile device).

**Comment by thisisaaronland** [comment]
```
curl -X GET 'https://whosonfirst-api.mapzen.com/?method=whosonfirst.places.getInfo&id=85632793&extras=name:&api_key=YOUR_MAPZEN_APIKEY'

{
	"record": {
		"wof:id": 85632793,
		"wof:parent_id": "102191583",
		"wof:name": "Australia",
		"wof:placetype": "country",
		"wof:country": "AU",
		"wof:repo": "whosonfirst-data",
		"name:mzn_x_preferred": [
			"استرالیا"
		],
		"name:new_x_preferred": [
			"अस्त्रेलिया"
		],
		"name:kal_x_preferred": [
			"Australia"
		],
                ...
		"name:lez_x_preferred": [
			"Австралия"
		],
		"name:ind_x_preferred": [
			"Australia"
		]
	},
	"stat": "ok"
}
```

Note the use of `&extras=name:` which says please include all the properties prefixed with `name:`

The goal is for this to be live and documented inside of the next couple weeks. I am just dealing with all the remaining fiddly details right now...

**Comment by thisisaaronland** [comment]
Also, just to be clear: What you're seeing above can be _probably_ be considered stable but it remains possible that things may change a bit between now and "live".

**Comment by davidbarratt** [comment]
@thisisaaronland This is amazing! Thank you! and I will anticipate changes.
