### ISSUE TITLE
Update hierarchy, belongsto, and controlled properties for NYC locality record

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#689]
[This commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/d35109870be2f61c4de05b8179ca13b658e5d4c5#diff-dba7b5f461d06c17e6c70790416b7993) reverted previous changes made to the `wof:controlled`, `wof:hierarchy`, and `wof:belongsto` fields in the locality record for New York City. 

Propose a PR to roll back these changes to the [New York City locality](https://whosonfirst.mapzen.com/spelunker/id/85977539/#9/40.6979/-73.9797) record. Changes should reflect what was completed in commits [1](https://github.com/whosonfirst-data/whosonfirst-data/commit/4ddc8a5496556f0d66340977ff773f1f0deccf4e#diff-dba7b5f461d06c17e6c70790416b7993), [2](https://github.com/whosonfirst-data/whosonfirst-data/commit/2ec9f93abc1a7d592315cc363b6394f913bdecd6#diff-dba7b5f461d06c17e6c70790416b7993), and [3](https://github.com/whosonfirst-data/whosonfirst-data/commit/75b046ef7574d494c7de003235eeafa69e3d469e#diff-dba7b5f461d06c17e6c70790416b7993).

[Git History](https://github.com/whosonfirst-data/whosonfirst-data/commits/master/data/859/775/39/85977539.geojson) for reference.

**Comment by nvkelso** [comment]
Please file a followup issue for the rePIPing of some of the NYC venues.

**Comment by stepps00** [comment]
Follow up issue regarding venues filed and referenced above.
