### ISSUE TITLE
Region bundle is empty

### ISSUE THREAD

**Issue by rjpereira** [whosonfirst-data/whosonfirst-data#691]
Apologise if this is not rh right place to report a problem with the distribution point of from mapzen, but noticed now that the region bundle is now empty (https://whosonfirst.mapzen.com/bundles/wof-region-latest.csv has 0 bytes).

Is there someone here that can follow up or let me know how to contact the team ?

Thanks

**Comment by nvkelso** [comment]
@dphiffer This sounds like the same bug that came up last week that you fixed for the PIP machines?

**Comment by dphiffer** [comment]
Yes, I was thinking that was the case too. I'll confer with @thisisaaronland.

**Comment by thisisaaronland** [comment]
@rjpereira - Fixed. Apologies for the bad craziness.

The tl;dr is "git lfs ...good times". That's actually the longer version,  too. The long version is how we got to that place at all but that will require a little more digging.
