### ISSUE TITLE
Incorrect superseding value for Northeast PDX neighbourhood

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#692]
The [neighbourhood record](https://whosonfirst.mapzen.com/spelunker/id/85893213/#15/45.5567/-122.6448) of "Northeast" in Portland has a `wof:superseded_by` value of "1108720843". This value should actually be "1108720843" to point to the new [Northeast macrohood](https://whosonfirst.mapzen.com/spelunker/id/1108720843/#12/45.5658/-122.5784) record.

**Comment by nvkelso** [comment]
(This is related to Nat's neighbourhood curation import.)
