### ISSUE TITLE
Bassas da India isn't a dependency

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#7]
wof_id  iso name    parent_id
85632337    TF  Bassas da India 85633147    

data/856/323/37/85632337.geojson

Bassas da India mapunit of 85632549 French Southern and Antarctic Lands (that region doesn't really have administrative subdivisions, each island is shown as a map unit in Natural Earth).

**Comment by nvkelso** [comment]
Ah, this should be disputed with Morocco, and just a tiny island between Madagascar and the African main continent.

**Comment by stepps00** [comment]
#687 and #681 have been merged. [Bassas de India](https://whosonfirst.mapzen.com/spelunker/id/1108833329/) is now a `disputed` record, closing issue.
