### ISSUE TITLE
admin-2-counties have ALL CAPS names

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#70]
Some geographies have place names in all caps.

For instance SERRA TALHADA (wof_id: 102056839) in Brazil should be something more like Serra Talhada.

Reported by @missinglink

**Comment by missinglink** [comment]
duplicate: https://github.com/whosonfirst/whosonfirst-data/issues/164

**Comment by stepps00** [comment]
Suggest we close this issue in preference of #164, which will update _all_ records, including any records with an admin2-level placetype.
