### ISSUE TITLE
Clean up records with a megacity tag

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#701]
Sort through all records with a `"wof:megacity":"1",` property (list of records [here](https://whosonfirst.mapzen.com/spelunker/megacities/#2/25.0/103.8)) and remove any records with an incorrect megacity tag. 

**Examples:**
- [Pechs](https://whosonfirst.mapzen.com/spelunker/id/85907577/#13/24.8740/67.0631), which should probably be Karachi.
- [Sydney](https://whosonfirst.mapzen.com/spelunker/id/85771099/#14/-34.0389/151.1938), which should actually be the `locality` of Syndey.
- [These neighbourhoods](https://whosonfirst.mapzen.com/spelunker/megacities/?&placetype=neighbourhood#2/5.5/151.2), which should probably point to the parent `locality`, not the neighbourhood.

Once complete, this tag should be used to generate new `metroarea` geometries and records.

**Comment by nvkelso** [comment]
Sounds good. Let's keep this issue focused on the `wof:megacity` property cleanup only. The `metroarea` work is for later, and loosely related.

**Comment by stepps00** [comment]
Per #790:

```
Heya,

I would like to use the wof:megacity flag to identify 'big name geocoding targets' :)

After clicking around a bit it seems like the property might not be rolled out across the whole repo?

ie.

Los Angeles (85923517, population ~4M) is considered a megacity but
London (101750367, population ~8M) is not?

what's the intended behavior of the megacity flag? is it simply cities over a certain population or is there more to it than that?

oh PS. @stepps00 that property is also a string when it could be encoded as a bool or an int:

javascript
"wof:megacity": "1",

thanks!

```

**Comment by stepps00** [comment]
Just in case, [here](https://github.com/whosonfirst-data/whosonfirst-data/files/4020397/megacities.txt) is a recent list of all records (ids and repo cc) for all records with a megacity tag.

**Comment by stepps00** [comment]
There are only two existing "megacity" localities missing population properties, both in China:

https://spelunker.whosonfirst.org/id/102027337/
https://spelunker.whosonfirst.org/id/102027369/

**Comment by stepps00** [comment]
The various PRs linked above should fix issues with **existing** "megacity" records.

In some cases, WOF maintained a `wof:megacity` property value of 1 for neighbourhoods, when the property should have been given to the parent locality (example: https://github.com/whosonfirst-data/whosonfirst-data-admin-bg/pull/8)

In some cases, WOF maintained a `wof:megacity` property value of 1 for the wrong locality, because a locality with the same name was flagged as a megacity. An example is Prague, USA being flagged, rather than Prague, CZ being flagged (https://github.com/whosonfirst-data/whosonfirst-data-admin-cz/pull/7)

In some cases, WOF was missing a `wof:megacity` property value of 1 for a locality record because it was not maintained through superseding work (example: https://github.com/whosonfirst-data/whosonfirst-data-admin-mx/pull/9 ) 

And, lastly, two locality records that correctly had `wof:megacity` flags in China were given population properties because they were missing.

This PR **does not** add all of the "megacity" property flags that are missing in various records. That work will be completed through https://github.com/whosonfirst-data/whosonfirst-data/issues/1547, as will adding polygons/population data to those ~600 records.

This PR simply corrects existing megacity flags and cleans up records for future work.

**Comment by stepps00** [comment]
Above PRs have been merged, closing this issue.
