### ISSUE TITLE
Localities in Mexico not named Mexico with Mexico spa_x_preferred

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#703]
Hi, I found these localities in Mexico that aren't named Mexico but have Mexico as a preferred spa name:

[Celaya](https://whosonfirst.mapzen.com/spelunker/id/101993095)
[Mexicali](https://whosonfirst.mapzen.com/spelunker/id/101993461)
[Ciudad Obregón](https://whosonfirst.mapzen.com/spelunker/id/101993827)
[Tultepec](https://whosonfirst.mapzen.com/spelunker/id/101991641)
[Silao](https://whosonfirst.mapzen.com/spelunker/id/101996777)
[Chihuahua](https://whosonfirst.mapzen.com/spelunker/id/101994137)
[Chichiquila](https://whosonfirst.mapzen.com/spelunker/id/101999407)
[Ecatepec de Morelos](https://whosonfirst.mapzen.com/spelunker/id/101992735)
[Veracruz](https://whosonfirst.mapzen.com/spelunker/id/101998843)
[Veracruz](https://whosonfirst.mapzen.com/spelunker/id/101998203)
[Agua Dulce](https://whosonfirst.mapzen.com/spelunker/id/101998901)
[Mérida](https://whosonfirst.mapzen.com/spelunker/id/102001097)
[Heroica Matamoros](https://whosonfirst.mapzen.com/spelunker/id/102000961)
[Minatitlán](https://whosonfirst.mapzen.com/spelunker/id/102000637)
[Minatitlán](https://whosonfirst.mapzen.com/spelunker/id/102000639)
[Nuevo Laredo](https://whosonfirst.mapzen.com/spelunker/id/102000965)

**Comment by stepps00** [comment]
Thanks for compiling this list, @trescube !
