### ISSUE TITLE
Cleanup admin-2-county names so they are human readable

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#71]
eg. central Paris ( 'PARIS-13E-ARRONDISSEMENT' ) (wof_id: 102069301)

reported by @missinglink

**Comment by stepps00** [comment]
Started correcting this issue with features in Paris that contain "-ARRONDISSEMENT" in the `wof:name` field by testing a modified version of the [add-field.py script](https://github.com/mapzen/whosonfirst-toolbox/blob/348e161b1a97ef0dcbec6be1788224c7024013eb/scripts/add-field.py).

Most recent commit in [this branch](https://github.com/whosonfirst-data/whosonfirst-data/tree/stepps00/france-names) takes care of this issue for records in Paris - are we keeping this issue open to clean-up **all** name fields for admin-2 features across WOF? 

Also, sources show that the correct `wof:name` for the example above, PARIS-13E-ARRONDISSEMENT, would be 13th Arrondissement of Paris (see: [this page](https://en.wikipedia.org/wiki/13th_arrondissement_of_Paris)). Features updated accordingly; I'll keep the branch open until discussion.

**Comment by nvkelso** [comment]
I'm fine closing this one, yeah!
