### ISSUE TITLE
Implode capital locality records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#711]
Similar to what happened with Wellington (tracked [here](https://github.com/whosonfirst-data/whosonfirst-data/issues/118)), the following localites have been split into multiple records:

- Athens:

  - https://whosonfirst.mapzen.com/spelunker/id/101752329 <- this geom for Athens is correct. No edits needed. 
  - https://whosonfirst.mapzen.com/spelunker/id/101913513 <- this is actually the rough geom for 1126028555.
  - https://whosonfirst.mapzen.com/spelunker/id/101913511 <- this is actually the rough geom for 1125835375.

- Jerusalem:

  - https://whosonfirst.mapzen.com/spelunker/id/101922189
  - https://whosonfirst.mapzen.com/spelunker/id/101922289
  - https://whosonfirst.mapzen.com/spelunker/id/101922269
  - https://whosonfirst.mapzen.com/spelunker/id/101922261
  - https://whosonfirst.mapzen.com/spelunker/id/101922271
  - https://whosonfirst.mapzen.com/spelunker/id/101922243
  - https://whosonfirst.mapzen.com/spelunker/id/101922257
  - https://whosonfirst.mapzen.com/spelunker/id/101922193

The best thing to do here is to merge all of these into a single record. More work is needed to untangle the areas around Jerusalem.

- Brussels:

  - https://whosonfirst.mapzen.com/spelunker/id/101751573/
  - https://whosonfirst.mapzen.com/spelunker/id/101913231/
  - https://whosonfirst.mapzen.com/spelunker/id/101913235/
  - https://whosonfirst.mapzen.com/spelunker/id/101913241/
  - https://whosonfirst.mapzen.com/spelunker/id/101913243/
  - https://whosonfirst.mapzen.com/spelunker/id/101913245/
  - https://whosonfirst.mapzen.com/spelunker/id/101913247/
  - https://whosonfirst.mapzen.com/spelunker/id/101913233/
  - https://whosonfirst.mapzen.com/spelunker/id/101913239/

Suggest deprecating all, aside from 101751573, then finding new data for the surrounding area. The existing geometries surrounding 101751573 are not Brussels - they are a mix of bad geometries and geometries that need to be split apart.

Related:

- Wellington:

  - See: https://github.com/whosonfirst-data/whosonfirst-data/issues/118

- Bratislava:

  - See: https://github.com/whosonfirst-data/whosonfirst-data/issues/575

**Comment by nvkelso** [comment]
I'm fine with this approach. It's expedient and we can refine later.

**Comment by stepps00** [comment]
New Athens record: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/117/561/273/1/1175612731.geojson

Jerusalem and Brussels still need some work, but this should be much simpler since #57 was recently merged.

**Comment by stepps00** [comment]
Jerusalem (and nearby records) were taken care of as part of #1476.

**Comment by stepps00** [comment]
The cases outlined in this issue are complete. If there are additional cases, let's open a new issue to track.
