### ISSUE TITLE
Indicate what the locals call their placetype

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#712]
When is a feature of X placetype really something else?

For instance, when is a `county` really a:

- county
- parish
- borough
- census district & etc

We're going to get a lot of this info from Statoids, and we have some of it now buried in QS properties from Statoids (for the USA).

**Comment by stepps00** [comment]
[This script](https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/census_type_check.py) creates a new `wof:placetype_local` property using the last word in the `qs:loc_alt` property. 

The key value lookup (`census_type_lookup`) needs to be updated to include all possible placetypes the US Census uses, but other than that, the script works given a list of `wof:id` values in a CSV.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/217

**Comment by stepps00** [comment]
This property has been added to ~3k records in the United States, via https://github.com/whosonfirst-data/whosonfirst-data/pull/759.

**Comment by nvkelso** [comment]
🎉, closing.

(The separate Statoids import will add more, later.)
