### ISSUE TITLE
WOF id 1108692869 missing from county bundle

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#719]
wof-county-latest.csv contains WOF id 1108692869 that has datapath `110/869/286/9/1108692869.geojson` but this file is missing from the county bundle.

**Comment by nvkelso** [comment]
I suspect the following 5 features are recent **neighbourhood** updates that point to a new record that has a bad `wof:id`:

- data/858/461/69/85846169.geojson
- data/858/511/47/85851147.geojson
- data/858/659/71/85865971.geojson
- data/858/668/53/85866853.geojson
- data/858/874/21/85887421.geojson

I found them while importing Nat's neighbourhood curation.

**Comment by stepps00** [comment]
@trescube - this issue should be resolved now that #723 was merged. Is this still an issue for Pelias?

**Comment by trescube** [comment]
That fixed it, thanks!
