### ISSUE TITLE
Import Nat's 20170404 neighbourhood delivery

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#725]
Includes all metro_tier 15 and 30 places. Will be a mix of updating existing records and creating new records.

- ~5k modified label centroids
    - _background: ~12k were modified in round 1, already imported_
- ~7k new neighbourhood features
    - _background: ~2k were added in round 1, already imported_

This will need a new script added to the toolbox repo.

**Modified:** `brown` tier 15 (mostly in US), `blue` tier 30 (mostly in Europe), `grey` was modified before in tier 1 (some more in this round as general property cleanup).

<img width="981" alt="screen shot 2017-04-05 at 14 32 53" src="https://cloud.githubusercontent.com/assets/853051/24728145/9b4d922e-1a0d-11e7-942a-a2b75e92db71.png">

**New:** `#ff0000` is added now, `#0000ff` was added before in tier 1.

<img width="979" alt="screen shot 2017-04-05 at 14 36 14" src="https://cloud.githubusercontent.com/assets/853051/24728144/9b3947ec-1a0d-11e7-9b3f-58c1664bbdb0.png">

**Comment by nvkelso** [comment]
Links up with #722, #724, #720.

**Comment by stepps00** [comment]
@nvkelso - are we OK to close this issue? All PRs linked above have been merged.

**Comment by nvkelso** [comment]
Yep, thanks for the reminder!
