### ISSUE TITLE
OH NOES!!! Finland!

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#727]
This record for Finland seemed to be broken: https://whosonfirst.mapzen.com/spelunker/id/136253047

**Comment by thisisaaronland** [comment]
Well, sort of. The Finland you are looking for is here:

https://whosonfirst.mapzen.com/spelunker/id/85633143/

The bug is that the Finland you were looking at lacks `deprecated` and `superseded_by` data. I am just cleaning up some other Git nonsense and then will update the record in question.

**Comment by thisisaaronland** [comment]
Related, the errant record in question has been that way since 2016:

https://github.com/whosonfirst-data/whosonfirst-data/commits/master/data/136/253/047/136253047.geojson

**Comment by thisisaaronland** [comment]
Oh wait. This is not a bug at all. This is not a country record. It's an empire record.

https://whosonfirst.mapzen.com/placetypes/
https://github.com/whosonfirst/whosonfirst-placetypes/blob/master/placetypes/country.json
https://github.com/whosonfirst/whosonfirst-placetypes/blob/master/placetypes/empire.json

**Comment by missinglink** [comment]
:+1: cool thanks.

is there a list of tags somewhere that I might want to target for exclusion for a geocoder?

**Comment by stepps00** [comment]
The Finland record in question in an `empire` record, separate from the `country` record of Finland, and is a valid record (taken care of previously in [this commit](https://github.com/whosonfirst-data/whosonfirst-data/pull/330)). 

I don't think the Finland record requires a `superseded_by` or `deprecated` date, but the `empire` records do need geometries, though ([tracked here](https://github.com/whosonfirst-data/whosonfirst-data/issues/335)).... unless I am missing something...

**Comment by thisisaaronland** [comment]
I don't believe there is not a fixed list yet. Off the top of my head, probably something like:

* Things on Null Island.
* Things that have a non-empty (or non "uuuu") `edtf:deprecated` date.
* Things that have a non-empty `wof:superseded_by` array
* Things that are flagged `mz:is_current=0`

If Pelias needs additional properties to the `mz:` namespace.

**Comment by nvkelso** [comment]
I would ignore empire (but I thought you do already).

**Comment by missinglink** [comment]
yep, we ignore `empire` in Pelias, I am inquiring for our new parsing lib which is based off WOF data

**Comment by missinglink** [comment]
so basically this?

```
  // skip deprecated records
  var deprecated = _.trim( wof.properties['edtf:deprecated'] );
  if( !_.isEmpty( deprecated ) && deprecated !== 'uuuu' ){
    return;
  }
```

what does 'uuuu' refer to?

**Comment by thisisaaronland** [comment]
@missinglink - Yeah, that seems correct. I saw rumblings on the EDTF mailing lists that at some point `uuuu` will become `XXXX` (because...) but that hasn't happened yet.

**Comment by missinglink** [comment]
:+1: awesome much thanks!
