### ISSUE TITLE
missing document 1108498856

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#728]
the following document references a macrocountry `1108498856` which doesn't exist:

https://whosonfirst.mapzen.com/spelunker/id/85925281

```
macrocounty_id: 1108498856
```

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/pull/550

**Comment by thisisaaronland** [comment]
Okay, I can try to take a look at this later today.
