### ISSUE TITLE
Clean up hierarchy and controlled properties for Sydney, AUS

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#731]
In preparation for upcoming Sydney neighbourhood work (tracked in issue https://github.com/whosonfirst-data/whosonfirst-data/issues/416), clean up the parent record (and surrounding records of that placetype) and `wof:hierarchy` of [Sydney, Australia](https://whosonfirst.mapzen.com/spelunker/id/101932003/#12/-33.8673/151.2100). 

Data is available through Australia's PSMA (import of this data tracked in issue https://github.com/whosonfirst-data/whosonfirst-data/issues/218). File a PR before neighbourhood work begins.  

```
    "wof:hierarchy":[
        {
            "continent_id":102191583,
            "country_id":85632793,
            "county_id":102049151,
            "localadmin_id":404226357,
            "locality_id":101932003,
            "region_id":85681545
        }
```

**Comment by nvkelso** [comment]
Let’s constrain this to only hierarchy and controlled properties, further
geom work can happy as part of #218 and #416.

**Comment by stepps00** [comment]
Work for just the Sydney record was updated per #1243. 

Closing and picking up where we left off with #218 and #416.
