### ISSUE TITLE
Australian county names end with ' (A)'

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#737]
hey, is there a reason that all the Australian counties have ' (A)' added on the end?

https://whosonfirst.mapzen.com/spelunker/id/85632793/descendants/?exclude=nullisland&placetype=county#5/-32.736/151.103

eg: `North Sydney (A)`

would it be possible to programmatically remove them from the name if they aren't significant?

**Comment by nvkelso** [comment]
Yes, good suggestion :)

**Comment by stepps00** [comment]
I'm expecting to start updating multiple placetypes in Australia, this can easily be done when I import/upgrade features at the county level in Australia. 

**Related:** https://github.com/whosonfirst-data/whosonfirst-data/issues/218

**Comment by stepps00** [comment]
Related: #904
