### ISSUE TITLE
Invalid json for New Orleans microhood

### ISSUE THREAD

**Issue by rmarianski** [whosonfirst-data/whosonfirst-data#741]
The contents of wof id `1108741363` are invalid json.

https://whosonfirst.mapzen.com/data/110/874/136/3/1108741363.geojson
https://whosonfirst.mapzen.com/spelunker/id/1108741363/

**Comment by nvkelso** [comment]
Looks like a bad merge here:

- https://github.com/whosonfirst-data/whosonfirst-data/blob/fd1b53bb9fad5c218030c30fffd8e4bcce9b5ca5/data/110/874/136/3/1108741363.geojson?short_path=b16aaf1

Compared with a clean state in:

- https://github.com/whosonfirst-data/whosonfirst-data/blob/da24689102296fe1366f873d3bca4bd9c218d2ad/data/110/874/136/3/1108741363.geojson?short_path=e063f1c

**Comment by nvkelso** [comment]
New Orleans microhood.

**Comment by nvkelso** [comment]
@thisisaaronland Can you check to see if the update made it to S3, please? (We're seeing it only updated in the Spelunker, and the older S3 file is still causing Tiles pagerduty alerts.)

**Comment by thisisaaronland** [comment]
Fixed.

**Comment by nvkelso** [comment]
Verified, thank you!
