### ISSUE TITLE
SoHo was renamed Soho in a recent change

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#744]
https://github.com/whosonfirst-data/whosonfirst-data/commit/320caff3b2d75935701f4e4313046416ac68dec2 appears to have changed the `wof:name` attribute of [SoHo](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/858/656/87/85865687.geojson) back to Soho

**Comment by stepps00** [comment]
Yikes - thanks for the issue, @orangejulius.. filing a PR to fix shortly.

**Comment by nvkelso** [comment]
That's my fault, I've filed a toolbox issue noted by Github above to prevent (most) future regressions.
