### ISSUE TITLE
Clean up dependency hierarchies

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#750]
Many dependency records have countries in their `wof:hierarchy`. This is causing countries to display _interesting_ descendant records. Examples:

- There are [83 region records](https://whosonfirst.mapzen.com/spelunker/id/85633793/descendants/?exclude=nullisland&placetype=region#2/39.2/-169.5) parented by the United States because dependencies like Guam and Samoa have region descendants
- There are [121 region records](https://whosonfirst.mapzen.com/spelunker/id/85633147/descendants/?exclude=nullisland&placetype=region#2/21.0/-178.1) parented by France because dependencies like Mayotte and Polynesia have region descendants

Hierarchies of a dependency record should only include the dependency (itself), its empire, and its continent. Dependency descendant records should inherit the same values (and not include countries).

This may also cause us to rework some of the country geometries. The geometry of [France](https://whosonfirst.mapzen.com/spelunker/id/85633147/#2/18.8/-3.0) ([related PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/365)) includes some overseas dependencies, the [United States](https://whosonfirst.mapzen.com/spelunker/id/85633793/#1/65/0) does not.

**Comment by binshe** [comment]
**Thank you** @stepps00 for investigating this issue.
**Thanks** @nvkelso for pointing out the relation to #789 and pelias/pelias#571.

I was trying to sort out why the queries in `New Caledonia`, a `dependency` of `France`, and `French Polynesia`, another `dependency` of `France`, did not return results properly sorted in the order "`street`, `locality `, `region`" or "`street`, `locality `, `dependency`".

Instead, the results are either limited to
A) "`street`, `country`" , or to
B) "`locality`, `country`"
which is of course of poor value.

A) For instance, no `locality`, `region` nor `dependency` appear in the result of the query:
- http://pelias.github.io/compare/#/v1/search%3Ftext=rue%20lamartine,%20Sud

It simply returns the not-so-precise result:
> "Rue Lamartine, France"

First result of query :
![rue lamartine_france](https://user-images.githubusercontent.com/28983379/26953365-26d95020-4caa-11e7-9890-3882e9e38288.png)

B) Broadly speaking, the Pelias queries "`street`, `Nouméa`" such as

- http://pelias.github.io/compare/#/v1/search%3Ftext=rue%20lamartine%20noumea

Just return "`locality`, `country`" (B.1 below), or "`locality`, `dependency`" (B.2 below).

B.1 - First result of query :
![noumea_france](https://user-images.githubusercontent.com/28983379/26953381-424b5e5c-4caa-11e7-9846-111a53e14c3d.png)

B.2 - Second result of query :
![noumea_new caledonia](https://user-images.githubusercontent.com/28983379/26953388-4a9e87f0-4caa-11e7-8c1d-77d200c274e5.png)

How can we solve this? How can I help?

Many thanks.
**Apologies if I am not very clear. This is my first set of contributions, I am trying to improve the results for my home region :)**

**Comment by nvkelso** [comment]
@binshe Glad to help, and thanks for the further commits to clarify :)

Note that Pelias search doesn't have separate `country` and `dependency` properties – they synthesize just `country` but source from whatever is appropriate. So @stepps00's changes in the related PR https://github.com/whosonfirst-data/whosonfirst-data/issues/763 should fix that part of the problem.

I've asked in the other issue about locality (city) polygons, that's the other missing piece here.
