### ISSUE TITLE
Many European venues are appearing in Seoul, South Korea

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#753]
I was looking for interesting international test cases by browsing the descendants of [Seoul, South Korea](https://whosonfirst.mapzen.com/spelunker/id/102026327/) when I was greeted with many many [european looking venues](https://whosonfirst.mapzen.com/spelunker/id/102026327/descendants/?exclude=nullisland#11/37.5442/126.9709)
![screenshot from 2017-04-24 16-04-09](https://cloud.githubusercontent.com/assets/111716/25356299/ad56f006-2907-11e7-9fe0-fc5b79c5fdb5.png)

They all appear to have Korean lat/lons and hierarchies, but European country codes and names.

**Comment by thisisaaronland** [comment]
The bad news is that this a known-known and just hasn't gotten the love it needs: Specifically, validating the ISO country that SimpleGeo assigned against a simple WOF-backed PIP query. It's on the list.

I was going to say the good news is: More venues in Korea but looking at that list it just looks like bunk data...

**Comment by nvkelso** [comment]
Yep, dup of https://github.com/whosonfirst-data/whosonfirst-data/issues/366.

**Comment by orangejulius** [comment]
No worries, I figured you knew. Good news is on closer inspection "many many" is only 23.

**Comment by nvkelso** [comment]
Please keep filing bugs! It's easy for us todup to an existing bug that may be hard to find bug :)

Good to hear on low number – we've generally seen it in less than 1% of cases.
