### ISSUE TITLE
Investigate locality borders in Săcele and Braşov in Romania

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#758]
This came in through support (see desk 329):

"in this request:
https://search.mapzen.com/v1/place?ids=openstreetmap%3Aaddress%3Away%3A271108860
the locality in the mapzen response is "Sacele"

the locality should be "Brasov", not Sacele; Sacele is a city a couple of
kilometers from that point. we checked the openstreetmaps datasource for
the way id 271108860 (from your response) and there the locality / city is
Brasov (so it's the correct value), you can see it in the query response:
http://www.openstreetmap.org/way/271108860#map=18/45.63629/25.60939&layers=N"

---

From Rhonda: here is the spelunker location for Săcele and Braşov overlapping localities: https://whosonfirst.mapzen.com/spelunker/id/101751991/#12/45.6443/25.6052
https://whosonfirst.mapzen.com/spelunker/id/101790893/#11/45.6571/25.6429

The response from the reverse search:

"properties": {
"id": "way:271108860",
"gid": "openstreetmap:address:way:271108860",
"layer": "address",
"source": "openstreetmap",
"source_id": "way:271108860",
"name": "10 Bulevardul Valea Cetății",
"housenumber": "10",
"street": "Bulevardul Valea Cetății",
"postalcode": "500289",
"accuracy": "point",
"country": "Romania",
"country_gid": "whosonfirst:country:85633745",
"country_a": "ROU",
"region": "Braşov",
"region_gid": "whosonfirst:region:85687683",
"locality": "Săcele",
"locality_gid": "whosonfirst:locality:101790893",
"neighbourhood": "Astra",
"neighbourhood_gid": "whosonfirst:neighbourhood:85901659",
"label": "10 Bulevardul Valea Cetății, Săcele, Romania"
}

**Comment by stepps00** [comment]
thanks @rmglennon - will take a look and let you know if I have any additional questions.
