### ISSUE TITLE
Chinese neighborhoods need CN iso code, not CH

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#77]
Looks like something is wrong in the Quattroshapes source and all the Chinese neighborhoods are getting ISO codes of CH instead of the correct CN. 

For instance:

Jing An Si (wof_id:85907501) in Shanghai 

Which lists:

```
 u'iso:country': u'CH',
 u'lbl:latitude': 31.221022,
 u'lbl:longitude': 121.437692,
 u'misc:gn_adm0_cc': u'CN',
```

And correctly lists the WOF country as China:

```
u'wof:hierarchy': [{u'country_id': u'85632695',
                     u'locality_id': u'102027181',
                     u'neighbourhood_id': u'85907501',
                     u'region_id': u'85669831'}],
```

**Comment by stepps00** [comment]
A bulk .geojson file is in the **S3 Dropbox's misc folder** that contains updated neighbourhood records for all of China: [link](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%2077/Issue77_ChinaNeightbourhoods_Import.geojson).

* Updated `wof:county` field. All values are now **CN**
* Updated `iso:county` field. All values are now **CN**
* Changed `wof:lastmodified` field, all values reflect a recent timestamp

This is a decent test case for the Boundary Issues tool; we're testing the upload process this week.

**Comment by nvkelso** [comment]
👍 These look good to me.  

I saw 161 neighbourhoods in the Spelunker belonging to China. 2 of those are marked as in India, and in China. That = 159 records which matches your GeoJSON collection count. 

Also in this issue, please kill the extra China hierarchy on those 2 Indian records:

- https://whosonfirst.mapzen.com/spelunker/id/85632695/descendants/?placetype=neighbourhood&iso=in#5/16.098/92.710

**Comment by stepps00** [comment]
The geojson file was imported to Who's On First through the Boundary Issues tool, see commit https://github.com/whosonfirst-data/whosonfirst-data/commit/68300dda3f75531dca1937b5fe232eee83d36ab6.

Once the changes are seen in master, I will close this issue.

**Comment by stepps00** [comment]
This update now appears in `master`. Closing this issue.

Link to updated records: [Link](https://whosonfirst.mapzen.com/spelunker/id/85632695/descendants/?placetype=neighbourhood&exclude=nullisland&iso=cn#4/31.93/121.44)
Link to commit: https://github.com/whosonfirst-data/whosonfirst-data/commit/68300dda3f75531dca1937b5fe232eee83d36ab6
