### ISSUE TITLE
Duplicate Crocker Highland neighbourhood records in Oakland/Piedmont

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#771]
Who's On First currently has two records for the same neighbbourhood, Crocker Highlands in Oakland. One records falls within Oakland (correct), while the other falls within the adjacent locality of Piedmont (incorrect). The following clean-up is needed:

- Add an `edtf:cessation` date, `mz:is_current`, and `wof:superseded_by` value to the Piedmont record
- Add a `wof:supersedes` value to the Oakland record
- Update the Oakland record's `lbl:latitude` and `lbl:longitude` values to reflect the values in the Piedmont record

**Duplicate records:**
https://whosonfirst.mapzen.com/spelunker/id/1108794107/#15/37.8119/-122.2297
https://whosonfirst.mapzen.com/spelunker/id/85872275/#13/37.8216/-122.2284

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/776
