### ISSUE TITLE
Ensure all records that have a cessation/deprecated date have an is_current prop = 0

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#774]
Make sure that all records in Who's On First that have a `edtf:cessation` or `edtf:deprecated` data set _also_ have a `mz:is_current` property set to `0`.

An example of this issue can be seen in a superseded "Netherlands" [country record](https://whosonfirst.mapzen.com/spelunker/id/85632727/#6/14.870/-65.687). This record actually represented the "Caribbean Netherlands" dependency, so it was correctly superseded into a new Caribbean Netherlands dependency record... but neither the `edtf` date or `mz:is_current` value were set.

**Comment by nvkelso** [comment]
Good find. Looks like you could set the cessation date to the file's `wof:lastmodified` (converting formats), or just the date you run the script.
