### ISSUE TITLE
Upgrade neighbourhood shapes for Ottawa

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#779]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Include the locality of [Gatineau](https://whosonfirst.mapzen.com/spelunker/id/101738041/#10/45.4863/-75.6264).

**Comment by stepps00** [comment]
Potential source, awaiting confirmation on the license type/accessibility: [http://neighbourhoodstudy.ca/](http://neighbourhoodstudy.ca/)

**Comment by stepps00** [comment]
Gatineau: Potential source, awaiting confirmation on the license type/accessibility: [http://www3.ville.gatineau.qc.ca/Infoterritoire/WebInterface/views/index.aspx](http://www3.ville.gatineau.qc.ca/Infoterritoire/WebInterface/views/index.aspx)

**Comment by stepps00** [comment]
Ottawa and Gatineau neighbourhood (and associated) records are updated. Files are in the `misc/Issue 779` folder on S3.

For post-merge clean-up: [gatineau_hierarchies.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1078510/gatineau_hierarchies.txt) and [ottawa_hierarchies.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1078511/ottawa_hierarchies.txt).

**Comment by nvkelso** [comment]
SEO: Canada

**Comment by thisisaaronland** [comment]
Ottawa data has `z` coordinates in geometry data which makes PostGIS cry like a baby (also we don't have `z` coordinates in WOF data at this time.

(Gatineau is fine.)

```
INFO:root:writing /usr/local/data/whosonfirst-data/data/112/585/399/3/1125853993.geojson
INFO:root:/usr/local/bin/wof-pgis-index -pgis-database whosonfirst -pgis-host localhost -pgis-user whosonfirst -mode files /usr/local/data/whosonfirst-data/data/112/585/399/3/112585399\
3.geojson
2017/07/05 19:38:29 pq: Geometry has Z dimension but column does not
2017/07/05 19:38:29 INSERT INTO whosonfirst (id, parent_id, placetype_id, is_superseded, is_deprecated, meta, geom_hash, lastmod, geom, centroid) VALUES ($1, $2, $3, $4, $5, $6, $7, $8\
, ST_GeomFromGeoJSON('{"coordinates":[[[[-75.91347800030945,45.39921399992619,0]
```

**Comment by stepps00** [comment]
Yikes! `z` values strike again. 

New Ottawa data is now in the S3 (`misc/Issue 779` folder with today's date in the filename).

**Comment by stepps00** [comment]
Closing issue, files have been imported.
