### ISSUE TITLE
Upgrade neighbourhood shapes for Quebec City

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#780]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Include the locality of [Lévis](https://whosonfirst.mapzen.com/spelunker/id/101737987/#10/46.7080/-71.2573).

**Comment by nvkelso** [comment]
SEO: Canada

**Comment by stepps00** [comment]
Records have been updated and reviewed. GeoJSON files are now in the S3 `misc/Issue 780` folder.

**Comment by thisisaaronland** [comment]
Quebec City has `z` coordinates in its geometries which makes PostGIS cry like a baby.

**Comment by stepps00** [comment]
Closing issue, files have been imported.

**Comment by stepps00** [comment]
Looks like Quebec City/Levis still has work to be done..

**Comment by stepps00** [comment]
Quebec neighbourhoods have been imported, per https://whosonfirst.mapzen.com/boundaryissues/pipeline/436

**Comment by stepps00** [comment]
Levis: https://whosonfirst.mapzen.com/boundaryissues/pipeline/438
