### ISSUE TITLE
Upgrade neighbourhood shapes for Winnipeg

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#783]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
**Source used for Winnipeg:** https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/can-wpgppd.json

**Aliases used in Winnipeg:** https://github.com/whosonfirst/whosonfirst-properties/commit/51797f3a856c5920403eb9bb3af2593f4eba9c40

**Comment by stepps00** [comment]
Winnipeg neighbourhood (and associated) records are updated. Files are in the `misc/Issue 783` folder on S3.

Over to @thisisaaronland

**Comment by stepps00** [comment]
For post-merge clean-up: [winnipeg_hierarchies_templates.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1029755/winnipeg_hierarchies_templates.txt)

**Comment by nvkelso** [comment]
SEO: Canada
