### ISSUE TITLE
Upgrade neighbourhood shapes for Regina, SK

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#784]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Sources: https://github.com/whosonfirst/whosonfirst-sources/pull/77

**Comment by stepps00** [comment]
Records have been reviewed and placed in the S3 'misc/Issue 784` folder.

**Comment by nvkelso** [comment]
SEO: Canada

**Comment by stepps00** [comment]
Closing issue, files have been imported.
