### ISSUE TITLE
Upgrade neighbourhood shapes for Edmonton, AB

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#785]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by stepps00** [comment]
Include localities of [Sherwood Park](https://whosonfirst.mapzen.com/spelunker/id/890456619/#4/54.87/-115.00) and [St Albert](https://whosonfirst.mapzen.com/spelunker/id/890458621/#4/54.87/-115.00).

**Comment by stepps00** [comment]
Updated records for Edmonton, Sherwood Park, and St Albert are in the `misc/Issue 785` folder on S3.

Assigning to myself as a pipeline import task.

**Comment by stepps00** [comment]
For post-merge clean-up: [Edmonton_Hierarchies.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1053144/Edmonton_Hierarchies.txt)

**Comment by nvkelso** [comment]
SEO: Canada

**Comment by stepps00** [comment]
This issue was completed through commits linked above. Closing.
