### ISSUE TITLE
floats encoded as strings

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#787]
heya, I noticed that sometimes floats are encoded as strings, such as in this example (from the same file):

```javascript
"geom:latitude": -41.072228,
"geom:longitude": 145.907314,
"lbl:latitude": "-41.0690002441",
"lbl:longitude": "145.895690918",
```

while it's not a huge deal, it means that downstream code has to check the type and cast the string values to floats, it's also a bit of a gotcha when getting started using the data.

would it be possible to tweak the JSON serialization library used by WOF to automatically convert all numeric fields to numeric encoding?

thanks!

**Comment by thisisaaronland** [comment]
@stepps00 - this is a good one for the test suite.

@missinglink - I can look at ensuring lat/lon fields are floats, going forward. Blanket converting things to numbers in Python (which is the current default for exporting records because reasons) results in hilarity like scientific notation...

**Comment by missinglink** [comment]
:1e+1:

**Comment by stepps00** [comment]
Good catch, thanks for the issue @missinglink.. I have these properties down as floats in a [property_type.json](https://github.com/whosonfirst/whosonfirst-tests/blob/master/property_types.json#L11-L12) file i've been working on, I'll make sure to test that these are floats going forward.

As for features with string `lbl` properties, here's [a list](https://github.com/whosonfirst-data/whosonfirst-data/files/993728/string_lbl.txt) of affected ids. I'll proposed a PR with property updates shortly.

**Comment by stepps00** [comment]
@missinglink - this issues should be fixed now, let me know if you come across this issue again.

**Comment by missinglink** [comment]
wow amazing, super fast turnaround, thanks @stepps00
