### ISSUE TITLE
HOW MUCH MEGACITY?

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#790]
Heya,

I would like to use the `wof:megacity` flag to identify 'big name geocoding targets' :)

After clicking around a bit it seems like the property might not be rolled out across the whole repo?

ie.

`Los Angeles` (85923517, population ~4M) is considered a megacity *but*
`London` (101750367, population ~8M) is not?

what's the intended behavior of the megacity flag? is it simply cities over a certain population or is there more to it than that?

oh PS. @stepps00 that property is also a string when it could be encoded as a bool or an int:

```javascript
"wof:megacity": "1",
```

thanks!

**Comment by missinglink** [comment]
a map is worth a thousand words!
![ss](https://cloud.githubusercontent.com/assets/738069/26062481/3591eaa0-398b-11e7-84a3-f2519aeee2b7.png)

by the look of this, there are none in Europe, which makes sense if it's about building heights?

**Comment by missinglink** [comment]
I found Leeds, Manchester and Liverpool in there, along with Glasgow and Dublin.

Maybe it's just an issue with London?

**Comment by stepps00** [comment]
Hey @missinglink, I've got an open issue for cleaning up the `wof:megacity` tag here: #701.

I'm going to close this as a duplicate issue, but copy your comment to the other issue. This is more than an issue in just London and with locality records; currently, the tag is used across a few placetypes and on records that aren't actually "megacities". 

If you come across any other irregularities with that tag, feel free to mention them in #701.

**Comment by nvkelso** [comment]
By the time population and population_tier are added (and mz:min_zoom)
that’ll be a more reliable measure.
