### ISSUE TITLE
Consider updating wof:concordance to handle multiple valid concordances per source

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#796]
In a recent PR to clean up locality features in Guam ([here](https://github.com/whosonfirst-data/whosonfirst-data/pull/710)), we noticed that some locality records have multiple concordance values per concordance source.

For example, Hagatna, Guam has two equally valid concordances (some values are identical, some are unique):

```
    "wof:concordances":{
        "gn:id":"7874008",
        "gp:id":"15021088",
        "qs:id":"743596",
        "wd:id":"Q30988",
        "wk:page":"Hag\u00e5t\u00f1a, Guam"
    },
```

and 

```
    "wof:concordances":{
        "fct:id":"11558486-8f76-11e1-848f-cfd5bf3ef515",
        "fips:code":"6634750",
        "gn:id":4044012,
        "gp:id":28718593,
        "qs:id":499184,
        "wd:id":"Q30988",
        "wk:page":"Hag\u00e5t\u00f1a, Guam"
    },
```

This is due to Hagatna, Guam being classified both as "Hagatna" and "Hagatna Village", though there is only one Hagatna locality in Guam. This issue has popped up before, though we only retained a single concordance value per concordance, which is probably the wrong thing to do in most cases.

We need a method to retain more than a single valid value per concordance. That may or may not require changing property types..

**Comment by stepps00** [comment]
I think we're okay to close this, see: https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/concordances_alt.json

tagging @nvkelso to confirm

**Comment by nvkelso** [comment]
Yes, close as process changed
