### ISSUE TITLE
Ensure megacities have population and population_rank

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#797]
Related to https://github.com/whosonfirst-data/whosonfirst-data/issues/240, let's ensure the several hundred megacities have `wof:population` (for the smaller incorporated locality, not the large megacity/metropolitan area pop), and a `wof:population_rank`.

**Comment by nvkelso** [comment]
Eg: https://whosonfirst.mapzen.com/spelunker/megacities/#2/25.0/103.8

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/701

**Comment by stepps00** [comment]
The majority of this work has been completed through recent population work. 

To do: 

- Clean up neighbourhoods tagged as megacities (eight of them): https://whosonfirst.mapzen.com/spelunker/megacities/?&placetype=neighbourhood
- Review all megacity records on this page, as several are missing population data. There is also a case of Prague, USA being tagged as a megacity: https://whosonfirst.mapzen.com/spelunker/megacities/?&page=8

**Comment by stepps00** [comment]
I'm going to close this issue, as most of the work is complete and https://github.com/whosonfirst-data/whosonfirst-data/issues/701 is still open.

I'll take care of any additional population/population_rank work through #701.
