### ISSUE TITLE
Add new Italian region of South Sardinia

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#798]
The Italian Provincia del Sud Sardegna took effect 4 February 2016:

- https://en.wikipedia.org/wiki/Province_of_South_Sardinia

`Once operating, it will include the suppressed provinces of Carbonia-Iglesias and Medio Campidano, great part of the old Province of Cagliari (without the 17 municipalities of the new Metropolitan City), and two other municipalities.`

**Comment by stepps00** [comment]
This work was completed in https://github.com/whosonfirst-data/whosonfirst-data/pull/1415, closing.
