### ISSUE TITLE
id 1108721803: 'Southwest Philadelphia' is misspelled

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#801]
[id 1108721803](https://whosonfirst.mapzen.com/spelunker/id/1108721803) has the name spelled wrong.  

is: Southwest Philaldephia 
should be: Southwest Philadelphia

**Comment by nvkelso** [comment]
Good candidate for quick fix in Boundary Issues?

**Comment by stepps00** [comment]
Unable to edit this feature in Boundary Issues right now - Boundary Issues is pulling from an older set of WOF data that does not include newer features (like this `macrohood` with a `wof:id` beginning in "110"). 

Probably related: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/254

PR: https://github.com/whosonfirst-data/whosonfirst-data/pull/802/files
