### ISSUE TITLE
Create WOF records from venues on The List

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#805]
[The List](http://www.calweb.net/~skoepke/) (aka the (San Francisco) Bay Area concert guide) has music venue data for ~140 music venues in the Bay Area. According to the organizers, the venue information is open to the public and there are no license restrictions.

Once formatted, this could be a good test run for the CSV import tool in Boundary Issues.

**Comment by thisisaaronland** [comment]
Agreed. Do we know anyone there? As in, do we know anyone to invite to work on/in BI.

cc @dphiffer

**Comment by stepps00** [comment]
I've been in contact with someone who updates the listings to collect the venue data and verify licensing. Once I get a response, I'll ask if they would like to contribute via BI.

**Comment by dphiffer** [comment]
That's great. You'll want a CSV where there's a full address column or lat/long stored in separate columns. I'd say it makes more sense for you to try importing it rather than set them up with their own accounts, but we could also go that route if we want to get more adventurous.

**Comment by stepps00** [comment]
Confirmed that there is no license restrictions on this data. I've standardized the data they provided into a csv file ([txt format](https://github.com/whosonfirst-data/whosonfirst-data/files/1039751/music_venues_the_list.copy.txt)) and will import via Boundary Issues' csv tool shortly..

**Comment by stepps00** [comment]
This venue data was imported through Boundary Issues' CSV import tool.

**Commits:**

- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/7510f2534faf0fc133bbc9f7dbaa6700865103e8
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/a81f0cfd86cef0868b7a0eb84a414a2404c3bb17
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/94336e83b000e1cff7fea5000b27d2fdf9f39451
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/608e30265a537dc2667f44988219af0d8a3a066c
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/03c85eafa5fe32c347c8d8ca5d322ad2edd0c5a1
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/9274e408ba53fe756382b3e366097387f9c3baff
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/6ff8774281c93b0cbb8591679809716d2443bf8a
- https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/88bcad7ef2951ecbf222617c545f6ea84b3a65d4

**Related/follow-up issues:**

- https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/97
- https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/247

Since all data has been imported, closing issue.
