### ISSUE TITLE
Add alternate names from Geonames.org

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#806]
Geonames.org has many alternate names, and we have concordance with their place IDs.

We'll probably need to do a round of this for the places we already have in WOF, and then another one after https://github.com/whosonfirst-data/whosonfirst-data/issues/108 is done.

- http://download.geonames.org/export/dump/alternateNames.zip
- Source page: http://download.geonames.org/export/dump/

Note that `isolanguage` has a few surprises in it like airport codes that aren't actual language codes that will need special handling.

```
The table 'alternate names' :
-----------------------------
alternateNameId   : the id of this alternate name, int
geonameid         : geonameId referring to id in table 'geoname', int
isolanguage       : iso 639 language code 2- or 3-characters; 4-characters 'post' for postal codes and 'iata','icao' and faac for airport codes, fr_1793 for French Revolution names,  abbr for abbreviation, link for a website, varchar(7)
alternate name    : alternate name or name variant, varchar(400)
isPreferredName   : '1', if this alternate name is an official/preferred name
isShortName       : '1', if this is a short name like 'California' for 'State of California'
isColloquial      : '1', if this alternate name is a colloquial or slang term
isHistoric        : '1', if this alternate name is historic and was used in the past

Remark : the field 'alternatenames' in the table 'geoname' is a short version of the
'alternatenames' table without links and postal codes but with ascii transliterations. 
You probably don't need both. If you don't need to know the language of a name 
variant, the field 'alternatenames' will be sufficient. If you need to know the language
of a name variant, then you will need to load the table 'alternatenames' and you can
drop the column in the geoname table.
```

**Comment by nvkelso** [comment]
We keep track of concordances in the following metafile:

- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/meta/wof-concordances-latest.csv

It has **~346k** features with a concordance, the majority of which (**~214k**) have a `gn:id` concordance.

For each of those, extract out alt names from Geonames.org alt file as described above.

**Comment by nvkelso** [comment]
This month @stepps00 added the name variants for places already in WOF that already had a GN concordance. Leaving this issue open as we should run again for places that _need_ a GN concordance, and because we're going to be importing a lot more of these soon.

**Comment by nvkelso** [comment]
I think this can be closed, as we've run this a few times now.

But first @stepps00 needs to document how to run it again – like where the script lives and how to run it.

**Comment by stepps00** [comment]
I've opened https://github.com/whosonfirst/whosonfirst-cookbook/pull/16 with a document on how to re-run the GeoNames import script. Closing this issue.
