### ISSUE TITLE
Ensure all Natural Earth populated places are in WOF

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#807]
This will ensure we have all major cities, and give us values like `ne:scalerank` which we can turn into `mz:min_zoom`, and population values to feed into `wof:population`.

**Comment by nvkelso** [comment]
An output should also include a "debug" file that includes the `wof:id` for each Natural Earth place to push upstream into that separate project.

**Comment by nvkelso** [comment]
I think this is done? @stepps00 to confirm.

**Comment by stepps00** [comment]
Examples of "populated place" records with NE properties:
- https://whosonfirst.mapzen.com/spelunker/id/85936429/
- https://whosonfirst.mapzen.com/spelunker/id/890442179/

Commits that imported NE "populated places" properties: 
- https://github.com/whosonfirst-data/whosonfirst-data/pull/867
