### ISSUE TITLE
Incorrect wk concordance properties for ~300 records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#810]
Roughly 300 records in Who's On First have incorrect `wk` properties. These records were given property values for another record with an identical name; an example is [San Antonio, Phillipines](https://whosonfirst.mapzen.com/spelunker/id/421172067/#8/15.305/120.164), which has `wk` properties for San Antonio, Texas.

A few of these affected records, with names of "Brooklyn," were updated in commit https://github.com/whosonfirst-data/whosonfirst-data/commit/6bfffd571460e38db3a0c37feeb69fff5d62729b.

Other affected records are listed in this file: [mismatchedcountries.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1045564/mismatchedcountries.txt)

Likely fix is to remove `wk` properties from these features.

**Comment by stepps00** [comment]
Shoutout to @trescube for finding these inconsistencies.

**Comment by trescube** [comment]
In a number of cases, the `wof:population` field was populated from `wk:population`.  Will `wof:population` automatically be updated to reflect this fields going away?

**Comment by stepps00** [comment]
If there is a `src:population` property equal to `wk`, I'll make sure to scrub the following properties:

- `src:population`
- `wof:population`
- `wof:population_rank`

**Comment by nvkelso** [comment]
If there’s other population values (say from geonames) on the record
already let’s re-source them instead of a total scrub.

**Comment by stepps00** [comment]
Yep, I'll rerun the population script once I scrub the bunk `wk` properties.
