### ISSUE TITLE
Commit 35736e09be0eb5e19d10fe0e02e14d4d0942cff7 results in data errors

### ISSUE THREAD

**Issue by roja** [whosonfirst-data/whosonfirst-data#814]
This commit:

https://github.com/whosonfirst-data/whosonfirst-data/commit/35736e09be0eb5e19d10fe0e02e14d4d0942cff7

Has introduced errors into the data i.e. the introduction of "<<<<<<< HEAD" into:

https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/110/880/259/1/1108802591.geojson

**Comment by thisisaaronland** [comment]
Thanks for this. That's my bad. I thought those had been cleared but clearly not. I will push a fix shortly.

**Comment by thisisaaronland** [comment]
```
grep -n -r -l -e '<<<<' ./data | wc -l
0
```

Okay, things should be fixed in source. Ancillary files (bundles, things in S3 etc.) will be updated shortly as the update robots grab.

Again, apologies for the bad craziness and thanks for the heads up.
