### ISSUE TITLE
Upgrade neighbourhood shapes for The Netherlands

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#837]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First

### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
This excludes prior work on Amsterdam, den Haag, Utrecht, & etc.

**Comment by stepps00** [comment]
This issue will require updates at the `localadmin` placetype. 

#870 was opened to track updates to import tools. The test file being used will include updates in **Friesland**. Make sure Friesland is only imported once between the two PRs.

**Comment by stepps00** [comment]
Noting that there will be a few dual hierarchies in Groningen, Limburg, and Utrecht.

**Comment by stepps00** [comment]
Files are now in the S3 `misc/Issue 837` folder. 

Tagging @nvkelso for review, then importing.

**Comment by nvkelso** [comment]
Per https://github.com/whosonfirst-data/whosonfirst-data/issues/837#issuecomment-317836134, we think the `localadmin` blocker is fixed because we ran a Friesland test and it worked fine.

**Comment by nvkelso** [comment]
Noting here that @ZBSingleton did look at the prior neighborhood polygon and point curation mentioned in https://github.com/whosonfirst-data/whosonfirst-data/issues/837#issuecomment-310507012 and resolved all that in the delivery.

**Comment by nvkelso** [comment]
I reviewed this along the way and am generally enthusiastic about the changes. If there's a one off we should fix later we can followup after the set is processed and merged. Let's proceed, please.

**Comment by stepps00** [comment]
Placing this on the Q4 priority list and assigning @thisisaaronland for import. The most recent files are now in the S3 misc/Issue 837 folder.

**Comment by stepps00** [comment]
Re-assigning myself to run these files through the pipeline.

**Comment by stepps00** [comment]
Amsterdam: https://whosonfirst.mapzen.com/boundaryissues/pipeline/478/

**Comment by stepps00** [comment]
Netherlands data has been merged, closing issue.
