### ISSUE TITLE
Add abbreviations to region records in six countries

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#840]
Add a `label:eng_x_abbreviation` property and `wof:shortcode` property to regions in:

- Australia
- Brazil
- India
- China
- South Africa 
- Russia

This is causing Pelias to fail when searching for addresses with region abbreviations in these countries (being tracked in https://github.com/pelias/pelias/issues/601).

**Comment by stepps00** [comment]
cc @tigerlily-he

**Comment by nvkelso** [comment]
Should also do this for India, China, South Africa, and Russia

**Comment by stepps00** [comment]
It makes sense to include all countries that have region/state labels are higher levels, so I'd say yes.. and we should probably include dependencies, as well.

**Comment by nvkelso** [comment]
Technically yes, but practically eh. Let's leave this focused on the handful mentioned above.

**Comment by nvkelso** [comment]
We've moved to label:{lang}_x_abbreviation and wof:shortcode for these now.
