### ISSUE TITLE
Set English preferred names for non-English marinearea features

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#843]
This list should capture _most_ of the non-English `marinearea` features:

These will need to be translated into English (from the current `wof:name`).

We should also determine what the original language is and set that language's preferred name to the `wof:name` value.

scalerank | featurecla | name | note | min_zoom
--------- | ---------- | ---- | ---- | --------
2 | bay | Bahía de Campeche | Bay of Campeche | 4
3 | gulf | Golfo de California |  | 5
4 | gulf | Golfe du Lion |  | 5.7
4 | gulf | Río de la Plata |  | 5.7
5 | bay | Bahía Blanca |  | 6
5 | gulf | Golfo de Penas |  | 6
5 | bay | Bahía Grande |  | 6
5 | gulf | Golfo de Tehuantepec |  | 6
5 | gulf | Golfo San Mat’as |  | 6
5 | gulf | Golfo de Guayaquil |  | 6
5 | gulf | Golfo Corcovado |  | 6
5 | fjord | Boknafjorden |  | 6
5 | fjord | Storfjorden |  | 6
5 | fjord | Vestfjorden |  | 6
5 | fjord | Skagerrak |  | 6
7 | sound | Øresund | The Sound | 7.6
7 | bay | Mecklenburger Bucht |  | 7.6
7 | bay | Baía de Marajó | Internal Brazil Amazon River Waters | 7.6
7 | gulf | Golfo de Urabá |  | 7.6
7 | bay | Baía de São Marcos |  | 7.6
7 | lagoon | Waddenzee |  | 7.6
7 | fjord | Sognefjorden |  | 7.6
7 | fjord | Trondheimsfjorden |  | 7.6
8 | sound | Seno de Skyring | _untitled_36 | 7.7
8 | sound | Seno Otway | _untitled_37 | 7.7
8 | channel | Canal do Sul | Internal Brazil Amazon River Waters | 7.7
8 | lagoon | Ozero Mogotoyevo | _untitled_55 | 7.7
8 | bay | Guba Gusinaya | _untitled_56 | 7.7
8 | strait | Selat Dampier |  | 7.7
9 | channel | Canal Perigoso | Internal Brazil Amazon River Waters | 7.8
9 | channel | Canal do Norte | Internal Brazil Amazon River Waters | 7.8
9 | lagoon | Bras d'Or Lake | _untitled_46 | 7.8
9 | strait | Selat Bali | _untitled_60 | 7.8

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/53

**Comment by nvkelso** [comment]
Sounds like some of these are corrupted accent marks in the WOF name as imported (table above from latest Natural Earth), so the `wof:name` & other names should be fixed.

**Comment by ndcartography** [comment]
| scalerank | featurecla | name                 | Original Lang | `eng_x_preferred`              | note                                | min_zoom | 
|-----------|------------|----------------------|---------------|-------------------------------|-------------------------------------|----------| 
| 2         | bay        | Bahía de Campeche    | spa           | Bay of Campeche               |                                     | 4        | 
| 3         | gulf       | Golfo de California  | spa           | Gulf of California            |                                     | 5        | 
| 4         | gulf       | Golfe du Lion        | fra           | Gulf of Lion                  |                                     | 5.7      | 
| 4         | gulf       | Río de la Plata      | spa           | River Plate                   |                                     | 5.7      | 
| 5         | bay        | Bahía Blanca         | spa           | Blanca Bay                    |                                     | 6        | 
| 5         | gulf       | Golfo de Penas       | spa           | Gulf of Penas                 |                                     | 6        | 
| 5         | bay        | Bahía Grande         | spa           | Bahia Grande                  |                                     | 6        | 
| 5         | gulf       | Golfo de Tehuantepec | spa           | Gulf of Tehuantepec           |                                     | 6        | 
| 5         | gulf       | Golfo San Mat’as     | spa           | Gulf of  Mat’as               |                                     | 6        | 
| 5         | gulf       | Golfo de Guayaquil   | spa           | Gulf of  Guayaquil            |                                     | 6        | 
| 5         | gulf       | Golfo Corcovado      | spa           | Gulf of  Corcovado            |                                     | 6        | 
| 5         | fjord      | Boknafjorden         | nno?          | Bokna fjord                   |                                     | 6        | 
| 5         | fjord      | Storfjorden          | nno?          | Stor fjord                    |                                     | 6        | 
| 5         | fjord      | Vestfjorden          | nno?          | Vest Fjord                    |                                     | 6        | 
| 5         | fjord      | Skagerrak            | nno?          | Skagen Strait?                |                                     | 6        | 
| 7         | sound      | Øresund              | dan?          | The Sound                     |                                     | 7.6      | 
| 7         | bay        | Mecklenburger Bucht  | deu           | Bay of Macklenburg            |                                     | 7.6      | 
| 7         | bay        | Baía de Marajó       | por           | Bay of Marajó                 | Internal Brazil Amazon River Waters | 7.6      | 
| 7         | gulf       | Golfo de Urabá       | spa           | Gulf of Urabá                 |                                     | 7.6      | 
| 7         | bay        | Baía de São Marcos   | por           | Bay of São Marcos             |                                     | 7.6      | 
| 7         | lagoon     | Waddenzee            |               | Wadden Sea                    |                                     | 7.6      | 
| 7         | fjord      | Sognefjorden         | nno?          | Sogne Fjord                   |                                     | 7.6      | 
| 7         | fjord      | Trondheimsfjorden    |               | Trondheim Fjord               |                                     | 7.6      | 
| 8         | sound      | Seno de Skyring      | spa           | Skyring Sound, Cove or Inlet? | _untitled_36                        | 7.7      | 
| 8         | sound      | Seno Otway           |               | Otway Sound, Cove or Inlet?   | _untitled_37                        | 7.7      | 
| 8         | channel    | Canal do Sul         |               |                               | Internal Brazil Amazon River Waters | 7.7      | 
| 8         | lagoon     | Ozero Mogotoyevo     | rus           | Lake Mogotoyevo               | _untitled_55                        | 7.7      | 
| 8         | bay        | Guba Gusinaya        | rus           | Gusinaya Bay                  | _untitled_56                        | 7.7      | 
| 8         | strait     | Selat Dampier        | ind           | Dampier Strait                |                                     | 7.7      | 
| 9         | channel    | Canal Perigoso       | por           |                               | Internal Brazil Amazon River Waters | 7.8      | 
| 9         | channel    | Canal do Norte       | por           |                               | Internal Brazil Amazon River Waters | 7.8      | 
| 9         | lagoon     | Bras d'Or Lake       | fra           | ?                             | _untitled_46                        | 7.8      | 
| 9         | strait     | Selat Bali           | ind           | Bali Strait                   | _untitled_60                        | 7.8      |

**Comment by nvkelso** [comment]
- `Skagerrak` > `Skagerrak` (no translation / transliteration seems to be the norm into English and other languages)
- `Seno de Skyring` > `Skyring Sound` (spa > eng)
- `Seno Otway` > `Otway Sound` (spa > eng)
- `Bras d'Or Lake` is English, and `Lac Bras d'Or` would be the French

Most those Fjords should be combo of Danish, Norwegian, Swedish preferred names.

We have a big print National Geographic Atlas and print Times Atlas by my desk you can also reference :)

**Comment by nvkelso** [comment]
Also `Canal` (spa, port) > `Channel` (eng)

**Comment by ndcartography** [comment]
@nvkelso Thank you! I'll definitely check out those atlases! :) 
Updated `wof:name` records to come

**Comment by ndcartography** [comment]
**Table edited above ^^ to be run through two separate scripts accomplish this:**

table is used as a .csv file to grab `wof:id` and assign var for `bunk_name` and `good_name` :
```
for row in reader:

        # what id are we looking for
        id = row['id']
        bunk_name = row['bunk_name']
        lang = row['lang']
        good_name = row['good_name']
```
The current `bunk_name` being used as a `wof:name` will be moved into the appropriate `{}_x_preferred`. If there is already a `{}_x_preferred` then `bunk_name` will replace `{}_x_preferred` and move the replaced record into `{}_x_variant` : 

```
if feature:    
                props = feature['properties']
                props['wof:name'] = good_name
                if props.has_key('name:' + str(lang) + '_x_preferred'):
                    if not props['name:' + str(lang) + '_x_preferred'] == "":
                        props['name:' + str(lang) + '_x_variant'] = props['name:' + str(lang) + '_x_preferred']
                        props['name:' + str(lang) + '_x_preferred'] = bunk_name
                else:
                    props['name:' + str(lang) + '_x_preferred'] = bunk_name
```

**Comment by nvkelso** [comment]
Just make sure you’re not adding a duplicate variant name and you’ll be
good to go.

**Comment by nvkelso** [comment]
Closing via https://github.com/whosonfirst-data/whosonfirst-data/issues/845.
