### ISSUE TITLE
Some Ireland places are listed with Iran country code

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#853]
https://whosonfirst.mapzen.com/spelunker/id/101751737/descendants/?exclude=nullisland&placetype=neighbourhood

```
85794425 Windy Arbour — this is a neighbourhood in Iran, Islamic Republic of
85794337 Mount Argus — this is a neighbourhood in Iran, Islamic Republic of
85794149 Artane — this is a neighbourhood in Iran, Islamic Republic of
85794153 Ashtown — this is a neighbourhood in Iran, Islamic Republic of
85794157 Baldoyle — this is a neighbourhood in Ireland
```

<img width="1129" alt="screen shot 2017-07-07 at 15 27 15" src="https://user-images.githubusercontent.com/853051/27979163-cda3d242-6328-11e7-827a-162f9ea9ef3a.png">

**Comment by thisisaaronland** [comment]
This is a known-known. There is (some large number) of places whose `iso:country` code as defined by SimpleGeo has no bearing on that place's actual lat,lon.

Dealing with this in anything but a localized, opportunistic way has never made it up the stack. There is probably at least one other open ticket (...somewhere) on the subject.

**Comment by nvkelso** [comment]
Related / duplicate of (TBD):

- https://github.com/whosonfirst-data/whosonfirst-data/issues/211
- https://github.com/whosonfirst-data/whosonfirst-data/issues/366
