### ISSUE TITLE
Incorrect country codes for descendants

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#855]
https://whosonfirst.mapzen.com/spelunker/id/101751737/descendants/?exclude=nullisland&iso=ir

These records in Dublin, Ireland have an `IR` (Iran) country code, instead of an `IE` (Ireland) country code.

FIle a PR to update these country codes, as well as any others in Ireland. This affects both `iso:country` and `wof:country` properties.

**Comment by nvkelso** [comment]
Dup of #853.
