### ISSUE TITLE
Empire of France has a parent_id of 0

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#856]
https://whosonfirst.mapzen.com/spelunker/id/136253037/

<img width="428" alt="cursor_and_who_s_on_first_spelunker___france___136253037" src="https://user-images.githubusercontent.com/9599/28093425-0c984e3a-664c-11e7-9250-fb617a726e72.png">

I didn't think 0 was a valid value for parent_id. (I have code that broke when it ran into this case)

**Comment by stepps00** [comment]
Ah, this is a pointer to the [record for Earth](https://whosonfirst.mapzen.com/spelunker/id/0/).. while we tend not to use `0` often, it is a valid `wof:id` and parents our records with an [`empire`](https://whosonfirst.mapzen.com/spelunker/placetypes/empire/) placetype (like France).

**Comment by simonw** [comment]
Aha! Makes sense. I'll fix my code in that case.

**Comment by thisisaaronland** [comment]
In retrospect it might have made more sense to make Null Island ID #0 but it ended up with ID #1 instead...
