### ISSUE TITLE
Add boundaries for the city of Edmonton (Alberta, Canada)

### ISSUE THREAD

**Issue by kareniel** [whosonfirst-data/whosonfirst-data#858]
I noticed today that the geometry for the city of Edmonton is a point. (https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/890/458/485/890458485.geojson)

I downloaded a shape file from Edmonton's Open Data Portal and merged the polygons together to make one solid shape. I would go ahead and create a pull request with the modified geojson for Edmonton but I want to make sure that I'm not missing steps, as I haven't contributed to this project before.

We already have a source in the `whosonfirst-sources` repo for this data. (https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/can-edmdsd.json)

Is there anything I'm missing?

![image](https://user-images.githubusercontent.com/419946/28186938-dd982dee-67ea-11e7-98b6-f199ce8b2dc1.png)

**Comment by stepps00** [comment]
Hey @kareniel, thanks for the issue!

We recently updated administrative records in Edmonton recently; I suspect you may be using an older version of whosonfirst-data.

Here is a link to Edmonton in our Spelunker: https://whosonfirst.mapzen.com/spelunker/id/85947083/
Here is the raw GeoJSON of the Edmonton `locality` record: https://whosonfirst.mapzen.com/data/859/470/83/85947083.geojson

I'm going to close this issue, but please let me know if you run into any other issues in Edmonton.

**Comment by stepps00** [comment]
Sorry for the confusion.. looks like we have two separate `locality` records for Edmonton.

The record you referenced (https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/890/458/485/890458485.geojson) is a point record that I will need to deprecate. 

The record I referenced above (https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/859/470/83/85947083.geojson) is the "valid" Edmonton record with a polygon geometry that should supersede the 890458485 record. 

This should only require a property update, as the polygon geometry that we have for Edmonton is the same shape (dissolved from the `can-edmdsd` source) that you've created. Thanks again for the issue, we'll file a PR shortly.

**Comment by stepps00** [comment]
Looks like things are a bit more complicated than that...

When updating the Edmonton neighbourhood data, two Edmonton records were swapped around. The _Edmonton, Canada_ record was not updated, but the _Edmonton, Kentucky_ record was updated. 

I need to poke around the import files and clean up the locality records in a PR..

**Comment by stepps00** [comment]
Hey @kareniel - just following up here.. we merged a PR that updated the Edmonton point record ([here](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/890/458/485/890458485.geojson)). Thanks for the issue!

**Comment by kareniel** [comment]
Wow, that was fast! Thank you for taking a look at this! :)
