### ISSUE TITLE
Rename the Czech Republic to Czechia?

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst-data/whosonfirst-data#862]
Apparently, "If you want to be cool, it’s _Czechia_"
https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic#Adoption_of_Czechia

Prompted from this tweet I encountered today:
https://twitter.com/jilliancyork/status/886523087222579200

**Comment by nvkelso** [comment]
This is legit

**Comment by stepps00** [comment]
_"Czechia was approved by the Czech government on 2 May 2016 as the Czech Republic's official short name"_

It was published in the United Nations UNTERM and UNGEGN country name databases in 2016. The name Czechia appears on some U.S. government web pages alongside Czech Republic, and Czechia is included in the ISO 3166 country codes list.

Per https://en.wikipedia.org/wiki/Czech_Republic:
- http://www.mzv.cz/jnp/en/issues_and_press/factsheets/x2016_04_21_the_completion_of_translations_of_the.html
- https://cz.usembassy.gov/
- https://www.state.gov/p/eur/ci/ez/
- https://unstats.un.org/unsd/geoinfo/geonames/

Sounds like a good case for an `eng_x_preferred` name, unless we want to swap out the `wof:name`. (!)

**Comment by thisisaaronland** [comment]
Preferred or variant.

**Comment by stepps00** [comment]
Updated via Boundary issues, closing issue.

- Swapped in "Czechia" as preferred name, moved existing preferred to variant slot: https://github.com/whosonfirst-data/whosonfirst-data/commit/45f3a56d92cba4ede71b85e9920f8736baba5fce
- Added historical name: https://github.com/whosonfirst-data/whosonfirst-data/commit/541197757548ba7efafb3d1d740c6b2938cc15c8
