### ISSUE TITLE
Invalid GIS data for Uttar Pradesh, India (85672205)

### ISSUE THREAD

**Issue by marc-mabe** [whosonfirst-data/whosonfirst-data#863]
I encountered two problems with this region:

**1. Inserting into MySQL geometry column:**

Insert Query (works):
```sql
INSERT INTO GeoRegion (countryCode, name, type, geo)
VALUES (%s, %s, %s, ST_GeomFromGeoJson(%s))
```

Using spatial function (error):
```
SELECT ST_Intersects(geo, ST_GeomFromGeoJson(%s)) valid FROM GeoRegion
WHERE countryCode = %s AND type = %s AND name = %s
```

Error: `Invalid GIS data provided to function st_within.`

**2. http://geojsonlint.com/**
`Line 381: Polygons and MultiPolygons should follow the right-hand rule`

---------------------------

I have "fixed" the JSN using https://github.com/mapbox/geojson-rewind. Then the geojsonlint error goes away but it didn't solved the MySQL Problem.

After reverting changes made here (https://github.com/dcmn-com/whosonfirst-data/commit/be538aafe8e77e8be66e03172a3e812faa709a33?short_path=1ec7785#diff-1ec7785d9d7d5b940501de36fcc5ebf7) MySQL wors fine.

**Comment by stepps00** [comment]
Hi @marc-mabe - thanks for this issue..

Are you seeing this in any other records? A quick check tells me the same issue is occurring with the [record of San Francisco](https://whosonfirst.mapzen.com/data/859/225/83/85922583.geojson) and I'm questioning whether this is an isolated issue.

**Comment by marc-mabe** [comment]
Hi @stepps00,
We encountered the issue with this entry only but we use a very small subset on regions right now.

Will try locally with San Francisco.

**Comment by stepps00** [comment]
Hi @marc-mabe - I've verified the id for Uttar Pradesh, India is in a set of ids created for upcoming work in https://github.com/whosonfirst-data/whosonfirst-data/issues/1071.

I am going to close this issue in preference of that issue/PR.
