### ISSUE TITLE
"Super Bowl City" in San Francisco is an obsolete neighbourhood

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#873]
e.g for this point in downtown San Francisco: latitude=37.794512 longitude=-122.395324

http://whosonfirst-api.mapzen.com/?method=whosonfirst.places.getHierarchiesByLatLon&latitude=37.794512&longitude=-122.395324&api_key=...&spr=1

    {
        "hierarchies": [
            {
                "microhood": {
                    "wof:id": 420561633,
                    "wof:parent_id": "85865899",
                    "wof:name": "Super Bowl City",
                    "wof:placetype": "microhood",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                },
                "neighbourhood": {
                    "wof:id": 85865899,
                    "wof:parent_id": "1108830801",
                    "wof:name": "Financial District",
                    "wof:placetype": "neighbourhood",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                },
                "continent": {
                    "wof:id": 102191575,
                    "wof:parent_id": "-1",
                    "wof:name": "North America",
                    "wof:placetype": "continent",
                    "wof:country": "",
                    "wof:repo": "whosonfirst-data"
                },
                "macrohood": {
                    "wof:id": 1108830801,
                    "wof:parent_id": "85922583",
                    "wof:name": "Downtown",
                    "wof:placetype": "macrohood",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                },
                "country": {
                    "wof:id": 85633793,
                    "wof:parent_id": "102191575",
                    "wof:name": "United States",
                    "wof:placetype": "country",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                },
                "locality": {
                    "wof:id": 85922583,
                    "wof:parent_id": "102087579",
                    "wof:name": "San Francisco",
                    "wof:placetype": "locality",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                },
                "county": {
                    "wof:id": 102087579,
                    "wof:parent_id": "85688637",
                    "wof:name": "San Francisco",
                    "wof:placetype": "county",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                },
                "region": {
                    "wof:id": 85688637,
                    "wof:parent_id": "85633793",
                    "wof:name": "California",
                    "wof:placetype": "region",
                    "wof:country": "US",
                    "wof:repo": "whosonfirst-data"
                }
            }
        ],
        "stat": "ok"
    }

Super Bowl City existed for the duration of the 2016 Super Bowl, but it shouldn't be returned by `whosonfirst.places.getHierarchiesByLatLon` today.

https://whosonfirst.mapzen.com/spelunker/id/420561633/ is Super Bowl City in the Spelunker.

**Comment by thisisaaronland** [comment]
Currently the API only excludes deprecated records by default, however the search-related methods have grown an `is_current=[1|0]` parameter – in addition to other "existential parameters like `is_superseded` and `is_deprecated`.

The `getHierarchiesByLatLon` method does not support those flags yet but we can add them. I would prefer that applications be explicit and left in charge of what they need (or expect) to return.

**Comment by thisisaaronland** [comment]
Related: https://github.com/whosonfirst/whosonfirst-www-api/issues/63

**Comment by stepps00** [comment]
Hey @simonw - thanks for the issue.. I've gone ahead and tagged this record with an `mz:is_current` property equal to `0`, rendering the record "not current".

Once the commit that added this property update is pushed, I will paste it here and close the issue.

**Comment by stepps00** [comment]
Here is the commit that added an `"mz:is_current":0` flag to the Super Bowl City record: https://github.com/whosonfirst-data/whosonfirst-data/commit/bab6f46b08e6bbcda02092d5720e728d6e742294

**Comment by stepps00** [comment]
This issue should be settled, closing issue.
