### ISSUE TITLE
A few more min_zoom, max_zoom adjustments for regions

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#877]
Migrated over from https://github.com/whosonfirst-data/whosonfirst-data/pull/867#issuecomment-318581170 as PR https://github.com/whosonfirst-data/whosonfirst-data/pull/867 has been merged already but @stepps00 noted this hadn't been completed.

I've (@nvkelso) reviewed the region min_zoom and max_zoom and created a CSV with 947 features to set (a few more over 795 are made up from manual review and polish). **Please add a new commit** which sets these `mz:min_zoom` and `mz:max_zoom` values onto the specified WOF features by `id`.

- https://gist.github.com/nvkelso/4463ad79b2e2df5eb95d3f6f16d080f2#file-final_948_region_zoom_changes-csv

<img width="931" alt="screen shot 2017-07-28 at 00 29 41" src="https://user-images.githubusercontent.com/853051/28707103-e8106dbc-732b-11e7-8807-10a21e10fc3c.png">

All features with min_zoom:

<img width="808" alt="screen shot 2017-07-28 at 00 13 03" src="https://user-images.githubusercontent.com/853051/28706791-8a60bc54-732a-11e7-9acd-5d3be935c034.png">

The 795 missing features (but more were edited):

<img width="887" alt="screen shot 2017-07-27 at 23 16 58" src="https://user-images.githubusercontent.com/853051/28706792-8c3c4dfe-732a-11e7-8de6-2ff3011f94a4.png">

Final counts per min_zoom:

<img width="243" alt="screen shot 2017-07-28 at 00 20 32" src="https://user-images.githubusercontent.com/853051/28706805-9a4cc5b8-732a-11e7-8617-9eaac14a7c8e.png">

**Comment by stepps00** [comment]
This work was done in this commit: https://github.com/whosonfirst-data/whosonfirst-data/commit/8672ee4ef9717f36c8809d933bd22608ddfaa2f0

I will cherry-pick this commit out into a new branch, turn it into a PR for this issue, then follow-up to make sure all the previous commits have been taken care of.
