### ISSUE TITLE
Add GeoNames concordance values to records missing the concordance

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#879]
Following up on https://github.com/whosonfirst-data/whosonfirst-data/issues/806, not all records in Who's On First have a concordance value. Adding this concordance would allow us to import names from the GeoNames [`alternatenames.txt`](http://download.geonames.org/export/dump/alternateNames.zip) file.

The records with existing GeoNames concordance values were given additional names in [this PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/874).

**Comment by nvkelso** [comment]
This was completed in several different PRs. Closing.
