### ISSUE TITLE
Reclassify `name:unk_x_*` properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#880]
[This PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/874) includes a commit that added new `name:*` properties to roughly 118k records. The file used to import these new names, though, omitted language codes for a good chunk of these names. 

For any record in Who's On First that has a `name:unk_x_variant` or `name:unk_x_preferred` properties, reclassify that property with the correct language code. 

Relevant Python module: https://pypi.python.org/pypi/langdetect

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/595

**Comment by nvkelso** [comment]
**Examples** (plentiful in USA, hard to find outside):

- [Belmont, Ohio](https://en.wikipedia.org/wiki/Belmont,_Ohio) was historically known as **Wrightstown**, so a English historic name `data/101/712/117/101712117.geojson`
- [Flushing, Ohio](https://en.wikipedia.org/wiki/Flushing,_Ohio) is the **Flushingtown** "town" center of the same-named [township](https://en.wikipedia.org/wiki/Flushing_Township,_Belmont_County,_Ohio), so more of an English name variant `data/101/712/127/101712127.geojson`
- [Harrisburg, Ohio](https://en.wikipedia.org/wiki/Harrisburg,_Ohio) was historically known as **Darby** `data/101/712/397/101712397.geojson`
- [East Cleveland, Ohio](https://en.wikipedia.org/wiki/East_Cleveland,_Ohio) has a neighbourhood called **Colamer** which it's sometimes known by. `data/101/712/575/101712575.geojson`
- **Laajasalo** has a Swedish name variant **Deger\u00f6gard** and an unknown variant of **Deger\u00f6gard**  `data/890/537/275/890537275.geojson`
- **Ban Pang, Thailand** has a tha_x_preferred name that's pretty, with a new unk_x_variant of `P\u0101ng` which I suspect is the romanized short form of the Thai. So who knows. `data/890/467/247/890467247.geojson` 
- **Desa Cempaka, Indonesia** has both new `name:ind_x_preferred`  of **Desa Cempaka** (good) and `name:unk_x_variant` of **Cempaka** (probably `ind_x_variant`)?`data/890/493/575/890493575.geojson`

**Comment by stepps00** [comment]
I'm noticing that a lot of these names are already in an existing French or Spanish `name:*` property (the Russian and English languages were already compared against in the script).

Before using the Python module to figure out which language the `name:unk_x_*` property value belongs to, the name should be compared against existing `name:*` values to remove any potential duplicates.

**Comment by nvkelso** [comment]
Regarding https://github.com/whosonfirst-data/whosonfirst-data/issues/880#issuecomment-320138556:

- data/404/528/735/404528735.geojson

```
 +    "name:eng_x_variant":[
 +        "Japan Sea"
 +    ],		      ],
 +    "name:unk_x_variant":[
 +        "Japan Sea"
 +    ],
```

I'm guessing the unknown variant got added before the English variant as an order of operations thing. We should redo for English and Russian, too (which are probably 99% right, but...)

**Comment by stepps00** [comment]
This was fixed in a crawl of each per-country repo.

The Sea of Japan example: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-xy/master/data/404/528/735/404528735.geojson
