### ISSUE TITLE
Warn on [] in names, prefer ()

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#89]
We've fixed up the regions with this problem in https://github.com/whosonfirst/whosonfirst-data/issues/50, but there may be other data that suffers from this issue, and we should warn when new data has a [] instead of ().

**Comment by nvkelso** [comment]
Stephen hasn't found other data with this problem. Closing.

**Comment by stepps00** [comment]
All issues taken care of in #50. 
Closing because there are no actionable to-dos for this issue.
