### ISSUE TITLE
NL postcode missing hierarchy and geometry

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#899]
this NL postcode is missing its hierarchy and its geometry is `0,0`:

https://whosonfirst.mapzen.com/spelunker/id/538963963/

**Comment by thisisaaronland** [comment]
This just means we don't have/know any information for that postal code. Remember the NL postalcodes were derived using the OA/Clustr method:

https://github.com/whosonfirst-data/whosonfirst-data-postalcode-nl
