### ISSUE TITLE
A few wrong name labels

### ISSUE THREAD

**Issue by laszbalo** [whosonfirst-data/whosonfirst-data#912]
1. Locality 85688069 has  a typo in one of the name labels: rus_x_**prefered**.
2. Locality 1108782561 has  a wrong name types: eng_x_historic. I think it should be eng_x_**historical** instead.
3. Macrohood 102147495 (BoCaCa) has  a name label in the old format as well as one in the current format. I think the old "name:eng_p" label should be removed.

With thanks,
Laszlo

**Comment by stepps00** [comment]
Hi @laszbalo - thanks for identifying these! I'll look into these cases and push a fix shortly!

**Comment by stepps00** [comment]
Thanks again @laszbalo - these issues should now be fixed!

**Comment by laszbalo** [comment]
@stepps00 
That's great. Thanks.
