### ISSUE TITLE
Clean up county records in Canada

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#926]
In preparation of the `admin2` import of Statoids data, clean up the existing [`county` records for Canada](https://whosonfirst.mapzen.com/spelunker/id/85633041/descendants/?exclude=nullisland&placetype=county). We currently have 231 `county` records, but across the regions/provinces of Canada, we should have 291.

See divisions per region/province, here: http://statoids.com/yca.html

**Comment by nvkelso** [comment]
Some of these aren't used for administration (like many Alaska counties) so should be marked with the statistical gore = 1 flag.
