### ISSUE TITLE
Duplicate Imatra localities

### ISSUE THREAD

**Issue by hugovk** [whosonfirst-data/whosonfirst-data#93]
These Finnish localities probably need merging:

> 101814019 Imatra — this is a locality in AL and its population is 29,615
> 101911301 Imatra — this is a locality in AL and its population is 29,615

Their polygons are distinct but close to each other: 

http://whosonfirst.mapzen.com/spelunker/id/101814019/
http://whosonfirst.mapzen.com/spelunker/id/101911301/

Bit easier to see how close they are here, as the GH maps show the lakes more clearly:

https://github.com/whosonfirst/whosonfirst-data/blob/master/data/101/814/019/101814019.geojson
https://github.com/whosonfirst/whosonfirst-data/blob/master/data/101/911/301/101911301.geojson

Not entirely sure what's going on here, as the area suggested by Google Maps is a single entity containing both these but also a bit larger area:

https://www.google.com/maps/place/Imatra,+Finland/@61.1799712,28.849521,11z/data=!3m1!4b1!4m2!3m1!1s0x4690a89442cef055:0xdebd20ac34c599a4

**Comment by hannesj** [comment]
Related to #99

**Comment by stepps00** [comment]
#607 was merged, closing issue.
