### ISSUE TITLE
County bundle missing files

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#941]
The latest county bundle has metadata referencing:

- 102/069/327/102069327.geojson
- 102/072/077/102072077.geojson
- 421/184/585/421184585.geojson
- 421/184/975/421184975.geojson

But these files to not exist in the data directory.

**Comment by stepps00** [comment]
Verified that these features are in the `wof-county-latest-bundle.tar.bz2` bundle [here](https://dist.whosonfirst.org/bundles/), closing issue..

- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/102/069/327/102069327.geojson
- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/102/072/077/102072077.geojson
- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/421/184/585/421184585.geojson
- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/421/184/975/421184975.geojson

Feel free to re-open this issue if something else looks off.
