### ISSUE TITLE
getHierarchiesByLatLon failing for this point in Overland Park, Kansas

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#942]
This point in Overland Park, Kansas: https://www.google.com/maps/search/38.871513,-94.655889

    38.871513,-94.655889

Returns an empty hierarchy from whosonfirst:

http://whosonfirst-api.mapzen.com/?method=whosonfirst.places.getHierarchiesByLatLon&latitude=38.871513&longitude=-94.655889&api_key=mapzen-xxx

    {
        "hierarchies": [],
        "stat": "ok"
    }

**Comment by thisisaaronland** [comment]
This appears to be a data bug, as in the hierarchy is empty. Even when a parent ID for a record might be `-1` (unknown or TBD) there should always be a hierarchy starting from the "nearest" ancestor.

https://whosonfirst.mapzen.com/spelunker/id/420525353/

We've updated the record to have a hierarchy and that change should roll out in the next 10 minutes or so. I will leave this issue open until then.

**Comment by dphiffer** [comment]
Looks like it’s working again: http://whosonfirst-api.mapzen.com/?method=whosonfirst.places.getHierarchiesByLatLon&latitude=38.871513&longitude=-94.655889&api_key=(snip)

**Comment by dphiffer** [comment]
... or rather the data update has made its way to the API.

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/commit/133974ba453f54d045f45947b3374d57724f258e
