### ISSUE TITLE
County "Nong" is duplicated

### ISSUE THREAD

**Issue by anyadvisor** [whosonfirst-data/whosonfirst-data#947]
```
1108416125 | uuuu | LA | LA | 1500012904 | 16.4021 | 106.5079 | 0 | Nong
1108416125 | uuuu | LA | LA | 1473897779 | 16.4021 | 106.5079 | 0 | Nong
```
Those records are identical (apart from date modified and filehash

**Comment by nvkelso** [comment]
Those WOF ids at the beginning look the same to me. Where are you seeing the duplicates, can you link to a file tree in Github or S3 buckets or API, please?

- https://whosonfirst.mapzen.com/spelunker/id/1108416125/

**Comment by anyadvisor** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/blob/master/meta/wof-county-latest.csv

Lines 899 & 902 I think (maybe 903)

**Comment by nvkelso** [comment]
I see what you mean. The IDs and paths look the same to me. @thisisaaronland any idea what's happening here?

**Comment by anyadvisor** [comment]
Another change should be:
```
uuuu | 85632733 |   | 10.61616 | 47.36795 | 421173973 | uuuu | -99 | -99 | 1501212044 | 0 | 0 | 421173973 | Ceerigaabo | 1108757789 | locality | 1108805621 |   | -99
```
->
```
uuuu | 85632733 |   | 10.61616 | 47.36795 | 421173973 | uuuu | XS | XS | 1501212044 | 0 | 0 | 421173973 | Erigavo | 1108757789 | locality | 1108805621 |   | XS
```

Source: https://en.wikipedia.org/wiki/Erigavo
Source: https://www.google.co.uk/maps/place/9%C2%B043'32.4%22N+46%C2%B016'32.1%22E/@10.0928769,47.0987615,5.5z/data=!4m5!3m4!1s0x0:0x0!8m2!3d9.725679!4d46.275584

I've found a few errors here and there, should I post them in this thread?

**Comment by thisisaaronland** [comment]
I will take a look at this shortly. It smells like a bug or a hiccup in the https://github.com/whosonfirst/go-whosonfirst-meta code but I'll need to poke around a bit before I can say anything for certain.

**Comment by anyadvisor** [comment]
I don't know if this is the correct place to ask, or if there is a forum or something, but how come the missing country ID's aren't reverse engineered from the wof_country, and vice versa using the dependency/country tables?

And what is the difference between an ID of 0 and an ID of -1?

**Comment by thisisaaronland** [comment]
https://whosonfirst.mapzen.com/docs/properties/wof/#parent_id

**Comment by anyadvisor** [comment]
Is it correct that records that have been deprecated are still referenced in by id in the other columns, region_id for example?

**Comment by thisisaaronland** [comment]
The easiest way to think about it is that it is _possible_. Ideally everything is updated in sync with all the other things but there may be cases where they are not, still.

**Comment by stepps00** [comment]
This is actually _not_ a bug in the code, but rather an erroneous/duplicate record that slipped into: https://github.com/whosonfirst-data/whosonfirst-data/tree/master/data/110/841/612/5

I will file a PR to deprecate that bunk record and tag it as not-current, as it should have never been imported in the first place...

Related: https://github.com/whosonfirst/whosonfirst-tests/issues/6
