### ISSUE TITLE
name properties contain nested arrays

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#950]
heya, recently I noticed a change to the format on some name properties, not sure if it was intentional, it's unexpected and causing some failures in our import code:

```
"name:fra_x_preferred": [
  "Samoa américaines"
],
"name:fra_x_variant": [
  "Samoa Américaines",
  [
    "Samoa Américain",
    "Samoa américaine",
    "Samoa occidentales",
    "Territoire de Samoa Américaines"
  ]
]
```

https://whosonfirst.mapzen.com/data/856/326/97/85632697.geojson

**Comment by missinglink** [comment]
I ran a script to check this against ~473k admin polygons and didn't find any others, looks like it's a one-off bug :)

**Comment by thisisaaronland** [comment]
Yeah, that's definitely a bug. I can fix that manually.

**Comment by thisisaaronland** [comment]
Fixed in master. This should roll out to the bundles, etc. shortly.
