### ISSUE TITLE
Ensure prior edited neighbourhoods are mz:is_current = 1

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#951]
Both Zach, Nat's, and Fogel's work in https://github.com/whosonfirst-data/whosonfirst-data/compare/pr-881.

**Comment by nvkelso** [comment]
@stepps00 this issue may be a dup, but I couldn't find the original.

**Comment by stepps00** [comment]
This issue is referenced as a part of https://github.com/whosonfirst-data/whosonfirst-data/issues/868.

I'm open to keeping this issue open for _just_ Zach, Nat, and M Forgel's updates and using #868 to track anything prior.

**Comment by stepps00** [comment]
This is being taken care of in https://github.com/whosonfirst-data/whosonfirst-data/pull/970. Will close this issue once merged.

**Comment by stepps00** [comment]
#970 was merged, closing issue.
