### ISSUE TITLE
Basse-Terre

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#953]
heya,

recently the capital of Guadeloupe, [Basse-Terre](https://whosonfirst.mapzen.com/spelunker/id/404428967/) was set as `mz:is_current: -1` as seen [here](https://github.com/whosonfirst-data/whosonfirst-data/blame/master/data/890/442/797/890442797.geojson).

we have a test suite covering all the capital cities around the world, which is now showing this as a failure.

It would be great if we could get this record back as 'current' with a hierarchy so users can search for it.

Thanks!

**Comment by missinglink** [comment]
oh also the `parent_id` could probably be set to `85671209` instead of `-1`

**Comment by nvkelso** [comment]
mz:is_current = 0 means not current.

but mz:is_current = -1 means “could be current, could be not current, don’t
know” and should be imported by Pelias.

Note: our exportify tool default to -1 on all newly modified features for a
the last month or two now so you’ll be seeing many more of these problems.

We can fix this for this record, but please attach the Pelias issue to
update your logic here.

**Comment by missinglink** [comment]
gotcha, I will import `-1` values too

commit: https://github.com/pelias/placeholder/commit/af67d2bc6ffd194eaa08e7f63b465f2994a45418

**Comment by missinglink** [comment]
oh sorry for closing the issue.

I linked above the logic we use for placeholder and [here](https://github.com/pelias/whosonfirst/blob/fe3f0ef48ab9a0f106be075ec2bae0cd3a9bfad9/src/components/isActiveRecord.js#L14-L16) is the logic we use for the whosonfirst importer.

It seems in both cases we are looking for a non-zero value, so, for now, we will continue importing the `-1` records.

**Comment by stepps00** [comment]
Hey @missinglink - it looks like this is a non-issue and your code should capture all records that are not tagged as "not current"

```
function isCurrent(wofData) {
  return wofData.properties['mz:is_current'] !== 0;
}
```

I'll close this issue unless there are other issues specific to Basse-Terre.

**Comment by thisisaaronland** [comment]
Probably more than anyone wants to know but...

https://github.com/whosonfirst/go-whosonfirst-geojson-v2/blob/master/properties/whosonfirst/whosonfirst.go#L160-L265

**Comment by nvkelso** [comment]
(If this place came from Natural Earth it’s lat/long is wrong and should be
fixed… NE v4 has the corrected location.)

**Comment by stepps00** [comment]
[Basse Terre](https://whosonfirst.mapzen.com/boundaryissues/id/404428967) now has a complete hierarchy - I added `reversegeo:latitude` and `reversegeo:longitude` properties to the record and updated it in Boundary Issues. ([commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/f63e8677171d127973491ef048362ee16c483df5))

[This issue](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/332) is still blocking the `wof:parent_id` from being updated in Boundary Issues (as suggested, it should be `85671209`), so I'll keep this issue open until this is figured out.

**Comment by stepps00** [comment]
Commit https://github.com/whosonfirst-data/whosonfirst-data/commit/3140793582111b0a3cf8ac519a9904ea9841f8d5 updated the [Basse Terre](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/404/428/967/404428967.geojson) record to include a full hierarchy and correct `wof:parent_id` property.

@missinglink - can you verify that the changes you requested have been merged? I will close this issue if so.

**Comment by missinglink** [comment]
@stepps00 looks good to me! thanks :)
