### ISSUE TITLE
St. Kilda West appears to be a neighbourhood, not a locality

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#955]
According to [Wikipedia](https://en.wikipedia.org/wiki/St_Kilda_West,_Victoria), St Kilda West appears to be a neighbourhood that's part of Melbourne or Port Phillip, not a city in its own right.  I'm open to argument on [the situation](https://www.maxim.com/.image/t_share/MTQ2MzE1NzUzNDkzMTEyNDE3/the-situation-jersey-shore-getty.jpg), though.

**Comment by nvkelso** [comment]
Australia is weird, and WOF definitely gets some of it wrong. We have an existing issue to revamp Australia in https://github.com/whosonfirst-data/whosonfirst-data/issues/218. Leaving #955 (this issue) open as a subtask.

**Comment by stepps00** [comment]
#218 was recently closed, as we've landed #1483 that included updated records at the neighbourhood, locality, localadmin, county, and macrocounty placetypes. St Kilda West is still a [locality record](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/101/933/579/101933579.geojson) in WOF, but the neighbourhood/locality placetypes are a bit funky in all of Australia. 

We're tracking follow-up Australia issues in https://github.com/whosonfirst-data/whosonfirst-data/issues/1509, https://github.com/whosonfirst-data/whosonfirst-data/issues/1508, and https://github.com/whosonfirst-data/whosonfirst-data/issues/1495, but I think this issue has been fixed.
