### ISSUE TITLE
Tel Aviv is a region and county vs a locality

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#961]
This came in through support (see Desk 888) where the user was searching for Tel Aviv with Mapzen Search. 

Part of it links back to a data question where Tel Aviv is both a region and a county, but not a locality. This caused unexpected search results.

See https://github.com/pelias/pelias/issues/648#issuecomment-331850052

Spelunker: 
https://whosonfirst.mapzen.com/spelunker/id/85672549/ (region)
https://whosonfirst.mapzen.com/spelunker/id/1108720837/ (county)

Side note, another user asked about Dubai being listed as a region and not a locality (see comment on https://github.com/whosonfirst-data/whosonfirst-data/issues/64#issuecomment-332326133).

**Comment by nvkelso** [comment]
Tel Aviv (the special `locality` that's a joined municipality) is in Natural Earth, and we've imported Natural Earth so @stepps00 will need to debug why it's not showing up.

From a [related Natural Earth v4 issue](https://github.com/nvkelso/natural-earth-vector/issues/214#issuecomment-327097600):

> A parallel Wikidata ID example of admin feature versus it's capital (unitary or otherwise) is Tel Aviv Q33935 and Tel Aviv-Yafo Municipality Q12410321). In this case the Natural Earth name is Tel Aviv-Yafo but your suggestion for Q33935 results in many more Wikipedia links with all the translations (but all missing -Yafo). This is really splitting hairs 😉 Generally Natural Earth favors the agglomeration name if it's a formal governing body (another example is the Gold Coast in Australia). If the use-case is linking up with OpenStreetMap's http://www.openstreetmap.org/relation/1382494 they list Q33935 but the names and the polygon shape in OSM suggest that's in error and it should be Q12410321 instead so I'm going to leave it.

We can look at Dubai at the same time.

**Comment by stepps00** [comment]
Who's On First has the record for "Tel Aviv-Yafo" (municipality) as a `locality`:  https://whosonfirst.mapzen.com/spelunker/id/1141909423/

The hierarchy includes both the `county` and `region` records of Tel Aviv linked above:

```
    "wof:hierarchy":[
        {
            "continent_id":102191569,
            "country_id":85632315,
            "county_id":1108720837,
            "empire_id":136253049,
            "locality_id":1141909423,
            "region_id":85672549
        }
    ],
```

The `wof:country` and `iso:country` were incorrect, so I updated them in [this commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/7ec6f59b64ac455112ad68ca5986532b08f97455). I'm not sure if there is anything else actionable here, but I will leave this open until the Search team verifies this is no longer an issue.

cc @missinglink

**Comment by missinglink** [comment]
:+1: I wasn't aware the name was actually `Tel Aviv-Yafo`, is this the same place people refer to as `Tel Aviv`? If so, could we please add a `name:*` variant with the search term `Tel Aviv`?

**Comment by nvkelso** [comment]
Good idea, yes

**Comment by stepps00** [comment]
Re https://github.com/whosonfirst-data/whosonfirst-data/issues/961#issuecomment-334794370, the Tel Aviv-Yafo record was updated (https://github.com/whosonfirst-data/whosonfirst-data/commit/6a64137186d47941fa9394f228b231690d637607) to include new `name:eng_x_preferred` and `name:eng_x_variant` properties.

**Comment by missinglink** [comment]
excellent, thank you! that will allow users to find it in placeholder & mapzen search

**Comment by stepps00** [comment]
No problem - I'm going to close this issue since we have the expected Tel Aviv records and `name:*` properties now.
