### ISSUE TITLE
Improve boundary for Buchen, Germany

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#962]
This came in through support (see Desk 1016). From the user: "...the result openstreetmap:address:way:138363033 has postal code, county and macrocounty, but no city (should be Buchen). How is the city deduced and how could I step in to fix such issues?"

It originally put in https://github.com/pelias/pelias/issues/649 for the search issue, but it looks like this is a data issue (see comments in the thread). Investigate alternative data sources, although there is a chance the original user could help here!

https://whosonfirst.mapzen.com/spelunker/id/101812993/

![image](https://user-images.githubusercontent.com/4380498/30885979-37a74c56-a2ca-11e7-8c8a-becffa1777aa.png)

**Comment by nvkelso** [comment]
I suspect the user is expecting to see the WOF equivalent placetype `localadmin` of https://en.wikipedia.org/wiki/Büchen_(Amt) which includes the Büchen `locality` WOF currently has, and 15 total localities.

We don't have `localadmin` here now. If the user can suggest an open source (and even an improved source for the `locality`, too) we can add them.

I think Pelias coalesces `localadmin` and `locality` to `locality` for some or all functionality. @trescube to confirm.

**Comment by nvkelso** [comment]
From Wikipedia:

> The Amt (plural: Ämter) is unique to the German Bundesländer (federal states) of Schleswig-Holstein, Mecklenburg-Western Pomerania and Brandenburg.

**Comment by missinglink** [comment]
Pelias sometimes coalesces `localadmin` and `locality` at search-time, so if a user asks for `?layers=localadmin` we will sometimes return either/or.

> Just because we try to give them what they *want*, not necessarily what they *asked for* :smile: 

This doesn't apply at index time when we use the point-in-polygon information to enrich the address data.

**Comment by stepps00** [comment]
I'm closing this issue, as it will be taken case of as part of https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/1. Let's use https://github.com/whosonfirst-data/whosonfirst-data/issues/1606 for all related admin updates in Germany.

I've verified in the new admin data that Buchen does have a more accurate polygon at the locality and localadmin placetypes.
