### ISSUE TITLE
Supersede duplicate imported City of X localities into their original representation [USA]

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#971]
This is a followup from reviewing https://github.com/whosonfirst-data/whosonfirst-data/pull/824#issuecomment-334619360.

Supersede duplicate localities into their better representation. 
Where better = the first one that often has a polygon already.

Examples:

- `City of Fortuna` into **Fortuna** (California)
- `City of San Francisco` into **San Francisco** (California)
- `City of College Park` into **College Park** (Maryland)

This is _probably_ just a USA problem?

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/824 has been merged - this is now a priority issue and will be worked on through mid-November.

**Comment by stepps00** [comment]
If any of these records have an existing `edtf:cessation` date, it should be moved to the `edtf:deprecated`. Deprecated =/= cessation.
