### ISSUE TITLE
Deprecate imported neighbourhoods in our curated cities

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#972]
This is a followup from reviewing https://github.com/whosonfirst-data/whosonfirst-data/pull/824#issuecomment-334619360.

Don't bother figuring out what to superseded them into just deprecate them en mass by intersecting with the polygons of the curated neighbourhoods (e.g. the ones in #945).

- `Central Waterfront` (is a dup, but ignore)
- `West of Twin Peaks` (looks to be new, but deprecate anyhow)

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/824 has been merged - this is now a priority issue and will be worked on through mid-November.

**Comment by stepps00** [comment]
[This file](https://github.com/whosonfirst-data/whosonfirst-data/files/1455014/locality_ids.txt) contains the `wof:id` of any locality that has curated neighbourhood records. 

A PR for this issue will deprecate any erroneous/new descendant neighbourhood point records for the localities listed in that file.
