### ISSUE TITLE
Supersede duplicate imported localities into their best representation

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#973]
This is a followup from reviewing https://github.com/whosonfirst-data/whosonfirst-data/pull/824#issuecomment-334619360, and is different than https://github.com/whosonfirst-data/whosonfirst-data/issues/971 which is USA focused.

This issue to global review of "nearby" localities to be flagged and evaluated if nearby of the same name are actually dup's of each other. Determine the best and supersede the other into the best.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/824 has been merged - this is now a priority issue and will be worked on through mid-November.

**Comment by stepps00** [comment]
```
1125271535
1125362663
1125376419
1125376423
1125384359
1125384383
1125385953
1125385979
1125407303
1125900467
890418173
890422123
890430517
890432989
890434705
890435937
890435939
890435941
890436921
890437259
890437267
890437729
890437919
890438369
890438433
890438455
890438459
890438487
890438513
890442283
890442805
890442811
890442815
890442825
890442831
890442839
890442861
890443063
890443241
890443279
890443293
890443321
890443343
890443367
890443405
890443609
890443621
890443767
890443779
890443781
1125269593
```

**Comment by stepps00** [comment]
These four files contain the ids for all new locality and localadmin records from the `qs_pg` import (filenames contain the commit:

[042a215d1d3979b5154c1d0efef8f662e5c272a3-files-points.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1480099/042a215d1d3979b5154c1d0efef8f662e5c272a3-files-points.txt)
[510bbb2eff306e3f3adf538d1839bd6c121e0eab-files-points.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1480100/510bbb2eff306e3f3adf538d1839bd6c121e0eab-files-points.txt)
[2139706d4218b42bd44f75a381c2c683a2f49ec7-files-points.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1480101/2139706d4218b42bd44f75a381c2c683a2f49ec7-files-points.txt)
[aa238672cf5f354471052d9737c484a92e44cee7-files-points.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1480102/aa238672cf5f354471052d9737c484a92e44cee7-files-points.txt)

**Comment by nvkelso** [comment]
- [ ] "City of" is taken care of in https://github.com/whosonfirst-data/whosonfirst-data/pull/1034.
- [ ] But we still need to determine dups for everything else, and there are certainly a ton of dup concordances, including many-to-many relationships. Fun times.
