### ISSUE TITLE
WoF label for Louisville is "Louisville Metro"

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#974]
Louisville (KY) is a combined city-county, but the WoF label for this locality is Louisville Metro. No one would really ever say "Louisville Metro" unless referring to the government or the police department. 

https://whosonfirst.mapzen.com/spelunker/id/85947523/

This makes the Mapzen Search result for my high school display as, "120 West Lee Street, Louisville Metro, KY, USA" 

The other combined city-county examples I checked do not have a separate label property, and their names are set as expected (name: Indianapolis, Nashville). This locality should be just Louisville.

Other relevant issue: https://github.com/whosonfirst-data/whosonfirst-data/issues/251

**Comment by stepps00** [comment]
Louisville was adjusted as a one-off update for #251. I'll check all records with a `wof:label` property and file a PR with proposed changes.

**Comment by stepps00** [comment]
We have division, county, civil parish, and city of * labels for existing records, but [Louisville](https://whosonfirst.mapzen.com/spelunker/id/85947523/) is the only record with "Metro".

**Comment by rmglennon** [comment]
thanks for checking, @stepps00!

**Comment by stepps00** [comment]
https://whosonfirst.mapzen.com/spelunker/id/85947523/

The label for this record is now just "Louisville". ([commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/fd23239554c035afec93d3955488c5eb7882e93c))

Closing issue, this should do the trick.
