### ISSUE TITLE
Fix duplicate dependency/region records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#988]
Often times, `dependency` records have a single descendant `region` record. Examples:

**Guam**
Dependency: https://whosonfirst.mapzen.com/spelunker/id/85632163/
Region: https://whosonfirst.mapzen.com/spelunker/id/85681227/

**Puerto Rico**
Dependency: https://whosonfirst.mapzen.com/spelunker/id/85633729/
Region: https://whosonfirst.mapzen.com/spelunker/id/85687331/

These `region` records are duplicates - we should maintain a single record for each of these places, but tag the `dependency` record with a placetype_alt...

**Comment by stepps00** [comment]
List of dependency records with duplicate descendant region records:

```
dependency_id,region_id
85632629,85681419
85632517,85681311
85633167,85684619
85632689,85681165
85632301,85681367
85632587,85681325
85632617,85681173
85633729,85687331
85632387,85671119
85632199,85669283
85632459,85681249
85632493,85681315
85632239,85681231
85632613,85681151
85632649,85681409
85632743,85680913
85632163,85681227
85632211,85681209
85632611,85681183
```

List of dependency records without duplicate descendant region records:

```
dependency_id
85632333
85632485
85632653
85632677
85632789
85632337
85632473
85632481
136251281
85632585
85632697
85632549
85632421
85632205
85632283
85632731
85632641
85632169
85633153
```

**Comment by nvkelso** [comment]
From our BRB, for the 20 some feature listed in https://github.com/whosonfirst-data/whosonfirst-data/issues/988#issuecomment-345345297 we should deprecate the region into the dependency and add placetype_alt of `region` to the `dependency`. It's also important to transfer props from region to dependency, and to move geoms around (when diff) as alts.
