### ISSUE TITLE
Ensure wof:placetype_alt is a list

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#995]
Crawl the repo and convert any `wof:placetype_alt` string value to a list. 

See: https://github.com/whosonfirst/py-mapzen-whosonfirst-export/issues/12

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/339

**Comment by stepps00** [comment]
This property should stay a string, closing issue.

**Comment by nvkelso** [comment]
To clarify, it stays a string of just one single alt value. If it's additionally co-terminous with something else, then additionally use that property to link the records.
