### ISSUE TITLE
Document venue repo naming schema

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#998]
Followup from: https://github.com/whosonfirst-data/whosonfirst-data/pull/986#discussion_r144999864.

**Comment by stepps00** [comment]
Dupe of https://github.com/whosonfirst-data/whosonfirst-data/issues/989 ?

**Comment by nvkelso** [comment]
Agree, closing. Updated the comment in the other issue as that's where I got confused.
