### ISSUE TITLE
Update records with incorrect ISO coded as "US"

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#999]
https://whosonfirst.mapzen.com/spelunker/id/1141906235/

ISO country = US

There are plenty more of these listed on https://whosonfirst.mapzen.com/spelunker/placetypes/locality/?geometry=point&iso=us (which is where I found this one)

**Comment by simonw** [comment]
(Related issue: #993)

**Comment by stepps00** [comment]
Relevant commit: https://github.com/whosonfirst-data/whosonfirst-data/commit/4768d05cda37b4ae67cc4663384fda5ed223de1b

**Comment by stepps00** [comment]
Likely replacing the  `wof:country` and `iso:country` property values with the ` "ne:ISO_A2"` property value for affected records (see: https://github.com/whosonfirst-data/whosonfirst-data/issues/999#issuecomment-337408464).
